### ISSUE TITLE
Wox.Plugin.Program System.NullReferenceException

### ISSUE THREAD

**Issue by lovebdsobuj** [Wox-launcher/Wox#1000]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 10/02/2016 10:40:57
Exception:
**Wox.Plugin.Program
System.NullReferenceException**

```
Object reference not set to an instance of an object.
   at Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 136
   at Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 102
   at Wox.Infrastructure.Stopwatch.Debug(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 19
   at Wox.Plugin.Program.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 94
   at Wox.Core.Plugin.PluginManager.<>c__DisplayClass19_0.<InitializePlugins>b__1() in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 98
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 27
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

```
# Overall Wox Doesn't Work After Update My Windows OS.

**Comment by roose** [comment]
Try latest version https://ci.appveyor.com/project/happlebao/wox/build/artifacts

**Comment by lovebdsobuj** [comment]
Windows SmartScreen prevented to **run** `Wox-1.3.297.exe`.
When user get it in stable version in `GitHub > Releases` section.

**Comment by roose** [comment]
@lovebdsobuj try right click on the `Wox-1.3.297.exe` open `Properties` click `Unblock` and `Apply` and run `Wox-1.3.297.exe`

**Comment by lances101** [comment]
@lovebdsobuj, builds from AppVeyor need to be unlocked first because they are not signed in any way (actually, I'm not sure if actual releases are signed, cannot check right now). I want to focus on this issue once @happlebao has some time. 

Regarding your issue, as @roose said, the latest build should have fixed that problem.

**Comment by lovebdsobuj** [comment]
`Wox v1.3.297` working perfectly. 👍
Hide Wox on Startup issue fixed.
Thanks for the hard works...
Really Wox is a good launcher for Windows.
Keep it up...

**Comment by lances101** [comment]
@happlebao, solved.
