### ISSUE TITLE
Wox version: 1.3.183 启动之时报错

### ISSUE THREAD

**Issue by wgzj** [Wox-launcher/Wox#1014]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 10/12/2016 22:37:27
Exception:
Wox.Core
System.MissingMethodException
Method not found: 'Int32 System.Runtime.InteropServices.Marshal.SizeOf(!!0)'.
   at Wox.Core.Resource.Theme.SetWindowAccent(Window wind, AccentState themeAccentMode)
   at Wox.MainWindow.OnLoaded(Object sender, RoutedEventArgs _) in C:\projects\wox\Wox\MainWindow.xaml.cs:line 53
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at MS.Internal.FrameworkObject.OnLoaded(RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by chenxiaoangle** [comment]
我也是这个错误，不影响使用但是每次搜索完后启动程序都会弹出来

**Comment by lances101** [comment]
@guorui029 the error you are getting is because you are trying to apply a theme with Blur on Windows 7 (which is not supported). Please try switching to a different theme.

**Comment by lances101** [comment]
You need at least Windows 8 for themes with Blur. This is a bug and is fixed in later builds. 

If you are still running into issues even after changing the theme, [try this build](https://ci.appveyor.com/api/buildjobs/cmvaiden1r4um51m/artifacts/Releases%2FWox-1.3.295.exe). 

Closed.
