### ISSUE TITLE
Exception after typing the last character of custom WebSearch keyword (once in 50 querries)

### ISSUE THREAD

**Issue by homoroselaps** [Wox-launcher/Wox#1015]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 10/12/2016 20:37:44
Exception:
mscorlib
System.ArgumentOutOfRangeException
Insertion index was out of range. Must be non-negative and less than or equal to size.
Parameter name: index
   at System.Collections.ArrayList.Insert(Int32 index, Object value)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   at System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
duplicate #926 please update relevant info there
