### ISSUE TITLE
Issue faced

### ISSUE THREAD

**Issue by fishdot** [Wox-launcher/Wox#1021]
On computer launch, Wox launched and even after restarting this message was shown, not sure what to do. Going to try a reinstall now.
## Known problems for 1.3.813:
1. `System.NullReferenceException`: try reset wox by delete %APPDATA%\Wox, backup before you do that
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: 设置 http 代理
## English

Try search existing issues before you open new one
1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 
## 中文 / Chinese

提问之前搜索一下已经有的 issue
1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 10/16/2016 03:10:53
Exception:
Wox.Plugin.Program
System.NullReferenceException
Object reference not set to an instance of an object.
   at Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 136
   at Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 102
   at Wox.Plugin.Program.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 94
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 27
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by lances101** [comment]
[Please try this build](https://ci.appveyor.com/api/buildjobs/cmvaiden1r4um51m/artifacts/Releases%2FWox-1.3.295.exe). 
You might need to unlock the binaries first (do that by opening properties and click unblock).

**Comment by lances101** [comment]
Did anything help, @fishdot ?

**Comment by fishdot** [comment]
Installed the build you linked, and things started to work again. However after testing it for a few days this is what I have come to realise thus far. When launching apps with this build, it doesn't show the application name. For example, when typing in steam, what used to come up at the top would be "Steam". However, now it would show "Steam Client Bootstrapper" which also launches steam. The iisue faced would be a confusion of apps when similar names are shown.

**Comment by bao-qian** [comment]
Steam Client Bootstrapper is not a similar name, it is the description in "Steam.lnk"
