### ISSUE TITLE
Exception:PresentationFramework System.InvalidOperationException Can only call DragMove when primary mouse button is down.

### ISSUE THREAD

**Issue by Ericteen** [Wox-launcher/Wox#1057]
## Known problems for 1.3.183:

1. `System.NullReferenceException`: try reset wox by delete %APPDATA%\Wox, backup before you do that
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: 设置 http 代理

## English

Try search existing issues before you open new one

1. Wox version / commit number: 1.3.183
2. Steps to **reproduce** the bug: error occurs when using browser shortcuts, for example, 'wiki + the things you want to search'
3. Windows version:Microsoft Windows NT 6.3.9600.0
4. Exception:PresentationFramework
System.InvalidOperationException
Can only call DragMove when primary mouse button is down.
   at System.Windows.Window.DragMove()
   at Wox.MainWindow.OnMouseDown(Object sender, MouseButtonEventArgs e) in C:\projects\wox\Wox\MainWindow.xaml.cs:line 109
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
[2016-11-07.txt](https://github.com/Wox-launcher/Wox/files/574495/2016-11-07.txt)

6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by wanxiangming** [comment]
oh，do you resolve the issue

**Comment by lances101** [comment]
[Please try this build](https://ci.appveyor.com/api/buildjobs/cmvaiden1r4um51m/artifacts/Releases%2FWox-1.3.295.exe). 
You might need to unlock the binaries first (do that by opening properties and click unblock).

**Comment by bao-qian** [comment]
although there is no workaround now, but this issue is duplicate: #811
