### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by felix5345** [Wox-launcher/Wox#1077]
## Known problems for 1.3.183:

1. `System.NullReferenceException`: try reset wox by delete %APPDATA%\Wox, backup before you do that
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: 设置 http 代理

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 11/10/2016 09:03:05
Exception:
mscorlib
System.IO.IOException
The process cannot access the file 'C:\Users\Jinjie\AppData\Local\Wox\app-1.3.67\Images\app_error.png' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:line 234
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:line 342
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<<DeleteDirectory>b__35>d__38.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:line 234
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:line 342
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassaf.<<installPackageToAppDir>b__a9>d__b7.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.ApplyReleases.cs:line 286
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:line 533
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__7b.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.ApplyReleases.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__a.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:line 533
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.EasyModeMixin.<UpdateApp>d__11.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\IUpdateManager.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Wox.Core.Updater.<UpdateApp>d__0.MoveNext() in C:\projects\wox\Wox.Core\Updater.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lances101** [comment]
Duplicate, please check #1068
