### ISSUE TITLE
Error everytime I open Wox

### ISSUE THREAD

**Issue by Wolfsdorf** [Wox-launcher/Wox#1091]
I tried deleting the wox folder in Appdata to no avail. This is my first time trying to use the program. It worked for a bit, I exit the program and then it wouldn't open anymore.

Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 11/12/2016 12:31:29
Exception:
Wox.Core
System.MissingMethodException
Method not found: 'Int32 System.Runtime.InteropServices.Marshal.SizeOf(!!0)'.
   at Wox.Core.Resource.Theme.SetWindowAccent(Window wind, AccentState themeAccentMode)
   at Wox.MainWindow.OnLoaded(Object sender, RoutedEventArgs _) in C:\projects\wox\Wox\MainWindow.xaml.cs:line 53
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at MS.Internal.FrameworkObject.OnLoaded(RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lances101** [comment]
I suppose you are running Windows 7. Therefore the `Accents` theming that was added to Windows in Win8 is what is failing for you. This issue is already fixed on newer builds. 

[Try this build (1.3.295)](https://ci.appveyor.com/api/buildjobs/cmvaiden1r4um51m/artifacts/Releases%2FWox-1.3.295.exe). 

Once you try it, please report back in case it didn't help you.

**Comment by Wolfsdorf** [comment]
That seemed to work, thanks!
