### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by altsanz** [Wox-launcher/Wox#1096]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 11/14/2016 13:21:37
Exception:
mscorlib
System.ArgumentOutOfRangeException
Insertion index was out of range. Must be non-negative and less than or equal to size.
Parameter name: index
   at System.Collections.ArrayList.Insert(Int32 index, Object value)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   at System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2016-11-14.txt](https://github.com/Wox-launcher/Wox/files/589184/2016-11-14.txt)

**Comment by lances101** [comment]
It looks like your system is having trouble resolving the address of github's api. We usually have these issues with people from china. Is it possible that `api.github.com` is blocked from the network you are trying to access? 

If you want to get rid of the constant error popup every time Wox checks for an update uncheck the "Auto Update" setting in the **General** tab of the **Settings** menu.

**Comment by bao-qian** [comment]
delete C:\ProgramData\Microsoft\Windows\Start Menu\Programs\HP Password Reset Tool
