### ISSUE TITLE
wox wrong

### ISSUE THREAD

**Issue by bombepro** [Wox-launcher/Wox#1099]
[2016-11-15.txt](https://github.com/Wox-launcher/Wox/files/590902/2016-11-15.txt)

Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\aslan\AppData\Roaming\Wox\Logs\1.3.183\2016-11-15.txt
2. copy below exception message
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 11/15/2016 09:39:18
Exception:
Wox.Plugin.Program
System.NullReferenceException
Object reference not set to an instance of an object.
   at Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 136
   at Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 102
   at Wox.Plugin.Program.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 94
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 27
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by bao-qian** [comment]
delete `%APPDATA%\Wox`, backup before you do that
