### ISSUE TITLE
program plugin does not work

### ISSUE THREAD

**Issue by jaredbidlow** [Wox-launcher/Wox#1110]
1. Wox version / commit number:  1.3.306
2. Steps to **reproduce** the bug:
3. Windows version: 10
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
```
2016-11-18 17:25:42.4767|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-11-18 17:25:42.5047|ERROR|System.Runtime.Serialization.ObjectManager.CompleteObject|Unable to load type System.Collections.Generic.List`1[[Wox.Plugin.Program.Program, Wox.Plugin.Program, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null]] required for deserialization.
2016-11-18 17:25:42.5157|ERROR|System.Runtime.Serialization.ObjectManager.CompleteObject|
   at System.Runtime.Serialization.ObjectManager.CompleteObject(ObjectHolder holder, Boolean bObjectFullyComplete)
2016-11-18 17:25:42.5157|ERROR|Wox.Infrastructure.Storage.BinaryStorage`1.Deserialize|Broken cache file: C:\Users\Jared\AppData\Roaming\Wox\Cache\ProgramIndexCache.dat
2016-11-18 17:25:42.5157|ERROR|Wox.Infrastructure.Storage.BinaryStorage`1.Deserialize|Unable to load type System.Collections.Generic.List`1[[Wox.Plugin.Program.Program, Wox.Plugin.Program, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null]] required for deserialization.
2016-11-18 17:25:42.5157|ERROR|Wox.Infrastructure.Storage.BinaryStorage`1.Deserialize|
   at System.Runtime.Serialization.ObjectManager.CompleteObject(ObjectHolder holder, Boolean bObjectFullyComplete)
   at System.Runtime.Serialization.ObjectManager.DoNewlyRegisteredObjectFixups(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.RegisterObject(Object obj, Int64 objectID, SerializationInfo info, Int64 idOfContainingObj, MemberInfo member, Int32[] arrayIndex)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.RegisterObject(Object obj, ParseRecord pr, ParseRecord objectPr, Boolean bIsString)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObjectEnd(ParseRecord pr)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at Wox.Infrastructure.Storage.BinaryStorage`1.Deserialize(FileStream stream) in C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:line 55
2016-11-18 17:25:42.5262|INFO|Wox.Plugin.Program.Main..ctor|Preload 0 programs from cache
2016-11-18 17:25:44.6339|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-11-18 17:25:44.6359|ERROR|System.IO.__Error.WinIOError|Access to the path 'C:\MyWinix\Cygwin\home\Admin\.cache' is denied.
2016-11-18 17:25:44.6359|ERROR|System.IO.__Error.WinIOError|
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2016-11-18 17:25:44.6359|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-11-18 17:25:44.6359|ERROR|System.RuntimeTypeHandle.CreateInstance|Exception has been thrown by the target of an invocation.
2016-11-18 17:25:44.6359|ERROR|System.RuntimeTypeHandle.CreateInstance|
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
2016-11-18 17:25:44.6359|ERROR|System.RuntimeTypeHandle.CreateInstance|Access to the path 'C:\MyWinix\Cygwin\home\Admin\.cache' is denied.
2016-11-18 17:25:44.6969|ERROR|System.RuntimeTypeHandle.CreateInstance|
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Wox.Plugin.Program.Programs.Win32.UnregisteredPrograms(List`1 sources, String[] suffixes) in C:\projects\wox\Plugins\Wox.Plugin.Program\Programs\Win32.cs:line 222
   at Wox.Plugin.Program.Programs.Win32.All(Settings settings) in C:\projects\wox\Plugins\Wox.Plugin.Program\Programs\Win32.cs:line 341
   at Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 64
   at Wox.Plugin.Program.Main..ctor() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 40
2016-11-18 17:25:44.6999|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|Program : Can't create instance
2016-11-18 17:25:44.6999|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|

2016-11-18 17:25:44.6999|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|Exception has been thrown by the target of an invocation.
2016-11-18 17:25:44.6999|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Wox.Core.Plugin.PluginsLoader.CSharpPlugins(List`1 source) in C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:line 66
2016-11-18 17:25:44.6999|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|Access to the path 'C:\MyWinix\Cygwin\home\Admin\.cache' is denied.
2016-11-18 17:25:44.6999|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Wox.Plugin.Program.Programs.Win32.UnregisteredPrograms(List`1 sources, String[] suffixes) in C:\projects\wox\Plugins\Wox.Plugin.Program\Programs\Win32.cs:line 222
   at Wox.Plugin.Program.Programs.Win32.All(Settings settings) in C:\projects\wox\Plugins\Wox.Plugin.Program\Programs\Win32.cs:line 341
   at Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 64
   at Wox.Plugin.Program.Main..ctor() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 40
2016-11-18 17:25:45.0989|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-11-18 17:25:45.0989|ERROR|System.IO.__Error.WinIOError|Could not find file 'C:\Users\Jared\AppData\Roaming\Wox\Plugins\Need-ef217581-8ab3-41ad-942a-80e44bb9eed2\db.txt'.
2016-11-18 17:25:45.0989|ERROR|System.IO.__Error.WinIOError|
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2016-11-18 17:25:45.4280|INFO|Wox.App.<OnStartup>b__8_0|Preload 200 images from cache
2016-11-18 17:25:47.7694|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-11-18 17:25:47.7694|ERROR|System.IO.__Error.WinIOError|Could not find file 'C:\Users\Jared\AppData\Local\Wox\packages\.betaId'.
2016-11-18 17:25:47.7694|ERROR|System.IO.__Error.WinIOError|
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2016-11-18 17:25:58.8523|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-11-18 17:25:58.8553|ERROR|System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation|Bitmap color context is not valid.
2016-11-18 17:25:58.8873|ERROR|System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation|
   at System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation()
2016-11-18 17:25:58.8873|ERROR|System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation|The specified color profile is invalid. (Exception from HRESULT: 0x800707DB)
2016-11-18 17:25:58.8873|ERROR|System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation|

2016-11-18 17:25:58.8873|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-11-18 17:25:58.8873|ERROR|System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation|Bitmap color context is not valid.
2016-11-18 17:25:58.8873|ERROR|System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation|
   at System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation()
2016-11-18 17:25:58.8873|ERROR|System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation|The specified color profile is invalid. (Exception from HRESULT: 0x800707DB)
2016-11-18 17:25:58.8873|ERROR|System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation|

2016-11-18 17:28:34.3300|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-11-18 17:28:34.3300|ERROR|Wox_EasyTotp.Base32Encoding.CharToValue|Character is not a Base32 character.
Parameter name: c
2016-11-18 17:28:34.3300|ERROR|Wox_EasyTotp.Base32Encoding.CharToValue|
   at Wox_EasyTotp.Base32Encoding.CharToValue(Char c) in G:\Dev\Github\Wox-EasyTotp\Wox-EasyTotp\Base32Encoding.cs:line 115
2016-11-18 17:28:37.7489|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-11-18 17:28:37.7489|ERROR|Wox_EasyTotp.Base32Encoding.CharToValue|Character is not a Base32 character.
Parameter name: c
2016-11-18 17:28:37.7489|ERROR|Wox_EasyTotp.Base32Encoding.CharToValue|
   at Wox_EasyTotp.Base32Encoding.CharToValue(Char c) in G:\Dev\Github\Wox-EasyTotp\Wox-EasyTotp\Base32Encoding.cs:line 115
2016-11-18 17:28:38.8992|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-11-18 17:28:38.8992|ERROR|Wox_EasyTotp.Base32Encoding.CharToValue|Character is not a Base32 character.
Parameter name: c
2016-11-18 17:28:38.8992|ERROR|Wox_EasyTotp.Base32Encoding.CharToValue|
   at Wox_EasyTotp.Base32Encoding.CharToValue(Char c) in G:\Dev\Github\Wox-EasyTotp\Wox-EasyTotp\Base32Encoding.cs:line 115
```
6. Screenshot (optional):

**Comment by bao-qian** [comment]
delete `%APPDATA%\Wox`, backup before you do that

**Comment by bao-qian** [comment]
Wox_EasyTotp 
is this your own plugin?

**Comment by jaredbidlow** [comment]
No, https://github.com/thennequin/Wox-EasyTotp

**Comment by jaredbidlow** [comment]
Thanks for the help
