### ISSUE TITLE
Crashes upon Wox launch

### ISSUE THREAD

**Issue by spoedvarkie** [Wox-launcher/Wox#1133]
I am on Windows ROG Rampage 64bit, modified Windows 7 Professional. I tried reinstalling everything related to Wox, yet still no effect and still crashes.

Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 11/28/2016 17:35:33
Exception:
Wox.Plugin.Program
System.NullReferenceException
Object reference not set to an instance of an object.
   at Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 136
   at Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 102
   at Wox.Plugin.Program.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 94
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 27
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
[2016-11-28.txt](https://github.com/Wox-launcher/Wox/files/616745/2016-11-28.txt)

**Comment by Eligioo** [comment]
Also checked your %appdata%?

**Comment by spoedvarkie** [comment]
Hi sorry but checked it for?

**Comment by bao-qian** [comment]
delete `%APPDATA%\Wox`, backup before you do that

**Comment by spoedvarkie** [comment]
I shall try it when I'm at the computer again thanks
