### ISSUE TITLE
[Weather ] System.ArgumentException Illegal characters in path. 

### ISSUE THREAD

**Issue by Wickemu** [Wox-launcher/Wox#1184]
Tried installing the Weather plug-in, now it crashes every time I try to load Wox.

Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 01/11/2017 08:55:56
Exception:
mscorlib
System.ArgumentException
Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Wox.Core.Plugin.PluginsLoader.PythonPlugins(List`1 source, String pythonDirecotry) in C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:line 105
   at Wox.Core.Plugin.PluginsLoader.Plugins(List`1 metadatas, PluginsSettings settings) in C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:line 21
   at Wox.Core.Plugin.PluginManager.LoadPlugins(PluginsSettings settings) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 85
   at Wox.App.<OnStartup>b__8_0() in C:\projects\wox\Wox\App.xaml.cs:line 48
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 28
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
delete that plugin in %APPDATA%\Wox, backup before you do that
