### ISSUE TITLE
Wox 1.3.183 System.InvalidOperationException

### ISSUE THREAD

**Issue by rissson** [Wox-launcher/Wox#1209]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 01/27/2017 22:54:50
Exception:
PresentationFramework
System.InvalidOperationException
Can only call DragMove when primary mouse button is down.
   at System.Windows.Window.DragMove()
   at Wox.MainWindow.OnMouseDown(Object sender, MouseButtonEventArgs e) in C:\projects\wox\Wox\MainWindow.xaml.cs:line 109
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2017-01-27.txt](https://github.com/Wox-launcher/Wox/files/736359/2017-01-27.txt)

**Comment by bao-qian** [comment]
although there is no workaround now, but this issue is duplicate: #811
