### ISSUE TITLE
crash when attempting to execute "start microsoft-edge:"

### ISSUE THREAD

**Issue by 6d61726b760a** [Wox-launcher/Wox#1243]
Get the following error when using the Runner plugin to execute "start microsoft-edge:<myurl>"

Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\markv\AppData\Roaming\Wox\Logs\1.3.183\
[2017-02-20.txt]
2017-02-20.txt
2. copy below exception message

Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 02/20/2017 08:49:33
Exception:
System
System.ComponentModel.Win32Exception
The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Wox.Plugin.Runner.Runner.RunCommand(ActionContext e, Query query, Command command)
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 146
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

(https://github.com/Wox-launcher/Wox/files/786261/2017-02-20.txt)

**Comment by ghost** [comment]
should that be "microsoft-edge:" instead of "start microsoft-edge:" ?

i had a shortcut.lnk file before that used "microsoft-edge:" as the target... it worked ok when double clicking but when i tried it with wox it would only open edge every second time. if youre having the same problem then let me know because i found some other target link in the end that worked with wox

**Comment by bao-qian** [comment]
just download new build, you will be able to search uwp.
https://ci.appveyor.com/project/happlebao/wox/build/artifacts, then download Releases\Wox-1.3.xxx.exe

**Comment by 6d61726b760a** [comment]
perfect, thanks!

--
Mark V
[0409291645]
