### ISSUE TITLE
System.NullReferenceException Object reference not set to an instance of an object. at Wox.Plugin.Program.Main.DefaultProgramSources() in 

### ISSUE THREAD

**Issue by daimamiao** [Wox-launcher/Wox#1247]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 02/21/2017 11:33:16
Exception:
Wox.Plugin.Program
System.NullReferenceException
Object reference not set to an instance of an object.
   at Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 136
   at Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 102
   at Wox.Plugin.Program.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 94
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 27
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
[2017-02-21.txt](https://github.com/Wox-launcher/Wox/files/789007/2017-02-21.txt)

**Comment by bao-qian** [comment]
感谢汇报
试一下新 build https://ci.appveyor.com/project/happlebao/wox/build/artifacts 的  `Releases\Wox-1.3.xxx.exe`
或者
删除 `%APPDATA%\Wox`，删前记得备份
