### ISSUE TITLE
1.3.352 on Win7 Programs plugin exception

### ISSUE THREAD

**Issue by lmf-mx** [Wox-launcher/Wox#1251]
Programs and not weighting properly, log shows an exception from the Programs plugin.

```
comp
```
mostly shows results from Everything.

```
computers
```
brings Active Directory Users and Computers near the top under Sleep and Ease of Access Center.

Exception:
```
2017-02-23 00:49:14.0242|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2017-02-23 00:49:14.0242|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2017-02-23 00:49:14.0242|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <One or more errors occurred.>
2017-02-23 00:49:14.0242|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)>
2017-02-23 00:49:14.0242|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <Could not find Windows Runtime type 'Windows.ApplicationModel.Package'.>
2017-02-23 00:49:14.0242|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   at Wox.Plugin.Program.Programs.UWP.All()
   at Wox.Plugin.Program.Main.<>c__DisplayClass12_0.<IndexPrograms>b__1() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 82
   at System.Threading.Tasks.Task.Execute()>
2017-02-23 00:49:14.0242|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <Operation is not supported on this platform.>
2017-02-23 00:49:14.0242|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <>
2017-02-23 00:49:14.0242|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
```

Looks like it's trying to query installed UWP apps on a system that doesn't support them?

**Comment by bao-qian** [comment]
screenshots for com and computer?

**Comment by bao-qian** [comment]
and could you upload the full log?

**Comment by bao-qian** [comment]
try https://ci.appveyor.com/project/happlebao/wox/build/1.3.356/artifacts

**Comment by lmf-mx** [comment]
[2017-02-23.txt](https://github.com/Wox-launcher/Wox/files/796923/2017-02-23.txt)
![wox-1 3 352-comp](https://cloud.githubusercontent.com/assets/22751224/23266059/42868e9c-f9ac-11e6-9674-5152b5776717.png)
![wox-1 3 352-computers](https://cloud.githubusercontent.com/assets/22751224/23266060/428685fa-f9ac-11e6-9e3e-aba5da3b20df.png)

There are the requested screens and the log.

Tested 1.3.356, no exception and the result weights are back. They are also updating properly.
#1252 was happening as well since it was breaking early and never finishing.

Thank you.

**Comment by huaryliu** [comment]
问题仍然存在，还是一直在Indexing，搜索的结果，只能包含部分D盘的程序，有些搜索不出来，感觉是不是那个地方有缓存，把这个Indexing缓存下来的，不管如何重装，感觉Indexing是一样的。再就是日志的位置在哪？

**Comment by lmf-mx** [comment]
%APPDATA$\Wox\Logs
