### ISSUE TITLE
System.InvalidOperationException Can only call DragMove when primary mouse button is down.

### ISSUE THREAD

**Issue by TspeedSVT** [Wox-launcher/Wox#1269]
Wox version: 1.3.357
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True
Python Path: 
Everything SDK Path: C:\Users\Thomas\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 03/02/2017 08:24:15
Exception:
PresentationFramework
System.InvalidOperationException
Can only call DragMove when primary mouse button is down.
   at System.Windows.Window.DragMove()
   at Wox.MainWindow.OnMouseDown(Object sender, MouseButtonEventArgs e) in C:\projects\wox\Wox\MainWindow.xaml.cs:line 153
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2017-03-02.txt](https://github.com/Wox-launcher/Wox/files/813002/2017-03-02.txt)

**Comment by bao-qian** [comment]
duplicate #811 
and could you find a way to reproduce it on new environment (e.g. new windows account)?

**Comment by bao-qian** [comment]
please give followup feedback on #811
