### ISSUE TITLE
System.IO.IOException - Access to the path 'Themes' is denied

### ISSUE THREAD

**Issue by mabdelfattah** [Wox-launcher/Wox#1274]
Wox version: 1.3.357
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True
Python Path: pythonw.exe
Everything SDK Path: C:\Users\XXX\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 03/05/2017 15:06:22
Exception:
mscorlib
System.IO.IOException
Access to the path 'Themes' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:line 234

But weird enough, I do not know what is this user 'PAULB' that has squirrel !!

**Comment by bao-qian** [comment]
> I do not know what is this user 'PAULB' that has squirrel !!

don't worry, that's a bug in the auto update framework

> Access to the path 'Themes' is denied.

try delete
`%APPDATA%\Wox`
`%LOCALAPPDATA%\Wox`,
then reinstall

**Comment by bao-qian** [comment]
reopen is issue still exist
