### ISSUE TITLE
error

### ISSUE THREAD

**Issue by HBenzaoui** [Wox-launcher/Wox#1275]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 03/05/2017 15:12:06
Exception:
Wox.Core
System.IO.FileNotFoundException
Could not load file or assembly 'ICSharpCode.SharpZipLib, Version=0.86.0.518, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at Wox.Core.Plugin.PluginInstaller.UnZip(String zipedFile, String strDirectory, Boolean overWrite)
   at Wox.Core.Plugin.PluginInstaller.Install(String path) in C:\projects\wox\Wox.Core\Plugin\PluginInstaller.cs:line 23
   at Wox.PublicAPIInstance.<>c__DisplayClass13_0.<InstallPlugin>b__0()
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Wox.Plugin.PluginManagement.Main.<>c__DisplayClass12_1.<ResultForInstallPlugin>b__0(ActionContext c) in C:\projects\wox\Plugins\Wox.Plugin.PluginManagement\Main.cs:line 171
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index)
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
Reinstall woz

**Comment by bao-qian** [comment]
Reinstall wox
