### ISSUE TITLE
安装有道翻译之后，yd不能激活程序，Newtonsoft.Json版本不对

### ISSUE THREAD

**Issue by huaryliu** [Wox-launcher/Wox#1283]
![image](https://cloud.githubusercontent.com/assets/4917574/23688085/27c6b9ec-03ed-11e7-9fd8-44897a154b85.png)

**看日志是缺少Newtonsoft.Json, Version=8.0.0.0，搜索了一下发现现在用的都是9.0了，是不是这个插件需要基于9.0重新编译一下。**
2017-03-08 10:45:06.6217|ERROR|PluginManager.QueryForPlugin|-------------------------- Begin exception --------------------------
2017-03-08 10:45:06.8185|ERROR|PluginManager.QueryForPlugin|Exception for plugin <有道翻译> when query <yd>
2017-03-08 10:45:07.1972|ERROR|PluginManager.QueryForPlugin|Exception fulle name:
 <System.IO.FileNotFoundException>
2017-03-08 10:45:07.7770|ERROR|PluginManager.QueryForPlugin|Exception message:
 <Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.>
2017-03-08 10:45:07.7770|ERROR|PluginManager.QueryForPlugin|Exception stack trace:
 <   at Wox.Plugin.Youdao.Main.Query(Query query)
   at Wox.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPlugin>b__0() in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 178
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 19
   at Wox.Core.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 0>
2017-03-08 10:45:08.1948|ERROR|PluginManager.QueryForPlugin|Exception source:
 <Wox.Plugin.Youdao>
2017-03-08 10:45:08.6267|ERROR|PluginManager.QueryForPlugin|Exception target site:
 <System.Collections.Generic.List`1[Wox.Plugin.Result] Query(Wox.Plugin.Query)>
2017-03-08 10:45:08.6267|ERROR|PluginManager.QueryForPlugin|-------------------------- End exception --------------------------

**Comment by huaryliu** [comment]
已解决。
从github上重新编译一下dll即可，放在AppData\Roaming\Wox\Plugins\有道翻译-33a12dce-de19-4dba-b597-8758f1c9c37f下即可

。
有道翻译的地址如下：
https://github.com/Wox-launcher/Wox.Plugin.Youdao

**Comment by bao-qian** [comment]
@JianhuaLiu wox 版本？

**Comment by huaryliu** [comment]
1.3.385
应该是最新Build版本，好像调整了Newtonsoft.Json的引用版本，导致原来的引用8.0的有道插件，报错。

**Comment by bao-qian** [comment]
插件更新了，请删除旧的后（删除 %APPDATA%\Plugin\youdao）重装
