### ISSUE TITLE
Error during installation of Wox 1.3.183 on Windows 10 with No Python.

### ISSUE THREAD

**Issue by pjdurai** [Wox-launcher/Wox#1288]
Windows 10
Already installed Everything Successfully.
No Python installed.

2017-03-09 10:38:28.0386|ERROR|Wox.Core.Plugin.PluginsLoader.PythonPlugins|Python can't be found in PATH.
2017-03-09 10:38:28.0606|ERROR|Wox.Core.Plugin.PluginsLoader.PythonPlugins|

2017-03-09 10:38:28.2958|INFO|Wox.Plugin.Program.Main.Init|Preload 371 programs from cache
2017-03-09 10:38:28.4499|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2017-03-09 10:38:28.4499|ERROR|Wox.Plugin.BrowserBookmark.Bookmark.set_Name|Could not load type 'Wox.Infrastructure.Unidecoder' from assembly 'Wox.Infrastructure, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null'.
2017-03-09 10:38:28.4499|ERROR|Wox.Plugin.BrowserBookmark.Bookmark.set_Name|
   at Wox.Plugin.BrowserBookmark.Bookmark.set_Name(String value)
   at Wox.Plugin.BrowserBookmark.FirefoxBookmarks.<GetBookmarks>b__1(SQLiteDataReader x) in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:line 39
2017-03-09 10:38:28.4559|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2017-03-09 10:38:28.4559|ERROR|System.Threading.Tasks.Parallel+<>c__DisplayClass17_0`1.<ForWorker>b__1|Could not load type 'Wox.Infrastructure.Unidecoder' from assembly 'Wox.Infrastructure, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null'.
2017-03-09 10:38:28.4559|ERROR|System.Threading.Tasks.Parallel+<>c__DisplayClass17_0`1.<ForWorker>b__1|
   at Wox.Plugin.BrowserBookmark.Bookmark.set_Name(String value)
   at Wox.Plugin.BrowserBookmark.FirefoxBookmarks.<GetBookmarks>b__1(SQLiteDataReader x) in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:line 39
   at Wox.Plugin.BrowserBookmark.Extensions.<Select>d__0`1.MoveNext() in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:line 85
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Wox.Plugin.BrowserBookmark.FirefoxBookmarks.GetBookmarks() in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:line 39
   at Wox.Plugin.BrowserBookmark.Main.Init(PluginInitContext context) in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\Main.cs:line 24
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 28
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
2017-03-09 10:38:28.5850|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2017-03-09 10:38:28.5850|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|One or more errors occurred.
2017-03-09 10:38:28.5850|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2017-03-09 10:38:28.5850|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|Could not load type 'Wox.Infrastructure.Unidecoder' from assembly 'Wox.Infrastructure, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null'.
2017-03-09 10:38:28.5850|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|
   at Wox.Plugin.BrowserBookmark.Bookmark.set_Name(String value)
   at Wox.Plugin.BrowserBookmark.FirefoxBookmarks.<GetBookmarks>b__1(SQLiteDataReader x) in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:line 39
   at Wox.Plugin.BrowserBookmark.Extensions.<Select>d__0`1.MoveNext() in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:line 85
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Wox.Plugin.BrowserBookmark.FirefoxBookmarks.GetBookmarks() in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:line 39
   at Wox.Plugin.BrowserBookmark.Main.Init(PluginInitContext context) in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\Main.cs:line 24
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 28
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
2017-03-09 10:38:28.5970|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2017-03-09 10:38:28.5970|ERROR|System.Threading.Tasks.Parallel.ForWorker|One or more errors occurred.
2017-03-09 10:38:28.5970|ERROR|System.Threading.Tasks.Parallel.ForWorker|
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
2017-03-09 10:38:28.5970|ERROR|System.Threading.Tasks.Parallel.ForWorker|Could not load type 'Wox.Infrastructure.Unidecoder' from assembly 'Wox.Infrastructure, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null'.
2017-03-09 10:38:28.5970|ERROR|System.Threading.Tasks.Parallel.ForWorker|
   at Wox.Plugin.BrowserBookmark.Bookmark.set_Name(String value)
   at Wox.Plugin.BrowserBookmark.FirefoxBookmarks.<GetBookmarks>b__1(SQLiteDataReader x) in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:line 39
   at Wox.Plugin.BrowserBookmark.Extensions.<Select>d__0`1.MoveNext() in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:line 85
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Wox.Plugin.BrowserBookmark.FirefoxBookmarks.GetBookmarks() in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:line 39
   at Wox.Plugin.BrowserBookmark.Main.Init(PluginInitContext context) in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\Main.cs:line 24
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 28
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
2017-03-09 10:38:28.5970|FATAL|Wox.Helper.ErrorReporting.Report|
## Exception

```
System.TypeLoadException: Could not load type 'Wox.Infrastructure.Unidecoder' from assembly 'Wox.Infrastructure, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null'.
   Source: Wox.Plugin.BrowserBookmark
   TargetAssembly: Wox.Plugin.BrowserBookmark, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Wox.Plugin.BrowserBookmark.dll
   TargetSite: Void set_Name(System.String)
   at Wox.Plugin.BrowserBookmark.Bookmark.set_Name(String value)
   at Wox.Plugin.BrowserBookmark.FirefoxBookmarks.<GetBookmarks>b__1(SQLiteDataReader x) in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:line 39
   at Wox.Plugin.BrowserBookmark.Extensions.<Select>d__0`1.MoveNext() in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:line 85
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Wox.Plugin.BrowserBookmark.FirefoxBookmarks.GetBookmarks() in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:line 39
   at Wox.Plugin.BrowserBookmark.Main.Init(PluginInitContext context) in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\Main.cs:line 24
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 28
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

System.AggregateException: One or more errors occurred.
   Source: mscorlib
   TargetAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
   TargetModule: CommonLanguageRuntimeLibrary
   TargetSite: Void ThrowIfExceptional(Boolean)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 94
   at Wox.App.<OnStartup>b__8_0() in C:\projects\wox\Wox\App.xaml.cs:line 53
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 28
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

## Environment

* Command Line: "C:\Users\i844441\AppData\Local\Wox\app-1.3.183\Wox.exe" --squirrel-firstrun
* Timestamp: 03/09/2017 10:38:28
* IntPtr Length: 8
* System Version: Microsoft Windows NT 10.0.10586.0
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.6.01038
   * v4 Full 4.6.01038
   * v4.0 Client 4.0.0.0

## Assemblies - Wox.exe

* Wox, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\Wox.exe)
* Wox.Infrastructure, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\Wox.Infrastructure.dll)
* Wox.Plugin, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\Wox.Plugin.dll)
* Wox.Core, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\Wox.Core.dll)
* Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\Newtonsoft.Json.dll)
* HelloWorldCSharp, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\Plugins\HelloWorldCSharp\HelloWorldCSharp.dll)
* Wox.Plugin.Caculator, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
* YAMP, Version=1.4.0.22422, Culture=neutral, PublicKeyToken=null (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Caculator\YAMP.dll)
* Wox.Plugin.Color, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
* Wox.Plugin.ControlPanel, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
* Wox.Plugin.Everything, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
* Wox.Plugin.Folder, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
* Wox.Plugin.PluginIndicator, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
* Wox.Plugin.PluginManagement, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
* Wox.Plugin.Program, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
* Wox.Plugin.Shell, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
* WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\WindowsInput.dll)
* Wox.Plugin.Sys, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
* Wox.Plugin.Url, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
* Wox.Plugin.WebSearch, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
* Wox.Plugin.BrowserBookmark, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\i844441\AppData\Roaming\Wox\Plugins\Browser Bookmarks-5677ceef-8153-4582-8965-f1ead317b202\Wox.Plugin.browserBookmark.dll)
* NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\NLog.dll)
* NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\NHotkey.dll)
* NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\i844441\AppData\Local\Wox\app-1.3.183\NHotkey.Wpf.dll)
* System.Data.SQLite, Version=1.0.94.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139 (C:\Users\i844441\AppData\Roaming\Wox\Plugins\Browser Bookmarks-5677ceef-8153-4582-8965-f1ead317b202\System.Data.SQLite.dll)
* mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
* PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
* System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
* PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
* System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
* System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
* System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
* System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
* System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
* System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
* System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
* PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)
* System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll)
* System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll)

2017-03-09 10:38:57.5042|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2017-03-09 10:38:57.5042|ERROR|System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment|Application identity is not set.
2017-03-09 10:38:57.5042|ERROR|System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment|
   at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()

Message from the Dialog Box

Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 03/09/2017 10:38:28
Exception:
Wox.Plugin.BrowserBookmark
System.TypeLoadException
Could not load type 'Wox.Infrastructure.Unidecoder' from assembly 'Wox.Infrastructure, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null'.
   at Wox.Plugin.BrowserBookmark.Bookmark.set_Name(String value)
   at Wox.Plugin.BrowserBookmark.FirefoxBookmarks.<GetBookmarks>b__1(SQLiteDataReader x) in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:line 39
   at Wox.Plugin.BrowserBookmark.Extensions.<Select>d__0`1.MoveNext() in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:line 85
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Wox.Plugin.BrowserBookmark.FirefoxBookmarks.GetBookmarks() in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:line 39
   at Wox.Plugin.BrowserBookmark.Main.Init(PluginInitContext context) in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\Main.cs:line 24
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 28
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by bao-qian** [comment]
delete BrowserBookmark.Bookmark from %APPDATA%\wox\plugins
