### ISSUE TITLE
System.IO.IOException Access to the path 'Plugins' / 'Themes' is denied. at System.IO.DirectoryInfo.MoveTo(String destDirName)

### ISSUE THREAD

**Issue by TriLRC** [Wox-launcher/Wox#1292]
[2017-03-11.txt](https://github.com/Wox-launcher/Wox/files/835485/2017-03-11.txt)
Wox version: 1.3.357
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True
Python Path:
Everything SDK Path: C:\Users\Ganesh Prasad\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 03/21/2017 23:11:36
Exception:
mscorlib
System.IO.IOException
Access to the path 'Plugins' is denied.
at System.IO.DirectoryInfo.MoveTo(String destDirName)
at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<b__1d>d__22.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:line 234

**Comment by bao-qian** [comment]
workaround:
delete %LOCALAPPDATA%\Wox
try disable your antivirus


probably related: https://github.com/atom/atom/issues/10383

**Comment by bao-qian** [comment]
for anybody still have this problem:
please
1. upload `%APPDATA%\Wox\Logs\date.txt`
2. upload `%LOCALAPPDATA%\SquirrelTemp\SquirrelSetup.log`
3. try delete `%LOCALAPPDATA%\Wox and report back`
4. try disable your antivirus and report back

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
