### ISSUE TITLE
System IO Exception

### ISSUE THREAD

**Issue by ganeshpprasad** [Wox-launcher/Wox#1312]
## Known problems for 1.3.183:

1. `System.NullReferenceException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.357
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: 设置 http 代理

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

Wox version: 1.3.357
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True
Python Path: 
Everything SDK Path: C:\Users\Ganesh Prasad\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 03/21/2017 23:11:36
Exception:
mscorlib
System.IO.IOException
Access to the path 'Plugins' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:line 234

**Comment by bao-qian** [comment]
1. whole log? 
2. duplicate #1292 
3. please reply in #1292
