### ISSUE TITLE
Logging an Error for 1.4.357

### ISSUE THREAD

**Issue by robertdefilippi** [Wox-launcher/Wox#1322]
Wox version: 1.3.357
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True
Python Path: 
Everything SDK Path: C:\Users\RRFD\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 03/29/2017 06:32:23
Exception:
mscorlib
System.IO.IOException
Access to the path 'Plugins' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:line 234

**Comment by bao-qian** [comment]
duplicated #1292
