### ISSUE TITLE
Wox got an error

### ISSUE THREAD

**Issue by arnonuem** [Wox-launcher/Wox#1332]
Unfortunately i was not able to attach the logfile because Github always complained :+1: 
"Something went really wrong, and we can’t process that file. Try again."
I tried txt file and i also tried a zipped version of it. Sorry about that.

Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 03/31/2017 18:41:55
Exception:
mscorlib
System.Threading.Tasks.TaskCanceledException
A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<GitHubUpdateManager>d__2b.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.Factory.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Wox.Core.Updater.<UpdateApp>d__0.MoveNext() in C:\projects\wox\Wox.Core\Updater.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
https://ci.appveyor.com/project/happlebao/wox/build/1.3.414/artifacts
