### ISSUE TITLE
Wox version: 1.3.183 error in win10

### ISSUE THREAD

**Issue by kutianwulei** [Wox-launcher/Wox#1343]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14931.0
Date: 04/06/2017 10:45:01
Exception:
Wox.Plugin.Program
System.NullReferenceException
Object reference not set to an instance of an object.
   at Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 136
   at Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 102
   at Wox.Plugin.Program.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 94
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 27
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by bao-qian** [comment]
https://ci.appveyor.com/project/happlebao/wox/build/1.3.423/artifacts
