### ISSUE TITLE
Wox出错啦

### ISSUE THREAD

**Issue by yurenzhen** [Wox-launcher/Wox#1367]
[2017-04-11.txt](https://github.com/Wox-launcher/Wox/files/913112/2017-04-11.txt)

Wox version: 1.3.357
OS Version: Microsoft Windows NT 10.0.10586.0
IntPtr Length: 8
x64: True
Python Path: pythonw.exe
Everything SDK Path: C:\Users\Renzhen\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 04/11/2017 20:08:20
Exception:
mscorlib
System.Threading.Tasks.TaskCanceledException
A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<GitHubUpdateManager>d__2b.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.Factory.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Wox.Core.Updater.<UpdateApp>d__0.MoveNext() in C:\projects\wox\Wox.Core\Updater.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) # #

**Comment by bao-qian** [comment]
Try latest pre release.

**Comment by bao-qian** [comment]
https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424
