### ISSUE TITLE
Wox 1.3.183 Exception: Newtonsoft.Json

### ISSUE THREAD

**Issue by rissson** [Wox-launcher/Wox#1369]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.15063.0
Date: 04/11/2017 18:31:37
Exception:
Newtonsoft.Json
Newtonsoft.Json.JsonReaderException
Unterminated string. Expected delimiter: ". Path 'Items[37].Query', line 153, position 10.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseProperty()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Wox.Infrastructure.Storage.JsonStrorage`1.Deserialize(String searlized) in C:\projects\wox\Wox.Infrastructure\Storage\JsonStorage.cs:line 58
   at Wox.Infrastructure.Storage.JsonStrorage`1.Load() in C:\projects\wox\Wox.Infrastructure\Storage\JsonStorage.cs:line 40
   at Wox.ViewModel.MainViewModel..ctor(Settings settings) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 62
   at Wox.App.<OnStartup>b__8_0() in C:\projects\wox\Wox\App.xaml.cs:line 49
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 28
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2017-04-11.txt](https://github.com/Wox-launcher/Wox/files/913986/2017-04-11.txt)
## Known problems for 1.3.183:

1. `System.NullReferenceException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by bao-qian** [comment]
try https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424

**Comment by lances101** [comment]
Closed due to inactivity. Author may reopen the issue if needed.
