### ISSUE TITLE
Wox Clock Bug

### ISSUE THREAD

**Issue by benyaminl** [Wox-launcher/Wox#1379]
Wox version: 1.3.424
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
IntPtr Length: 8
x64: True

Python Path: C:\Users\Ben\AppData\Local\Programs\Python\Python35-32\pythonw.exe
Everything SDK Path: C:\Users\Ben\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 04/19/2017 01:17:18
Exception:
Wox.Plugin.SimpleClock
System.TypeLoadException
Could not load type 'Wox.Infrastructure.Storage.Storage`1' from assembly 'Wox.Infrastructure, Version=1.3.424.0, Culture=neutral, PublicKeyToken=null'.
   at Wox.Plugin.SimpleClock.Commands.Alarm.AlarmTimerCommand.CommandExecution(List`1 args)
   at Wox.Plugin.Boromak.CommandHandlerBase.Execute(List`1 args) in C:\Users\Boris\Documents\SourceControl\Wox\Wox.Plugin.SimpleClock\Wox.Plugin.Boromak\Wox.Plugin.Boromak\CommandHandlerBase.cs:line 166
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 146
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2017-04-19.txt](https://github.com/Wox-launcher/Wox/files/930661/2017-04-19.txt)

**Comment by lances101** [comment]
SimpleClock is not a default Wox plugin. [Please use the plugin's repository](https://github.com/lances101/Wox.Plugin.SimpleClock). There is already an issue open about Wox not being compatible with the latest version - https://github.com/lances101/Wox.Plugin.SimpleClock/issues/5

Closed due to being related to a third-party plugin.
