### ISSUE TITLE
Everything plugin stopped working

### ISSUE THREAD

**Issue by kastnerp** [Wox-launcher/Wox#1383]
Hi everyone,

the Everything plugin doesn't seem to work anymore. Everything itself works just fine. Any hints how I could solve this?

1. Wox version / commit number: I tried both 1.3.424 and 1.3.183
2. Steps to **reproduce** the bug: Search results just don't show up
3. Windows version: Windows 10, latest updates
4. Exception: No exceptions are thrown, I can see the plugin in the plugin tab and it shows a init time of 26 ms.
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`): This logs folder doesn't exist on my machine, just checked with Everything.

Thank you,

Patrick

**Comment by rodcloutier** [comment]
Same thing here. Calculator does not work either, nor any of the built in commands 

Log:
```
2017-04-19 14:23:08.1117|INFO|App.OnStartup|Begin Wox startup ----------------------------------------------------
2017-04-19 14:23:08.1307|INFO|App.OnStartup|Runtime info:
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True
2017-04-19 14:23:08.1307|INFO|BinaryStorage.TryLoad|Cache file not exist, load default data
2017-04-19 14:23:08.1618|INFO|BinaryStorage.TryLoad|Cache file not exist, load default data
2017-04-19 14:23:08.1828|INFO|ImageLoader.Initialize|Preload images cost <24ms>
2017-04-19 14:23:08.1938|INFO|ImageLoader.Initialize|Number of preload images is <0>
2017-04-19 14:23:08.1938|INFO|Wox.Infrastructure.Alphabet.Initialize|Preload pinyin cache <35ms>
2017-04-19 14:23:08.1938|INFO|Wox.Infrastructure.Alphabet.Initialize|Number of preload pinyin combination<0>
2017-04-19 14:23:08.5000|INFO|BinaryStorage.TryLoad|Cache file not exist, load default data
2017-04-19 14:23:08.5050|INFO|BinaryStorage.TryLoad|Cache file not exist, load default data
2017-04-19 14:23:08.5050|INFO|Wox.Plugin.Program.Main|Preload programs cost <9ms>
2017-04-19 14:23:08.5050|INFO|Wox.Plugin.Program.Main|Number of preload win32 programs <0>
2017-04-19 14:23:08.5050|INFO|Wox.Plugin.Program.Main|Number of preload uwps <0>
2017-04-19 14:23:08.7372|ERROR|UWP.LogoPathFromUri| <Windows.MiracastView_cw5n1h2txyewy!Microsoft.Windows.MiracastView> can't find logo uri for <SmallLogo.png>, Package location <C:\Windows\MiracastView>.
2017-04-19 14:23:08.8923|ERROR|UWP.ResourceFromPri|-------------------------- Begin exception --------------------------2017-04-19 14:23:08.8953|ERROR|UWP.ResourceFromPri|Load pri failed <@{Microsoft.3DBuilder_14.0.1031.0_x64__8wekyb3d8bbwe? ms-resource:///resources/appDescription}> with HResult <2147942522> and location <C:\Program Files\WindowsApps\Microsoft.3DBuilder_14.0.1031.0_x64__8wekyb3d8bbwe>.
2017-04-19 14:23:08.8953|ERROR|UWP.ResourceFromPri|Exception fulle name:
 <System.Runtime.InteropServices.COMException>
2017-04-19 14:23:08.8953|ERROR|UWP.ResourceFromPri|Exception message:
 <Unspecified error

'Microsoft Corporation' violates pattern constraint of '\bms-resource:.{1,256}'.
>
2017-04-19 14:23:08.8953|ERROR|UWP.ResourceFromPri|Exception stack trace:
 <>
2017-04-19 14:23:08.9103|ERROR|UWP.ResourceFromPri|Exception source:
 <>
2017-04-19 14:23:08.9103|ERROR|UWP.ResourceFromPri|Exception target site:
 <>
2017-04-19 14:23:08.9103|ERROR|UWP.ResourceFromPri|Exception HResult:
 <-2147024774>
2017-04-19 14:23:08.9103|ERROR|UWP.ResourceFromPri|-------------------------- End exception --------------------------
2017-04-19 14:23:08.9253|ERROR|UWP.ResourceFromPri|-------------------------- Begin exception --------------------------2017-04-19 14:23:08.9253|ERROR|UWP.ResourceFromPri|Load pri failed <@{Microsoft.MicrosoftOfficeHub_17.8107.7600.0_x64__8wekyb3d8bbwe? ms-resource://Microsoft.MicrosoftOfficeHub/officehubintl/AppManifest_GetOffice_Description}> with HResult <2147942522> and location <C:\Program Files\WindowsApps\Microsoft.MicrosoftOfficeHub_17.8107.7600.0_x64__8wekyb3d8bbwe>.2017-04-19 14:23:08.9253|ERROR|UWP.ResourceFromPri|Exception fulle name:
 <System.Runtime.InteropServices.COMException>
2017-04-19 14:23:08.9253|ERROR|UWP.ResourceFromPri|Exception message:
 <Unspecified error

'Microsoft Corporation' violates pattern constraint of '\bms-resource:.{1,256}'.
>
2017-04-19 14:23:08.9253|ERROR|UWP.ResourceFromPri|Exception stack trace:
 <>
2017-04-19 14:23:08.9443|ERROR|UWP.ResourceFromPri|Exception source:
 <>
2017-04-19 14:23:08.9443|ERROR|UWP.ResourceFromPri|Exception target site:
 <>
2017-04-19 14:23:08.9443|ERROR|UWP.ResourceFromPri|Exception HResult:
 <-2147024774>
2017-04-19 14:23:08.9583|ERROR|UWP.ResourceFromPri|-------------------------- End exception --------------------------
2017-04-19 14:23:08.9583|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2017-04-19 14:23:08.9583|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2017-04-19 14:23:08.9583|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.Runtime.InteropServices.COMException>
2017-04-19 14:23:08.9764|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <Unspecified error

'Windows Photo DRM Viewer' violates pattern constraint of '\bms-resource:.{1,256}'.
>
2017-04-19 14:23:08.9764|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   at Shell.IShellLinkW.GetDescription(StringBuilder pszName, Int32 cch)
   at Wox.Plugin.Program.Programs.Win32.LnkProgram(String path) in C:\projects\wox\Plugins\Wox.Plugin.Program\Programs\Win32.cs:line 162>
2017-04-19 14:23:08.9764|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <>
2017-04-19 14:23:08.9904|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <Void GetDescription(System.Text.StringBuilder, Int32)>
2017-04-19 14:23:08.9904|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2147467259>
2017-04-19 14:23:08.9904|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2017-04-19 14:23:08.9904|ERROR|Win32.LnkProgram|-------------------------- Begin exception --------------------------
2017-04-19 14:23:09.0054|ERROR|Win32.LnkProgram|COMException when parsing shortcut <C:\ProgramData\Microsoft\Windows\Start Menu\Programs\MiracastView.lnk> with HResult <-2147467259>
2017-04-19 14:23:09.0054|ERROR|Win32.LnkProgram|Exception fulle name:
 <System.Runtime.InteropServices.COMException>
2017-04-19 14:23:09.0054|ERROR|Win32.LnkProgram|Exception message:
 <Unspecified error

'Windows Photo DRM Viewer' violates pattern constraint of '\bms-resource:.{1,256}'.
>
2017-04-19 14:23:09.0194|ERROR|Win32.LnkProgram|Exception stack trace:
 <   at Shell.IShellLinkW.GetDescription(StringBuilder pszName, Int32 cch)
   at Wox.Plugin.Program.Programs.Win32.LnkProgram(String path) in C:\projects\wox\Plugins\Wox.Plugin.Program\Programs\Win32.cs:line 162>
2017-04-19 14:23:09.0194|INFO|PluginManager.InitializePlugins|Total init cost for <System Commands> is <1ms>
2017-04-19 14:23:09.0194|INFO|PluginManager.InitializePlugins|Total init cost for <Program> is <25ms>
2017-04-19 14:23:09.0194|INFO|PluginManager.InitializePlugins|Total init cost for <Folder> is <4ms>
2017-04-19 14:23:09.0194|ERROR|Win32.LnkProgram|Exception source:
 <>
2017-04-19 14:23:09.0194|INFO|PluginManager.InitializePlugins|Total init cost for <Calculator> is <60ms>
2017-04-19 14:23:09.0194|INFO|PluginManager.InitializePlugins|Total init cost for <Shell> is <9ms>
2017-04-19 14:23:09.0194|INFO|PluginManager.InitializePlugins|Total init cost for <Colors> is <1ms>
2017-04-19 14:23:09.0194|INFO|PluginManager.InitializePlugins|Total init cost for <Wox Plugin Management> is <1ms>
2017-04-19 14:23:09.0194|INFO|PluginManager.InitializePlugins|Total init cost for <Plugin Indicator> is <1ms>
2017-04-19 14:23:09.0194|INFO|PluginManager.InitializePlugins|Total init cost for <URL> is <1ms>
2017-04-19 14:23:09.0344|INFO|PluginManager.InitializePlugins|Total init cost for <Web Searches> is <11ms>
2017-04-19 14:23:09.0344|INFO|PluginManager.InitializePlugins|Total init cost for <Hello World Python> is <0ms>
2017-04-19 14:23:09.0344|ERROR|Win32.LnkProgram|Exception target site:
 <Void GetDescription(System.Text.StringBuilder, Int32)>
2017-04-19 14:23:09.0344|INFO|PluginManager.InitializePlugins|Total init cost for <Everything> is <25ms>
2017-04-19 14:23:09.0724|ERROR|Win32.LnkProgram|Exception HResult:
 <-2147467259>
2017-04-19 14:23:09.0724|ERROR|Win32.LnkProgram|-------------------------- End exception --------------------------
2017-04-19 14:23:09.0974|INFO|Wox.Plugin.Program.Main|Program index cost <580ms>
2017-04-19 14:23:09.1225|INFO|PluginManager.InitializePlugins|Total init cost for <Control Panel> is <100ms>
2017-04-19 14:23:09.1225|INFO|App.OnStartup|Dependencies Info:
Python Path: pythonw.exe
Everything SDK Path: C:\Users\rcloutier2\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
2017-04-19 14:23:09.1375|INFO|App.OnStartup|End Wox startup ----------------------------------------------------
2017-04-19 14:23:09.1375|INFO|App.OnStartup|Startup cost <1108ms>
2017-04-19 14:23:09.3927|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2017-04-19 14:23:09.3967|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2017-04-19 14:23:09.3967|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.IO.FileNotFoundException>
2017-04-19 14:23:09.3967|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <Could not find file 'C:\Users\rcloutier2\AppData\Local\Wox\packages\.betaId'.>
2017-04-19 14:23:09.3967|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)>
2017-04-19 14:23:09.4097|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <mscorlib>
2017-04-19 14:23:09.4097|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <Void WinIOError(Int32, System.String)>
2017-04-19 14:23:09.4097|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2147024894>
2017-04-19 14:23:09.4097|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2017-04-19 14:23:09.7589|INFO|Updater.UpdateApp|Future Release <{
  "SHA1": "8CE02A3E4D480E4C221F141120535DE3F9857B5E",
  "BaseUrl": null,
  "Filename": "Wox-1.3.183-full.nupkg",
  "Query": null,
  "Filesize": 4724719,
  "IsDelta": false,
  "StagingPercentage": null
}
```

**Comment by FGummesson** [comment]
Same problem for me. No results are shown. If any help, i'll paste my log from today too. 

```
2017-08-30 08:36:19.5344|INFO|App.OnStartup|Begin Wox startup ----------------------------------------------------
2017-08-30 08:36:19.5544|INFO|App.OnStartup|Runtime info:
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.10586.0
IntPtr Length: 8
x64: True
2017-08-30 08:36:20.7123|INFO|Wox.Infrastructure.Alphabet.Initialize|Preload pinyin cache <1109ms>
2017-08-30 08:36:20.7123|INFO|Wox.Infrastructure.Alphabet.Initialize|Number of preload pinyin combination<0>
2017-08-30 08:36:21.0664|ERROR|PluginConfig.GetPluginMetadata|Didn't find config file <C:\Users\FIGU\AppData\Roaming\Wox\Plugins\Wox.Plugin.Runner-4041a2e4-e30a-440c-9cdc-6e9f5216183d\plugin.json>
2017-08-30 08:36:21.0664|ERROR|PluginConfig.GetPluginMetadata|Didn't find config file <C:\Users\FIGU\AppData\Roaming\Wox\Plugins\Wox.Plugin.Runner-6b315270-a412-481d-b89e-d09b164a0712\plugin.json>
2017-08-30 08:36:21.2425|INFO|ImageLoader.Initialize|Preload images cost <1658ms>
2017-08-30 08:36:21.2485|INFO|ImageLoader.Initialize|Number of preload images is <200>
2017-08-30 08:36:21.3436|INFO|Wox.Plugin.Program.Main|Preload programs cost <3ms>
2017-08-30 08:36:21.3436|INFO|Wox.Plugin.Program.Main|Number of preload win32 programs <253>
2017-08-30 08:36:21.3436|INFO|Wox.Plugin.Program.Main|Number of preload uwps <35>
2017-08-30 08:36:21.4852|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2017-08-30 08:36:21.4852|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2017-08-30 08:36:21.4987|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.ArgumentException>
2017-08-30 08:36:21.4987|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <Value does not fall within the expected range.>
2017-08-30 08:36:21.5367|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   at Shell.IShellLinkW.Resolve(_RemotableHandle& hwnd, UInt32 fFlags)
   at Wox.Plugin.Program.Programs.Win32.LnkProgram(String path) in C:\projects\wox\Plugins\Wox.Plugin.Program\Programs\Win32.cs:line 149>
2017-08-30 08:36:21.5437|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <Wox.Plugin.Program>
2017-08-30 08:36:21.5437|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <Void Resolve(Shell._RemotableHandle ByRef, UInt32)>
2017-08-30 08:36:21.5577|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2147024809>
2017-08-30 08:36:21.5577|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2017-08-30 08:36:21.5728|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2017-08-30 08:36:21.5728|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2017-08-30 08:36:21.5728|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.BadImageFormatException>
2017-08-30 08:36:21.5918|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <Could not load file or assembly 'Wox.Skype, Version=1.0.0.96, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.>
2017-08-30 08:36:21.5918|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)>
2017-08-30 08:36:21.6078|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <mscorlib>
2017-08-30 08:36:21.6078|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <System.Reflection.RuntimeAssembly _nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)>
2017-08-30 08:36:21.6218|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2147024885>
2017-08-30 08:36:21.6218|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2017-08-30 08:36:21.6378|ERROR|Win32.LnkProgram|-------------------------- Begin exception --------------------------
2017-08-30 08:36:21.6378|ERROR|Win32.LnkProgram|Exception when parsing shortcut <C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Desktop.lnk>
2017-08-30 08:36:21.6518|ERROR|Win32.LnkProgram|Exception fulle name:
 <System.ArgumentException>
2017-08-30 08:36:21.6518|ERROR|Win32.LnkProgram|Exception message:
 <Value does not fall within the expected range.>
2017-08-30 08:36:21.6678|ERROR|Win32.LnkProgram|Exception stack trace:
 <   at Shell.IShellLinkW.Resolve(_RemotableHandle& hwnd, UInt32 fFlags)
   at Wox.Plugin.Program.Programs.Win32.LnkProgram(String path) in C:\projects\wox\Plugins\Wox.Plugin.Program\Programs\Win32.cs:line 149>
2017-08-30 08:36:21.6678|ERROR|Win32.LnkProgram|Exception source:
 <Wox.Plugin.Program>
2017-08-30 08:36:21.6678|ERROR|Win32.LnkProgram|Exception target site:
 <Void Resolve(Shell._RemotableHandle ByRef, UInt32)>
2017-08-30 08:36:21.6848|ERROR|Win32.LnkProgram|Exception HResult:
 <-2147024809>
2017-08-30 08:36:21.6848|ERROR|Win32.LnkProgram|-------------------------- End exception --------------------------
2017-08-30 08:36:21.6988|ERROR|UWP.LogoPathFromUri| <windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel> can't find logo uri for <SmallLogo.png>, Package location <C:\Windows\ImmersiveControlPanel>.
2017-08-30 08:36:21.6988|ERROR|PluginsLoader.CSharpPlugins|-------------------------- Begin exception --------------------------
2017-08-30 08:36:21.7129|ERROR|PluginsLoader.CSharpPlugins|Couldn't load assembly for Wox.Skype
2017-08-30 08:36:21.7129|ERROR|PluginsLoader.CSharpPlugins|Exception fulle name:
 <System.BadImageFormatException>
2017-08-30 08:36:21.7279|ERROR|PluginsLoader.CSharpPlugins|Exception message:
 <Could not load file or assembly 'Wox.Skype, Version=1.0.0.96, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.>
2017-08-30 08:36:21.7279|ERROR|PluginsLoader.CSharpPlugins|Exception stack trace:
 <   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Wox.Core.Plugin.PluginsLoader.<>c__DisplayClass4_0.<CSharpPlugins>b__1() in C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:line 48>
2017-08-30 08:36:21.7459|ERROR|PluginsLoader.CSharpPlugins|Exception source:
 <mscorlib>
2017-08-30 08:36:21.7459|ERROR|PluginsLoader.CSharpPlugins|Exception target site:
 <System.Reflection.RuntimeAssembly _nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)>
2017-08-30 08:36:21.7639|ERROR|PluginsLoader.CSharpPlugins|Exception HResult:
 <-2147024885>
2017-08-30 08:36:21.7639|ERROR|PluginsLoader.CSharpPlugins|-------------------------- End exception --------------------------
2017-08-30 08:36:21.7834|ERROR|PluginsLoader.PythonPlugins|Can't find python executable in <b 
2017-08-30 08:36:21.8219|ERROR|UWP.ResourceFromPri|-------------------------- Begin exception --------------------------
2017-08-30 08:36:21.8219|ERROR|UWP.ResourceFromPri|Load pri failed <@{Microsoft.WindowsFeedback_10.0.10586.0_neutral_neutral_cw5n1h2txyewy? ms-resource:///resources/FeedbackApp.Resources/AppName/Text}> with HResult <2147957527> and location <C:\Windows\SystemApps\WindowsFeedback_cw5n1h2txyewy>.
2017-08-30 08:36:21.8369|ERROR|UWP.ResourceFromPri|Exception fulle name:
 <System.Runtime.InteropServices.COMException>
2017-08-30 08:36:21.8369|ERROR|UWP.ResourceFromPri|Exception message:
 <Unspecified error

'Windows Feedback' violates pattern constraint of '\bms-resource:.{1,256}'.
>
2017-08-30 08:36:21.8219|ERROR|UWP.LogoPathFromUri| <Windows.MiracastView_cw5n1h2txyewy!Microsoft.Windows.MiracastView> can't find logo uri for <SmallLogo.png>, Package location <C:\Windows\MiracastView>.
2017-08-30 08:36:21.8569|ERROR|UWP.ResourceFromPri|Exception stack trace:
 <>
2017-08-30 08:36:21.8810|ERROR|UWP.ResourceFromPri|Exception source:
 <>
2017-08-30 08:36:21.8930|ERROR|UWP.ResourceFromPri|Exception target site:
 <>
2017-08-30 08:36:21.9090|ERROR|UWP.ResourceFromPri|Exception HResult:
 <-2147009769>
2017-08-30 08:36:21.9220|ERROR|UWP.ResourceFromPri|-------------------------- End exception --------------------------
2017-08-30 08:36:21.9380|ERROR|UWP.ResourceFromPri|-------------------------- Begin exception --------------------------
2017-08-30 08:36:21.9500|ERROR|UWP.ResourceFromPri|Load pri failed <@{Microsoft.WindowsFeedback_10.0.10586.0_neutral_neutral_cw5n1h2txyewy? ms-resource:///resources/FeedbackApp.Resources/AppDescription}> with HResult <2147957527> and location <C:\Windows\SystemApps\WindowsFeedback_cw5n1h2txyewy>.
2017-08-30 08:36:21.9620|ERROR|UWP.ResourceFromPri|Exception fulle name:
 <System.Runtime.InteropServices.COMException>
2017-08-30 08:36:21.9620|ERROR|UWP.ResourceFromPri|Exception message:
 <NamedResource Not Found. (Exception from HRESULT: 0x80073B17)>
2017-08-30 08:36:21.9860|ERROR|UWP.ResourceFromPri|Exception stack trace:
 <>
2017-08-30 08:36:21.9960|ERROR|UWP.ResourceFromPri|Exception source:
 <>
2017-08-30 08:36:21.9960|ERROR|UWP.ResourceFromPri|Exception target site:
 <>
2017-08-30 08:36:22.0171|ERROR|UWP.ResourceFromPri|Exception HResult:
 <-2147009769>
2017-08-30 08:36:22.0281|ERROR|UWP.ResourceFromPri|-------------------------- End exception --------------------------
2017-08-30 08:36:22.0281|ERROR|UWP.ResourceFromPri|-------------------------- Begin exception --------------------------
2017-08-30 08:36:22.0491|ERROR|UWP.ResourceFromPri|Load pri failed <@{Microsoft.3DBuilder_14.1.1302.0_x64__8wekyb3d8bbwe? ms-resource:///resources/appDescription}> with HResult <2147942522> and location <C:\Program Files\WindowsApps\Microsoft.3DBuilder_14.1.1302.0_x64__8wekyb3d8bbwe>.
2017-08-30 08:36:22.0601|ERROR|UWP.ResourceFromPri|Exception fulle name:
 <System.Runtime.InteropServices.COMException>
2017-08-30 08:36:22.0601|ERROR|UWP.ResourceFromPri|Exception message:
 <Unspecified error

'Microsoft Corporation' violates pattern constraint of '\bms-resource:.{1,256}'.
>
2017-08-30 08:36:22.0831|ERROR|UWP.ResourceFromPri|Exception stack trace:
 <>
2017-08-30 08:36:22.0961|ERROR|UWP.ResourceFromPri|Exception source:
 <>
2017-08-30 08:36:22.1081|ERROR|UWP.ResourceFromPri|Exception target site:
 <>
2017-08-30 08:36:22.1201|ERROR|UWP.ResourceFromPri|Exception HResult:
 <-2147024774>
2017-08-30 08:36:22.1201|ERROR|UWP.ResourceFromPri|-------------------------- End exception --------------------------
2017-08-30 08:36:22.3809|INFO|PluginManager.InitializePlugins|Total init cost for <Colors> is <12ms>
2017-08-30 08:36:22.3809|INFO|PluginManager.InitializePlugins|Total init cost for <Plugin Indicator> is <13ms>
2017-08-30 08:36:22.3809|INFO|PluginManager.InitializePlugins|Total init cost for <Folder> is <16ms>
2017-08-30 08:36:22.3809|INFO|PluginManager.InitializePlugins|Total init cost for <Calculator> is <134ms>
2017-08-30 08:36:22.3919|INFO|PluginManager.InitializePlugins|Total init cost for <Wox Plugin Management> is <14ms>
2017-08-30 08:36:22.4024|INFO|PluginManager.InitializePlugins|Total init cost for <Program> is <41ms>
2017-08-30 08:36:22.4024|INFO|PluginManager.InitializePlugins|Total init cost for <Everything> is <43ms>
2017-08-30 08:36:22.4024|INFO|PluginManager.InitializePlugins|Total init cost for <Shell> is <41ms>
2017-08-30 08:36:22.4204|INFO|PluginManager.InitializePlugins|Total init cost for <URL> is <22ms>
2017-08-30 08:36:22.4204|INFO|PluginManager.InitializePlugins|Total init cost for <System Commands> is <18ms>
2017-08-30 08:36:22.4384|INFO|PluginManager.InitializePlugins|Total init cost for <Web Searches> is <37ms>
2017-08-30 08:36:22.5015|INFO|PluginManager.InitializePlugins|Total init cost for <Wox.Plugin.Runner> is <120ms>
2017-08-30 08:36:22.6192|INFO|Wox.Plugin.Program.Main|Program index cost <1265ms>
2017-08-30 08:36:22.7938|INFO|PluginManager.InitializePlugins|Total init cost for <Control Panel> is <430ms>
2017-08-30 08:36:22.7938|INFO|App.OnStartup|Dependencies Info:
Python Path: 
Everything SDK Path: C:\Users\FIGU\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
2017-08-30 08:36:22.8198|INFO|App.OnStartup|End Wox startup ----------------------------------------------------  
2017-08-30 08:36:22.8278|INFO|App.OnStartup|Startup cost <3453ms>
2017-08-30 08:36:25.0072|INFO|Updater.UpdateApp|Future Release <{
  "SHA1": "8CE02A3E4D480E4C221F141120535DE3F9857B5E",
  "BaseUrl": null,
  "Filename": "Wox-1.3.183-full.nupkg",
  "Query": null,
  "Filesize": 4724719,
  "IsDelta": false,
  "StagingPercentage": null
}>
```

**Comment by bao-qian** [comment]
#
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
