### ISSUE TITLE
ArgumentOutOfRangeException on ArrayList.Insert

### ISSUE THREAD

**Issue by wisnuprama** [Wox-launcher/Wox#1404]
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True
[2017-05-05.txt](https://github.com/Wox-launcher/Wox/files/978937/2017-05-05.txt)

Python Path: C:\Users\wisnuprama\Anaconda3\pythonw.exe
Everything SDK Path: C:\Users\wisnuprama\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 05/05/2017 19:06:36
Exception:
mscorlib
System.ArgumentOutOfRangeException
Insertion index was out of range. Must be non-negative and less than or equal to size.
Parameter name: index
   at System.Collections.ArrayList.Insert(Int32 index, Object value)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   at System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lances101** [comment]
Seems like this goes further back. See #926 
Although we have enough logs, we still need more information as to when this happens. Please describe what you where doing when this happened.

**Comment by lances101** [comment]
As this is a duplicate, I'm closing it. Please use #926
