### ISSUE TITLE
Wox version: 1.3.183

### ISSUE THREAD

**Issue by boomer647** [Wox-launcher/Wox#1418]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 05/14/2017 14:38:06
Exception:
Wox.Plugin.Program
System.NullReferenceException
[2017-05-14.txt](https://github.com/Wox-launcher/Wox/files/999152/2017-05-14.txt)

Object reference not set to an instance of an object.
   at Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 136
   at Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 102
   at Wox.Plugin.Program.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 94
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 27
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by z8888q** [comment]
me too

**Comment by lances101** [comment]
@boomer647 @z8888q  we do not support 1.3.183 anymore, sorry. I know that 1.3.183 is marked as latest release, but its not the most stable build. Please try build [1.3.424](https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424)
