### ISSUE TITLE
OnContextMenusForSettingsClick NullReferenceException

### ISSUE THREAD

**Issue by ghost** [Wox-launcher/Wox#1426]
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 05/19/2017 15:38:52
Exception:
Wox
System.NullReferenceException
Object reference not set to an instance of an object.
   at Wox.MainWindow.OnContextMenusForSettingsClick(Object sender, RoutedEventArgs e) in C:\projects\wox\Wox\MainWindow.xaml.cs:line 201
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2017-05-19.txt](https://github.com/Wox-launcher/Wox/files/1014425/2017-05-19.txt)

**Comment by lances101** [comment]
Could you add some information on what you were trying to do?
This is the first time I've seen this issue.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
