### ISSUE TITLE
豆瓣电影，豆瓣图书这些插件中文没办法搜索

### ISSUE THREAD

**Issue by gikerch** [Wox-launcher/Wox#1466]
Python写的插件好像只能支持英文搜索，中文没有结果，有没有人知道这个是软件问题还是插件自身的问题？ 试过了豆瓣电影，豆瓣图书都不行

**Comment by gikerch** [comment]
**日志中说是编码问题**
2017-06-14 21:24:19.1969|ERROR|JsonRPCPlugin.Execute|Traceback (most recent call last):
  File "C:\Users\zw491\AppData\Roaming\Wox\Plugins\豆瓣图书-f5620e40-eb2c-46b6-a18d-7ba6cd0ad14f\main.py", line 34, in <module>
    Main()
  File "C:\Users\zw491\AppData\Local\Wox\app-1.3.424\JsonRPC\wox.py", line 13, in __init__
    rpc_request = json.loads(sys.argv[1])
  File "D:\Anaconda2\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "D:\Anaconda2\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Anaconda2\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
**UnicodeDecodeError: 'utf8' codec can't decode byte 0xcb in position 0: invalid continuation byte**

**Comment by lances101** [comment]
What Python version are you using?

**Comment by lances101** [comment]
Closed due to inactivity. Author may reopen the issue if needed.
