### ISSUE TITLE
Issue when install plugin Wox.Plugin.Macros 1.0.1

### ISSUE THREAD

**Issue by dazzzlet** [Wox-launcher/Wox#1482]
Log file: [Link](https://drive.google.com/file/d/0B6iVsmIgrkP_bW9HTVdlRHdVbzQ/view?usp=sharing)

Wox version: 1.3.424
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\IVS\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 06/19/2017 16:25:24
Exception:
mscorlib
System.AggregateException
One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 91
   at Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:line 60
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by spences10** [comment]
Does this issue kill your Wox install? 

I had an error after installing the `Wox.Plugin.Macros` and I wasn't able to use Wox afterwards

I had to delete the plugin from here: `C:\Users\<user>\AppData\Roaming\Wox\Plugins`

**Comment by lances101** [comment]
It seems like you are using "Macros" plugin, which is not an official Wox plugin therefore we cannot provide support for it. The plugin is not compatible with the latest version of Wox and therefore is crashing it. 

You can ask the developer to update it, or you can fork, update and upload it yourself as a new plugin.

In order to continue using Wox you need to delete this plugin. This can be done by exiting Wox, going to `%appdata%/Wox/Plugins` and deleting the corresponding plugin's folder.

Closed due to being a third-party plugin.
