### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Rafael-Marinho** [Wox-launcher/Wox#1501]
## Known problems for 1.3.183:

1. `System.NullReferenceException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\Rafael Marinho\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 07/03/2017 14:10:41
Exception:
mscorlib
System.AggregateException
One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 91
   at Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:line 60
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[Issues.txt](https://github.com/Wox-launcher/Wox/files/1120196/Issues.txt)

**Comment by lances101** [comment]
Could you add more information about the issue? Please attach a log that contains the error. 
You can find it in `%appdata%\Wox\Logs\<version_folder>\<date>.txt`

**Comment by lances101** [comment]
Closed due to inactivity. Author may reopen the issue if needed.
