### ISSUE TITLE
fix discogs

### ISSUE THREAD

**Issue by mahsking** [Wox-launcher/Wox#1535]
## Known problems for 1.3.183:

1. `System.NullReferenceException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424

## English

Try search existing issues before you open new one

1. Wox version / commit number: 1.3.424
2. Steps to **reproduce** the bug:
3. Windows version: Microsoft Windows NT 10.0.15063.0
4. Exception: Wox.Plugin.Discogs
System.NullReferenceException
Object reference not set to an instance of an object.
   at Wox.Plugin.Discogs.DiscogsSettings.View_Loaded(Object sender, RoutedEventArgs re) in E:\Tobias\Dokumente\Develop\Wox.Plugin.Discogs\DiscogsSettings.xaml.cs:line 22
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):C:\Users\Mahyar\AppData\Roaming\Wox\Logs\1.3.424\2017-07-31.txt
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by lances101** [comment]
It seems like you are using "Discogs", which is not an official Wox plugin therefore we cannot provide support for it. The plugin is not compatible with the latest version of Wox and therefore is crashing it. 

You can ask the developer to update it, or you can fork, update and upload it yourself as a new plugin.

In order to continue using Wox you need to delete this plugin. This can be done by exiting Wox, going to `%appdata%/Wox/Plugins` and deleting the corresponding plugin's folder.

Closed due to being a third-party plugin.
