### ISSUE TITLE
在切换系统显示语言，及非unicode显示语言后，wox启动挂掉

### ISSUE THREAD

**Issue by daiybh** [Wox-launcher/Wox#168]
我把系统显示语言由中文切换为english(us) ，非unicode显示语言切换为 english(us),
重启电脑后，程序挂掉，并报exception
config.json 里面的内容全是0（16进制）
## Exception

```
System.NullReferenceException: Object reference not set to an instance of an object.
   Source: Wox.Infrastructure
   TargetAssembly: Wox.Infrastructure, Version=1.0.0.219, Culture=neutral, PublicKeyToken=null
   TargetModule: Wox.Infrastructure.dll
   TargetSite: Void OnAfterLoadConfig(Wox.Infrastructure.Storage.UserSettings.UserSettingStorage)
   at Wox.Infrastructure.Storage.UserSettings.UserSettingStorage.OnAfterLoadConfig(UserSettingStorage storage) in c:\Projects\Wox\Wox.Infrastructure\Storage\UserSettings\UserSettingStorage.cs:line 166
   at Wox.Infrastructure.Storage.BaseStorage`1.Load() in c:\Projects\Wox\Wox.Infrastructure\Storage\BaseStorage.cs:line 77
   at Wox.Infrastructure.Storage.BaseStorage`1.get_Instance() in c:\Projects\Wox\Wox.Infrastructure\Storage\BaseStorage.cs:line 39
   at Wox.MainWindow..ctor() in c:\Projects\Wox\Wox\MainWindow.xaml.cs:line 155
   at Wox.App.OnStartup(StartupEventArgs e) in c:\Projects\Wox\Wox\App.xaml.cs:line 100
   at System.Windows.Application.<.ctor>b__0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)
```

**Comment by orzFly** [comment]
应当只与非  Unicode  代码页有关，这个改变了 System.Text.Encoding.Default。

**Comment by bao-qian** [comment]
现在呢？
https://github.com/Wox-launcher/Wox/releases/tag/v1.2.900

**Comment by bao-qian** [comment]
设置重写了，应该修复了
https://github.com/Wox-launcher/Wox/releases/tag/v1.3.0
