### ISSUE TITLE
Wox got an error when running

### ISSUE THREAD

**Issue by Gabrielvon** [Wox-launcher/Wox#1718]
Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file:
[2017-12-05.txt](https://github.com/Wox-launcher/Wox/files/1530357/2017-12-05.txt)

2. copy below exception message
Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 12/05/2017 16:55:54
Exception:
mscorlib
System.ArgumentOutOfRangeException
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.set_Item(Int32 index, Object value)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   at System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lances101** [comment]
It seems like you are using an old version of Wox.
Please download one of the latest versions from [the releases page.](https://github.com/Wox-launcher/Wox/releases)

Reopen this issue if the problem persists.
