### ISSUE TITLE
Error prompt

### ISSUE THREAD

**Issue by YeaseonZhang** [Wox-launcher/Wox#1753]
Wox version: 1.3.424
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
IntPtr Length: 8
x64: True

Python Path: D:\Dev\Python\Python36-32\pythonw.exe
Everything SDK Path: C:\Users\zhangtao18\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 12/15/2017 15:33:01
Exception:
mscorlib
System.ArgumentOutOfRangeException
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.set_Item(Int32 index, Object value)
   at System.Windows.Data.ListCollectionView.AdjustShadowCopy(NotifyCollectionChangedEventArgs e)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   at System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lances101** [comment]
Please replicate the error and attach an error log

**Comment by lances101** [comment]
Closed due to inactivity. Reopen if author replies.
