### ISSUE TITLE
PluginsList plugin - Wox got an error [FATAL]

### ISSUE THREAD

**Issue by dimitrior** [Wox-launcher/Wox#1774]
I am now unable to OPEN WOX!! 
#1598

Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.16299.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\dimitri\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 12/22/2017 11:56:00
Exception:
mscorlib
System.AggregateException
One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 91
   at Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:line 60
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by dimitrior** [comment]
FIXED by deleting pluginslist folder from C:\Users\USERNAME\AppData\Roaming\Wox\Plugins 
#1598
#1668

**Comment by lances101** [comment]
PluginsList is not an official Wox plugin therefore we cannot provide support for it. 

You can [ask the developer to update it here](https://github.com/vladimirantos/Wox.Plugins.PluginsList/), or you can fork it, update it and upload it as a new plugin. 

Anyway, the functionality of the plugin is already included in Wox. You can get a list of installed plugins by using the `wpm list` command. 

Closed due to being a third-party plugin.
