### ISSUE TITLE
can't search anything

### ISSUE THREAD

**Issue by jessonsh** [Wox-launcher/Wox#1775]
Wox version: 1.3.424
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
IntPtr Length: 8
x64: True

Python Path: C:\Python27\pythonw.exe
Everything SDK Path: C:\Users\lhq\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 12/22/2017 22:20:06
Exception:
mscorlib
System.AggregateException
One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 91
   at Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:line 60
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.Excep

tionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jessonsh** [comment]
just now, i failed to upload the attachment, so send it now
[2017-12-22.zip](https://github.com/Wox-launcher/Wox/files/1582693/2017-12-22.zip)

**Comment by lances101** [comment]
One or more of your plugins are not compatible with the latest Wox version. I've seen Express and SimpleClock for now, but there may be others. 

Exit Wox. Open `%appdata%/Wox` and delete your Plugins folder. Reopen this issue if that does not fix it.
