### ISSUE TITLE
ArgumentOutOfRange exception thrown typing 'win' + window name (might be caused by plugin)

### ISSUE THREAD

**Issue by Antaris** [Wox-launcher/Wox#1831]
Wox version: 1.3.475
OS Version: Microsoft Windows NT 10.0.15063.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\abbottm\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 01/12/2018 10:40:56
Exception:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.set_Item(Int32 index, Object value)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   at System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Antaris** [comment]
Same as https://github.com/Wox-launcher/Wox/issues/1799, but using latest version.

**Comment by lances101** [comment]
Thank you @Antaris. Sadly, as you can see the logs do not point to any specific point in Wox code, so it will be hard to find what is actually causing it. 

Can you replicate this issue?
If possible, could you please write down the specific steps you are taking for this to happen?
If you can replicate it, I would need to know what plugins you are using. For that, upload the latest log file from `%appdata%/Wox/Logs/<date>.txt`. 

My assumption is that Wox is modifying a collection that is bound to a WPF component at which point that one errors out. 


Maintainer notes: 
- possibly related to https://github.com/Wox-launcher/Wox/issues/926
- in theory this happens somewhere during result handling and reordering as the collections should not be touched anywhere else

**Comment by Antaris** [comment]
@lances101 I will try and replicate it, thus far it hasn't reoccurred. Happened shortly after I installed a new plugin, think it was the `kill x` plugin.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
