### ISSUE TITLE
Possibly broken after installing Steam plugin, cannot uninstall

### ISSUE THREAD

**Issue by veerserif** [Wox-launcher/Wox#1847]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Opened Wox after using `wpm install steam` to install the steam plugin
2. After that, any time Wox is launched or the settings menu is touched generates an error window
3. Wox then cannot load anything, `wpm uninstall` does not generate list of plugins to uninstall

### Wox Error Window text

Wox version: 1.3.475
OS Version: Microsoft Windows NT 10.0.15063.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\minimuminim\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 01/19/2018 19:39:58
Exception:
System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'G:\Games\steamapps'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at WoxSteam.Library.<GetGames>d__5.MoveNext() in c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Library.cs:line 47
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at WoxSteam.Steam.LoadGames() in c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Steam.cs:line 191
   at WoxSteam.Steam.Load() in c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Steam.cs:line 60
   at WoxSteam.Main.Init(PluginInitContext context) in c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Main.cs:line 60
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 19
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 101
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 91
   at Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:line 60
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'G:\Games\steamapps'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at WoxSteam.Library.<GetGames>d__5.MoveNext() in c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Library.cs:line 47
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at WoxSteam.Steam.LoadGames() in c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Steam.cs:line 191
   at WoxSteam.Steam.Load() in c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Steam.cs:line 60
   at WoxSteam.Main.Init(PluginInitContext context) in c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Main.cs:line 60
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 19
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 101
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

### Detailed logs

(drop your log file here)
[2018-01-19.txt](https://github.com/Wox-launcher/Wox/files/1648334/2018-01-19.txt)

### Screenshots (optional)

(drop your screenshot here)

**Comment by lances101** [comment]
It seems like you are using the "Steam" plugin. The plugin is not compatible with the latest version of Wox and therefore is crashing it. 

Said plugin is developed by a third-party, thus we cannot provide support for it or update it. You can ask the developer to update it, or you can fork, update and upload it yourself as a new plugin.

In order to continue using Wox you need to delete this plugin. This can be done by exiting Wox, going to `%appdata%/Wox/Plugins` and deleting the corresponding plugin's folder.

Closed due to being a third-party plugin. If issue persists after uninstalling it, please reopen. 

## Note
The issue with Wox crashing after installing incompatible plugins is already fixed on the dev branch and will be soon merged into the master builds.
