### ISSUE TITLE
Error after restart

### ISSUE THREAD

**Issue by 1danmi** [Wox-launcher/Wox#1866]
### Are you submitting a bug report?

Yes.

### Steps to reproduce

I just restarted my laptop and a messagebox with this error appeared.

### Wox Error Window text

Wox version: 1.3.475
OS Version: Microsoft Windows NT 10.0.17083.0
IntPtr Length: 8
x64: True

Python Path: C:\Program Files\Python\python36\pythonw.exe
Everything SDK Path: 
Date: 01/29/2018 11:55:17
Exception:
System.Net.WebException: The operation has timed out
   at System.Net.FileWebRequest.GetResponse()
   at MS.Internal.WpfWebRequestHelper.GetResponse(WebRequest request)
   at MS.Internal.WpfWebRequestHelper.GetResponseStream(WebRequest request, ContentType& contentType)
   at System.Windows.ResourceDictionary.set_Source(Uri value)
   at Wox.Core.Resource.Internationalization.LoadLanguage(Language language) in C:\projects\wox\Wox.Core\Resource\Internationalization.cs:line 128
   at Wox.Core.Resource.Internationalization..ctor() in C:\projects\wox\Wox.Core\Resource\Internationalization.cs:line 27
   at Wox.Core.Resource.InternationalizationManager.get_Instance() in C:\projects\wox\Wox.Core\Resource\InternationalizationManager.cs:line 18
   at Wox.ViewModel.MainViewModel..ctor(Settings settings) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 44
   at Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:line 58
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs
[2018-01-29.txt](https://github.com/Wox-launcher/Wox/files/1673030/2018-01-29.txt)

**Comment by lances101** [comment]
Duplicate of https://github.com/Wox-launcher/Wox/issues/1866

```
What language were you using when this happened?
```

Please answer these questions in the provided issue. Thank you.
