### ISSUE TITLE
Wox Error when it starts

### ISSUE THREAD

**Issue by manojv81** [Wox-launcher/Wox#1897]
### Are you submitting a bug report?
Yes
(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

Wox version: 1.3.475
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\VarmaM\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 02/11/2018 14:52:19
Exception:
System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at Wox.SettingWindow.SetStartup() in C:\projects\wox\Wox\SettingWindow.xaml.cs:line 63
   at Wox.App.AutoStartup() in C:\projects\wox\Wox\App.xaml.cs:line 97
   at Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:line 80
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

[2018-02-11.txt](https://github.com/Wox-launcher/Wox/files/1714222/2018-02-11.txt)
(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
