### ISSUE TITLE
Wox got an error

### ISSUE THREAD

**Issue by ReyoungLee** [Wox-launcher/Wox#1898]
Wox version: 1.3.475
OS Version: Microsoft Windows NT 10.0.16299.0
IntPtr Length: 8
x64: True

Python Path: pythonw.exe
Everything SDK Path: C:\Users\Rey\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 02/14/2018 01:43:32
Exception:
System.Exception: Couldn't acquire lock, is another instance running
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut) in C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\Utility.cs:line 778
   at Squirrel.UpdateManager.<acquireUpdateLock>b__32_0() in C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:line 274
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext() in C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Wox.Core.Updater.<UpdateApp>d__1.MoveNext() in C:\projects\wox\Wox.Core\Updater.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Wox.SettingWindow.<OnCheckUpdates>d__24.MoveNext() in C:\projects\wox\Wox\SettingWindow.xaml.cs:line 309
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2018-02-14.txt](https://github.com/Wox-launcher/Wox/files/1720971/2018-02-14.txt)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
