### ISSUE TITLE
Unknown error detected immediately after application downloading

### ISSUE THREAD

**Issue by wwwww1100** [Wox-launcher/Wox#1901]
### Are you submitting a bug report?

Yes. 

### Steps to reproduce

1. Download Wox-1.3.475 from github. 
2. As long as the download was completed, google chrome plugin McAfee WebAdvisor started checking automatically.  
3. After a few seconds, a warning session popped on screen with "Wox-1.3.475.exe Installation has failed". 

### Wox Error Window text

Wox-1.3.475.exe Installation has failed.

There was an error while installing the application. Check the setup log for more information and contact the author. 

### Detailed logs

    2018-02-15 00:58:34> Program: Starting Squirrel Updater: --install .
2018-02-15 00:58:34> Program: Starting install, writing to C:\Users\Harold Wang\AppData\Local\SquirrelTemp
2018-02-15 00:58:34> Program: About to install to: C:\Users\Harold Wang\AppData\Local\Wox
2018-02-15 00:58:34> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Harold Wang\AppData\Local\Wox\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2018-02-15 00:58:34> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Harold Wang\AppData\Local\Wox\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2018-02-15 00:58:34> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Harold Wang\AppData\Local\SquirrelTemp
2018-02-15 00:58:34> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2018-02-15 00:58:34> ApplyReleasesImpl: Writing files to app directory: C:\Users\Harold Wang\AppData\Local\Wox\app-1.3.475
2018-02-15 00:58:34> LogHost: Rigging execution stub for lib/net45/Wox_ExecutionStub.exe to C:\Users\Harold Wang\AppData\Local\Wox\Wox.exe
2018-02-15 00:58:34> ApplyReleasesImpl: Squirrel Enabled Apps: []
2018-02-15 00:58:34> ApplyReleasesImpl: No apps are marked as Squirrel-aware! Going to run them all
2018-02-15 00:58:34> ApplyReleasesImpl: About to create shortcuts for Wox.exe, rootAppDir C:\Users\Harold Wang\AppData\Local\Wox
2018-02-15 00:58:34> ApplyReleasesImpl: Creating shortcut for Wox.exe => C:\Users\Harold Wang\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Wox\Wox.lnk
2018-02-15 00:58:34> ApplyReleasesImpl: About to save shortcut: C:\Users\Harold Wang\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Wox\Wox.lnk (target C:\Users\Harold Wang\AppData\Local\Wox\Wox.exe, workingDir C:\Users\Harold Wang\AppData\Local\Wox\app-1.3.475, args , toastActivatorCSLID 9da9f3e0-d1f9-5b8f-a96b-7228c4d219b2)
2018-02-15 00:58:34> ApplyReleasesImpl: Creating shortcut for Wox.exe => C:\Users\Harold Wang\Desktop\Wox.lnk
2018-02-15 00:58:34> ApplyReleasesImpl: About to save shortcut: C:\Users\Harold Wang\Desktop\Wox.lnk (target C:\Users\Harold Wang\AppData\Local\Wox\Wox.exe, workingDir C:\Users\Harold Wang\AppData\Local\Wox\app-1.3.475, args , toastActivatorCSLID 9da9f3e0-d1f9-5b8f-a96b-7228c4d219b2)
2018-02-15 00:58:34> A2018-02-15 00:58:35> Program: Starting Squirrel Updater: --install .
2018-02-15 00:58:35> Program: Starting install, writing to C:\Users\Harold Wang\AppData\Local\SquirrelTemp
2018-02-15 00:58:35> Program: About to install to: C:\Users\Harold Wang\AppData\Local\Wox
2018-02-15 00:58:35> Program: Install path C:\Users\Harold Wang\AppData\Local\Wox already exists, burning it to the ground
2018-02-15 00:58:36> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Harold Wang\AppData\Local\Wox\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2018-02-15 00:58:36> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Harold Wang\AppData\Local\Wox\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2018-02-15 00:58:36> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Harold Wang\AppData\Local\SquirrelTemp
2018-02-15 00:58:36> CheckForUpdateImpl: The file C:\Users\Harold Wang\AppData\Local\SquirrelTemp\RELEASES does not exist, something is probably broken with your application
2018-02-15 00:58:36> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Exception: The file C:\Users\Harold Wang\AppData\Local\SquirrelTemp\RELEASES does not exist, something is probably broken with your application
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Exception: The file C:\Users\Harold Wang\AppData\Local\SquirrelTemp\RELEASES does not exist, something is probably broken with your application
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

(drop your log file here)

### Screenshots (optional)
 
![image](https://user-images.githubusercontent.com/35984090/36217682-1ef4250c-11ed-11e8-9367-540bdfc2c2c2.png)

(drop your screenshot here)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
