### ISSUE TITLE
Wox got an error when open

### ISSUE THREAD

**Issue by tonytan1** [Wox-launcher/Wox#1921]
### Are you submitting a bug report?
 Yes

### Steps to reproduce

1. click Wox to open
2. got an error popup window 

### Wox Error Window text

Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\p5067\AppData\Roaming\Wox\Logs\1.3.424\2018-03-01.txt
2. copy below exception message
[2018-03-01.txt](https://github.com/Wox-launcher/Wox/files/1769415/2018-03-01.txt)

Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.15063.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 03/01/2018 09:24:37
Exception:
mscorlib
System.IO.IOException
The process cannot access the file 'C:\Users\p5067\AppData\Roaming\Wox\Cache\Pinyin.cache' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Wox.Infrastructure.Storage.BinaryStorage`1.Save(T data) in C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:line 99
   at Wox.Infrastructure.Storage.BinaryStorage`1.TryLoad(T defaultData) in C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:line 44
   at Wox.Infrastructure.Alphabet.<>c.<Initialize>b__3_0() in C:\projects\wox\Wox.Infrastructure\Alphabet.cs:line 25
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at Wox.Infrastructure.Alphabet.Initialize() in C:\projects\wox\Wox.Infrastructure\Alphabet.cs:line 29
   at Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:line 54
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

(drop your log file here)
[2018-03-01.txt](https://github.com/Wox-launcher/Wox/files/1769416/2018-03-01.txt)

### Screenshots (optional)

(drop your screenshot here)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
