### ISSUE TITLE
Using clock plugin trying to set an alarm

### ISSUE THREAD

**Issue by lgjmac** [Wox-launcher/Wox#1929]
Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\lewis\AppData\Roaming\Wox\Logs\1.3.524\2018-03-06.txt
2. copy below exception message

Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.16299.0
IntPtr Length: 8
x64: True

Python Path: C:\Program Files (x86)\Python36-32\pythonw.exe
Everything SDK Path: C:\Users\lewis\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 03/06/2018 11:58:55
Exception:
System.TypeLoadException: Could not load type 'Wox.Infrastructure.Storage.Storage`1' from assembly 'Wox.Infrastructure, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null'.
   at Wox.Plugin.SimpleClock.Commands.Alarm.AlarmAddCommand.CommandExecution(List`1 args)
   at Wox.Plugin.Boromak.CommandHandlerBase.Execute(List`1 args) in C:\Users\Boris\Documents\SourceControl\Wox\Wox.Plugin.SimpleClock\Wox.Plugin.Boromak\Wox.Plugin.Boromak\CommandHandlerBase.cs:line 166
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 146
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
