### ISSUE TITLE
wox stop working 

### ISSUE THREAD

**Issue by doriancuentas** [Wox-launcher/Wox#1973]
```
Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\user\AppData\Roaming\Wox\Logs\1.3.183\2018-04-11.txt
2. copy below exception message
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.16299.0
Date: 04/11/2018 04:34:21
Exception:
Wox.Plugin.Program
System.NullReferenceException
Object reference not set to an instance of an object.
   at Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 136
   at Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 102
   at Wox.Plugin.Program.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 94
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 27
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )


```

## **i'm wox user but also a python beginner so maybe a pip plugin is causing the problem**

```
> pip freeze
beautifulsoup4==4.6.0
certifi==2018.1.18
chardet==3.0.4
colorama==0.3.9
Django==2.0.2
django-adminlte2==0.2.3
django-authority==0.13.2
django-datatables-view==1.15.1
django-easy-audit==1.0
django-extensions==2.0.6
django-widget-tweaks==1.4.1
gTTS==1.2.2
gTTS-token==1.1.1
idna==2.6
logzero==1.5.0
lyricwikia==0.1.9
mutagen==1.40.0
pafy==0.5.4
pathlib==1.0.1
psycopg2==2.7.4
pytz==2017.3
PyYAML==3.12
requests==2.18.4
six==1.11.0
spotipy==2.4.4
titlecase==0.12.0
unicode-slugify==0.1.3
Unidecode==1.0.22
urllib3==1.22
virtualenv==15.1.0
youtube-dl==2018.3.20
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command. 
```

### **the log file** 
```

2018-04-11 04:38:25.3514|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2018-04-11 04:38:25.3634|ERROR|Wox.Plugin.Everything.Main.Save|Object reference not set to an instance of an object.
2018-04-11 04:38:25.3634|ERROR|Wox.Plugin.Everything.Main.Save|
   at Wox.Plugin.Everything.Main.Save() in C:\projects\wox\Plugins\Wox.Plugin.Everything\Main.cs:line 29
2018-04-11 04:38:25.3974|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2018-04-11 04:38:25.4064|ERROR|System.Windows.Window.WmClose|Object reference not set to an instance of an object.
2018-04-11 04:38:25.4064|ERROR|System.Windows.Window.WmClose|
   at Wox.Plugin.Everything.Main.Save() in C:\projects\wox\Plugins\Wox.Plugin.Everything\Main.cs:line 29
   at Wox.Core.Plugin.PluginManager.Save() in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 62
   at Wox.ViewModel.MainViewModel.Save() in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 587
   at System.Windows.Window.OnClosing(CancelEventArgs e)
   at System.Windows.Window.WmClose()
2018-04-11 04:38:25.4594|FATAL|Wox.Helper.ErrorReporting.Report|
## Exception

```
System.NullReferenceException: Object reference not set to an instance of an object.
   Source: Wox.Plugin.Everything
   TargetAssembly: Wox.Plugin.Everything, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Wox.Plugin.Everything.dll
   TargetSite: Void Save()
   at Wox.Plugin.Everything.Main.Save() in C:\projects\wox\Plugins\Wox.Plugin.Everything\Main.cs:line 29
   at Wox.Core.Plugin.PluginManager.Save() in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 62
   at Wox.ViewModel.MainViewModel.Save() in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 587
   at System.Windows.Window.OnClosing(CancelEventArgs e)
   at System.Windows.Window.WmClose()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

## Environment

* Command Line: "C:\Users\user\AppData\Local\Wox\app-1.3.183\Wox.exe" 
* Timestamp: 04/11/2018 04:38:25
* IntPtr Length: 8
* System Version: Microsoft Windows NT 10.0.16299.0
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.7.02556
   * v4 Full 4.7.02556
   * v4.0 Client 4.0.0.0

## Assemblies - Wox.exe

* Wox, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\user\AppData\Local\Wox\app-1.3.183\Wox.exe)
* Wox.Infrastructure, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\user\AppData\Local\Wox\app-1.3.183\Wox.Infrastructure.dll)
* Wox.Plugin, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\user\AppData\Local\Wox\app-1.3.183\Wox.Plugin.dll)
* Wox.Core, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\user\AppData\Local\Wox\app-1.3.183\Wox.Core.dll)
* Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\user\AppData\Local\Wox\app-1.3.183\Newtonsoft.Json.dll)
* Wox.Plugin.Caculator, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\user\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
* YAMP, Version=1.4.0.22422, Culture=neutral, PublicKeyToken=null (C:\Users\user\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Caculator\YAMP.dll)
* Wox.Plugin.Color, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\user\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
* Wox.Plugin.ControlPanel, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\user\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
* Wox.Plugin.Everything, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\user\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
* Wox.Plugin.Folder, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\user\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
* Wox.Plugin.PluginIndicator, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\user\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
* Wox.Plugin.PluginManagement, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\user\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
* Wox.Plugin.Program, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\user\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
* Wox.Plugin.Sys, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\user\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
* Wox.Plugin.Url, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\user\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
* Wox.Plugin.WebSearch, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\user\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
* NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\user\AppData\Local\Wox\app-1.3.183\NHotkey.dll)
* NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\user\AppData\Local\Wox\app-1.3.183\NHotkey.Wpf.dll)
* NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\user\AppData\Local\Wox\app-1.3.183\NLog.dll)
* Windows.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\Windows\system32\WinMetadata\Windows.UI.winmd)
* Windows.Foundation, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\Windows\system32\WinMetadata\Windows.Foundation.winmd)
* mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
* PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
* System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
* PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
* System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
* System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
* System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
* System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
* System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
* System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
* PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)
* System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
* PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll)
* UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll)
* System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
* PresentationFramework-SystemXmlLinq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXmlLinq\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXmlLinq.dll)
* PresentationFramework-SystemXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll)
* UIAutomationProvider, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll)
* Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll)
* System.Runtime.InteropServices.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.WindowsRuntime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.WindowsRuntime.dll)
* System.Runtime.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.WindowsRuntime\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.WindowsRuntime.dll)
* System.Deployment, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Deployment\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Deployment.dll)
* PresentationFramework-SystemDrawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemDrawing\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemDrawing.dll)
* System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_64\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll)

2018-04-11 04:38:25.7107|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2018-04-11 04:38:25.7263|ERROR|Wox.App.Dispose|Object reference not set to an instance of an object.
2018-04-11 04:38:25.7419|ERROR|Wox.App.Dispose|
   at Wox.App.Dispose() in C:\projects\wox\Wox\App.xaml.cs:line 134
2018-04-11 04:38:25.7732|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2018-04-11 04:38:25.7888|ERROR|Wox.Helper.ErrorReporting.UnhandledExceptionHandle|Object reference not set to an instance of an object.
2018-04-11 04:38:25.7888|ERROR|Wox.Helper.ErrorReporting.UnhandledExceptionHandle|
   at Wox.Helper.ErrorReporting.UnhandledExceptionHandle(Object sender, UnhandledExceptionEventArgs e) in C:\projects\wox\Wox\Helper\ErrorReporting.cs:line 0
2018-04-11 04:38:40.5115|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2018-04-11 04:38:40.5679|ERROR|System.Runtime.Remoting.Channels.Ipc.IpcPort.Connect|Port is Busy: All pipe instances are busy.

2018-04-11 04:38:40.5821|ERROR|System.Runtime.Remoting.Channels.Ipc.IpcPort.Connect|
   at System.Runtime.Remoting.Channels.Ipc.IpcPort.Connect(String portName, Boolean secure, TokenImpersonationLevel impersonationLevel, Int32 timeout)
2018-04-11 04:38:40.6290|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2018-04-11 04:38:40.6290|ERROR|System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage|Port is Busy: All pipe instances are busy.

2018-04-11 04:38:40.6446|ERROR|System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage|

Server stack trace: 
   at System.Runtime.Remoting.Channels.Ipc.IpcPort.Connect(String portName, Boolean secure, TokenImpersonationLevel impersonationLevel, Int32 timeout)
   at System.Runtime.Remoting.Channels.Ipc.ConnectionCache.GetConnection(String portName, Boolean secure, TokenImpersonationLevel level, Int32 timeout)
   at System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
2018-04-11 04:38:40.6915|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2018-04-11 04:38:40.7071|ERROR|Wox.Helper.ErrorReporting.UnhandledExceptionHandle|Object reference not set to an instance of an object.
2018-04-11 04:38:40.7228|ERROR|Wox.Helper.ErrorReporting.UnhandledExceptionHandle|
   at Wox.Helper.ErrorReporting.UnhandledExceptionHandle(Object sender, UnhandledExceptionEventArgs e) in C:\projects\wox\Wox\Helper\ErrorReporting.cs:line 20

```

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
