### ISSUE TITLE
wox got an error when launch

### ISSUE THREAD

**Issue by Ericteen** [Wox-launcher/Wox#2023]
### Steps to reproduce

1. Error occurred when launch wox

### Wox Error Window text

Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.3.9600.0
Date: 05/07/2018 10:59:17
Exception:
Newtonsoft.Json
Newtonsoft.Json.JsonReaderException
Unterminated string. Expected delimiter: ". Path 'Items[39].ExecutedDateTime', line 161, position 58.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseString(Char quote, ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsDateTime()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Wox.Infrastructure.Storage.JsonStrorage`1.Deserialize(String searlized) in C:\projects\wox\Wox.Infrastructure\Storage\JsonStorage.cs:line 58
   at Wox.Infrastructure.Storage.JsonStrorage`1.Load() in C:\projects\wox\Wox.Infrastructure\Storage\JsonStorage.cs:line 40
   at Wox.ViewModel.MainViewModel..ctor(Settings settings) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 62
   at Wox.App.<OnStartup>b__8_0() in C:\projects\wox\Wox\App.xaml.cs:line 49
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 28
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

[2018-05-07.txt](https://github.com/Wox-launcher/Wox/files/1978402/2018-05-07.txt)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
