### ISSUE TITLE
Error trying to launch Google Chrome from Wox.Plugin.Runner

### ISSUE THREAD

**Issue by philipstratford** [Wox-launcher/Wox#2076]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Install Wox.Plugin.Runner plugin
2. Add a new shortcut in the plugin settings to open Google Chrome - C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
3. Assign the command the shortcut 'keep'
4. Save the new command, close Settings and type 'r keep' in the Wox search box.

### Wox Error Window text

Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.15063.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\phil2415\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 06/21/2018 10:31:25
Exception:
System
System.ComponentModel.Win32Exception
The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Wox.Plugin.Runner.Runner.RunCommand(ActionContext e, Query query, Command command)
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 146
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2018-06-21.txt](https://github.com/Wox-launcher/Wox/files/2122978/2018-06-21.txt)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by philipstratford** [comment]
This just started working correctly after I closed the Settings window.
