### ISSUE TITLE
Error while idling in the background.

### ISSUE THREAD

**Issue by DariusHutchison** [Wox-launcher/Wox#2084]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Wox was running in the background unused and thew this error.
2.
3.

### Wox Error Window text

Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 07/01/2018 21:31:47
Exception:
System.Net.WebException: The operation has timed out
   at System.Net.FileWebRequest.GetResponse()
   at MS.Internal.WpfWebRequestHelper.GetResponse(WebRequest request)
   at MS.Internal.WpfWebRequestHelper.GetResponseStream(WebRequest request, ContentType& contentType)
   at System.Windows.ResourceDictionary.set_Source(Uri value)
   at Wox.Core.Resource.Internationalization.LoadLanguage(Language language) in C:\projects\wox\Wox.Core\Resource\Internationalization.cs:line 128
   at Wox.Core.Resource.Internationalization..ctor() in C:\projects\wox\Wox.Core\Resource\Internationalization.cs:line 27
   at Wox.Core.Resource.InternationalizationManager.get_Instance() in C:\projects\wox\Wox.Core\Resource\InternationalizationManager.cs:line 18
   at Wox.ViewModel.MainViewModel..ctor(Settings settings) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 44
   at Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:line 58
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) 

### Detailed logs

[2018-07-01.txt](https://github.com/Wox-launcher/Wox/files/2153546/2018-07-01.txt)

### Screenshots (optional)

(drop your screenshot here)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
