### ISSUE TITLE
Wox.Plugin.SimpleClock bug

### ISSUE THREAD

**Issue by yunga** [Wox-launcher/Wox#2124]
### Are you submitting a bug report?

Yes

### Steps to reproduce

After having installed the Wox.Plugin.SimpleClock (wpm install Wox.Plugin.SimpleClock):

1. Launch Wox.
2. Type: clock add 14:00
3. Press Enter, it breaks.

Note 14:00 is a time in the future (if that matters?).

### Wox Error Window text

Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\Yunga\AppData\Roaming\Wox\Logs\1.3.524\2018-07-21.txt
2. copy below exception message

Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\Yunga\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 07/21/2018 13:45:55
Exception:
System.TypeLoadException: Could not load type 'Wox.Infrastructure.Storage.Storage`1' from assembly 'Wox.Infrastructure, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null'.
   at Wox.Plugin.SimpleClock.Commands.Alarm.AlarmAddCommand.CommandExecution(List`1 args)
   at Wox.Plugin.Boromak.CommandHandlerBase.Execute(List`1 args) in C:\Users\Boris\Documents\SourceControl\Wox\Wox.Plugin.SimpleClock\Wox.Plugin.Boromak\Wox.Plugin.Boromak\CommandHandlerBase.cs:line 166
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 146
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

[2018-07-21.txt](https://github.com/Wox-launcher/Wox/files/2216118/2018-07-21.txt)

**Comment by jhdxr** [comment]
thanks for your report. however, this is a bug related to SimpleClock plugin, and this is repo for wox main program. you should report this to the author of SimpleClock plugin.
