### ISSUE TITLE
Wox got an error

### ISSUE THREAD

**Issue by drkvogel** [Wox-launcher/Wox#2128]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. opened search bar with ctrl+space
2. started typing `wpm install Python Calculator` but only got to `wpm i`
3. crash!

### Wox Error Window text

Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\cbird\AppData\Roaming\Wox\Logs\1.3.183\2018-07-22.txt
2. copy below exception message
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.17134.0
Date: 07/22/2018 16:57:35
Exception:
mscorlib
System.ArgumentOutOfRangeException
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.set_Item(Int32 index, Object value)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   at System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2018-07-22.txt](https://github.com/Wox-launcher/Wox/files/2217157/2018-07-22.txt)
[2018-07-22.txt](https://github.com/Wox-launcher/Wox/files/2217159/2018-07-22.txt)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)
[2018-07-22.txt](https://github.com/Wox-launcher/Wox/files/2217160/2018-07-22.txt)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
