### ISSUE TITLE
System.ArgumentException: Illegal characters in path

### ISSUE THREAD

**Issue by MojaveWastelander** [Wox-launcher/Wox#2131]
[2018-07-24.txt](https://github.com/Wox-launcher/Wox/files/2222185/2018-07-24.txt)

Installed ok, worked fine until next reboot. Now always starts with an error window and terminates.
Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 07/24/2018 08:59:44
Exception:
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Wox.Core.Plugin.PluginsLoader.PythonPlugins(List`1 source, String pythonDirecotry) in C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:line 119
   at Wox.Core.Plugin.PluginsLoader.Plugins(List`1 metadatas, PluginsSettings settings) in C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:line 22
   at Wox.Core.Plugin.PluginManager.LoadPlugins(PluginsSettings settings) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 85
   at Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:line 58
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
