### ISSUE TITLE
System.Exception: Update.exe not found, not a Squirrel-installed app

### ISSUE THREAD

**Issue by cpriest** [Wox-launcher/Wox#2158]
### Are you submitting a bug report?

Yes

### Steps to reproduce

* Anything that causes Wox to restart (installing a plugin for example).
* Does not happen if Wox is exited and then started.

### Wox Error Window text

```
Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\Clint\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 08/09/2018 09:47:06
Exception:
System.Exception: Update.exe not found, not a Squirrel-installed app?
   at Squirrel.UpdateManager.getUpdateExe() in C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:line 313
   at Squirrel.UpdateManager.RestartApp(String exeToStart, String arguments) in C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:line 196
   at Wox.Plugin.Sys.Main.<Commands>b__14_7(ActionContext c) in C:\projects\wox\Plugins\Wox.Plugin.Sys\Main.cs:line 177
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 146
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### Detailed logs

[2018-08-09.txt](https://github.com/Wox-launcher/Wox/files/2274600/2018-08-09.txt)

### Additional Info

* Wox was installed via Scoop with custom scoop directory of C:\Scoop

**Comment by SirJayEarn** [comment]
I got the same issue. Seems likely to be related to wox being installed via scoop, as this also applies for me. I uninstalled wox and reinstalled it using the installer (the "normal" windows-way). Now this error does not seems to occur any longer.
Would be nice to be able to use scoop though.

**Comment by Cry0nicS** [comment]
The issue still persists...

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup. 
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
