### ISSUE TITLE
[Bug] Application not found - Thank you

### ISSUE THREAD

**Issue by mickeyang** [Wox-launcher/Wox#2174]
### Are you submitting a bug report?
Yes, I am submitting a bug.

### Steps to reproduce

I was trying to google "dog" in WOX.

1.use g dog

### Wox Error Window text

Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: pythonw.exe
Everything SDK Path: C:\Users\mickeyang\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 08/17/2018 06:11:21
Exception:
System.ComponentModel.Win32Exception (0x80004005): **Application not found**
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Wox.Plugin.WebSearch.Main.<>c__DisplayClass8_1.<Query>b__1(ActionContext c) in C:\projects\wox\Plugins\Wox.Plugin.WebSearch\Main.cs:line 67
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 146
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

[2018-08-17.txt](https://github.com/Wox-launcher/Wox/files/2294760/2018-08-17.txt)

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/18319165/44226658-bc62b100-a1e4-11e8-82e4-9ed97e2e8d90.png)

**Comment by mickeyang** [comment]
Thanks for developing this powerful tool.

I look forward to hearing from you.

**Comment by roose** [comment]
Hi @mickeyang do you have a default browser in the Windows `Settings -> Apps -> Default apps`?

**Comment by mickeyang** [comment]
Thank you.
Problem solved.

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup. 
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
