### ISSUE TITLE
Error Upload

### ISSUE THREAD

**Issue by dylbrwn** [Wox-launcher/Wox#2187]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Installed Wox, rebooted and the error message appeared
2. Uninstalled and reinstalled, same issue
3. uninstalled python...rebooted, uninstall and reinstalled Wox. Same issue

### Wox Error Window text

Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 08/25/2018 17:59:59
Exception:
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Wox.Core.Plugin.PluginsLoader.PythonPlugins(List`1 source, String pythonDirecotry) in C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:line 119
   at Wox.Core.Plugin.PluginsLoader.Plugins(List`1 metadatas, PluginsSettings settings) in C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:line 22
   at Wox.Core.Plugin.PluginManager.LoadPlugins(PluginsSettings settings) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 85
   at Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:line 58
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

(drop your log file here)
[2018-08-25.txt](https://github.com/Wox-launcher/Wox/files/2321108/2018-08-25.txt)

### Screenshots (optional)

(drop your screenshot here)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup. 
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
