### ISSUE TITLE
Wox does not work - Wox version: 1.3.524

### ISSUE THREAD

**Issue by maxilai** [Wox-launcher/Wox#2295]
[2018-12-18.txt](https://github.com/Wox-launcher/Wox/files/2688874/2018-12-18.txt)

Wox version: 1.3.524
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
IntPtr Length: 8
x64: True

Python Path: pythonw.exe
Everything SDK Path: 
Date: 12/18/2018 12:16:22
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Wox.MainWindow.OnContextMenusForSettingsClick(Object sender, RoutedEventArgs e) in C:\projects\wox\Wox\MainWindow.xaml.cs:line 201
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
