### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by sjoerger1101** [Wox-launcher/Wox#2348]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Opened Wox with my keyboard shortcut
2. Started typing my query into Wox
3. Wox closes and error shows up (Wox doesn't completely quit, it just closes the pop up query window) (One observation while the error happened, it looks like the cursor somehow ended up in the position right before the last letter I type instead of the position _after_ the letter that I typed, as I would expect.)

This issue happens to me probably once per week and seems to only happen when I'm typing my query fast. If I type slowly, the issue doesn't seem to happen.

### Wox Error Window text
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.15063.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\sjoerger\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 01/29/2019 12:53:34
Exception:
mscorlib
System.ArgumentOutOfRangeException
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.set_Item(Int32 index, Object value)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   at System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

[2019-01-29.txt](https://github.com/Wox-launcher/Wox/files/2807767/2019-01-29.txt)

If file attachment didn't work, here is the exception text from that log for this error: 
2019-01-29 09:19:23.2131|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2019-01-29 09:19:23.2251|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2019-01-29 09:19:23.2336|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.ComponentModel.Win32Exception>
2019-01-29 09:19:23.2482|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <Clipboard format registration did not succeed.>
2019-01-29 09:19:23.2482|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   at System.Windows.Forms.DataFormats.GetFormat(String format)>
2019-01-29 09:19:23.2682|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <System.Windows.Forms>
2019-01-29 09:19:23.2787|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <Format GetFormat(System.String)>
2019-01-29 09:19:23.2787|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2147467259>
2019-01-29 09:19:23.2978|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
