### ISSUE TITLE
'Everything" Issue

### ISSUE THREAD

**Issue by LiterallyOutOfIdeas** [Wox-launcher/Wox#2361]
### Are you submitting a bug report?

No

### Wox Error Window text
Recieving this error and have uninstalled
 NeXt.Vdf.UnexpectedCharacterException: Exception of type 'NeXt.Vdf.UnexpectedCharacterException' was thrown.
   at NeXt.Vdf.VdfDeserializer.GetTextToDelimiter(String s, Int32 startindex, Int32& endIndex, Boolean& fullStop) in C:\Users\Kamen\Documents\Visual Studio 2015\Projects\NeXt.Vdf-master\VdfDeserializer.cs:line 153
   at NeXt.Vdf.VdfDeserializer.HandleLine(Action`1 callback, String line) in C:\Users\Kamen\Documents\Visual Studio 2015\Projects\NeXt.Vdf-master\VdfDeserializer.cs:line 277
   at NeXt.Vdf.VdfDeserializer.Tokenize(String s) in C:\Users\Kamen\Documents\Visual Studio 2015\Projects\NeXt.Vdf-master\VdfDeserializer.cs:line 315
   at NeXt.Vdf.VdfDeserializer.Deserialize() in C:\Users\Kamen\Documents\Visual Studio 2015\Projects\NeXt.Vdf-master\VdfDeserializer.cs:line 338
   at WoxSteam.Game..ctor(String pathToManifest, String resourcesPath) in c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Game.cs:line 46
   at WoxSteam.Library.<GetGames>d__5.MoveNext() in c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Library.cs:line 51
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at WoxSteam.Steam.LoadGames() in c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Steam.cs:line 191
   at WoxSteam.Steam.Load() in c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Steam.cs:line 60
   at WoxSteam.Main.Init(PluginInitContext context) in c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Main.cs:line 60
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 19
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 101
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 91
   at Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:line 60
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (Inner Exception #0) NeXt.Vdf.UnexpectedCharacterException: Exception of type 'NeXt.Vdf.UnexpectedCharacterException' was thrown.
   at NeXt.Vdf.VdfDeserializer.GetTextToDelimiter(String s, Int32 startindex, Int32& endIndex, Boolean& fullStop) in C:\Users\Kamen\Documents\Visual Studio 2015\Projects\NeXt.Vdf-master\VdfDeserializer.cs:line 153
   at NeXt.Vdf.VdfDeserializer.HandleLine(Action`1 callback, String line) in C:\Users\Kamen\Documents\Visual Studio 2015\Projects\NeXt.Vdf-master\VdfDeserializer.cs:line 277
   at NeXt.Vdf.VdfDeserializer.Tokenize(String s) in C:\Users\Kamen\Documents\Visual Studio 2015\Projects\NeXt.Vdf-master\VdfDeserializer.cs:line 315
   at NeXt.Vdf.VdfDeserializer.Deserialize() in C:\Users\Kamen\Documents\Visual Studio 2015\Projects\NeXt.Vdf-master\VdfDeserializer.cs:line 338
   at WoxSteam.Game..ctor(String pathToManifest, String resourcesPath) in c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Game.cs:line 46
   at WoxSteam.Library.<GetGames>d__5.MoveNext() in c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Library.cs:line 51
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at WoxSteam.Steam.LoadGames() in c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Steam.cs:line 191
   at WoxSteam.Steam.Load() in c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Steam.cs:line 60
   at WoxSteam.Main.Init(PluginInitContext context) in c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Main.cs:line 60
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 19
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 101
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
-->

### Detailed logs
[2019-02-18.txt](https://github.com/Wox-launcher/Wox/files/2878180/2019-02-18.txt)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
