### ISSUE TITLE
Wox got an Error when adding pluginslist plugin

### ISSUE THREAD

**Issue by BoardWatcher** [Wox-launcher/Wox#2362]
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by BoardWatcher** [comment]
Received this error when adding the PluginsList Plugin to Wox.


Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17763.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\charl\AppData\Local\Programs\Python\Python37\pythonw.exe
Everything SDK Path: C:\Users\charl\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 02/20/2019 11:20:11
Exception:
System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\charl\AppData\Local\Wox\app-1.3.183\Plugins'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at Wox.Plugins.PluginsList.Main.LoadPluginInfo(String path)
   at Wox.Plugins.PluginsList.Main.Init(PluginInitContext context)
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 19
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 101
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 91
   at Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:line 60
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\charl\AppData\Local\Wox\app-1.3.183\Plugins'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at Wox.Plugins.PluginsList.Main.LoadPluginInfo(String path)
   at Wox.Plugins.PluginsList.Main.Init(PluginInitContext context)
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 19
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 101
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

**Comment by thediehl** [comment]
The issue is caused by PluginsList using [hardcoded values for Wox's Plugin directory](https://github.com/vladimirantos/Wox.Plugins.PluginsList/blob/3a81455fc96720c21aa28996fd9344f140e1783d/Wox.Plugins.PluginsList/Main.cs#L13) within the user's Local AppData directory. 

In particular, the Local AppData's subdirectory "Wox\app-x.xx.xxx" was suddenly wrong following an update to Wox today. The plugin wants it to be "Wox\app-1.3.183", but I now have "Wox\app-1.3.524".

Although it's just a "band-aid" fix, I did the following to get Wox working again (at least, until PluginsList's author decides to update the plugin).

1. Open Command Prompt as Administrator
2. Run the command "cd %localappdata%\Wox"
3. Run the command "mklink /D app-1.3.183 app-1.3.524"
4. Restart Wox (may need to kill it with Task Manager)
