### ISSUE TITLE
有道的几个插件有问题

### ISSUE THREAD

**Issue by zergneptune** [Wox-launcher/Wox#2378]
#2377 有道插件报错。
我刚装上以后是可以的，过一阵就搜不出翻译了。日志如下。

2019-02-26 15:22:00.3678|ERROR|PluginManager.QueryForPlugin|-------------------------- Begin exception --------------------------
2019-02-26 15:22:00.3678|ERROR|PluginManager.QueryForPlugin|Exception for plugin <有道翻译> when query <yd 火>
2019-02-26 15:22:00.3828|ERROR|PluginManager.QueryForPlugin|Exception fulle name:
 <Newtonsoft.Json.JsonReaderException>
2019-02-26 15:22:00.3828|ERROR|PluginManager.QueryForPlugin|Exception message:
 <Unexpected character encountered while parsing value: <. Path '', line 0, position 0.>
2019-02-26 15:22:00.3828|ERROR|PluginManager.QueryForPlugin|Exception stack trace:
 <   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Wox.Plugin.Youdao.Main.Query(Query query)
   at Wox.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPlugin>b__0() in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 178
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 19
   at Wox.Core.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 0>
2019-02-26 15:22:00.3988|ERROR|PluginManager.QueryForPlugin|Exception source:
 <Newtonsoft.Json>
2019-02-26 15:22:00.3988|ERROR|PluginManager.QueryForPlugin|Exception target site:
 <Boolean ParseValue()>
2019-02-26 15:22:00.3988|ERROR|PluginManager.QueryForPlugin|Exception HResult:
 <-2146233088>
2019-02-26 15:22:00.4138|ERROR|PluginManager.QueryForPlugin|-------------------------- End exception --------------------------

**Comment by zergneptune** [comment]
顺便，有道的几个插件都是这样，就是装上以后刚开始是可以的，但是等一会再用就不行了

**Comment by ttttmr** [comment]
有道翻译私Key版可以用

**Comment by AkiraX2** [comment]
确实不好用，推荐这个https://github.com/harrynull/WoxDictionary

**Comment by jhdxr** [comment]
因为大部分有道插件所有人共用一个key，然后免费的调用次数是非常有限的，所以很容易就超了。。。然后就用不了了，我自己用的也是私Key版，没什么问题

**Comment by AkiraX2** [comment]
> 因为大部分有道插件所有人共用一个key，然后免费的调用次数是非常有限的，所以很容易就超了。。。然后就用不了了，我自己用的也是私Key版，没什么问题

我的公用版出了问题之后，我就弄了一个私key版的，不知道什么原因也不行。

**Comment by ZENOTME** [comment]
> > 因为大部分有道插件所有人共用一个key，然后免费的调用次数是非常有限的，所以很容易就超了。。。然后就用不了了，我自己用的也是私Key版，没什么问题
> 
> 我的公用版出了问题之后，我就弄了一个私key版的，不知道什么原因也不行。

可能是公用版没有删掉？下载私用版要把公用版删掉才可以正常使用私用版的 我是这样的
