### ISSUE TITLE
System.InvalidOperationException thrown when launching `cmd` with elevated privileges

### ISSUE THREAD

**Issue by sql-sith** [Wox-launcher/Wox#2455]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. I called up Wox/Everything using WindowsKey+R. 
2. I believe I had to click in the search box in order to give it the cursor, but I'm not sure. It might have already had the cursor - sometimes it does and sometimes it doesn't, but I can't remember for this particular instance.
3. I typed in `cmd`. 
4. I right-clicked on `cmd` when it appeared as a search result. 
5. I chose the option to run as administrator. 
6. The `cmd` window launched as intended but at the same time ...
8. ... a pop-up appeared asking me to open an issue here, so that is what I am doing.
9. Note that I have not been able to repro on-demand, but hopefully the attached information will help.

### Wox Error Window text

```
Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\chris\AppData\Roaming\Wox\Logs\1.3.524\2019-04-20.txt
2. copy below exception message

Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17763.0
IntPtr Length: 8
x64: True

Python Path: C:\Python37\pythonw.exe
Everything SDK Path: C:\Users\chris\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 04/20/2019 16:31:22
Exception:
System.InvalidOperationException: Can only call DragMove when primary mouse button is down.
   at System.Windows.Window.DragMove()
   at Wox.MainWindow.OnMouseDown(Object sender, MouseButtonEventArgs e) in C:\projects\wox\Wox\MainWindow.xaml.cs:line 151
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### Detailed logs

[2019-04-20.txt](https://github.com/Wox-launcher/Wox/files/3100625/2019-04-20.txt)

### Screenshots (optional)

(drop your screenshot here)
I don't think a screenshot would be helpful since the only related visible content was the window asking me to open this ticket and the `cmd` window which did open successfully.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
