### ISSUE TITLE
Wox crashed when Windows 10 1903 Startup

### ISSUE THREAD

**Issue by gingerbreap** [Wox-launcher/Wox#2493]
### Are you submitting a bug report?
Yes
(write your answer here)

### Steps to reproduce

1. 打开软件 Open the software
2. Error 且无法进行任何操作 Error occured and no actions can be done
3. 卸载下安装包重装 Uninstall and reinstall using re-downloaded installer
4. Same Error

### Wox Error Window text

Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.18890.0
IntPtr Length: 8
x64: True

Python Path: D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\pythonw.exe
Everything SDK Path: C:\Users\peter\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 05/24/2019 22:30:02
Exception:
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at WoxSteam.Options.Load() in c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Options.cs:line 35
   at WoxSteam.Main.Init(PluginInitContext context) in c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Main.cs:line 60
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 18
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 93
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 91
   at Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:line 60
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at WoxSteam.Options.Load() in c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Options.cs:line 35
   at WoxSteam.Main.Init(PluginInitContext context) in c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Main.cs:line 60
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 18
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 93
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
(paste here)

### Detailed logs

[2019-05-24.txt](https://github.com/Wox-launcher/Wox/files/3217334/2019-05-24.txt)
(drop your log file here)

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/27958821/58335343-fc417d80-7e73-11e9-9c91-e0b1b03116b6.png)
(drop your screenshot here)

**Comment by BlueDrink9** [comment]
I personally managed to fix crashes on 1903 by deleting my plugins folder at `%Appdata%/wox/plugins`.

From the error logs, I blame the steam plugin.

**Comment by gingerbreap** [comment]
@BlueDrink9 So is it possible to only delete the steam plugin this way? Don't really want to delete the whole thing....

**Comment by BlueDrink9** [comment]
Yes, I just deleted the steam plugin folder within that directory and left the rest, and Wox started working again after a restart

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
