### ISSUE TITLE
Error when starting mediaplayer over "WIN+R" replacement

### ISSUE THREAD

**Issue by demudeva** [Wox-launcher/Wox#2522]
### Are you submitting a bug report?
Yes
### Steps to reproduce
1. Change Setting: Settings>Plugin>Shell>Choose "RunCommand"
2. Typing: mpv "youtube link" for example "mpv https://www.youtube.com/watch?v=5PdXIHGvMpk"

normally i would use the native WIN+R commandwindow type in mpv "youtube link" and the mediaplayer would play the file over youtube-dl. I dont have a strong pc so it makes watching yt videos fine.

### Wox Error Window text
Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.17763.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\Cankurtaran\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 06/30/2019 17:46:37
Exception:
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Wox.Plugin.Shell.Main.Execute(String command, Boolean runAsAdministrator) in C:\projects\wox\Plugins\Wox.Plugin.Shell\Main.cs:line 233
   at Wox.Plugin.Shell.Main.<>c__DisplayClass11_0.<ResultsFromlHistory>b__2(ActionContext c) in C:\projects\wox\Plugins\Wox.Plugin.Shell\Main.cs:line 157
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 146
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
### Detailed logs
see file upload
[2019-06-30.txt](https://github.com/Wox-launcher/Wox/files/3343060/2019-06-30.txt)

### Screenshots (optional)
i think its quite simple.

**Comment by manitaggarwal** [comment]
Does unchecking it in cmd plugins also brings it up?
