### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by Jinquang** [Wox-launcher/Wox#2535]
### Are you submitting a bug report?
是的

### Steps to reproduce

1. 打开wox
2. 输入 yd st
3.  报错，出现下面的log

### Wox Error Window text

Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\firstboot\Anaconda2\pythonw.exe
Everything SDK Path: C:\Users\firstboot\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 07/12/2019 16:00:49
Exception:
mscorlib
System.ArgumentOutOfRangeException
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.set_Item(Int32 index, Object value)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   at System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
