### ISSUE TITLE
Got this error messagad, Please help

### ISSUE THREAD

**Issue by sagar-monga** [Wox-launcher/Wox#2561]
### Are you submitting a bug report?

No

### Steps to reproduce

1. Open Wox
2. Search for any program/file/plugin
3. Error message 

### Wox Error Window text

Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17763.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\Sagar\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 08/05/2019 11:18:02
Exception:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.set_Item(Int32 index, Object value)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   at System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

### Detailed logs

[2019-08-05.txt](https://github.com/Wox-launcher/Wox/files/3466115/2019-08-05.txt)

### Screenshots (optional)

(drop your screenshot here)

**Comment by Vicropht** [comment]
Hello sagar-monga, try disabling the everything plugin, it appears to not be working correctly

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
