### ISSUE TITLE
error message on start: unhandled exception

### ISSUE THREAD

**Issue by jaredbidlow** [Wox-launcher/Wox#267]

**Comment by che-wf** [comment]
I don't see any explanation for this; however, I'm getting this error when I try running it for the first time. Here's is the full log of my error. 

``````
## Exception

```
System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Wox\Config' is denied.
   Source: mscorlib
   TargetAssembly: mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
   TargetModule: CommonLanguageRuntimeLibrary
   TargetSite: Void WinIOError(Int32, System.String)
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, DirectorySecurity dirSecurity)
   at System.IO.Directory.CreateDirectory(String path, DirectorySecurity directorySecurity)
   at Wox.Infrastructure.Storage.BaseStorage`1.Load() in c:\projects\wox\Wox.Infrastructure\Storage\BaseStorage.cs:line 79
   at Wox.Infrastructure.Storage.BaseStorage`1.get_Instance() in c:\projects\wox\Wox.Infrastructure\Storage\BaseStorage.cs:line 51
   at Wox.MainWindow..ctor() in c:\projects\wox\Wox\MainWindow.xaml.cs:line 164
   at Wox.App.OnStartup(StartupEventArgs e) in c:\projects\wox\Wox\App.xaml.cs:line 39
   at System.Windows.Application.<.ctor>b__0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)

```

## Environment

* Command Line: "C:\Program Files (x86)\Wox\Wox.exe" 
* Exception Handle: System.Windows.Application.DispatcherUnhandledException
* Timestamp: 2015-06-10T13:03:47.0434476-04:00
* IntPtr Length: 8
* System Version: Microsoft Windows NT 6.2.9200.0
* CLR Version: 2.0.50727.8009
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.5.51650
   * v4 Full 4.5.51650
   * v4.0 Client 4.0.0.0

## Assemblies - Wox.exe

* Wox, Version=1.1.1.295, Culture=neutral, PublicKeyToken=null (C:\Program Files (x86)\Wox\Wox.exe)
* Wox.Plugin, Version=1.1.1.295, Culture=neutral, PublicKeyToken=null (C:\Program Files (x86)\Wox\Wox.Plugin.dll)
* Wox.Infrastructure, Version=1.1.1.295, Culture=neutral, PublicKeyToken=null (C:\Program Files (x86)\Wox\Wox.Infrastructure.dll)
* WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Program Files (x86)\Wox\WindowsInput.dll)
* NHotkey, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null (C:\Program Files (x86)\Wox\NHotkey.dll)
* mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorlib.dll)
* PresentationFramework, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\windows\assembly\GAC_MSIL\PresentationFramework\3.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* WindowsBase, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\windows\assembly\GAC_MSIL\WindowsBase\3.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\windows\assembly\GAC_MSIL\System\2.0.0.0__b77a5c561934e089\System.dll)
* PresentationCore, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\windows\assembly\GAC_64\PresentationCore\3.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\windows\assembly\GAC_MSIL\System.Core\3.5.0.0__b77a5c561934e089\System.Core.dll)
* System.Runtime.Remoting, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\windows\assembly\GAC_MSIL\System.Runtime.Remoting\2.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\windows\assembly\GAC_MSIL\System.Windows.Forms\2.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
* System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\windows\assembly\GAC_MSIL\System.Drawing\2.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
* System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\windows\assembly\GAC_MSIL\System.Xml\2.0.0.0__b77a5c561934e089\System.Xml.dll)
* System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\windows\assembly\GAC_MSIL\System.Configuration\2.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* PresentationFramework.Classic, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\windows\assembly\GAC_MSIL\PresentationFramework.Classic\3.0.0.0__31bf3856ad364e35\PresentationFramework.Classic.dll)
* PresentationFramework.Aero, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\windows\assembly\GAC_MSIL\PresentationFramework.Aero\3.0.0.0__31bf3856ad364e35\PresentationFramework.Aero.dll)

## Modules - Wox

* C:\Program Files (x86)\Wox\Wox.exe (Wox, 1.1.1.295, Wox, 1.1.1.295, ), 0x0000000000E20000
* C:\windows\SYSTEM32\ntdll.dll (NT Layer DLL, 6.3.9600.17031 (winblue_gdr.140221-1952), Microsoft® Windows® Operating System, 6.3.9600.17031, Microsoft Corporation), 0x00007FF8FF920000
* C:\windows\SYSTEM32\MSCOREE.DLL (Microsoft .NET Runtime Execution Engine, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF8F1E60000
* C:\windows\system32\KERNEL32.dll (Windows NT BASE API Client DLL, 6.3.9600.17031 (winblue_gdr.140221-1952), Microsoft® Windows® Operating System, 6.3.9600.17031, Microsoft Corporation), 0x00007FF8FE000000
* C:\windows\system32\KERNELBASE.dll (Windows NT BASE API Client DLL, 6.3.9600.17031 (winblue_gdr.140221-1952), Microsoft® Windows® Operating System, 6.3.9600.17031, Microsoft Corporation), 0x00007FF8FBAC0000
* C:\Program Files (x86)\AVG\AVG2015\avghooka.dll (None, 15.0.0.5961, AVG Internet Security, 15.0.0.5961, AVG Technologies CZ, s.r.o.), 0x00007FF8E9C80000
* C:\windows\system32\ADVAPI32.dll (Advanced Windows 32 Base API, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF8FE4F0000
* C:\windows\system32\msvcrt.dll (Windows NT CRT DLL, 7.0.9600.17415 (winblue_r4.141028-1500), Microsoft® Windows® Operating System, 7.0.9600.17415, Microsoft Corporation), 0x00007FF8FDEF0000
* C:\windows\SYSTEM32\sechost.dll (Host for SCM/SDDL/LSA Lookup APIs, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF8FC120000
* C:\windows\system32\RPCRT4.dll (Remote Procedure Call Runtime, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF8FBDC0000
* C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll (Microsoft .NET Runtime Execution Engine, 4.0.30319.34209 built by: FX452RTMGDR, Microsoft® .NET Framework, 4.0.30319.34209, Microsoft Corporation), 0x00007FF8F1D60000
* C:\windows\system32\SHLWAPI.dll (Shell Light-weight Utility Library, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF8FE1F0000
* C:\windows\SYSTEM32\combase.dll (Microsoft COM for Windows, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF8FC2E0000
* C:\windows\system32\USER32.dll (Multi-User Windows USER API Client DLL, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF8FDCB0000
* C:\windows\system32\GDI32.dll (GDI Client DLL, 6.3.9600.17415 (winblue_r4.141028-1500), Microsoft® Windows® Operating System, 6.3.9600.17415, Microsoft Corporation), 0x00007FF8FC500000
* C:\windows\system32\IMM32.DLL (Multi-User Windows IMM32 API Client DLL, 6.3.9600.17415 (winblue_r4.141028-1500), Microsoft® Windows® Operating System, 6.3.9600.17415, Microsoft Corporation), 0x00007FF8FE140000
* C:\windows\system32\MSCTF.dll (MSCTF Server DLL, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF8FC180000
* C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorwks.dll (Microsoft .NET Runtime Common Language Runtime - WorkStation, 2.0.50727.8009 (FX35W81RTMGDR.050727-8000), Microsoft® .NET Framework, 2.0.50727.8009, Microsoft Corporation), 0x00007FF8F12E0000
* C:\windows\WinSxS\amd64_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.8428_none_88dcdb0b2fb19957\MSVCR80.dll (Microsoft® C Runtime Library, 8.00.50727.8428, Microsoft® Visual Studio® 2005, 8.00.50727.8428, Microsoft Corporation), 0x00000000517B0000
* C:\windows\system32\shell32.dll (Windows Shell Common Dll, 6.3.9600.17031 (winblue_gdr.140221-1952), Microsoft® Windows® Operating System, 6.3.9600.17031, Microsoft Corporation), 0x00007FF8FC790000
* C:\windows\SYSTEM32\SHCORE.dll (SHCORE, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF8F9DE0000
* C:\windows\SYSTEM32\profapi.dll (User Profile Basic API, 6.3.9600.17415 (winblue_r4.141028-1500), Microsoft® Windows® Operating System, 6.3.9600.17415, Microsoft Corporation), 0x00007FF8FB890000
* C:\windows\assembly\NativeImages_v2.0.50727_64\mscorlib\6227ee011c9930128c5ad76841ecf2ee\mscorlib.ni.dll (Microsoft Common Language Runtime Class Library, 2.0.50727.8009 (FX35W81RTMGDR.050727-8000), Microsoft® .NET Framework, 2.0.50727.8009, Microsoft Corporation), 0x00007FF8EFB20000
* C:\windows\system32\ole32.dll (Microsoft OLE for Windows, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF8FE5A0000
* C:\windows\SYSTEM32\kernel.appcore.dll (AppModel API Host, 6.3.9600.17415 (winblue_r4.141028-1500), Microsoft® Windows® Operating System, 6.3.9600.17415, Microsoft Corporation), 0x00007FF8FA680000
* C:\windows\SYSTEM32\CRYPTBASE.dll (Base cryptographic API DLL, 6.3.9600.17415 (winblue_r4.141028-1500), Microsoft® Windows® Operating System, 6.3.9600.17415, Microsoft Corporation), 0x00007FF8FB760000
* C:\windows\SYSTEM32\bcryptPrimitives.dll (Windows Cryptographic Primitives Library, 6.3.9600.17415 (winblue_r4.141028-1500), Microsoft® Windows® Operating System, 6.3.9600.17415, Microsoft Corporation), 0x00007FF8FB6F0000
* C:\windows\system32\uxtheme.dll (Microsoft UxTheme Library, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF8FA550000
* C:\Program Files\Common Files\microsoft shared\ink\tiptsf.dll (Touch Keyboard and Handwriting Panel Text Services Framework, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF8F3140000
* C:\windows\system32\OLEAUT32.dll (, 6.3.9600.17560, , 6.3.9600.17560, Microsoft Corporation), 0x00007FF8FE420000
* C:\windows\assembly\NativeImages_v2.0.50727_64\System\eaa20bd3bf0cb4085563a53ce2344adc\System.ni.dll (.NET Framework, 2.0.50727.8009 (FX35W81RTMGDR.050727-8000), Microsoft® .NET Framework, 2.0.50727.8009, Microsoft Corporation), 0x00007FF8EE5F0000
* C:\windows\assembly\NativeImages_v2.0.50727_64\WindowsBase\03ced133dc09e46fc261b19e713dfb5a\WindowsBase.ni.dll (WindowsBase.dll, 3.0.6920.8005 built by: FX35W81RTMGDR, Microsoft® .NET Framework, 3.0.6920.8005, Microsoft Corporation), 0x00007FF8E58B0000
* C:\windows\assembly\NativeImages_v2.0.50727_64\PresentationCore\9f72d244cc305236aa8d8803e2385552\PresentationCore.ni.dll (PresentationCore.dll, 3.0.6920.8005 built by: FX35W81RTMGDR, Microsoft® .NET Framework, 3.0.6920.8005, Microsoft Corporation), 0x00007FF8E48E0000
* C:\windows\assembly\NativeImages_v2.0.50727_64\PresentationFramewo#\099c5d9b448dd29baec0bbc1563b70aa\PresentationFramework.ni.dll (PresentationFramework.dll, 3.0.6920.8005 built by: FX35W81RTMGDR, Microsoft® .NET Framework, 3.0.6920.8005, Microsoft Corporation), 0x00007FF8D52B0000
* C:\Windows\Microsoft.NET\Framework64\v3.0\WPF\wpfgfx_v0300.dll (wpfgfx_v0300.dll, 3.0.6920.8005 built by: FX35W81RTMGDR, Microsoft® .NET Framework, 3.0.6920.8005, Microsoft Corporation), 0x0000000051350000
* C:\windows\assembly\NativeImages_v2.0.50727_64\System.Core\e0cbbb43ac117955b71d70bb8510fcf8\System.Core.ni.dll (.NET Framework, 3.5.30729.7903 built by: Win9Rel, Microsoft® .NET Framework, 3.5.30729.7903, Microsoft Corporation), 0x00007FF8D4F80000
* C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorjit.dll (Microsoft .NET Runtime Just-In-Time Compiler, 2.0.50727.7905 (win9rel.050727-7900), Microsoft® .NET Framework, 2.0.50727.7905, Microsoft Corporation), 0x00007FF8EF750000
* C:\windows\SYSTEM32\SspiCli.dll (Security Support Provider Interface, 6.3.9600.17415 (winblue_r4.141028-1500), Microsoft® Windows® Operating System, 6.3.9600.17415, Microsoft Corporation), 0x00007FF8FB6C0000
* C:\windows\assembly\NativeImages_v2.0.50727_64\System.Runtime.Remo#\96c78b803536d9b7a7545eb19bd9fed6\System.Runtime.Remoting.ni.dll (Microsoft .NET Runtime Object Remoting, 2.0.50727.8012 (FX35W81RTMGDR.050727-8000), Microsoft® .NET Framework, 2.0.50727.8012, Microsoft Corporation), 0x00007FF8F2AB0000
* C:\windows\SYSTEM32\CRYPTSP.dll (Cryptographic Service Provider API, 6.3.9600.17415 (winblue_r4.141028-1500), Microsoft® Windows® Operating System, 6.3.9600.17415, Microsoft Corporation), 0x00007FF8FB190000
* C:\windows\system32\rsaenh.dll (Microsoft Enhanced Cryptographic Provider, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF8FB090000
* C:\windows\SYSTEM32\bcrypt.dll (Windows Cryptographic Primitives Library, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF8FB3B0000
* C:\windows\system32\dwmapi.dll (Microsoft Desktop Window Manager API, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF8F9BE0000
* C:\windows\assembly\NativeImages_v2.0.50727_64\System.Drawing\ca43a3085d56bbbeb9920035e37bab68\System.Drawing.ni.dll (.NET Framework, 2.0.50727.8015 (FX35W81RTMGDR.050727-8000), Microsoft® .NET Framework, 2.0.50727.8015, Microsoft Corporation), 0x00007FF8EF3B0000
* C:\windows\assembly\NativeImages_v2.0.50727_64\System.Windows.Forms\bfc65bbcd57339e25ac320d50859e32d\System.Windows.Forms.ni.dll (.NET Framework, 2.0.50727.8015 (FX35W81RTMGDR.050727-8000), Microsoft® .NET Framework, 2.0.50727.8015, Microsoft Corporation), 0x00007FF8ED550000
* C:\Program Files (x86)\Wox\Wox.Plugin.dll (Wox.Plugin, 1.1.1.295, Wox.Plugin, 1.1.1.295, ), 0x000000001C020000
* C:\Program Files (x86)\Wox\Wox.Infrastructure.dll (Wox.Infrastructure, 1.1.1.295, Wox.Infrastructure, 1.1.1.295, ), 0x000000001C040000
* C:\Program Files (x86)\Wox\WindowsInput.dll (WindowsInput, 1.0.4.0, WindowsInput, 1.0.4.0, michaelnoonan), 0x000000001C1C0000
* C:\Program Files (x86)\Wox\NHotkey.dll (NHotkey, 1.1.0.0, NHotkey, 1.1.0.0, ), 0x000000001C1E0000
* C:\windows\system32\psapi.dll (Process Status Helper, 6.3.9600.17415 (winblue_r4.141028-1500), Microsoft® Windows® Operating System, 6.3.9600.17415, Microsoft Corporation), 0x00007FF8FE410000
* C:\windows\SYSTEM32\urlmon.dll (OLE32 Extensions for Win32, 11.00.9600.16384 (winblue_rtm.130821-1623), Internet Explorer, 11.00.9600.16384, Microsoft Corporation), 0x00007FF8F3A50000
* C:\windows\SYSTEM32\iertutil.dll (Run time utility for Internet Explorer, 11.00.9600.16384 (winblue_rtm.130821-1623), Internet Explorer, 11.00.9600.16384, Microsoft Corporation), 0x00007FF8F3780000
* C:\windows\SYSTEM32\WININET.dll (Internet Extensions for Win32, 11.00.9600.16384 (winblue_rtm.130821-1623), Internet Explorer, 11.00.9600.16384, Microsoft Corporation), 0x00007FF8F3530000
* C:\windows\SYSTEM32\USERENV.dll (Userenv, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF8FAE20000
* C:\windows\SYSTEM32\WindowsCodecs.dll (Microsoft Windows Codecs Library, 6.3.9600.17669 (winblue_r8.150128-1500), Microsoft® Windows® Operating System, 6.3.9600.17669, Microsoft Corporation), 0x00007FF8F9A30000
* C:\windows\SYSTEM32\mscms.dll (Microsoft Color Matching System DLL, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF8F8760000
* C:\windows\assembly\NativeImages_v2.0.50727_64\System.Xml\0c0a5cc6d838d661c624d6d7e4d48855\System.Xml.ni.dll (.NET Framework, 2.0.50727.8009 (FX35W81RTMGDR.050727-8000), Microsoft® .NET Framework, 2.0.50727.8009, Microsoft Corporation), 0x00007FF8ECEA0000
* C:\windows\assembly\NativeImages_v2.0.50727_64\System.Configuration\45e619ade9b4e897a84329bef35c4383\System.Configuration.ni.dll (System.Configuration.dll, 2.0.50727.8007 (FX35W81RTMGDR.050727-8000), Microsoft® .NET Framework, 2.0.50727.8007, Microsoft Corporation), 0x00007FF8DC170000
* C:\windows\SYSTEM32\WindowsCodecsExt.dll (Microsoft Windows Codecs Extended Library, 6.3.9600.17415 (winblue_r4.141028-1500), Microsoft® Windows® Operating System, 6.3.9600.17415, Microsoft Corporation), 0x00007FF8E8C60000
* C:\windows\assembly\GAC_MSIL\PresentationFramework.Classic\3.0.0.0__31bf3856ad364e35\PresentationFramework.Classic.dll (PresentationFramework.Classic.dll, 3.0.6920.7903 built by: Win9Rel, Microsoft® .NET Framework, 3.0.6920.7903, Microsoft Corporation), 0x000000001C440000
* C:\windows\SYSTEM32\d3d9.dll (Direct3D 9 Runtime, 6.3.9600.17415 (winblue_r4.141028-1500), Microsoft® Windows® Operating System, 6.3.9600.17415, Microsoft Corporation), 0x00007FF8ECC10000
* C:\windows\SYSTEM32\VERSION.dll (Version Checking and File Installation Libraries, 6.3.9600.17415 (winblue_r4.141028-1500), Microsoft® Windows® Operating System, 6.3.9600.17415, Microsoft Corporation), 0x00007FF8F8720000
* C:\windows\SYSTEM32\igdumdim64.dll (User Mode Driver for Intel(R) Graphics Technology, 10.18.14.4029, Intel HD Graphics Drivers for Windows 8(R), 10.18.14.4029, Intel Corporation), 0x00007FF8D1F00000
* C:\windows\assembly\NativeImages_v2.0.50727_64\PresentationFramewo#\3888e8e5c06ec56c1b1a4ab9c73cc89d\PresentationFramework.Aero.ni.dll (PresentationFramework.Aero.dll, 3.0.6920.7903 built by: Win9Rel, Microsoft® .NET Framework, 3.0.6920.7903, Microsoft Corporation), 0x00007FF8DB570000
* C:\Windows\Microsoft.NET\Framework64\v2.0.50727\diasymreader.dll (Dia based SymReader, 8.0.50727.8007 (FX35W81RTMGDR.050727-8000), Microsoft® Visual Studio® 2005, 8.0.50727.8007, Microsoft Corporation), 0x00007FF8F2C30000

## Threads - 11

* 18256, Running Normal, Started: 06/10/15 13:03:46, StartAddress: 0x00007FF8FF935410
* 22704, Wait Normal, Started: 06/10/15 13:03:46, StartAddress: 0x00007FF8FF935410
* 23564, Wait Highest, Started: 06/10/15 13:03:46, StartAddress: 0x00007FF8FF935410
* 23976, Wait Normal, Started: 06/10/15 13:03:46, StartAddress: 0x00007FF8FF935410
* 21892, Wait Normal, Started: 06/10/15 13:03:46, StartAddress: 0x00007FF8FF935410
* 22308, Wait Normal, Started: 06/10/15 13:03:46, StartAddress: 0x00007FF8FF935410
* 24068, Wait Normal, Started: 06/10/15 13:03:46, StartAddress: 0x00007FF8FF935410
* 23248, Wait Normal, Started: 06/10/15 13:03:46, StartAddress: 0x00007FF8FF935410
* 24360, Wait Normal, Started: 06/10/15 13:03:46, StartAddress: 0x00007FF8FF935410
* 23932, Wait Normal, Started: 06/10/15 13:03:46, StartAddress: 0x00007FF8FF935410
* 24128, Wait Normal, Started: 06/10/15 13:03:47, StartAddress: 0x00007FF8FF935410
``````

**Comment by qianlifeng** [comment]
This is permission issues. Don't put Wox in C:\Program Files when you enabled UAC. You can try to put Wox folder to other places, e.g. D:\Wox

**Comment by sschuberth** [comment]
Wouldn't it actually be more appropriate for Wox to fall back to `%AppData%\Wox\Config` if `<Directory of Wox.exe>\Config` cannot be accessed, so that you actually _can_ put it under `%ProgramFiles%`?

**Comment by deltaidea** [comment]
@sschuberth :+1: That is the correct solution.

**Comment by bao-qian** [comment]
should be fixed in latest pre release:
https://github.com/Wox-launcher/Wox/releases/tag/v1.2.900
