### ISSUE TITLE
Wox Stopped Working, Shows this error

### ISSUE THREAD

**Issue by Abhinaviitp007** [Wox-launcher/Wox#2672]
Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.18363.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 12/07/2019 18:43:10
Exception:
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Wox.Core.Plugin.PluginsLoader.<>c__DisplayClass4_0.<CSharpPlugins>b__1() in C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:line 55
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 19
   at Wox.Core.Plugin.PluginsLoader.CSharpPlugins(List`1 source) in C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:line 84
   at Wox.Core.Plugin.PluginsLoader.Plugins(List`1 metadatas, PluginsSettings settings) in C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:line 22
   at Wox.Core.Plugin.PluginManager.LoadPlugins(PluginsSettings settings) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 85
   at Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:line 58
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2019-12-07.txt](https://github.com/Wox-launcher/Wox/files/3935091/2019-12-07.txt)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
