### ISSUE TITLE
Wox 1.3.524 got an error, google query

### ISSUE THREAD

**Issue by AlexDT** [Wox-launcher/Wox#2700]
Not sure what the bug is, but wox crashed after trying to google something.

### Steps to reproduce
1. Write my query
2. Went to the front of the query to add the letter g to make it a google search query
[2020-01-15.txt](https://github.com/Wox-launcher/Wox/files/4064354/2020-01-15.txt)

### Wox Error Window text
Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.18362.0
IntPtr Length: 8
x64: True

Python Path: pythonw.exe
Everything SDK Path: C:\Users\909221\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 01/15/2020 11:07:52
Exception:
System.ArgumentOutOfRangeException: Insertion index was out of range. Must be non-negative and less than or equal to size.
Parameter name: index
   at System.Collections.ArrayList.Insert(Int32 index, Object value)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   at System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
