### ISSUE TITLE
Wox crashes when restarting after uninstalling a plugin

### ISSUE THREAD

**Issue by LoZeno** [Wox-launcher/Wox#2701]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Install wox plugin by drag-and-drop in the wox bar (NOT with wpm)
2. use wpm uninstall <plugin name> to uninstall the plugin
3. when prompted, reply "yes" to restart wox
4. crash happens

### Wox Error Window text
Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.18363.0
IntPtr Length: 8
x64: True

Python Path: pythonw.exe
Everything SDK Path: C:\Users\Tesco-UKE12364653\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 01/17/2020 09:10:34
Exception:
System.Exception: Update.exe not found, not a Squirrel-installed app?
   at Squirrel.UpdateManager.getUpdateExe() in C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:line 313
   at Squirrel.UpdateManager.RestartApp(String exeToStart, String arguments) in C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:line 196
   at Wox.Plugin.PluginManagement.Main.UnInstallPlugin(PluginMetadata plugin) in C:\projects\wox\Plugins\Wox.Plugin.PluginManagement\Main.cs:line 221
   at Wox.Plugin.PluginManagement.Main.<>c__DisplayClass13_1.<ResultForUnInstallPlugin>b__2(ActionContext e) in C:\projects\wox\Plugins\Wox.Plugin.PluginManagement\Main.cs:line 197
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 146
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

[2020-01-17.txt](https://github.com/Wox-launcher/Wox/files/4075898/2020-01-17.txt)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
