### ISSUE TITLE
"The system cannot find the file specified" when using action keyword for Control Panel

### ISSUE THREAD

**Issue by zejjnt** [Wox-launcher/Wox#2732]
### Are you submitting a bug report?
Yes

### Steps to reproduce
* Set action keyword "cp" (without "") for the Control Panel plugin
* Try using that keyword in Wox

### Wox Error Window text
Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.18363.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\ZaInT\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 02/17/2020 03:53:56
Exception:
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Wox.Plugin.Shell.Main.Execute(String command, Boolean runAsAdministrator) in C:\projects\wox\Plugins\Wox.Plugin.Shell\Main.cs:line 233
   at Wox.Plugin.Shell.Main.<>c__DisplayClass10_0.<GetCurrentCmd>b__0(ActionContext c) in C:\projects\wox\Plugins\Wox.Plugin.Shell\Main.cs:line 139
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 146
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs
2020-02-17 03:53:56.2369|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2020-02-17 03:53:56.2369|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2020-02-17 03:53:56.2448|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.ComponentModel.Win32Exception>
2020-02-17 03:53:56.2448|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <The system cannot find the file specified>
2020-02-17 03:53:56.2448|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)>
2020-02-17 03:53:56.2448|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <System>
2020-02-17 03:53:56.2597|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)>
2020-02-17 03:53:56.2597|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2147467259>
2020-02-17 03:53:56.2597|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2020-02-17 03:53:56.3207|FATAL|UnHandledException|
## Exception

```
System.ComponentModel.Win32Exception: The system cannot find the file specified
   Source: System
   TargetAssembly: System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
   TargetModule: System.dll
   TargetSite: Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Wox.Plugin.Shell.Main.Execute(String command, Boolean runAsAdministrator) in C:\projects\wox\Plugins\Wox.Plugin.Shell\Main.cs:line 233
   at Wox.Plugin.Shell.Main.<>c__DisplayClass10_0.<GetCurrentCmd>b__0(ActionContext c) in C:\projects\wox\Plugins\Wox.Plugin.Shell\Main.cs:line 139
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 146
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

## Environment
* Command Line: "C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Wox.exe" 
* Timestamp: 02/17/2020 03:53:56
* Wox version: 1.3.578
* OS Version: Microsoft Windows NT 10.0.18363.0
* IntPtr Length: 8
* x64: True
* Python Path: 
* Everything SDK Path: C:\Users\ZaInT\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.8.03752
   * v4 Full 4.8.03752
   * v4.0 Client 4.0.0.0

## Assemblies - Wox.exe

* Wox, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Wox.exe)
* Wox.Infrastructure, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Wox.Infrastructure.dll)
* Wox.Plugin, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Wox.Plugin.dll)
* Wox.Core, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Wox.Core.dll)
* NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\NLog.dll)
* Pinyin4Net, Version=2016.4.24.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Pinyin4Net.dll)
* Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Newtonsoft.Json.dll)
* Wox.Plugin.Caculator, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
* Mages.Core, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Caculator\Mages.Core.dll)
* Wox.Plugin.Color, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
* Wox.Plugin.ControlPanel, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
* Wox.Plugin.Everything, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
* Wox.Plugin.Folder, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
* Wox.Plugin.PluginIndicator, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
* Wox.Plugin.PluginManagement, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
* Wox.Plugin.Program, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
* Wox.Plugin.Shell, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
* WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\WindowsInput.dll)
* Wox.Plugin.Sys, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
* Wox.Plugin.Url, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
* Wox.Plugin.WebSearch, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
* NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\NHotkey.dll)
* Windows.ApplicationModel, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\Windows\system32\WinMetadata\Windows.ApplicationModel.winmd)
* Windows.Management, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\Windows\system32\WinMetadata\Windows.Management.winmd)
* Windows.Foundation, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\Windows\system32\WinMetadata\Windows.Foundation.winmd)
* Windows.Storage, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\Windows\system32\WinMetadata\Windows.Storage.winmd)
* NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\NHotkey.Wpf.dll)
* Squirrel, Version=1.5.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Squirrel.dll)
* Splat, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\Splat.dll)
* NuGet.Squirrel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\ZaInT\AppData\Local\Wox\app-1.3.578\NuGet.Squirrel.dll)
* Windows.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\Windows\system32\WinMetadata\Windows.UI.winmd)
* mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
* PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
* System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
* PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
* System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
* System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
* System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
* System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
* System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
* System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
* System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
* System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll)
* PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)
* System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
* System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll)
* UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll)
* UIAutomationProvider, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll)
* PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll)
* PresentationFramework-SystemXmlLinq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXmlLinq\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXmlLinq.dll)
* PresentationFramework-SystemXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll)
* Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll)
* System.Runtime.InteropServices.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.WindowsRuntime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.WindowsRuntime.dll)

2020-02-17 03:54:06.1764|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2020-02-17 03:54:06.1819|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2020-02-17 03:54:06.1819|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.Deployment.Application.InvalidDeploymentException>
2020-02-17 03:54:06.1819|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <Application identity is not set.>
2020-02-17 03:54:06.1992|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()>
2020-02-17 03:54:06.1992|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <System.Deployment>
2020-02-17 03:54:06.1992|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <System.Deployment.Application.ApplicationDeployment get_CurrentDeployment()>
2020-02-17 03:54:06.2156|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2146233087>
2020-02-17 03:54:06.2156|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2020-02-17 03:57:12.6656|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2020-02-17 03:57:12.6656|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2020-02-17 03:57:12.6656|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.FormatException>
2020-02-17 03:57:12.6815|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <Input string was not in a correct format.>
2020-02-17 03:57:12.6815|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)>
2020-02-17 03:57:12.6815|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <mscorlib>
2020-02-17 03:57:12.6984|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <Double ParseDouble(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)>
2020-02-17 03:57:12.6984|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2146233033>
2020-02-17 03:57:12.6984|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
