### ISSUE TITLE
error message asked me to open a case

### ISSUE THREAD

**Issue by eddiesq604** [Wox-launcher/Wox#2740]
Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.18363.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 02/25/2020 18:35:32
Exception:
System.Net.WebException: The operation has timed out
   at System.Net.FileWebRequest.GetResponse()
   at MS.Internal.WpfWebRequestHelper.GetResponse(WebRequest request)
   at System.Windows.ResourceDictionary.set_Source(Uri value)
   at Wox.Core.Resource.Internationalization.LoadLanguage(Language language) in C:\projects\wox\Wox.Core\Resource\Internationalization.cs:line 128
   at Wox.Core.Resource.Internationalization..ctor() in C:\projects\wox\Wox.Core\Resource\Internationalization.cs:line 27
   at Wox.Core.Resource.InternationalizationManager.get_Instance() in C:\projects\wox\Wox.Core\Resource\InternationalizationManager.cs:line 18
   at Wox.ViewModel.MainViewModel..ctor(Settings settings) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 44
   at Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:line 58
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

<!-

- 
     ===================================================
     DO NOT DELETE UNTIL YOU HAVE READ THE FIRST SECTION
     ===================================================

     To be able to help you we need enough information to find
     what is causing your issue. Please follow the instructions 
     and type the requested information where prompted. 
     
     ===================================================
     中文版说明，请仔细阅读并在填写后删除此说明段落，无效的反馈会被直接关闭
     ===================================================
     请遵循以下说明，提供我们所需要的信息来，这样我们才能找出导致你
     遇到的问题的原因，来更好的帮助你。
     如果可以的话，请附上一份英文的翻译（哪怕是直接使用谷歌翻译）
     请注意，无效的反馈（尤其是没有填写下面那些信息的反馈）会被直接关闭！
-->

### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
