### ISSUE TITLE
Wox System.InvalidOperationException

### ISSUE THREAD

**Issue by homer1993** [Wox-launcher/Wox#2769]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. open wox via shortcut
2. search an application called "thu" > thunderbird
3. "wox got an error" box showed up

### Wox Error Window text

2020-03-13 08:07:41.7728|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2020-03-13 08:07:41.8195|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2020-03-13 08:07:41.8435|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.InvalidOperationException>
2020-03-13 08:07:41.8654|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <Can only call DragMove when primary mouse button is down.>
2020-03-13 08:07:41.8963|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   at System.Windows.Window.DragMove()>
2020-03-13 08:07:41.9118|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <PresentationFramework>
2020-03-13 08:07:41.9118|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <Void DragMove()>
2020-03-13 08:07:41.9257|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2146233079>
2020-03-13 08:07:41.9257|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------

### Detailed logs

2020-03-13 08:07:41.7728|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2020-03-13 08:07:41.8195|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2020-03-13 08:07:41.8435|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.InvalidOperationException>
2020-03-13 08:07:41.8654|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <Can only call DragMove when primary mouse button is down.>
2020-03-13 08:07:41.8963|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   at System.Windows.Window.DragMove()>
2020-03-13 08:07:41.9118|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <PresentationFramework>
2020-03-13 08:07:41.9118|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <Void DragMove()>
2020-03-13 08:07:41.9257|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2146233079>
2020-03-13 08:07:41.9257|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2020-03-13 08:07:41.9916|FATAL|UnHandledException|
## Exception

```
System.InvalidOperationException: Can only call DragMove when primary mouse button is down.
   Source: PresentationFramework
   TargetAssembly: PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
   TargetModule: PresentationFramework.dll
   TargetSite: Void DragMove()
   at System.Windows.Window.DragMove()
   at Wox.MainWindow.OnMouseDown(Object sender, MouseButtonEventArgs e) in C:\projects\wox\Wox\MainWindow.xaml.cs:line 158
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

## Environment
* Command Line: "C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Wox.exe" 
* Timestamp: 03/13/2020 08:07:41
* Wox version: 1.3.578
* OS Version: Microsoft Windows NT 10.0.18363.0
* IntPtr Length: 8
* x64: True
* Python Path: pythonw.exe
* Everything SDK Path: C:\Users\%username%\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.8.03752
   * v4 Full 4.8.03752
   * v4.0 Client 4.0.0.0

## Assemblies - Wox.exe

* Wox, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Wox.exe)
* Wox.Infrastructure, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Wox.Infrastructure.dll)
* Wox.Plugin, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Wox.Plugin.dll)
* Wox.Core, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Wox.Core.dll)
* NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\NLog.dll)
* Pinyin4Net, Version=2016.4.24.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Pinyin4Net.dll)
* Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Newtonsoft.Json.dll)
* Wox.Plugin.Caculator, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
* Mages.Core, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Caculator\Mages.Core.dll)
* Wox.Plugin.Color, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
* Wox.Plugin.ControlPanel, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
* Wox.Plugin.Everything, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
* Wox.Plugin.Folder, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
* Wox.Plugin.PluginIndicator, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
* Wox.Plugin.PluginManagement, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
* Wox.Plugin.Program, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
* Wox.Plugin.Shell, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
* WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\WindowsInput.dll)
* Wox.Plugin.Sys, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
* Wox.Plugin.Url, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
* Wox.Plugin.WebSearch, Version=1.3.578.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
* NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\NHotkey.dll)
* Windows.ApplicationModel, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.ApplicationModel.winmd)
* Windows.Foundation, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.Foundation.winmd)
* Windows.Management, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.Management.winmd)
* Windows.Storage, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.Storage.winmd)
* Windows.System, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.System.winmd)
* NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\NHotkey.Wpf.dll)
* Squirrel, Version=1.5.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Squirrel.dll)
* Splat, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\Splat.dll)
* NuGet.Squirrel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\%username%\AppData\Local\Wox\app-1.3.578\NuGet.Squirrel.dll)
* mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
* PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
* System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
* PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
* System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
* System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
* System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
* System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
* System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
* System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
* System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
* System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll)
* PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)
* System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
* System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll)
* UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll)
* UIAutomationProvider, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll)
* PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll)
* PresentationFramework-SystemXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll)
* PresentationFramework-SystemXmlLinq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXmlLinq\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXmlLinq.dll)

2020-03-13 08:14:55.5553|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2020-03-13 08:14:55.5852|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2020-03-13 08:14:55.6112|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.Deployment.Application.InvalidDeploymentException>
2020-03-13 08:14:55.6371|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <Application identity is not set.>
2020-03-13 08:14:55.6767|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()>
2020-03-13 08:14:55.6920|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <System.Deployment>
2020-03-13 08:14:55.7135|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <System.Deployment.Application.ApplicationDeployment get_CurrentDeployment()>
2020-03-13 08:14:55.7369|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2146233087>
2020-03-13 08:14:55.7628|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
