### ISSUE TITLE
Timer Plugin Wox Issue

### ISSUE THREAD

**Issue by ghost** [Wox-launcher/Wox#2803]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Installed Timer plugin using command 'wpm install Timer'.
2. Once it installed and wox restarted, I entered the keyword followed by space followed by an integer to denote the seconds to set the timer for as per the instructions by the author using command 'timer 3'
3. Got timer wox error with a new screen pop up that asked me to upload a log file and redirected me here to add a new issue.

### Wox Error Window text

Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.18362.0
IntPtr Length: 8
x64: True

Python Path: pythonw.exe
Everything SDK Path: C:\Users\DELL\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 04/12/2020 00:50:24
Exception:
System.ArgumentOutOfRangeException: Insertion index was out of range. Must be non-negative and less than or equal to size.
Parameter name: index
   at System.Collections.ArrayList.Insert(Int32 index, Object value)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   at System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

[2020-04-12.txt](https://github.com/Wox-launcher/Wox/files/4465262/2020-04-12.txt)

### Screenshots (optional)

(drop your screenshot here)

![image](https://user-images.githubusercontent.com/45403199/79053225-59dfe380-7c59-11ea-8ee3-021e22ab4ec7.png)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
