### ISSUE TITLE
"Wox has stopped working" after installing a plugin and restart confirmation

### ISSUE THREAD

**Issue by Leon99** [Wox-launcher/Wox#287]

**Comment by Leon99** [comment]
Here is what debugging shows - after typing Exit in Dev, in MainWindow.CloseApp():

System.InvalidOperationException was unhandled
  Message=There is no registered CultureInfo with the IetfLanguageTag 'ug'.
  Source=PresentationCore
  StackTrace:
       at System.Windows.Markup.XmlLanguage.GetEquivalentCulture()
       at System.Windows.Markup.XmlLanguage.TryGetEquivalentCulture(CultureInfo& culture)
  InnerException: System.ArgumentException
       Message=Culture name 'ug' is not supported.
Parameter name: name
       Source=mscorlib
       ParamName=name
       StackTrace:
            at System.Globalization.CultureInfo.GetCultureInfo(String name)
            at System.Globalization.CultureInfo.GetCultureInfoByIetfLanguageTag(String name)
            at MS.Internal.PresentationCore.SafeSecurityHelper.GetCultureInfoByIetfLanguageTag(String languageTag)
            at System.Windows.Markup.XmlLanguage.GetEquivalentCulture()
       InnerException:

**Comment by bao-qian** [comment]
Hi, I refactored the logic of restart. use `ping` to test existence of Wox will cause more bugs in the future.
Please try with build [1.2.592](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.592/artifacts) and provide feedbacks.

@Leon99

**Comment by bao-qian** [comment]
#322
