### ISSUE TITLE
System.Exception: Couldn't acquire lock, is another instance runningSample bug report

### ISSUE THREAD

**Issue by lcyan** [Wox-launcher/Wox#2884]
Wox version: 1.3.881
OS Version: Microsoft Windows NT 10.0.17763.0
IntPtr Length: 8
x64: True

Python Path: pythonw.exe
Everything SDK Path: C:\Users\Administrator\AppData\Local\Wox\app-1.3.881\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 04/27/2020 10:00:33
Exception:
System.Exception: Couldn't acquire lock, is another instance running
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut) in C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\Utility.cs:line 778
   at Squirrel.UpdateManager.<acquireUpdateLock>b__32_0() in C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:line 274
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext() in C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Wox.Core.Updater.<UpdateApp>d__5.MoveNext() in C:\projects\wox\Wox.Core\Updater.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Wox.ViewModel.SettingWindowViewModel.<UpdateApp>d__8.MoveNext() in C:\projects\wox\Wox\ViewModel\SettingWindowViewModel.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2020-04-27.txt](https://github.com/Wox-launcher/Wox/files/4536981/2020-04-27.txt)

**Comment by bao-qian** [comment]
there is another instance running, try to find and kill it.
or you can always restart you computer or relogin
