### ISSUE TITLE
WOX plugin Define ERROR

### ISSUE THREAD

**Issue by homeostashish** [Wox-launcher/Wox#2895]
Exception:
System.Exception: Update.exe not found, not a Squirrel-installed app?
   at Squirrel.UpdateManager.getUpdateExe() in C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:line 313
   at Squirrel.UpdateManager.RestartApp(String exeToStart, String arguments) in C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:line 196
   at Wox.Core.Plugin.PluginInstaller.Install(String path) in C:\projects\wox\Wox.Core\Plugin\PluginInstaller.cs:line 93
   at Wox.PublicAPIInstance.<>c__DisplayClass18_0.<InstallPlugin>b__0() in C:\projects\wox\Wox\PublicAPIInstance.cs:line 134
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Wox.Plugin.PluginManagement.Main.<>c__DisplayClass12_0.<ResultForInstallPlugin>b__0(ActionContext c) in C:\projects\wox\Plugins\Wox.Plugin.PluginManagement\Main.cs:line 175
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_7(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 160
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

THE LOG FILE   --->   [2020-04-29.txt](https://github.com/Wox-launcher/Wox/files/4550627/2020-04-29.txt)

**Comment by bao-qian** [comment]
duplicate #2896
