### ISSUE TITLE
WOX Plugin Error while restarting wox

### ISSUE THREAD

**Issue by homeostashish** [Wox-launcher/Wox#2896]
LOG FILE : [2020-04-29.txt](https://github.com/Wox-launcher/Wox/files/4550648/2020-04-29.txt)

EXEPTION ERROR:

Wox version: 1.3.881
OS Version: Microsoft Windows NT 10.0.18363.0
IntPtr Length: 8
x64: True

Python Path: pythonw.exe
Everything SDK Path: C:\Users\Ashish Kr. Prasad\Downloads\Wox-1.3.881\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 04/29/2020 14:26:09
Exception:
System.Exception: Update.exe not found, not a Squirrel-installed app?
   at Squirrel.UpdateManager.getUpdateExe() in C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:line 313
   at Squirrel.UpdateManager.RestartApp(String exeToStart, String arguments) in C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:line 196
   at Wox.Plugin.Sys.Main.<Commands>b__14_9(ActionContext c) in C:\projects\wox\Plugins\Wox.Plugin.Sys\Main.cs:line 209
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_7(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 160
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
please describe how to reproduce this error
