### ISSUE TITLE
permission check

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#2930]
https://github.com/Wox-launcher/Wox/issues/2625
https://github.com/Wox-launcher/Wox/issues/2929

```
System.UnauthorizedAccessException: Access to the path 'C:\Users\web\Documents\Tencent Files\3494350596\Image\Group\$$GO`){5J%)`I0NV4UWS$IK.png' is denied.
    HResult: -2147024891
    Source: mscorlib
    TargetAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
    TargetModule: CommonLanguageRuntimeLibrary
    TargetSite: Void WinIOError(Int32, System.String)
    StackTrace: --------------------
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at Wox.Image.ImageLoader.LoadInternal(String path) in C:\Users\Ricky\Code\Wox\Wox\Image\ImageLoader.cs:line 71
   at Wox.Image.ImageCache.Add(String key, Func`2 imageFactory) in C:\Users\Ricky\Code\Wox\Wox\Image\ImageCache.cs:line 111
   at Wox.Image.ImageCache.<>c__DisplayClass11_0.<GetOrAdd>b__0() in C:\Users\Ricky\Code\Wox\Wox\Image\ImageCache.cs:line 95
   at System.Threading.Tasks.Task.Execute()
```

**Comment by bao-qian** [comment]
https://github.com/Wox-launcher/Wox/issues/2578

**Comment by bao-qian** [comment]
https://github.com/Wox-launcher/Wox/issues/1068

**Comment by bao-qian** [comment]
https://github.com/Wox-launcher/Wox/issues/1292

**Comment by bao-qian** [comment]
https://github.com/Wox-launcher/Wox/issues/726

**Comment by bao-qian** [comment]
https://github.com/Wox-launcher/Wox/issues/2470

**Comment by bao-qian** [comment]
https://github.com/Wox-launcher/Wox/issues/2342

**Comment by bao-qian** [comment]
https://github.com/Wox-launcher/Wox/issues/2388
