### ISSUE TITLE
windows 8 detection support.

### ISSUE THREAD

**Issue by aaaxx** [Wox-launcher/Wox#2932]
```
Exception begin --------------------
  System.MissingMethodException: Method not found: 'System.Runtime.InteropServices.WindowsRuntime.EventRegistrationToken Windows.UI.ViewManagement.UISettings.add_ColorValuesChanged(Windows.Foundation.TypedEventHandler`2<Windows.UI.ViewManagement.UISettings,System.Object>)'.
  HResult: -2146233069
  Data: <System.Object> -> <>
  Data: <AlreadySentByRaygun> -> <True>
  Source: Wox.Core
  TargetAssembly: Wox.Core, Version=1.3.1036.0, Culture=neutral, PublicKeyToken=null
  TargetModule: Wox.Core.dll
  TargetSite: Void AutoReload()
  StackTrace: --------------------
   at Wox.Core.Resource.Theme.AutoReload()
   at Wox.Core.Resource.ThemeManager.get_Instance() in C:\projects\wox\Wox.Core\Resource\ThemeManager.cs:line 18
   at Wox.App.<OnStartup>b__16_0() in C:\projects\wox\Wox\App.xaml.cs:line 115
   at Wox.Infrastructure.Stopwatch.StopWatchNormal(Logger logger, String message, Action action, String methodName) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 34
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Exception end ------------------------------------------------------------
```

```
Exception begin --------------------
  System.MissingMethodException: Method not found: 'System.Runtime.InteropServices.WindowsRuntime.EventRegistrationToken Windows.UI.ViewManagement.UISettings.add_ColorValuesChanged(Windows.Foundation.TypedEventHandler`2<Windows.UI.ViewManagement.UISettings,System.Object>)'.
  HResult: -2146233069
  Data: <System.Object> -> <>
  Data: <AlreadySentByRaygun> -> <True>
  Source: Wox.Core
  TargetAssembly: Wox.Core, Version=1.3.1036.0, Culture=neutral, PublicKeyToken=null
  TargetModule: Wox.Core.dll
  TargetSite: Void AutoReload()
  StackTrace: --------------------
   at Wox.Core.Resource.Theme.AutoReload()
   at Wox.Core.Resource.ThemeManager.get_Instance() in C:\projects\wox\Wox.Core\Resource\ThemeManager.cs:line 18
   at Wox.MainWindow.OnLoaded(Object sender, RoutedEventArgs _) in C:\projects\wox\Wox\MainWindow.xaml.cs:line 62
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Exception end ------------------------------------------------------------
```
[2020-05-15.txt](https://github.com/Wox-launcher/Wox/files/4631913/2020-05-15.txt)

**Comment by bao-qian** [comment]
are you using windows 8?

**Comment by aaaxx** [comment]
Yes, 8.1 Pro.

**Comment by bao-qian** [comment]
please try new build, which has fix for this bug

https://ci.appveyor.com/project/bao-qian/wox/builds/32932441/artifacts

let me know if it fix or not.
