### ISSUE TITLE
Control Panel plugin init failure

### ISSUE THREAD

**Issue by jhdxr** [Wox-launcher/Wox#2974]
I'm using 1.4.1115, which is upgrade from 1.3.674. The control panel plugin is reported crashed and disabled automatically.

```
2020-05-20 21:38:10.8484|ERROR|Wox.Core.Plugin.PluginManager|InitializePlugins|Fail to Init plugin: Control Panel|Exception begin --------------------
  System.NullReferenceException: Object reference not set to an instance of an object.
  HResult: -2147467261
  Data: <ID> -> <209621585B9B4D81813913C507C058C6>
  Data: <Name> -> <Control Panel>
  Data: <Website> -> <https://github.com/Wox-launcher/Wox>
  Source: Wox.Plugin.ControlPanel
  TargetAssembly: Wox.Plugin.ControlPanel, Version=1.4.1115.0, Culture=neutral, PublicKeyToken=null
  TargetModule: Wox.Plugin.ControlPanel.dll
  TargetSite: System.Collections.Generic.List`1[Wox.Plugin.ControlPanel.ControlPanelItem] Create(UInt32, System.String, System.String)
  StackTrace: --------------------
   at Wox.Plugin.ControlPanel.ControlPanelList.Create(UInt32 iconSize, String iconFolder, String fileType) in C:\projects\wox\Plugins\Wox.Plugin.ControlPanel\ControlPanelList.cs:line 82
   at Wox.Plugin.ControlPanel.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.ControlPanel\Main.cs:line 32
   at Wox.Infrastructure.Stopwatch.StopWatchDebug(Logger logger, String message, Action action, String methodName) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 21
   at Wox.Core.Plugin.PluginManager.<>c__DisplayClass21_0.<InitializePlugins>b__0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 0
Exception end ------------------------------------------------------------
```

**Comment by jhdxr** [comment]
enable the plugin won't casue any error, but it's not functioning. Restarting Wox later will lead to the plugin auto disabled again.

**Comment by bao-qian** [comment]
try this new build, 
https://ci.appveyor.com/project/bao-qian/wox/builds/33003377/artifacts

I will release it today.

**Comment by jhdxr** [comment]
confirm fixed.
