### ISSUE TITLE
Um i got this error i tried to follow the instructions on submitting this correctly 

### ISSUE THREAD

**Issue by Joshuadigweed** [Wox-launcher/Wox#3006]
i got this error when starting wox from the start menu the first ever time trying to  run it 

[2020-05-23.txt](https://github.com/Wox-launcher/Wox/files/4671245/2020-05-23.txt)

Error id: 02c29a87e5cc449db8d8f1b36fc252d7
Exception begin --------------------
  System.NullReferenceException: Object reference not set to an instance of an object.
  HResult: -2147467261
  Data: <System.Object> -> <>
  Source: Wox
  TargetAssembly: Wox, Version=1.4.1129.0, Culture=neutral, PublicKeyToken=null
  TargetModule: Wox.exe
  TargetSite: Void OnSecondAppStarted(System.Collections.Generic.IList`1[System.String])
  StackTrace: --------------------
   at Wox.App.OnSecondAppStarted(IList`1 args) in C:\projects\wox\Wox\App.xaml.cs:line 202
   at Wox.Helper.SingleInstance`1.ActivateFirstInstanceCallback(Object arg) in C:\projects\wox\Wox\Helper\SingleInstance.cs:line 418
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Exception end ------------------------------------------------------------

**Comment by Joshuadigweed** [comment]
wox is working now using the preset alt space but i guess there was going to be like an options menu

**Comment by bao-qian** [comment]
please try latest release 
https://github.com/Wox-launcher/Wox/releases/tag/v1.4.1196
