### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by django-wong** [Wox-launcher/Wox#306]
at Wox.ShellContext.IShellFolder.ParseDisplayName(IntPtr hwnd, IntPtr pbc, String pszDisplayName, UInt32& pchEaten, IntPtr& ppidl, UInt32& pdwAttributes)
   at Wox.ShellContext.ShellContextMenuManager.GetContextMenus(String path) in c:\projects\wox\Wox\ShellContext\ShellContextMenuManager.cs:line 23
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at MS.Internal.FrameworkObject.OnLoaded(RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)

**Comment by qianlifeng** [comment]
Wox v1.1?

**Comment by django-wong** [comment]
Wox v1.2 on win8.1

**Comment by bao-qian** [comment]
请参照[faq](https://github.com/Wox-launcher/Wox/wiki/FAQ-%E4%B8%AD%E6%96%87)提供更详细的说明。

**Comment by happlebao** [comment]
close due to no response, reopen it if you have more info.

**Comment by bao-qian** [comment]
因为没有进一步反馈，所以关闭这个 issue，有更多信息的话请重开。
