### ISSUE TITLE
FileNotFoundException on startup

### ISSUE THREAD

**Issue by ogero** [Wox-launcher/Wox#308]
Wox Version: 1.1.1  

![wox_startup_crash](https://cloud.githubusercontent.com/assets/167090/8965995/294ff2fe-3605-11e5-8e50-a4c0e5ced12b.png)

**Comment by wickles** [comment]
I get the same error. Mine reads:

``````
---------------------------
Wox - Unhandled Exception
---------------------------
Wox has occured an error that can't be handled. 



## Exception



```

System.IO.FileNotFoundException: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\LibreOffice 4.4\LibreOffice.lnk

Source: System.Drawing

TargetAssembly: System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

TargetModule: System.Drawing.dll

TargetSite: System.Drawing.Icon ExtractAssociatedIcon(System.String, Int32)

at System.Drawing.Icon.ExtractAssociatedIcon(String filePath, Int32 index)

at Wox.ImageLoader.ImageLoader.GetIcon(String fileName) in c:\projects\wox\Wox\ImageLoader\ImageLoader.cs:line 42

at Wox.ImageLoader.ImageLoader.Load(String path, Boolean addToCache) in c:\projects\wox\Wox\ImageLoader\ImageLoader.cs:line 103

at Wox.ImageLoader.ImageLoader.PreloadImages() in c:\projects\wox\Wox\ImageLoader\ImageLoader.cs:line 61

at Wox.MainWindow.<.ctor>b__13(Object o) in c:\projects\wox\Wox\MainWindow.xaml.cs:line 200

at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

at System.Threading._ThreadPoolWaitCallback.PerformWaitCallbackInternal(_ThreadPoolWaitCallback tpWaitCallBack)

at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback(Object state)



```
``````

Thought it was an issue with Windows 10, but I see you are not on Windows 10. On the other hand, I just upgraded LibreOffice to version 5, which changed the shortcut. So it's probably an issue with the application/shortcut database getting out of date with links that don't exist anymore. ~~Have you uninstalled or altered that program, "Gyazo GIF"?~~ Nevermind, I see that it does not exist in the explorer window you included.

**Comment by qianlifeng** [comment]
V1.2-beta has solved this issues, pls try that version.

**Comment by nicholasblexrud** [comment]
https://github.com/qianlifeng/Wox/releases/download/v1.2.0-beta/Wox-1.2.0-beta.zip
