### ISSUE TITLE
i cant use the clock and dictionary plugin after downloading it from "http://www.wox.one/plugin/184"

### ISSUE THREAD

**Issue by GarvBatra123** [Wox-launcher/Wox#3110]

**Comment by GarvBatra123** [comment]
I keep on getting this error:



You can help us to fix this issue by opening issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\UserData\Logs\1.4.1196\2020-07-21.txt
2. copy below exception message
Error id: 21ff718d58464b8e9ffc3c5e04505927
Exception begin --------------------
  System.TypeLoadException: Could not load type 'Wox.Infrastructure.Storage.Storage`1' from assembly 'Wox.Infrastructure, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null'.
  HResult: -2146233054
  Data: <System.Object> -> <>
  Source: Wox.Plugin.SimpleClock
  TargetAssembly: Wox.Plugin.SimpleClock, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  TargetModule: Wox.Plugin.SimpleClock.dll
  TargetSite: Boolean CommandExecution(System.Collections.Generic.List`1[System.String])
  StackTrace: --------------------
   at Wox.Plugin.SimpleClock.Commands.Alarm.AlarmAddCommand.CommandExecution(List`1 args)
   at Wox.Plugin.Boromak.CommandHandlerBase.Execute(List`1 args) in C:\Users\Boris\Documents\SourceControl\Wox\Wox.Plugin.SimpleClock\Wox.Plugin.Boromak\Wox.Plugin.Boromak\CommandHandlerBase.cs:line 166
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__17_7(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 209
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Exception end ------------------------------------------------------------

## Runtime Info
* Command Line: "C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Wox.exe" 
* Portable Mode: True
* Timestamp: 07/21/2020 13:49:44
* Wox version: 1.4.1196
* OS Version: Microsoft Windows NT 10.0.20170.0
* x64 OS: True
* x64 Process: True
* System Language: en-GB
* Wox Language: en
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.8.04161
   * v4 Full 4.8.04161
   * v4.0 Client 4.0.0.0

## SDK Info
* Python Path: pythonw.exe
* Everything SDK Path: C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll

## Assemblies - Wox.exe

* Wox, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Wox.exe)
* NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\NLog.dll)
* Wox.Core, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Wox.Core.dll)
* Sentry, Version=2.1.1.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0 (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Sentry.dll)
* Sentry.Protocol, Version=2.1.1.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0 (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Sentry.Protocol.dll)
* System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\System.Collections.Immutable.dll)
* Wox.Infrastructure, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Wox.Infrastructure.dll)
* System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\System.Net.Http.dll)
* System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\System.ValueTuple.dll)
* Wox.Plugin, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Wox.Plugin.dll)
* Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Newtonsoft.Json.dll)
* Squirrel, Version=1.9.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Squirrel.dll)
* Splat, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Splat.dll)
* Wox.Plugin.Caculator, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
* HelloWorldCSharp, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Plugins\HelloWorldCSharp\HelloWorldCSharp.dll)
* Wox.Plugin.ControlPanel, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
* Wox.Plugin.Color, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
* Wox.Plugin.BrowserBookmark, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Plugins\Wox.Plugin.BrowserBookmark\Wox.Plugin.browserBookmark.dll)
* Mages.Core, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Plugins\Wox.Plugin.Caculator\Mages.Core.dll)
* Wox.Plugin.Everything, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
* Wox.Plugin.PluginIndicator, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
* Wox.Plugin.Folder, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
* Wox.Plugin.PluginManagement, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
* Wox.Plugin.Shell, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
* Wox.Plugin.Program, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
* Wox.Plugin.Sys, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
* WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\WindowsInput.dll)
* Wox.Plugin.WebSearch, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
* SimpleWebSearch, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\UserData\Plugins\Simple Web Search-0be9e68c-ed3a-41b9-ab89-49a0ce0922e9\SimpleWebSearch.dll)
* OpenWeatherMap, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\UserData\Plugins\Weather.Open-353c15cc-3d0c-4ec5-92f6-1dd8bb1f3b2b\OpenWeatherMap.dll)
* Wox.Plugin.Url, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
* Wox.Plugin.SimpleClock, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\UserData\Plugins\Wox.Plugin.SimpleClock-dfa8b3a2-4f77-4389-8bfd-174e5e331ca6\Wox.Plugin.SimpleClock.dll)
* Wox.Plugin.Boromak, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\UserData\Plugins\Wox.Plugin.SimpleClock-dfa8b3a2-4f77-4389-8bfd-174e5e331ca6\Wox.Plugin.Boromak.dll)
* Dictionary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\UserData\Plugins\Dictionary-bc8eb832-882f-470d-962c-0e7c749a3e68\Dictionary.dll)
* Microsoft.Data.Sqlite, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Plugins\Wox.Plugin.BrowserBookmark\Microsoft.Data.Sqlite.dll)
* NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\NHotkey.dll)
* NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\NHotkey.Wpf.dll)
* System.Data.SQLite, Version=1.0.106.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139 (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\UserData\Plugins\Dictionary-bc8eb832-882f-470d-962c-0e7c749a3e68\System.Data.SQLite.dll)
* Windows.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.UI.winmd)
* Windows.Foundation, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.Foundation.winmd)
* System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\System.Runtime.dll)
* CommandLine, Version=2.7.82.0, Culture=neutral, PublicKeyToken=5a870481e358d379 (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\CommandLine.dll)
* Sentry.PlatformAbstractions, Version=1.1.0.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0 (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Sentry.PlatformAbstractions.dll)
* System.Runtime.InteropServices.RuntimeInformation, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\System.Runtime.InteropServices.RuntimeInformation.dll)
* Microsoft.WindowsAPICodePack.Shell, Version=1.1.4.0, Culture=neutral, PublicKeyToken=8985beaab7ea3f04 (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Microsoft.WindowsAPICodePack.Shell.dll)
* Microsoft.WindowsAPICodePack, Version=1.1.4.0, Culture=neutral, PublicKeyToken=8985beaab7ea3f04 (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\Microsoft.WindowsAPICodePack.dll)
* ToolGood.Words, Version=3.0.1.2, Culture=neutral, PublicKeyToken=d330f4fd115e6143 (C:\Users\garvb_zo160rt\Downloads\MODIFICATIONS AND TASK VIEWERS\Wox\app-1.4.1196\ToolGood.Words.dll)
* mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
* PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
* System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
* PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
* System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
* netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll)
* System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
* System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
* System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
* System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
* System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
* System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
* System.Runtime.Caching, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Caching\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Caching.dll)
* PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)
* WindowsFormsIntegration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsFormsIntegration\v4.0_4.0.0.0__31bf3856ad364e35\WindowsFormsIntegration.dll)
* System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
* System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll)
* System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll)
* System.Runtime.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.WindowsRuntime\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.WindowsRuntime.dll)
* System.Runtime.InteropServices.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.WindowsRuntime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.WindowsRuntime.dll)
* PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll)
* System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll)
* PresentationFramework-SystemXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll)
* PresentationFramework-SystemXmlLinq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXmlLinq\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXmlLinq.dll)
* UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll)
* UIAutomationProvider, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll)
* System.Deployment, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Deployment\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Deployment.dll)
* PresentationFramework-SystemDrawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemDrawing\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemDrawing.dll)
