### ISSUE TITLE
Installed software are not recommended

### ISSUE THREAD

**Issue by JJplane** [Wox-launcher/Wox#3116]
i am not sure which setting i have changed, then the wox doesn't show any useful suggestions but some basic tools that wox, i cann't get any software installed on my pc now .
![image](https://user-images.githubusercontent.com/28783826/88171943-cbfd9680-cc52-11ea-879c-e8d439cfceae.png)

**Comment by bitkleberAST** [comment]
Did you change pathes in settings of program plugin? (Settings -> Plugin -> Program -> Program Sources)
Maybe it would help to remove all entries there, add one after another, reindex after adding one and try to find/start programs of the recently added path.

Can you upload your log files here? Open a new Windows Explorer and input %appdata%\Wox\Logs\ into the address bar. The most recent log file should be sufficient.

**Comment by JJplane** [comment]
2020-09-13 15:57:54.0820|ERROR|Wox.Plugin.Program.Programs.Win32|ProgramPaths|Permission denied C:\Users\jipen\AppData\Roaming\Microsoft\Windows\Start Menu
2020-09-13 15:57:54.1029|ERROR|Wox.Plugin.Program.Programs.Win32|ProgramPaths|Permission denied C:\ProgramData\Microsoft\Windows\Start Menu
2020-09-13 15:57:54.1079|INFO|Wox.Plugin.Program.Main|IndexPrograms|Win32 index cost <50ms>
2020-09-13 15:57:54.1533|INFO|Wox.Plugin.Program.Main|IndexPrograms|UWP index cost <95ms>
2020-09-13 15:57:54.1543|INFO|Wox.Plugin.Program.Main|IndexPrograms|Number of indexed win32 programs <214>
2020-09-13 15:57:54.1543|INFO|Wox.Plugin.Program.Main|IndexPrograms|Number of indexed uwps <38>
2020-09-13 15:57:55.0620|ERROR|Wox.Plugin.Program.Programs.UWP|All|Cannot parse UWP C:\Program Files (x86)\Microsoft\Edge\Application|Exception begin --------------------
  System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\Microsoft\Edge\Application\AppxManifest.xml'.
  HResult: -2147024894
  Data: <FullName> -> <Microsoft.MicrosoftEdge.Stable_85.0.564.51_neutral__8wekyb3d8bbwe>
  Data: <Location> -> <C:\Program Files (x86)\Microsoft\Edge\Application>
  Source: mscorlib
  TargetAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  TargetModule: CommonLanguageRuntimeLibrary
  TargetSite: Void WinIOError(Int32, System.String)
  StackTrace: --------------------
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at Wox.Plugin.Program.Programs.UWP.InitializeAppInfo() in C:\projects\wox\Plugins\Wox.Plugin.Program\Programs\UWP.cs:line 51
   at Wox.Plugin.Program.Programs.UWP.<>c__DisplayClass25_0.<All>b__0(UWP package, ParallelLoopState state) in C:\projects\wox\Plugins\Wox.Plugin.Program\Programs\UWP.cs:line 151
Exception end ------------------------------------------------------------


2020-09-13 15:57:55.0759|ERROR|Wox.Plugin.Program.Programs.Win32|ProgramPaths|Permission denied C:\Users\jipen\AppData\Roaming\Microsoft\Windows\Start Menu
2020-09-13 15:57:55.0959|ERROR|Wox.Plugin.Program.Programs.Win32|ProgramPaths|Permission denied C:\ProgramData\Microsoft\Windows\Start Menu
2020-09-13 15:57:55.0959|INFO|Wox.Plugin.Program.Main|IndexPrograms|Win32 index cost <50ms>
2020-09-13 15:57:55.1328|INFO|Wox.Plugin.Program.Main|IndexPrograms|UWP index cost <80ms>
2020-09-13 15:57:55.1328|INFO|Wox.Plugin.Program.Main|IndexPrograms|Number of indexed win32 programs <214>
2020-09-13 15:57:55.1328|INFO|Wox.Plugin.Program.Main|IndexPrograms|Number of indexed uwps <38>

**Comment by JJplane** [comment]
The settings of program plugin has been changed as you mentioned, which i have tried before.Now it give useless folders index.(i tried to get IDE pycharm, but these folders showed)
![image](https://user-images.githubusercontent.com/28783826/93013372-8027f780-f5da-11ea-9602-3b2f89f103be.png)

**Comment by JJplane** [comment]
> The settings of program plugin has been changed as you mentioned, which i have tried before.Now it give useless folders index.(i tried to get IDE pycharm, but these folders showed)
> ![image](https://user-images.githubusercontent.com/28783826/93013372-8027f780-f5da-11ea-9602-3b2f89f103be.png)
![image](https://user-images.githubusercontent.com/28783826/93013429-f88eb880-f5da-11ea-8bd3-29d5bb69ef6d.png)
