### ISSUE TITLE
Wox identified as exhibiting ransomware behaviour by Bitdefender

### ISSUE THREAD

**Issue by rawky1986** [Wox-launcher/Wox#3160]
Wox identified as exhibiting ransomware behaviour by Bitdefender

The following message is noted against the error. 

> "The process C:\Users\XXXX\AppData\Local\Wox\app-1.4.1196\Wox.exe manifests ransomware behavior and was blocked. Several files were encrypted by it and we couldn't automatically restore all of them. You can find the files to be restored below."

Unknown particularly how to reproduce, appears to have happened twice this morning and is the first time this behaviour has been exhibited. 

Wox should not be exhibiting encryption behaviour. 

**Runtime info**
 - Windows 10 Version:  Pro - 10.0.18363
 - Wox version: 1.4.1196

**Wox Error Window text**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/50354737/90631777-3c301580-e21b-11ea-9c85-647a1366d40c.png)

**Detailed logs**
Please upload latest log file: 
`%APPDATA%\Wox\Logs\version\<date>.txt`
Please upload log as a whole file

drop and drop your latest log file here
2020-08-19 12:54:23.1409|INFO|Wox.App|OnStartup|Begin Wox startup----------------------------------------------------
2020-08-19 12:54:23.5159|INFO|Wox.App|OnStartup|## Runtime Info
* Command Line: "C:\Users\XXXXX\AppData\Local\Wox\app-1.4.1196\Wox.exe" 
* Portable Mode: False
* Timestamp: 08/19/2020 12:54:23
* Wox version: 1.4.1196
* OS Version: Microsoft Windows NT 10.0.18363.0
* x64 OS: True
* x64 Process: True
* System Language: en-GB
* Wox Language: en
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.8.03752
   * v4 Full 4.8.03752
   * v4.0 Client 4.0.0.0
   * v4.8

2020-08-19 12:54:23.9960|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Hello World CSharp> is <8ms>
2020-08-19 12:54:23.9960|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Calculator> is <14ms>
2020-08-19 12:54:24.0039|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Colors> is <3ms>
2020-08-19 12:54:24.0039|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Everything> is <7ms>
2020-08-19 12:54:24.0039|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Folder> is <15ms>
2020-08-19 12:54:24.0193|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Plugin Indicator> is <2ms>
2020-08-19 12:54:24.0193|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Wox Plugin Management> is <2ms>
2020-08-19 12:54:24.0466|INFO|Wox.Plugin.Program.Main|preloadPrograms|Preload programs cost <13ms>
2020-08-19 12:54:24.0481|INFO|Wox.Plugin.Program.Main|preloadPrograms|Number of preload win32 programs <364>
2020-08-19 12:54:24.0481|INFO|Wox.Plugin.Program.Main|preloadPrograms|Number of preload uwps <50>
2020-08-19 12:54:24.0481|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Program> is <31ms>
2020-08-19 12:54:24.0481|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <System Commands> is <1ms>
2020-08-19 12:54:24.0481|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Browser Bookmarks> is <52ms>
2020-08-19 12:54:24.0659|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <URL> is <4ms>
2020-08-19 12:54:24.0659|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Shell> is <9ms>
2020-08-19 12:54:24.0659|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Web Searches> is <18ms>
2020-08-19 12:54:24.0659|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Hello World Python> is <0ms>
2020-08-19 12:54:24.1160|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Control Panel> is <119ms>
2020-08-19 12:54:24.1369|INFO|Wox.Core.Resource.Theme|.ctor|Runtime Version 10.0.18363.0 True
2020-08-19 12:54:24.2748|INFO|Wox.App|OnStartup|SDK Info: ## SDK Info
* Python Path: C:\Python27\pythonw.exe
* Everything SDK Path: C:\Users\XXXXX\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll

2020-08-19 12:54:24.2748|INFO|Wox.App|OnStartup|End Wox startup ----------------------------------------------------  
2020-08-19 12:54:24.2837|INFO|Wox.App|OnStartup|Startup cost <1265ms>
2020-08-19 12:54:24.9156|INFO|Wox.Core.Updater|UpdateApp|Future Release <{
  "SHA1": "69FCC97E4B7B2702885463793AD617ED2D0C94B6",
  "BaseUrl": null,
  "Filename": "Wox-1.4.1196-full.nupkg",
  "Query": null,
  "Filesize": 8527076,
  "IsDelta": false,
  "StagingPercentage": null
}>
2020-08-19 12:54:26.3679|ERROR|Wox.Plugin.Program.Programs.UWP|All|Cannot parse UWP C:\Program Files\WindowsApps\Microsoft.HaloCombatEvolved_1.1367.0.0_x64__8wekyb3d8bbwe|Exception begin --------------------
  System.ArgumentException: Cannot read Applications key from C:\Program Files\WindowsApps\Microsoft.HaloCombatEvolved_1.1367.0.0_x64__8wekyb3d8bbwe\AppxManifest.xml
  HResult: -2147024809
  Data: <FullName> -> <Microsoft.HaloCombatEvolved_1.1367.0.0_x64__8wekyb3d8bbwe>
  Data: <Location> -> <C:\Program Files\WindowsApps\Microsoft.HaloCombatEvolved_1.1367.0.0_x64__8wekyb3d8bbwe>
  Source: Wox.Plugin.Program
  TargetAssembly: Wox.Plugin.Program, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null
  TargetModule: Wox.Plugin.Program.dll
  TargetSite: Void InitializeAppInfo()
  StackTrace: --------------------
   at Wox.Plugin.Program.Programs.UWP.InitializeAppInfo() in C:\projects\wox\Plugins\Wox.Plugin.Program\Programs\UWP.cs:line 95
   at Wox.Plugin.Program.Programs.UWP.<>c__DisplayClass25_0.<All>b__0(UWP package, ParallelLoopState state) in C:\projects\wox\Plugins\Wox.Plugin.Program\Programs\UWP.cs:line 151
Exception end ------------------------------------------------------------

2020-08-19 12:54:26.7543|INFO|Wox.Plugin.Program.Main|IndexPrograms|UWP index cost <699ms>
2020-08-19 12:54:27.5563|INFO|Wox.Plugin.Program.Main|IndexPrograms|Win32 index cost <1500ms>
2020-08-19 12:54:27.5781|INFO|Wox.Plugin.Program.Main|IndexPrograms|Number of indexed win32 programs <364>
2020-08-19 12:54:27.5846|INFO|Wox.Plugin.Program.Main|IndexPrograms|Number of indexed uwps <50>

**Comment by bao-qian** [comment]
there is absolutely no encryption logic in the code.
I have completed no idea about this warning.
please give the full path and name of the files it warns, it may help to diagnose the problem.
