### ISSUE TITLE
You can help us to fix this issue 

### ISSUE THREAD

**Issue by Alceatraz** [Wox-launcher/Wox#3329]
Error id: 6b0265a2320a40bf8e44bca1c56b4194
Exception begin --------------------
  System.NullReferenceException: Object reference not set to an instance of an object.
  HResult: -2147467261
  Data: <System.Object> -> <>
  Source: Wox.Core
  TargetAssembly: Wox.Core, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null
  TargetModule: Wox.Core.dll
  TargetSite: Boolean <GetPluginsForInterface>b__27_0(Wox.Plugin.PluginPair)
  StackTrace: --------------------
   at Wox.Core.Plugin.PluginManager.<>c__27`1.<GetPluginsForInterface>b__27_0(PluginPair p) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 241
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at Wox.Core.Resource.Internationalization.AddPluginLanguageDirectories() in C:\projects\wox\Wox.Core\Resource\Internationalization.cs:line 47
   at Wox.Core.Resource.Internationalization..ctor() in C:\projects\wox\Wox.Core\Resource\Internationalization.cs:line 30
   at Wox.Core.Resource.InternationalizationManager.get_Instance() in C:\projects\wox\Wox.Core\Resource\InternationalizationManager.cs:line 18
   at Wox.ViewModel.MainViewModel..ctor(Boolean useUI) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 79
   at Wox.App.<OnStartup>b__15_0() in C:\projects\wox\Wox\App.xaml.cs:line 106
   at Wox.Infrastructure.Stopwatch.StopWatchNormal(Logger logger, String message, Action action, String methodName) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 33
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Exception end ------------------------------------------------------------

**Comment by Alceatraz** [comment]
[Uploading 2021-01-12.txt…]()
