### ISSUE TITLE
Programs plugin does not find anything (Exception: Permission denied <directory>)

### ISSUE THREAD

**Issue by augustohp** [Wox-launcher/Wox#3382]
Wox does not find any installed program when searched. Not with _partial queries_ (`not` should list `notepad.exe` as result) or _full queries_ (`notepad.exe` should list `notepad.exe` as result).

If _Everything_ is installed and enabled programs are found but are displayed in an inconvenient order, they don't appear or do not appear as first option.

**Steps to reproduce**
1. Enter `notepad` as _query_
1. _Result list_ is empty

**Expected behavior**
See the program listed in the _result list_, preferably as the first result if more entries are available.

**Additional information**
- Fixes tried using information gathered from apparently related issues:
    - Removed cache directory (`%APPDATA%/Roam/Wox`) mentioned in #1698 
    - Added _Start Menu_ directory manually as mentioned also in #1698 
    - Adding the program directory as a _Program Source_, mentioned in #1390, works but if I add `C:\Program files (x86)` no program is found
-  Different settings tried with Program plugin:
    - With `Index Start Menu` enabled, `Index Registry` disabled, empty `Program Sources` list
    - With `Index Start Menu` enabled,  `Index Registry` enabled, empty `Program Sources` list
    - With `Index Start Menu` disabled, `Index Registry` enabled, empty `Program Sources` list
- [Complete log file available for download](https://github.com/Wox-launcher/Wox/files/6056879/2021-02-28.txt)
<details>
<summary>Excerpt of log after startup</summary>

```
2021-02-28 02:45:08.3079|INFO|Wox.App|Dispose|Wox Start Displose
2021-02-28 02:45:23.5124|INFO|Wox.App|OnStartup|Begin Wox startup----------------------------------------------------
2021-02-28 02:45:23.6944|INFO|Wox.App|OnStartup|## Runtime Info
* Command Line: "C:\Users\User\AppData\Local\Wox\app-1.4.1196\Wox.exe" 
* Portable Mode: False
* Timestamp: 02/28/2021 02:45:23
* Wox version: 1.4.1196
* OS Version: Microsoft Windows NT 10.0.19042.0
* x64 OS: True
* x64 Process: True
* System Language: pt-BR
* Wox Language: en
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.8.04084
   * v4 Full 4.8.04084
   * v4.0 Client 4.0.0.0

2021-02-28 02:45:24.1669|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Hello World CSharp> is <26ms>
2021-02-28 02:45:24.1669|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Wox Plugin Management> is <28ms>
2021-02-28 02:45:24.1669|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Colors> is <26ms>
2021-02-28 02:45:24.1669|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <System Commands> is <20ms>
2021-02-28 02:45:24.1669|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Plugin Indicator> is <29ms>
2021-02-28 02:45:24.1679|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Folder> is <42ms>
2021-02-28 02:45:24.1679|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Everything> is <34ms>
2021-02-28 02:45:24.1679|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <URL> is <20ms>
2021-02-28 02:45:24.1679|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Calculator> is <62ms>
2021-02-28 02:45:24.1849|INFO|Wox.Plugin.Program.Main|preloadPrograms|Preload programs cost <10ms>
2021-02-28 02:45:24.1849|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Currency> is <36ms>
2021-02-28 02:45:24.1849|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Web Searches> is <38ms>
2021-02-28 02:45:24.1849|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Shell> is <41ms>
2021-02-28 02:45:24.1849|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Browser Bookmarks> is <79ms>
2021-02-28 02:45:24.1849|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Hello World Python> is <0ms>
2021-02-28 02:45:24.2039|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Control Panel> is <65ms>
2021-02-28 02:45:24.2039|INFO|Wox.Plugin.Program.Main|preloadPrograms|Number of preload win32 programs <1>
2021-02-28 02:45:24.2339|INFO|Wox.Plugin.Program.Main|preloadPrograms|Number of preload uwps <58>
2021-02-28 02:45:24.2339|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Program> is <117ms>
2021-02-28 02:45:24.2559|INFO|Wox.Core.Resource.Theme|.ctor|Runtime Version 10.0.19042.0 True
2021-02-28 02:45:24.3985|INFO|Wox.App|OnStartup|SDK Info: ## SDK Info
* Python Path: pythonw.exe
* Everything SDK Path: C:\Users\User\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll

2021-02-28 02:45:24.4035|INFO|Wox.App|OnStartup|End Wox startup ----------------------------------------------------  
2021-02-28 02:45:24.4035|INFO|Wox.App|OnStartup|Startup cost <1019ms>
2021-02-28 02:45:25.9230|INFO|Wox.Core.Updater|UpdateApp|Future Release <{
  "SHA1": "69FCC97E4B7B2702885463793AD617ED2D0C94B6",
  "BaseUrl": null,
  "Filename": "Wox-1.4.1196-full.nupkg",
  "Query": null,
  "Filesize": 8527076,
  "IsDelta": false,
  "StagingPercentage": null
}>
2021-02-28 02:45:26.2560|ERROR|Wox.Plugin.Program.Programs.Win32|ProgramPaths|Permission denied C:\Users\User\AppData\Roaming\Microsoft\Windows\Start Menu
2021-02-28 02:45:26.2620|ERROR|Wox.Plugin.Program.Programs.Win32|ProgramPaths|Permission denied C:\ProgramData\Microsoft\Windows\Start Menu
2021-02-28 02:45:26.3115|ERROR|Wox.Plugin.Program.Programs.UWP|All|Cannot parse UWP C:\Program Files\WindowsApps\Microsoft.DigitalOwnership_1.0.1.0_x64__8wekyb3d8bbwe|Exception begin --------------------
  System.ArgumentException: Cannot read Applications key from C:\Program Files\WindowsApps\Microsoft.DigitalOwnership_1.0.1.0_x64__8wekyb3d8bbwe\AppxManifest.xml
  HResult: -2147024809
  Data: <FullName> -> <Microsoft.DigitalOwnership_1.0.1.0_x64__8wekyb3d8bbwe>
  Data: <Location> -> <C:\Program Files\WindowsApps\Microsoft.DigitalOwnership_1.0.1.0_x64__8wekyb3d8bbwe>
  Source: Wox.Plugin.Program
  TargetAssembly: Wox.Plugin.Program, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null
  TargetModule: Wox.Plugin.Program.dll
  TargetSite: Void InitializeAppInfo()
  StackTrace: --------------------
   at Wox.Plugin.Program.Programs.UWP.InitializeAppInfo() in C:\projects\wox\Plugins\Wox.Plugin.Program\Programs\UWP.cs:line 95
   at Wox.Plugin.Program.Programs.UWP.<>c__DisplayClass25_0.<All>b__0(UWP package, ParallelLoopState state) in C:\projects\wox\Plugins\Wox.Plugin.Program\Programs\UWP.cs:line 151
Exception end ------------------------------------------------------------
```
</details>

**Runtime info**
 - Windows 10 Version: 10 Pro
 - Wox version: 1.4.1196 (most recent release at the creation of this bug)

**Comment by kaufmann1** [comment]
I have the same issue, wox doesn'T show apps like notepad++ or webstorm

**Comment by Streyder** [comment]
Any news on this? Wox is pretty useless without the program plugin

**Comment by MoulikRT** [comment]
I know this may sound obvious, but by any chance, have you bounded the program plugin to an action keyword? I had the same issue as you and after scratching my head for hours I realized that I had to set it to a key and completely forgot about it. It seems Wox does not show program results if you have not specified the keyword.

**Comment by Streyder** [comment]
I have not, but I have since moved away from wox to a more actively developed option because the amount of bugs and minor inconveniences got to the point I was frustrated

**Comment by MoulikRT** [comment]
Could you please name that option as I have just installed wox today after switching from Hain. I liked Hain's UI more but it is lacking in features. I would love to explore more options if you recommend them.

**Comment by Streyder** [comment]
I would find it very unfair to advertise for an alternative product for wox on their own github page, although nothing happend here in the last year. But if you look at the "wox" topic on github: https://github.com/topics/wox there might be some (very) related repositories that should fit your needs
