### ISSUE TITLE
Wox intercepts Win + r shortcut on Windows

### ISSUE THREAD

**Issue by HongKilDong** [Wox-launcher/Wox#3530]
Wox intercepts Win+r key shortcut on Windows.

**To Reproduce**
Press Win+r

**Expected behavior**
Windows' dialog 'Run command' are displayed

**Runtime info**
 - Windows 10
 - current Wox version

**Screenshots**
![](http://dl3.joxi.net/drive/2021/09/08/0020/0232/1360104/04/6baf48a04b.jpg)

**Detailed logs**
2021-09-08 11:36:51.0730|INFO|Wox.App|OnStartup|Begin Wox startup----------------------------------------------------
2021-09-08 11:36:51.3440|INFO|Wox.App|OnStartup|## Runtime Info
* Command Line: "C:\Users\User\AppData\Local\Wox\app-1.4.1196\Wox.exe" 
* Portable Mode: False
* Timestamp: 09/08/2021 11:36:51
* Wox version: 1.4.1196
* OS Version: Microsoft Windows NT 10.0.19043.0
* x64 OS: True
* x64 Process: True
* System Language: ru-RU
* Wox Language: en
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v4 Client 4.8.04084
   * v4 Full 4.8.04084
   * v4.0 Client 4.0.0.0

2021-09-08 11:36:51.7590|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Hello World CSharp> is <4ms>
2021-09-08 11:36:51.7590|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Browser Bookmarks> is <15ms>
2021-09-08 11:36:51.7590|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Colors> is <4ms>
2021-09-08 11:36:51.7590|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Everything> is <14ms>
2021-09-08 11:36:51.7730|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Calculator> is <38ms>
2021-09-08 11:36:51.7730|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Wox Plugin Management> is <13ms>
2021-09-08 11:36:51.7730|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Folder> is <18ms>
2021-09-08 11:36:51.8010|INFO|Wox.Plugin.Program.Main|preloadPrograms|Preload programs cost <9ms>
2021-09-08 11:36:51.8010|INFO|Wox.Plugin.Program.Main|preloadPrograms|Number of preload win32 programs <110>
2021-09-08 11:36:51.8010|INFO|Wox.Plugin.Program.Main|preloadPrograms|Number of preload uwps <32>
2021-09-08 11:36:51.8010|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Program> is <29ms>
2021-09-08 11:36:51.8050|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Plugin Indicator> is <2ms>
2021-09-08 11:36:51.8050|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <System Commands> is <2ms>
2021-09-08 11:36:51.8050|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <URL> is <4ms>
2021-09-08 11:36:51.8050|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Shell> is <16ms>
2021-09-08 11:36:51.8050|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Web Searches> is <20ms>
2021-09-08 11:36:51.8050|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Hello World Python> is <0ms>
2021-09-08 11:36:51.8250|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Control Panel> is <69ms>
2021-09-08 11:36:51.8430|INFO|Wox.Core.Resource.Theme|.ctor|Runtime Version 10.0.19043.0 True
2021-09-08 11:36:51.9710|INFO|Wox.App|OnStartup|SDK Info: ## SDK Info
* Python Path: pythonw.exe
* Everything SDK Path: C:\Users\User\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll

2021-09-08 11:36:51.9710|INFO|Wox.App|OnStartup|End Wox startup ----------------------------------------------------  
2021-09-08 11:36:51.9710|INFO|Wox.App|OnStartup|Startup cost <1019ms>
2021-09-08 11:36:52.7866|INFO|Wox.Core.Updater|UpdateApp|Future Release <{
  "SHA1": "69FCC97E4B7B2702885463793AD617ED2D0C94B6",
  "BaseUrl": null,
  "Filename": "Wox-1.4.1196-full.nupkg",
  "Query": null,
  "Filesize": 8527076,
  "IsDelta": false,
  "StagingPercentage": null
}>
2021-09-08 11:36:53.8334|ERROR|Wox.Plugin.Program.Programs.Win32|ProgramPaths|Permission denied C:\Users\User\AppData\Roaming\Microsoft\Windows\Start Menu
2021-09-08 11:36:53.8414|ERROR|Wox.Plugin.Program.Programs.Win32|ProgramPaths|Permission denied C:\ProgramData\Microsoft\Windows\Start Menu
2021-09-08 11:36:53.8974|ERROR|Wox.Plugin.Program.Programs.UWP|All|Cannot parse UWP C:\Program Files (x86)\Microsoft\Edge\Application|Exception begin --------------------
  System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\Microsoft\Edge\Application\AppxManifest.xml'.
  HResult: -2147024894
  Data: <FullName> -> <Microsoft.MicrosoftEdge.Stable_93.0.961.38_neutral__8wekyb3d8bbwe>
  Data: <Location> -> <C:\Program Files (x86)\Microsoft\Edge\Application>
  Source: mscorlib
  TargetAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  TargetModule: CommonLanguageRuntimeLibrary
  TargetSite: Void WinIOError(Int32, System.String)
  StackTrace: --------------------
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at Wox.Plugin.Program.Programs.UWP.InitializeAppInfo() in C:\projects\wox\Plugins\Wox.Plugin.Program\Programs\UWP.cs:line 51
   at Wox.Plugin.Program.Programs.UWP.<>c__DisplayClass25_0.<All>b__0(UWP package, ParallelLoopState state) in C:\projects\wox\Plugins\Wox.Plugin.Program\Programs\UWP.cs:line 151
Exception end ------------------------------------------------------------

2021-09-08 11:36:54.1364|INFO|Wox.Plugin.Program.Main|IndexPrograms|UWP index cost <325ms>
2021-09-08 11:36:54.8148|INFO|Wox.Plugin.Program.Main|IndexPrograms|Win32 index cost <1004ms>
2021-09-08 11:36:54.8148|INFO|Wox.Plugin.Program.Main|IndexPrograms|Number of indexed win32 programs <110>
2021-09-08 11:36:54.8228|INFO|Wox.Plugin.Program.Main|IndexPrograms|Number of indexed uwps <32>

**Comment by HongKilDong** [comment]
https://github.com/Wox-launcher/Wox/issues/1990
