### ISSUE TITLE
Wox Worked But After Setting My Python DIR Correctly... 

### ISSUE THREAD

**Issue by crazy54** [Wox-launcher/Wox#3557]
Fresh W11 Install - Running Python 3.9 and this issue began right after a single plugin installation. Removal of this plugin did not resolve the issue, leading me to believe something else is at play. Let me know if I can provide additional logging or details. As soon as you open Wox the error box shows up and the error below is presented. Disablement of the Everything search plugin does nothing to stop the error either. 

The state that Wox is in currently, is the search bar can be called up, however it is trying to search the last string that was entered (even with the setting to clear out the last query in settings)  and the progress bar is pulsing across the input box as if it was trying to figure out what results it can get. 

**Error Output**

**Wox version:** 1.3.524
**OS Version:** Microsoft Windows NT 10.0.22000.0
**IntPtr Length:** 8
**x64:** True

Python Path: C:\Python39\pythonw.exe
Everything SDK Path: C:\Users\USERNAME\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 10/18/2021 14:39:36
Exception:

   at Wox.Core.Resource.Internationalization.ChangeLanguage(Language language) in C:\projects\wox\Wox.Core\Resource\Internationalization.cs:line 89
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.ComboBox.OnSelectionChanged(SelectionChangedEventArgs e)
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
   at System.Windows.Controls.Primitives.Selector.SelectItemWithValue(Object value, Boolean selectNow)
   at System.Windows.Controls.Primitives.Selector.CoerceSelectedValue(DependencyObject d, Object value)
   at System.Windows.DependencyObject.ProcessCoerceValue(DependencyProperty dp, PropertyMetadata metadata, EntryIndex& entryIndex, Int32& targetIndex, EffectiveValueEntry& newEntry, EffectiveValueEntry& oldEntry, Object& oldValue, Object baseValue, Object controlValue, CoerceValueCallback coerceValueCallback, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, Boolean skipBaseValueChecks)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

2021-10-20 21:21:05.0453|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2021-10-20 21:21:05.0453|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2021-10-20 21:21:05.0453|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.NullReferenceException>
2021-10-20 21:21:05.0453|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <Object reference not set to an instance of an object.>
2021-10-20 21:21:05.0453|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   at Wox.Core.Resource.Internationalization.ChangeLanguage(Language language) in C:\projects\wox\Wox.Core\Resource\Internationalization.cs:line 89>
2021-10-20 21:21:05.0453|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <Wox.Core>
2021-10-20 21:21:05.0453|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <Void ChangeLanguage(Wox.Core.Resource.Language)>
2021-10-20 21:21:05.0453|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2147467261>
2021-10-20 21:21:05.0453|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2021-10-20 21:21:05.0508|FATAL|UnHandledException|
## Exception

```
System.NullReferenceException: Object reference not set to an instance of an object.
   Source: Wox.Core
   TargetAssembly: Wox.Core, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Wox.Core.dll
   TargetSite: Void ChangeLanguage(Wox.Core.Resource.Language)
   at Wox.Core.Resource.Internationalization.ChangeLanguage(Language language) in C:\projects\wox\Wox.Core\Resource\Internationalization.cs:line 89
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.ComboBox.OnSelectionChanged(SelectionChangedEventArgs e)
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
   at System.Windows.Controls.Primitives.Selector.SelectItemWithValue(Object value, Boolean selectNow)
   at System.Windows.Controls.Primitives.Selector.CoerceSelectedValue(DependencyObject d, Object value)
   at System.Windows.DependencyObject.ProcessCoerceValue(DependencyProperty dp, PropertyMetadata metadata, EntryIndex& entryIndex, Int32& targetIndex, EffectiveValueEntry& newEntry, EffectiveValueEntry& oldEntry, Object& oldValue, Object baseValue, Object controlValue, CoerceValueCallback coerceValueCallback, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, Boolean skipBaseValueChecks)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

## Environment
* Command Line: "C:\Users\jerem\AppData\Local\Wox\app-1.3.524\Wox.exe" 
* Timestamp: 10/20/2021 21:21:05
* Wox version: 1.3.524
* OS Version: Microsoft Windows NT 10.0.22000.0
* IntPtr Length: 8
* x64: True
* Python Path: C:\Python39\pythonw.exe
* Everything SDK Path: C:\Users\jerem\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.8.04161
   * v4 Full 4.8.04161
   * v4.0 Client 4.0.0.0

## Assemblies - Wox.exe

* Wox, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\Wox.exe)
* Wox.Infrastructure, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\Wox.Infrastructure.dll)
* Wox.Plugin, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\Wox.Plugin.dll)
* Wox.Core, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\Wox.Core.dll)
* NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\NLog.dll)
* Pinyin4Net, Version=2016.4.24.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\Pinyin4Net.dll)
* Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\Newtonsoft.Json.dll)
* Wox.Plugin.Caculator, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
* Mages.Core, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.Caculator\Mages.Core.dll)
* Wox.Plugin.Color, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
* Wox.Plugin.ControlPanel, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
* Wox.Plugin.Everything, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
* Wox.Plugin.Folder, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
* Wox.Plugin.PluginIndicator, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
* Wox.Plugin.PluginManagement, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
* Wox.Plugin.Program, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
* Wox.Plugin.Shell, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
* WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\WindowsInput.dll)
* Wox.Plugin.Sys, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
* Wox.Plugin.Url, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
* Wox.Plugin.WebSearch, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
* Wox.Plugin.IPAddress, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Roaming\Wox\Plugins\IP Address-4ea5684c-9573-457c-b5c1-3d5ffc2af0ff\Wox.Plugin.IPAddress.dll)
* WoxSteam, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Roaming\Wox\Plugins\Steam-71b8afef-cdbb-49dd-b137-18f63602dbda\WoxSteam.dll)
* WoxTwitch, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Roaming\Wox\Plugins\Twitch Browser-d9a25253-fddf-40fb-95de-56872277422c\WoxTwitch.dll)
* NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\NHotkey.dll)
* Windows.ApplicationModel, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.ApplicationModel.winmd)
* Windows.Management, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.Management.winmd)
* Windows.Foundation, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.Foundation.winmd)
* NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Local\Wox\app-1.3.524\NHotkey.Wpf.dll)
* Windows.Storage, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.Storage.winmd)
* Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\jerem\AppData\Roaming\Wox\Plugins\Steam-71b8afef-cdbb-49dd-b137-18f63602dbda\Newtonsoft.Json.dll)
* NeXt.Vdf, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\jerem\AppData\Roaming\Wox\Plugins\Steam-71b8afef-cdbb-49dd-b137-18f63602dbda\NeXt.Vdf.dll)
* mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
* PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
* System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
* PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
* System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
* System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
* System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
* System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
* System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
* System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
* System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
* System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll)
* PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)
* System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
* PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll)
* UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll)
* UIAutomationProvider, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll)
* PresentationFramework-SystemXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll)
* PresentationFramework-SystemXmlLinq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXmlLinq\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXmlLinq.dll)
* System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll)

2021-10-20 21:21:35.9793|ERROR|App.RegisterAppDomainExceptions

|-------------------------- Begin exception --------------------------
2021-10-20 21:21:35.9793|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2021-10-20 21:21:35.9793|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.FormatException>
2021-10-20 21:21:35.9793|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <Input string was not in a correct format.>
2021-10-20 21:21:35.9793|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)>
2021-10-20 21:21:35.9793|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <mscorlib>
2021-10-20 21:21:35.9793|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <Double ParseDouble(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)>
2021-10-20 21:21:35.9793|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2146233033>
2021-10-20 21:21:35.9793|ERROR|App.RegisterAppDomainExceptions
|-------------------------- End exception --------------------------

2021-10-20 21:21:35.9958|ERROR|App.RegisterAppDomainExceptions

|-------------------------- Begin exception --------------------------
2021-10-20 21:21:35.9958|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2021-10-20 21:21:35.9958|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.Deployment.Application.InvalidDeploymentException>
2021-10-20 21:21:35.9958|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <Application identity is not set.>
2021-10-20 21:21:35.9958|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()>
2021-10-20 21:21:35.9958|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <System.Deployment>
2021-10-20 21:21:35.9958|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <System.Deployment.Application.ApplicationDeployment get_CurrentDeployment()>
2021-10-20 21:21:35.9958|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2146233087>
2021-10-20 21:21:35.9958|ERROR|App.RegisterAppDomainExceptions
|-------------------------- End exception --------------------------

Release Data

OriginalFilename  : Wox.exe
FileDescription   : Wox
ProductName       : Wox
Comments          : Release build, https://github.com/Wox-launcher/Wox
CompanyName       : Wox
FileName          : C:\Users\USER\AppData\Local\Wox\app-1.3.524\Wox.exe
FileVersion       : 1.3.524
ProductVersion    : 1.3.524
IsDebug           : False
IsPatched         : False
IsPreRelease      : False
IsPrivateBuild    : False
IsSpecialBuild    : False
Language          : Language Neutral
LegalCopyright    : The MIT License (MIT)
FileVersionRaw    : 1.3.524.0
ProductVersionRaw : 1.3.524.0

**Comment by crazy54** [comment]
hello? *ello....eloo...eooo...oo...oo* Anyone here? *ere....errr....eeree....ea....r....*
