### ISSUE TITLE
wox = 1.4.1196  & windows=win10,windows inner version = 19044.1706

### ISSUE THREAD

**Issue by XuelinHu** [Wox-launcher/Wox#3695]
**cannot start the wox with art+space,**

log as following...

2022-05-12 14:50:08.7130|ERROR|Wox.Plugin.Program.Programs.Win32|ProgramPaths|Permission denied C:\Users\PC\AppData\Roaming\Microsoft\Windows\Start Menu
2022-05-12 14:50:08.7130|ERROR|Wox.Plugin.Program.Programs.Win32|ProgramPaths|Permission denied C:\ProgramData\Microsoft\Windows\Start Menu
2022-05-12 14:50:08.7442|ERROR|Wox.Plugin.Program.Programs.UWP|All|Cannot parse UWP C:\Program Files (x86)\Microsoft\Edge\Application|Exception begin --------------------
  System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\Microsoft\Edge\Application\AppxManifest.xml'.
  HResult: -2147024894
  Data: <FullName> -> <Microsoft.MicrosoftEdge.Stable_101.0.1210.39_neutral__8wekyb3d8bbwe>
  Data: <Location> -> <C:\Program Files (x86)\Microsoft\Edge\Application>
  Source: mscorlib
  TargetAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=&hidden&
  TargetModule: CommonLanguageRuntimeLibrary
  TargetSite: Void WinIOError(Int32, System.String)
  StackTrace: --------------------
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at Wox.Plugin.Program.Programs.UWP.InitializeAppInfo() in C:\projects\wox\Plugins\Wox.Plugin.Program\Programs\UWP.cs:line 51
   at Wox.Plugin.Program.Programs.UWP.<>c__DisplayClass25_0.<All>b__0(UWP package, ParallelLoopState state) in C:\projects\wox\Plugins\Wox.Plugin.Program\Programs\UWP.cs:line 151
Exception end ------------------------------------------------------------

2022-05-12 14:50:08.9241|INFO|Wox.Plugin.Program.Main|IndexPrograms|UWP index cost <215ms>
2022-05-12 14:50:09.4979|INFO|Wox.Plugin.Program.Main|IndexPrograms|Win32 index cost <785ms>
2022-05-12 14:50:09.4979|INFO|Wox.Plugin.Program.Main|IndexPrograms|Number of indexed win32 programs <152>
2022-05-12 14:50:09.4979|INFO|Wox.Plugin.Program.Main|IndexPrograms|Number of indexed uwps <32>

**Comment by XuelinHu** [comment]
when I copy a file AppxManifest.xml intothe path C:\Program Files (x86)\Microsoft\Edge\Application\.
error log as following: 


2022-05-12 15:27:56.1319|INFO|Wox.Plugin.Program.Main|IndexPrograms|UWP index cost <210ms>
2022-05-12 15:27:56.9418|INFO|Wox.Plugin.Program.Main|IndexPrograms|Win32 index cost <1015ms>
2022-05-12 15:27:56.9418|INFO|Wox.Plugin.Program.Main|IndexPrograms|Number of indexed win32 programs <152>
2022-05-12 15:27:56.9574|INFO|Wox.Plugin.Program.Main|IndexPrograms|Number of indexed uwps <32>
2022-05-12 15:28:54.7291|INFO|Wox.Core.Updater|UpdateApp|Future Release <{
  "SHA1": "12312",
  "BaseUrl": null,
  "Filename": "Wox-1.4.1196-full.nupkg",
  "Query": null,
  "Filesize": 8527076,
  "IsDelta": false,
  "StagingPercentage": null
}>
2022-05-12 15:30:12.4964|INFO|Wox.App|OnStartup|Begin Wox startup----------------------------------------------------
2022-05-12 15:30:12.7205|INFO|Wox.App|OnStartup|## Runtime Info
* Command Line: "C:\Users\PC\AppData\Local\Wox\app-1.4.1196\Wox.exe" --squirrel-firstrun
* Portable Mode: False
* Timestamp: 05/12/2022 15:30:12
* Wox version: 1.4.1196
* OS Version: Microsoft Windows NT 10.0.19044.0
* x64 OS: True
* x64 Process: True
* System Language: zh-CN
* Wox Language: en
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.8.04084
   * v4 Full 4.8.04084
   * v4.0 Client 4.0.0.0

2022-05-12 15:30:13.0177|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Hello World CSharp> is <4ms>
2022-05-12 15:30:13.0177|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Colors> is <4ms>
2022-05-12 15:30:13.0177|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Plugin Indicator> is <2ms>
2022-05-12 15:30:13.0177|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Shell> is <9ms>
2022-05-12 15:30:13.0177|INFO|Wox.Infrastructure.Storage.BinaryStorage`1|TryLoad|Cache file not exist, load default data
2022-05-12 15:30:13.0177|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Wox Plugin Management> is <1ms>
2022-05-12 15:30:13.0333|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <System Commands> is <2ms>
2022-05-12 15:30:13.0333|INFO|Wox.Infrastructure.Storage.BinaryStorage`1|TryLoad|Cache file not exist, load default data
2022-05-12 15:30:13.0489|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Folder> is <5ms>
2022-05-12 15:30:13.0489|INFO|Wox.Plugin.Program.Main|preloadPrograms|Preload programs cost <37ms>
2022-05-12 15:30:13.0645|INFO|Wox.Plugin.Program.Main|preloadPrograms|Number of preload win32 programs <0>
2022-05-12 15:30:13.0645|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <随手记> is <13ms>
2022-05-12 15:30:13.0645|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Calculator> is <13ms>
2022-05-12 15:30:13.0788|INFO|Wox.Plugin.Program.Main|preloadPrograms|Number of preload uwps <0>
2022-05-12 15:30:13.0788|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Control Panel> is <62ms>
2022-05-12 15:30:13.0788|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Web Searches> is <14ms>
2022-05-12 15:30:13.0944|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <URL> is <3ms>
2022-05-12 15:30:13.0944|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Program> is <84ms>
2022-05-12 15:30:13.1131|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Everything> is <7ms>
2022-05-12 15:30:13.1131|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Wox.Plugin.Timestamp> is <1ms>
2022-05-12 15:30:13.1131|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Bookmarks Seacher(fix)> is <0ms>
2022-05-12 15:30:13.1318|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Hosts> is <0ms>
2022-05-12 15:30:13.1318|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <有道翻译> is <2ms>
2022-05-12 15:30:13.1318|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Bookmarks Seacher> is <0ms>
2022-05-12 15:30:13.1474|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Translator (Google translate)> is <0ms>
2022-05-12 15:30:15.1108|ERROR|Wox.Plugin.Program.Programs.Win32|ProgramPaths|Permission denied C:\Users\PC\AppData\Roaming\Microsoft\Windows\Start Menu
2022-05-12 15:30:15.1336|ERROR|Wox.Plugin.Program.Programs.Win32|ProgramPaths|Permission denied C:\ProgramData\Microsoft\Windows\Start Menu
2022-05-12 15:30:15.1496|ERROR|Wox.Plugin.Program.Programs.UWP|All|Cannot parse UWP C:\Program Files (x86)\Microsoft\Edge\Application|Exception begin --------------------
  System.ArgumentException: Cannot read Applications key from C:\Program Files (x86)\Microsoft\Edge\Application\AppxManifest.xml
  HResult: -2147024809
  Data: <FullName> -> <Microsoft.MicrosoftEdge.Stable_101.0.1210.39_neutral__8wekyb3d8bbwe>
  Data: <Location> -> <C:\Program Files (x86)\Microsoft\Edge\Application>
  Source: Wox.Plugin.Program
  TargetAssembly: Wox.Plugin.Program, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null
  TargetModule: Wox.Plugin.Program.dll
  TargetSite: Void InitializeAppInfo()
  StackTrace: --------------------
   at Wox.Plugin.Program.Programs.UWP.InitializeAppInfo() in C:\projects\wox\Plugins\Wox.Plugin.Program\Programs\UWP.cs:line 95
   at Wox.Plugin.Program.Programs.UWP.<>c__DisplayClass25_0.<All>b__0(UWP package, ParallelLoopState state) in C:\projects\wox\Plugins\Wox.Plugin.Program\Programs\UWP.cs:line 151
Exception end ------------------------------------------------------------


2022-05-12 15:30:15.3375|INFO|Wox.Plugin.Program.Main|IndexPrograms|UWP index cost <225ms>
2022-05-12 15:30:16.0056|INFO|Wox.Plugin.Program.Main|IndexPrograms|Win32 index cost <894ms>
2022-05-12 15:30:16.0056|INFO|Wox.Plugin.Program.Main|IndexPrograms|Number of indexed win32 programs <152>
2022-05-12 15:30:16.0056|INFO|Wox.Plugin.Program.Main|IndexPrograms|Number of indexed uwps <32>

**Comment by XuelinHu** [comment]
remove the pofiles of plugins, it is fiexd
