### ISSUE TITLE
Wox2 not working at all

### ISSUE THREAD

**Issue by sdsy888** [Wox-launcher/Wox#4000]
**Describe the bug**
The wox v1 works fine on my win11. 
But wox2 dosen't work at all (no response at all): after double-click the exe file, only an icon shows at the right bottom corner. No actions when click(both right-click and left-click) the icon. 
Also, no action after hitting the shortcut  alt+space. 

**Expected behavior**
works as normal as v1.

**Version**
- [ ] v1 (has no resource to fix)
- [ x] v2

**Platforms**
- [ ] Macos
- [x ] Windows
- [ ] Linux

**Additional context**

**Comment by qianlifeng** [comment]
pls help to upload log located in `C:\Users\<yourname>\.wox\log`

**Comment by cconrad** [comment]
I have the same problem as OP, here is my log:

```
2024-03-25 11:39:33.284 G0000001 f976cc32-df65-48cc-846c-ed6ca9a97581 [INF] [Wox] ------------------------------
2024-03-25 11:39:33.284 G0000001 f976cc32-df65-48cc-846c-ed6ca9a97581 [INF] [Wox] Wox starting
2024-03-25 11:39:33.284 G0000001 f976cc32-df65-48cc-846c-ed6ca9a97581 [INF] [Wox] golang version: 1.21.4
2024-03-25 11:39:33.284 G0000001 f976cc32-df65-48cc-846c-ed6ca9a97581 [INF] [Wox] wox data location: C:\Users\mail/.wox
2024-03-25 11:39:33.284 G0000001 f976cc32-df65-48cc-846c-ed6ca9a97581 [INF] [Wox] user data location: C:\Users\mail/.wox/wox-user
2024-03-25 11:39:33.332 G0000001 f976cc32-df65-48cc-846c-ed6ca9a97581 [INF] [Wox] extracted theme file: dark.json, cost: 0ms
2024-03-25 11:39:33.332 G0000001 f976cc32-df65-48cc-846c-ed6ca9a97581 [INF] [Wox] extracted theme file: light.json, cost: 0ms
2024-03-25 11:39:33.333 G0000001 f976cc32-df65-48cc-846c-ed6ca9a97581 [INF] [Wox] extracted embed files, cost: 49ms
2024-03-25 11:39:34.021 G0000029 367b5d10-5b89-4b52-84f9-ce7522981d52 [INF] [Wox] start to get theme manifest from Wox Official Theme Store(https://raw.githubusercontent.com/Wox-launcher/Wox/v2/theme-store.json)
2024-03-25 11:39:34.047 G0000001 f976cc32-df65-48cc-846c-ed6ca9a97581 [INF] [Wox] start loading plugins
2024-03-25 11:39:34.047 G0000001 f976cc32-df65-48cc-846c-ed6ca9a97581 [INF] [Wox] start loading system plugins, found 14 system plugins
2024-03-25 11:39:34.047 G0000001 f976cc32-df65-48cc-846c-ed6ca9a97581 [DBG] [Wox] finish loading system plugins, cost 0 ms
2024-03-25 11:39:34.047 G0000001 f976cc32-df65-48cc-846c-ed6ca9a97581 [DBG] [Wox] start loading user plugin metadata
2024-03-25 11:39:34.047 G0000001 f976cc32-df65-48cc-846c-ed6ca9a97581 [INF] [Wox] start loading user plugins, found 0 user plugins
2024-03-25 11:39:34.048 G0000038 06e12a31-4f5c-4762-b139-5eca4959fc4f [INF] [Wox] start init plugin: Calculator
2024-03-25 11:39:34.048 G0000038 06e12a31-4f5c-4762-b139-5eca4959fc4f [INF] [Wox] init plugin Calculator finished, cost 0 ms
2024-03-25 11:39:34.048 G0000039 e9a30486-4200-434a-a900-5d52c156a766 [INF] [Wox] start init plugin: Chatgpt
2024-03-25 11:39:34.048 G0000048 ea0f06f7-079b-4930-997c-9a63483b8d80 [INF] [Wox] start init plugin: Url
2024-03-25 11:39:34.048 G0000051 3dc1e720-d6b2-4a54-a305-cfc289121189 [INF] [Wox] start init plugin: App
2024-03-25 11:39:34.048 G0000048 ea0f06f7-079b-4930-997c-9a63483b8d80 [INF] [Wox] init plugin Url finished, cost 0 ms
2024-03-25 11:39:34.048 G0000039 e9a30486-4200-434a-a900-5d52c156a766 [WRN] [Chatgpt] model is empty
2024-03-25 11:39:34.049 G0000039 e9a30486-4200-434a-a900-5d52c156a766 [INF] [Chatgpt] no non-active chats to load
2024-03-25 11:39:34.049 G0000039 e9a30486-4200-434a-a900-5d52c156a766 [INF] [Chatgpt] no active chat to load
2024-03-25 11:39:34.049 G0000039 e9a30486-4200-434a-a900-5d52c156a766 [INF] [Chatgpt] loaded 0 nonactive chats, has active chat: false
2024-03-25 11:39:34.049 G0000039 e9a30486-4200-434a-a900-5d52c156a766 [INF] [Wox] init plugin Chatgpt finished, cost 1 ms
2024-03-25 11:39:34.049 G0000045 4399e5d6-633a-4bde-975c-487d4d59eab7 [INF] [Wox] start init plugin: Selection
2024-03-25 11:39:34.049 G0000045 4399e5d6-633a-4bde-975c-487d4d59eab7 [INF] [Wox] init plugin Selection finished, cost 0 ms
2024-03-25 11:39:34.049 G0000054 62a050f1-609d-4d7d-b4de-7133aa0e157e [INF] [Wox] start to get plugin manifest from Wox Official Plugin Store(https://raw.githubusercontent.com/Wox-launcher/Wox/v2/plugin-store.json)
2024-03-25 11:39:34.049 G0000051 3dc1e720-d6b2-4a54-a305-cfc289121189 [INF] [App] start to load app cache
2024-03-25 11:39:34.049 G0000051 3dc1e720-d6b2-4a54-a305-cfc289121189 [WRN] [App] app cache file not found
2024-03-25 11:39:34.049 G0000051 3dc1e720-d6b2-4a54-a305-cfc289121189 [INF] [Wox] init plugin App finished, cost 1 ms
2024-03-25 11:39:34.050 G0000042 a3c3c157-2426-4e0d-ae37-a1710955669a [INF] [Wox] start init plugin: Clipboard History
2024-03-25 11:39:34.050 G0000042 a3c3c157-2426-4e0d-ae37-a1710955669a [INF] [Wox] init plugin Clipboard History finished, cost 0 ms
2024-03-25 11:39:34.050 G0000052 1c9eb2a8-75e3-49ad-8edb-d334669d1767 [DBG] [Wox] start finding nodejs path
2024-03-25 11:39:34.050 G0000049 68abe8e1-b4a3-4a9b-82b5-4762a762f518 [INF] [Wox] start init plugin: WebSearch
2024-03-25 11:39:34.050 G0000052 1c9eb2a8-75e3-49ad-8edb-d334669d1767 [INF] [Wox] finally use default node from env path
2024-03-25 11:39:34.050 G0000053 1b842389-e35b-4cd0-b5d4-c59520c33c19 [INF] [Wox] <PYTHON Host Impl> starting host on port 39903
2024-03-25 11:39:34.050 G0000053 1b842389-e35b-4cd0-b5d4-c59520c33c19 [INF] [Wox] <PYTHON Host Impl> host path: python
2024-03-25 11:39:34.050 G0000053 1b842389-e35b-4cd0-b5d4-c59520c33c19 [INF] [Wox] <PYTHON Host Impl> host entry: C:\Users\mail/.wox/hosts/python-host.pyz
2024-03-25 11:39:34.050 G0000053 1b842389-e35b-4cd0-b5d4-c59520c33c19 [INF] [Wox] <PYTHON Host Impl> host args: 
2024-03-25 11:39:34.050 G0000100 a1911396-9ffa-4979-9305-d37033eea0f3 [INF] [App] start to get apps
2024-03-25 11:39:34.050 G0000053 1b842389-e35b-4cd0-b5d4-c59520c33c19 [INF] [Wox] <PYTHON Host Impl> host log directory: C:\Users\mail/.wox/log/hosts
2024-03-25 11:39:34.050 G0000049 68abe8e1-b4a3-4a9b-82b5-4762a762f518 [INF] [WebSearch] loaded 0 web searches
2024-03-25 11:39:34.050 G0000049 68abe8e1-b4a3-4a9b-82b5-4762a762f518 [INF] [Wox] init plugin WebSearch finished, cost 0 ms
2024-03-25 11:39:34.050 G0000052 1c9eb2a8-75e3-49ad-8edb-d334669d1767 [INF] [Wox] <NODEJS Host Impl> starting host on port 39904
2024-03-25 11:39:34.050 G0000052 1c9eb2a8-75e3-49ad-8edb-d334669d1767 [INF] [Wox] <NODEJS Host Impl> host path: node
2024-03-25 11:39:34.050 G0000052 1c9eb2a8-75e3-49ad-8edb-d334669d1767 [INF] [Wox] <NODEJS Host Impl> host entry: C:\Users\mail/.wox/hosts/node-host.js
2024-03-25 11:39:34.050 G0000052 1c9eb2a8-75e3-49ad-8edb-d334669d1767 [INF] [Wox] <NODEJS Host Impl> host args: 
2024-03-25 11:39:34.050 G0000052 1c9eb2a8-75e3-49ad-8edb-d334669d1767 [INF] [Wox] <NODEJS Host Impl> host log directory: C:\Users\mail/.wox/log/hosts
2024-03-25 11:39:34.051 G0000043 52c67220-ae8b-4511-af09-f433dbed4e53 [INF] [Wox] start init plugin: System Plugin Indicator
2024-03-25 11:39:34.051 G0000043 52c67220-ae8b-4511-af09-f433dbed4e53 [INF] [Wox] init plugin System Plugin Indicator finished, cost 0 ms
2024-03-25 11:39:34.052 G0000044 b6b555ca-8010-4431-bc4e-d22e49ae9966 [INF] [Wox] start init plugin: Wox Query History
2024-03-25 11:39:34.052 G0000044 b6b555ca-8010-4431-bc4e-d22e49ae9966 [INF] [Wox] init plugin Wox Query History finished, cost 0 ms
2024-03-25 11:39:34.053 G0000046 08c4bef4-c7c6-489e-9f8d-6a3787c8944b [INF] [Wox] start init plugin: System Commands
2024-03-25 11:39:34.053 G0000046 08c4bef4-c7c6-489e-9f8d-6a3787c8944b [INF] [Wox] init plugin System Commands finished, cost 0 ms
2024-03-25 11:39:34.053 G0000040 29365011-f2c5-4aaf-b805-55a0744856c4 [INF] [Wox] start init plugin: Backup and restore Wox settings
2024-03-25 11:39:34.053 G0000040 29365011-f2c5-4aaf-b805-55a0744856c4 [INF] [Wox] init plugin Backup and restore Wox settings finished, cost 0 ms
2024-03-25 11:39:34.053 G0000047 498e6814-c696-4806-a878-d3dc7eb476fe [INF] [Wox] start init plugin: Theme manager
2024-03-25 11:39:34.053 G0000047 498e6814-c696-4806-a878-d3dc7eb476fe [INF] [Wox] init plugin Theme manager finished, cost 0 ms
2024-03-25 11:39:34.053 G0000041 e9ec2cfe-7ae0-4dcc-a7a5-ab6709d2324e [INF] [Wox] start init plugin: BrowserBookmark
2024-03-25 11:39:34.053 G0000041 e9ec2cfe-7ae0-4dcc-a7a5-ab6709d2324e [INF] [Wox] init plugin BrowserBookmark finished, cost 0 ms
2024-03-25 11:39:34.054 G0000050 96190d0b-7ac9-4cdf-85be-ba91a161a45b [INF] [Wox] start init plugin: Wox Plugin Manager
2024-03-25 11:39:34.054 G0000050 96190d0b-7ac9-4cdf-85be-ba91a161a45b [ERR] [Wox Plugin Manager] Failed to unmarshal local plugin directories: unexpected end of JSON input
2024-03-25 11:39:34.054 G0000050 96190d0b-7ac9-4cdf-85be-ba91a161a45b [INF] [Wox] init plugin Wox Plugin Manager finished, cost 0 ms
2024-03-25 11:39:34.058 G0000056 f976cc32-df65-48cc-846c-ed6ca9a97581 [INF] [Wox] register normal hotkey: alt+space
2024-03-25 11:39:34.061 G0000100 a1911396-9ffa-4979-9305-d37033eea0f3 [INF] [App] found 116 apps in 5 groups
2024-03-25 11:39:34.063 G0000053 1b842389-e35b-4cd0-b5d4-c59520c33c19 [INF] [Wox] <PYTHON Host Impl> host pid: 29144
2024-03-25 11:39:34.063 G0000105 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Administrative Tools/iSCSI Initiator.lnk: no target path found
2024-03-25 11:39:34.067 G0000105 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Administrative Tools/services.lnk: no target path found
2024-03-25 11:39:34.080 G0000056 f976cc32-df65-48cc-846c-ed6ca9a97581 [INF] [Wox] register normal hotkey: win+alt+space
2024-03-25 11:39:34.080 G0000056 f976cc32-df65-48cc-846c-ed6ca9a97581 [INF] [Wox] register double hotkey: ctrl+ctrl
2024-03-25 11:39:34.080 G0000056 f976cc32-df65-48cc-846c-ed6ca9a97581 [INF] [Wox] websocket server start at：ws://localhost:39900
2024-03-25 11:39:34.084 G0000052 1c9eb2a8-75e3-49ad-8edb-d334669d1767 [INF] [Wox] <NODEJS Host Impl> host pid: 20620
2024-03-25 11:39:34.144 G0000108 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/WSL.lnk: no target path found
2024-03-25 11:39:34.146 G0000108 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Windows PowerShell/Windows PowerShell ISE (x86).lnk: no target path found
2024-03-25 11:39:34.146 G0000108 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Windows PowerShell/Windows PowerShell ISE.lnk: no target path found
2024-03-25 11:39:34.148 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Accessibility/Speech Recognition.lnk: no target path found
2024-03-25 11:39:34.159 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Accessories/Remote Desktop Connection.lnk: no target path found
2024-03-25 11:39:34.160 G0000105 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Brother/Brother Utilities.lnk: no target path found
2024-03-25 11:39:34.170 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Accessories/Steps Recorder.lnk: no target path found
2024-03-25 11:39:34.171 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Accessories/Windows Media Player Legacy.lnk: no target path found
2024-03-25 11:39:34.177 G0000105 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Brother/Brother iPrint&Scan.lnk: no target path found
2024-03-25 11:39:34.181 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Accessories/Wordpad.lnk: no target path found
2024-03-25 11:39:34.181 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Administrative Tools/Component Services.lnk: no target path found
2024-03-25 11:39:34.182 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Administrative Tools/Computer Management.lnk: no target path found
2024-03-25 11:39:34.183 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Administrative Tools/Disk Cleanup.lnk: no target path found
2024-03-25 11:39:34.183 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Administrative Tools/Event Viewer.lnk: no target path found
2024-03-25 11:39:34.184 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Administrative Tools/Memory Diagnostics Tool.lnk: no target path found
2024-03-25 11:39:34.185 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Administrative Tools/ODBC Data Sources (32-bit).lnk: no target path found
2024-03-25 11:39:34.185 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Administrative Tools/ODBC Data Sources (64-bit).lnk: no target path found
2024-03-25 11:39:34.186 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Administrative Tools/Performance Monitor.lnk: no target path found
2024-03-25 11:39:34.187 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Administrative Tools/RecoveryDrive.lnk: no target path found
2024-03-25 11:39:34.190 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Administrative Tools/Registry Editor.lnk: no target path found
2024-03-25 11:39:34.191 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Administrative Tools/Resource Monitor.lnk: no target path found
2024-03-25 11:39:34.208 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Administrative Tools/Security Configuration Management.lnk: no target path found
2024-03-25 11:39:34.212 G0000107 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/System Tools/Task Manager.lnk: no target path found
2024-03-25 11:39:34.212 G0000179 a3c3c157-2426-4e0d-ae37-a1710955669a [INF] [Clipboard History] clipboard data changed, type=text
2024-03-25 11:39:34.225 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Administrative Tools/System Configuration.lnk: no target path found
2024-03-25 11:39:34.226 G0000179 a3c3c157-2426-4e0d-ae37-a1710955669a [INF] [Wox] plugin setting saved: 5f815d98-27f5-488d-a756-c317ea39935b
2024-03-25 11:39:34.226 G0000179 a3c3c157-2426-4e0d-ae37-a1710955669a [INF] [Clipboard History] save clipboard history, count:1, cost:11ms
2024-03-25 11:39:34.236 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Administrative Tools/System Information.lnk: no target path found
2024-03-25 11:39:34.237 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Administrative Tools/Task Scheduler.lnk: no target path found
2024-03-25 11:39:34.245 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Administrative Tools/Windows Defender Firewall with Advanced Security.lnk: no target path found
2024-03-25 11:39:34.247 G0000104 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Administrative Tools/dfrgui.lnk: no target path found
2024-03-25 11:39:34.251 G0000054 62a050f1-609d-4d7d-b4de-7133aa0e157e [INF] [Wox] found 4 plugins from stores
2024-03-25 11:39:34.251 G0000075 b4e05ac6-7833-480e-8d3c-d18a6764f735 [INF] [Wox] start to get plugin manifest from Wox Official Plugin Store(https://raw.githubusercontent.com/Wox-launcher/Wox/v2/plugin-store.json)
2024-03-25 11:39:34.261 G0000107 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/TechSmith/Snagit 2023 Editor.lnk: no target path found
2024-03-25 11:39:34.276 G0000107 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/TechSmith/Snagit 2023.lnk: no target path found
2024-03-25 11:39:34.278 G0000029 367b5d10-5b89-4b52-84f9-ce7522981d52 [INF] [Wox] found 1 themes from stores
2024-03-25 11:39:34.285 G0000075 b4e05ac6-7833-480e-8d3c-d18a6764f735 [INF] [Wox] found 4 plugins from stores
2024-03-25 11:39:34.292 G0000108 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/dupeGuru/Uninstall.lnk: no target path found
2024-03-25 11:39:34.293 G0000071 f976cc32-df65-48cc-846c-ed6ca9a97581 [INF] [Wox] added execute permission to ui app
2024-03-25 11:39:34.293 G0000071 f976cc32-df65-48cc-846c-ed6ca9a97581 [INF] [Wox] start ui, path=C:\Users\mail/.wox/ui/flutter/wox/wox.exe, port=39900, pid=31364
2024-03-25 11:39:34.300 G0000107 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/TechSmith/Snagit 2024 Editor.lnk: no target path found
2024-03-25 11:39:34.320 G0000107 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/TechSmith/Snagit 2024.lnk: no target path found
2024-03-25 11:39:34.337 G0000105 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/HexChat/HexChat Config Folder.lnk: no target path found
2024-03-25 11:39:34.344 G0000071 f976cc32-df65-48cc-846c-ed6ca9a97581 [INF] [Wox] ui app pid: 11124
2024-03-25 11:39:34.372 G0000107 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Transmission Qt Client.lnk: no target path found
2024-03-25 11:39:34.382 G0000107 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/TrustedQSL/Quick Start.lnk: no target path found
2024-03-25 11:39:34.398 G0000107 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/TrustedQSL/TQSL.lnk: no target path found
2024-03-25 11:39:34.453 G0000105 a1911396-9ffa-4979-9305-d37033eea0f3 [ERR] [App] error getting app info for C:\ProgramData\Microsoft\Windows\Start Menu\Programs/Logi/Logi Options+.lnk: no target path found
2024-03-25 11:39:34.489 G0000100 a1911396-9ffa-4979-9305-d37033eea0f3 [INF] [App] wrote app cache to C:\Users\mail/.wox/cache/wox-app-cache.json
2024-03-25 11:39:34.489 G0000100 a1911396-9ffa-4979-9305-d37033eea0f3 [INF] [App] indexed 76 apps, cost 439 ms
2024-03-25 11:39:34.512 G0000148 f976cc32-df65-48cc-846c-ed6ca9a97581 [INF] [Wox] ui connected: 127.0.0.1:39914
2024-03-25 11:39:34.645 G0000026 406901a9-7f26-4594-90b1-357e4e8fd26f [INF] [Wox] [SYS LOG] Traceback (most recent call last):
2024-03-25 11:39:34.645 G0000026 31ee2d7a-0572-41ee-b5f2-1d14753ccf90 [INF] [Wox] [SYS LOG]   File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\mail\.wox\hosts\python-host.pyz\__main__.py", line 18, in <module>
2024-03-25 11:39:34.645 G0000026 11de139b-afc4-40be-8dc2-41b084adcd17 [INF] [Wox] [SYS LOG]   File "C:\Users\mail\.wox\hosts\python-host.pyz\logger.py", line 14, in info
2024-03-25 11:39:34.645 G0000026 57412f20-cb09-4dc1-92f4-761aaa493641 [INF] [Wox] [SYS LOG]   File "C:\Users\mail\.wox\hosts\python-host.pyz\logger.py", line 22, in __inner_log
2024-03-25 11:39:34.645 G0000026 9929758c-04b1-4273-a57b-190cd61d144c [INF] [Wox] [SYS LOG] TypeError: Logger.log() missing 2 required positional arguments: '_Logger__level' and '_Logger__message'
2024-03-25 11:39:35.027 G0000091 41c8a133-27c6-4028-a0ee-83974a437f2f [INF] [Wox] [Wox -> UI] ShowApp: {"LastQueryMode":"empty","Position":{"Type":"MouseScreen","X":880,"Y":240},"QueryHistories":[],"SelectAll":false}
2024-03-25 11:39:35.028 G0000201 41c8a133-27c6-4028-a0ee-83974a437f2f [DBG] [Wox] got <ShowApp> response from ui
2024-03-25 11:39:35.028 G0000200 41c8a133-27c6-4028-a0ee-83974a437f2f [INF] [ UI] Received message: ShowApp
2024-03-25 11:39:35.029 G0000202 41c8a133-27c6-4028-a0ee-83974a437f2f [DBG] [Wox] got <VisibilityChanged> request from ui
2024-03-25 11:39:35.074 G0000053 1b842389-e35b-4cd0-b5d4-c59520c33c19 [ERR] [Wox] <PYTHON Host Impl> failed to connect to host: dial tcp [::1]:39903: connectex: No connection could be made because the target machine actively refused it.
2024-03-25 11:44:18.477 G0000770 a3c3c157-2426-4e0d-ae37-a1710955669a [INF] [Clipboard History] clipboard data changed, type=text
2024-03-25 11:44:18.479 G0000770 a3c3c157-2426-4e0d-ae37-a1710955669a [INF] [Wox] plugin setting saved: 5f815d98-27f5-488d-a756-c317ea39935b
2024-03-25 11:44:18.479 G0000770 a3c3c157-2426-4e0d-ae37-a1710955669a [INF] [Clipboard History] save clipboard history, count:2, cost:1ms
ion: C:\Users\mail/.wox
2024-03-25 11:39:36.160 G0000001 16bc3ea7-de0a-45c1-b509-79c83d0a184f [INF] [Wox] user data location: C:\Users\mail/.wox/wox-user
2024-03-25 11:39:36.181 G0000001 16bc3ea7-de0a-45c1-b509-79c83d0a184f [ERR] [Wox] failed to extract embed file: open C:\Users\mail/.wox/ui/flutter/wox/data/icudtl.dat: The requested operation cannot be performed on a file with a user-mapped section open.
```

**Comment by fsilly** [comment]
Same here, I double clicked the exe file and nothing happened. I even tried starting with admin rights. Also windows wanted to "protect my PC" when launching it.

**Comment by fsilly** [comment]
![image](https://github.com/Wox-launcher/Wox/assets/46908682/cb0e8253-142e-4ce8-898b-707e60f11ab4)
My windows installation

**Comment by fsilly** [comment]
something to be running tho 
![image](https://github.com/Wox-launcher/Wox/assets/46908682/a4e4bef5-ea21-4406-9c5b-3bd684a3defd)

**Comment by qianlifeng** [comment]
> Same here, I double clicked the exe file and nothing happened. I even tried starting with admin rights. Also windows wanted to "protect my PC" when launching it.

could you please upload log file located in C:\Users\<yourname>\.wox\log. wox will extract some files during app start, which maybe the reason windows wants to "protected my PC"

**Comment by sdsy888** [comment]
> > Same here, I double clicked the exe file and nothing happened. I even tried starting with admin rights. Also windows wanted to "protect my PC" when launching it.
> 
> could you please upload log file located in C:\Users<yourname>.wox\log. wox will extract some files during app start, which maybe the reason windows wants to "protected my PC"

[log.txt](https://github.com/Wox-launcher/Wox/files/14818297/log.txt)

Hi, here is the log file on my PC. I downloaded the newest wox.exe today(2024/4/1) and found that wox can run now. 
It can be opened using shortcut, but it  won't respond to the click operation( e.g. when trying installing a plugin, the "install" button have no respond to the clicking).

Should you need more log or information, just let me know.

**Comment by qianlifeng** [comment]
> > > Same here, I double clicked the exe file and nothing happened. I even tried starting with admin rights. Also windows wanted to "protect my PC" when launching it.
> > 
> > 
> > could you please upload log file located in C:\Users.wox\log. wox will extract some files during app start, which maybe the reason windows wants to "protected my PC"
> 
> [log.txt](https://github.com/Wox-launcher/Wox/files/14818297/log.txt)
> 
> Hi, here is the log file on my PC. I downloaded the newest wox.exe today(2024/4/1) and found that wox can run now. It can be opened using shortcut, but it won't respond to the click operation( e.g. when trying installing a plugin, the "install" button have no respond to the clicking).
> 
> Should you need more log or information, just let me know.

It's your network issues that can't download plugin from github. I will improve the UE if there is a download err.
> Get "https://github.com/Wox-launcher/Wox.Plugin.DeepL/releases/latest/download/Wox.Plugin.DeepL.wox": dial tcp 20.205.243.166:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by sdsy888** [comment]
> > > > Same here, I double clicked the exe file and nothing happened. I even tried starting with admin rights. Also windows wanted to "protect my PC" when launching it.
> > > 
> > > 
> > > could you please upload log file located in C:\Users.wox\log. wox will extract some files during app start, which maybe the reason windows wants to "protected my PC"
> > 
> > 
> > [log.txt](https://github.com/Wox-launcher/Wox/files/14818297/log.txt)
> > Hi, here is the log file on my PC. I downloaded the newest wox.exe today(2024/4/1) and found that wox can run now. It can be opened using shortcut, but it won't respond to the click operation( e.g. when trying installing a plugin, the "install" button have no respond to the clicking).
> > Should you need more log or information, just let me know.
> 
> It's your network issues that can't download plugin from github. I will improve the UE if there is a download err.
> 
> > Get "https://github.com/Wox-launcher/Wox.Plugin.DeepL/releases/latest/download/Wox.Plugin.DeepL.wox": dial tcp 20.205.243.166:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

However, I have the VPN and I can connect to the `github.com` with or without the VPN. So is there a way to set the proxy for wox?

**Comment by sdsy888** [comment]
BTW, I cannot right click the wox icon in the task bar. So I have to kill the wox through task manager every time.

**Comment by qianlifeng** [comment]
> BTW, I cannot right click the wox icon in the task bar. So I have to kill the wox through task manager every time.

It's an known issue on windows, we will try to fix later. You can type `exit` to quit Wox for now.

**Comment by qianlifeng** [comment]
Wox v2 on windows should be working as expected now.
