### ISSUE TITLE
Seek for error Solution

### ISSUE THREAD

**Issue by Fadeedee** [Wox-launcher/Wox#4021]
Error id: 48aac445de4e4ffa808e58e9c67ac9ca
Exception begin --------------------
  System.NullReferenceException: Object reference not set to an instance of an object.
  HResult: -2147467261
  Data: <System.Object> -> <>
  Source: Wox
  TargetAssembly: Wox, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null
  TargetModule: Wox.exe
  TargetSite: Void OnSecondAppStarted(System.Collections.Generic.IList`1[System.String])
  StackTrace: --------------------
   at Wox.App.OnSecondAppStarted(IList`1 args) in C:\projects\wox\Wox\App.xaml.cs:line 202
   at Wox.Helper.SingleInstance`1.ActivateFirstInstanceCallback(Object arg) in C:\projects\wox\Wox\Helper\SingleInstance.cs:line 418
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Exception end ------------------------------------------------------------

**Comment by Fadeedee** [comment]
After downloading the jdk from IDEA and restarting the computer, this error message was displayed.

**Comment by qianlifeng** [comment]
see #3937
