### ISSUE TITLE
Crash when open containing folder of *.lnk item

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#404]

**Comment by lances101** [comment]
any details? I seem to be able to open containing folders of *.lnk without problem.

**Comment by bao-qian** [comment]
It depends on application, for example this one:
![java help](http://i.imgur.com/3LKcbhR.png)

```
Path cannot be the empty string or all whitespace.
Parameter name: path
```

```
System.ArgumentException
mscorlib
   at System.IO.Directory.GetParent(String path)
   at Wox.Plugin.Program.Programs.<>c__DisplayClass17_0.<LoadContextMenus>b__1(ActionContext _) in C:\Users\Ricky\Documents\GitHub\Wox\Plugins\Wox.Plugin.Program\Programs.cs:line 230
   at Wox.MainWindow.SelectResult(Result result) in C:\Users\Ricky\Documents\GitHub\Wox\Wox\MainWindow.xaml.cs:line 832
   at Wox.ResultPanel.OnLeftMouseClick(Result result) in C:\Users\Ricky\Documents\GitHub\Wox\Wox\ResultPanel.xaml.cs:line 37
   at Wox.ResultPanel.LbResults_OnPreviewMouseDown(Object sender, MouseButtonEventArgs e) in C:\Users\Ricky\Documents\GitHub\Wox\Wox\ResultPanel.xaml.cs:line 282
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)

```

**Comment by lances101** [comment]
Oh, of course, because the "Get Help.lnk" is a http link, so it cannot resolve a path. 
I think, the intended behavior in this case, would be to open the directory of the `.lnk` file, right?

**Comment by bao-qian** [comment]
Yes, it should behave same as "Open file location"
Not only the http link, it also happened on some Chinese application. 
e.g. ![yyy](http://i.imgur.com/QyhifSM.png)

Probably there are more cases, I'm not sure.

**Comment by lances101** [comment]
I've created a `漢.lnk` and PR #426 seems to open it just fine. 

Could you try it on your system? ([appveyor link](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.617/artifacts))

**Comment by bao-qian** [comment]
I think root cause is because `CreateShortcut` is a hack.
The proper way should be the top answer listed [here](http://stackoverflow.com/questions/139010/how-to-resolve-a-lnk-in-c-sharp) using `IShellLinkW`.

**Comment by lances101** [comment]
Avoiding using `IWshRuntimeLibrary` sounds like a good idea to me. I am just not sure that it would still open the correct folder. I will try it now. 

Edit: works well. Although, still requires the changes in PR #426 to handle HTTP links.

**Comment by lances101** [comment]
Updated PR #426. `IWshRuntimeLibrary` is no longer in use.
