### ISSUE TITLE
1. upload log file: C:\Users\PangRongDian\AppData\Roaming\Wox\Logs\1.4.1196\2024-06-26.txt 2. copy below exception message

### ISSUE THREAD

**Issue by pangrongdian** [Wox-launcher/Wox#4054]
Exception begin --------------------
  System.ComponentModel.Win32Exception: System call failed
  HResult: -2147467259
  Data: <System.Object> -> <>
  Source: System
  TargetAssembly: System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  TargetModule: System.dll
  TargetSite: Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
  StackTrace: --------------------
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Wox.Plugin.Folder.Main.<>c__DisplayClass22_0.<CreateOpenCurrentFolderResult>b__0(ActionContext c) in C:\projects\wox\Plugins\Wox.Plugin.Folder\Main.cs:line 289
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__17_7(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 209
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Exception end ------------------------------------------------------------

## Runtime Info
* Command Line: "C:\Users\PangRongDian\AppData\Local\Wox\app-1.4.1196\Wox.exe" 
* Portable Mode: False
* Timestamp: 06/26/2024 12:24:25
* Wox version: 1.4.1196
* OS Version: Microsoft Windows NT 10.0.19045.0
* x64 OS: True
* x64 Process: True
* System Language: en-US
* Wox Language: zh-cn
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.8.09037
   * v4 Full 4.8.09037
   * v4.0 Client 4.0.0.0

## SDK Info
* Python Path: 
* Everything SDK Path: C:\Users\PangRongDian\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll

**Comment by qianlifeng** [comment]
see #3937
