### ISSUE TITLE
tried to reinstall wox but now it's not installing

### ISSUE THREAD

**Issue by Wapachu** [Wox-launcher/Wox#4064]
I initially installed the program way back 2020. I just thought of reinstalling it to see if there are any changes or updates. Now, when I reinstall, I get this pop-up. 
![image](https://github.com/user-attachments/assets/3e453e7b-4b94-432c-aac0-25c6acd2c5b1)

And here is the log.

2024-07-24 19:24:19> Program: Starting Squirrel Updater: --install . --rerunningWithoutUAC
2024-07-24 19:24:19> Program: Starting install, writing to C:\Users\paul_\AppData\Local\SquirrelTemp
2024-07-24 19:24:19> Program: About to install to: C:\Users\paul_\AppData\Local\Wox
2024-07-24 19:24:19> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\paul_\AppData\Local\Wox' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Users\paul_\AppData\Local\Wox' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

I hope someone can help me with this issue.

**Comment by qianlifeng** [comment]
> Access to the path 'C:\Users\paul_\AppData\Local\Wox' is denied

Try to remove this folder manually and then install
