### ISSUE TITLE
wox built on macos can not be opened 

### ISSUE THREAD

**Issue by cuichenli** [Wox-launcher/Wox#4070]
**Version**  

- [ ] v1 (has no resource to fix)
- [x] v2

**Platform**  

- [x] Macos
- [ ] Windows
- [ ] Linux

**Description**  

I successfully built Wox on my local machine with `just dev` and it seems unable to start properly. Basically I can see the wox icon from dock, but I can not see any open window. 

I am not familiar with how to debug app like this, but when I tried to run the `wox` file from `wox.app/Contents/MacOS/wox`, I can see the following error:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DioException [connection error]: The connection errored: Connection refused This indicates an error which most likely cannot be solved by the library.
Error: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = localhost, port = 50201
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:519)
<asynchronous suspension>
#1      WoxHttpUtil.postData (package:wox/utils/wox_http_util.dart:35)
<asynchronous suspension>
#2      WoxApi.loadTheme (package:wox/api/wox_api.dart:21)
<asynchronous suspension>
#3      WoxThemeUtil.loadTheme (package:wox/utils/wox_theme_util.dart:15)
<asynchronous suspension>
#4      initialServices (package:wox/main.dart:53)
<asynchronous suspension>
#5      main (package:wox/main.dart:24)
<asynchronous suspension>
```

**Log**  

please upload wox log to help identify your bug.
- `~/.wox/log/log` if you use macos or linux
Somehow I can not see any logs from this file. I even added one extra line to log some dummy information at https://github.com/Wox-launcher/Wox/blob/v2/Wox.UI.Flutter/wox/lib/utils/wox_http_util.dart#L34 but still the log file is empty. 

I am new to the tech stack used by Wox, so please let me know if I missed anything. Thanks!

**Comment by cuichenli** [comment]
i see the issue now, when in development mode, i need to run the `wox` backend as well. i will create a PR to update the document later
