### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SunShineGong** [Wox-launcher/Wox#4088]
Exception begin --------------------
  System.Exception: Couldn't acquire lock, is another instance running
  HResult: -2146233088
  Data: <System.Object> -> <>
  Data: <AlreadySentByRaygun> -> <True>
  Source: Squirrel
  TargetAssembly: Squirrel, Version=1.9.1.0, Culture=neutral, PublicKeyToken=null
  TargetModule: Squirrel.dll
  TargetSite: Void .ctor(System.String, System.TimeSpan)
  StackTrace: --------------------
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut) in C:\Users\ana\code\Squirrel\Squirrel.Windows\src\Squirrel\Utility.cs:line 842
   at Squirrel.UpdateManager.<acquireUpdateLock>b__32_0() in C:\Users\ana\code\Squirrel\Squirrel.Windows\src\Squirrel\UpdateManager.cs:line 274
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext() in C:\Users\ana\code\Squirrel\Squirrel.Windows\src\Squirrel\UpdateManager.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Wox.Core.Updater.<UpdateApp>d__5.MoveNext() in C:\projects\wox\Wox.Core\Updater.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Wox.ViewModel.SettingWindowViewModel.<UpdateApp>d__7.MoveNext() in C:\projects\wox\Wox\ViewModel\SettingWindowViewModel.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Exception end ------------------------------------------------------------

## Runtime Info
* Command Line: "C:\Users\gongjj\AppData\Local\Wox\app-1.3.1039\Wox.exe" 
* Timestamp: 10/15/2024 14:01:58
* Wox version: 1.3.1039
* OS Version: Microsoft Windows NT 10.0.19043.0
* x64: True
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.8.04084
   * v4 Full 4.8.04084
   * v4.0 Client 4.0.0.0

## SDK Info
* Python Path: 
* Everything SDK Path: C:\Users\gongjj\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll

## Assemblies - Wox.exe

* Wox, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\gongjj\AppData\Local\Wox\app-1.3.1039\Wox.exe)
* Wox.Core, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\gongjj\AppData\Local\Wox\app-1.3.1039\Wox.Core.dll)
* Wox.Infrastructure, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\gongjj\AppData\Local\Wox\app-1.3.1039\Wox.Infrastructure.dll)
* Pinyin4Net, Version=2016.4.24.0, Culture=neutral, PublicKeyToken=null (C:\Users\gongjj\AppData\Local\Wox\app-1.3.1039\Pinyin4Net.dll)
* NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\gongjj\AppData\Local\Wox\app-1.3.1039\NLog.dll)
* Wox.Plugin, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\gongjj\AppData\Local\Wox\app-1.3.1039\Wox.Plugin.dll)
* Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\gongjj\AppData\Local\Wox\app-1.3.1039\Newtonsoft.Json.dll)
* Mindscape.Raygun4Net4, Version=5.10.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\gongjj\AppData\Local\Wox\app-1.3.1039\Mindscape.Raygun4Net4.dll)
* Mindscape.Raygun4Net, Version=5.10.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\gongjj\AppData\Local\Wox\app-1.3.1039\Mindscape.Raygun4Net.dll)
* HelloWorldCSharp, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\gongjj\AppData\Local\Wox\app-1.3.1039\Plugins\HelloWorldCSharp\HelloWorldCSharp.dll)
[2024-10-15.txt](https://github.com/user-attachments/files/17373337/2024-10-15.txt)

**Comment by qianlifeng** [comment]
see #3937
