### ISSUE TITLE
Bug: installation of plugins is not working

### ISSUE THREAD

**Issue by joordonezoArago** [Wox-launcher/Wox#4117]
**Version**  

- [ ] v1 (has no resource to fix)
- [x] v2

**Platform**  

- [ ] Macos
- [x] Windows
- [ ] Linux

**Description**  

installation of plugins is not working on windows 11 pro with wox version v2.0.0-2024.12-nightly.
![woxInstallError](https://github.com/user-attachments/assets/1c1533bc-44ce-429f-9688-c200d661ea44)
![image](https://github.com/user-attachments/assets/045f5932-61c3-46a1-baf2-abac456da997)

**Log**  
2024-12-26 15:20:42.632 G0000455 022555ca-3121-4daa-bbad-a2b9449f6dd5 [INF] [ UI] installing plugin: DeepL translator
2024-12-26 15:20:42.633 G0000342 483cf8d1-2fdd-41f1-98a9-98723a6cd573 [INF] [Wox] start to get plugin manifest from Wox Official Plugin Store(https://raw.githubusercontent.com/Wox-launcher/Wox/v2/store-plugin.json)
2024-12-26 15:20:42.633 G0000456 ed4d8cef-9752-43f9-a367-bb678aadc52a [INF] [ UI] Posting data to http://localhost:53982/plugin/install
2024-12-26 15:20:42.656 G0000342 483cf8d1-2fdd-41f1-98a9-98723a6cd573 [INF] [Wox] found 9 plugins from stores
2024-12-26 15:20:42.656 G0000342 483cf8d1-2fdd-41f1-98a9-98723a6cd573 [INF] [Wox] start to install plugin DeepL translator(0.0.6)
2024-12-26 15:20:42.656 G0000342 483cf8d1-2fdd-41f1-98a9-98723a6cd573 [ERR] [Wox] NODEJS runtime is not started, please start first
2024-12-26 15:20:42.658 G0000037 4f8284ab-96bd-40f8-8aba-24e5e4b49353 [INF] [Wox] [SYS LOG] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: can't install plugin: NODEJS runtime is not started, please start first
#0      WoxHttpUtil.postData (package:wox/utils/wox_http_util.dart:36)
<asynchronous suspension>
#1      WoxApi.installPlugin (package:wox/api/wox_api.dart:45)
<asynchronous suspension>
#2      WoxSettingController.installPlugin (package:wox/modules/setting/wox_setting_controller.dart:105)
<asynchronous suspension>

2024-12-26 15:20:42.658 G0000377 ed4d8cef-9752-43f9-a367-bb678aadc52a [ERR] [ UI] Failed to post data, url=http://localhost:53982/plugin/install, data={id: 09ea2847-929c-440a-aa2c-9b74bcaae69f}, err=Exception: can't install plugin: NODEJS runtime is not started, please start first, stacktrace=#0      WoxHttpUtil.postData (package:wox/utils/wox_http_util.dart:36)
<asynchronous suspension>
#1      WoxApi.installPlugin (package:wox/api/wox_api.dart:45)
<asynchronous suspension>
#2      WoxSettingController.installPlugin (package:wox/modules/setting/wox_setting_controller.dart:105)
<asynchronous suspension>

2024-12-26 15:20:46.838 G0000467 44e43043-cfb6-4d18-a4f9-37957b636161 [INF] [ UI] installing plugin: Spotify
2024-12-26 15:20:46.839 G0000468 63ee2c68-4189-4a2f-9a1b-4b76e1ff6881 [INF] [ UI] Posting data to http://localhost:53982/plugin/install
2024-12-26 15:20:46.841 G0000469 6b91496a-be89-4660-b219-25c6a4f380df [INF] [Wox] start to get plugin manifest from Wox Official Plugin Store(https://raw.githubusercontent.com/Wox-launcher/Wox/v2/store-plugin.json)
2024-12-26 15:20:47.024 G0000469 6b91496a-be89-4660-b219-25c6a4f380df [INF] [Wox] found 9 plugins from stores
2024-12-26 15:20:47.024 G0000469 6b91496a-be89-4660-b219-25c6a4f380df [INF] [Wox] start to install plugin Spotify(0.0.1)
2024-12-26 15:20:47.024 G0000469 6b91496a-be89-4660-b219-25c6a4f380df [ERR] [Wox] NODEJS runtime is not started, please start first
2024-12-26 15:20:47.026 G0000037 a7264e75-41b9-4aaa-adb4-9a9aea8617de [INF] [Wox] [SYS LOG] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: can't install plugin: NODEJS runtime is not started, please start first
#0      WoxHttpUtil.postData (package:wox/utils/wox_http_util.dart:36)
<asynchronous suspension>
#1      WoxApi.installPlugin (package:wox/api/wox_api.dart:45)
<asynchronous suspension>
#2      WoxSettingController.installPlugin (package:wox/modules/setting/wox_setting_controller.dart:105)
<asynchronous suspension>

2024-12-26 15:20:47.026 G0000457 63ee2c68-4189-4a2f-9a1b-4b76e1ff6881 [ERR] [ UI] Failed to post data, url=http://localhost:53982/plugin/install, data={id: aeb94d3d-9c39-4917-9cd0-a4cde95433a2}, err=Exception: can't install plugin: NODEJS runtime is not started, please start first, stacktrace=#0      WoxHttpUtil.postData (package:wox/utils/wox_http_util.dart:36)
<asynchronous suspension>
#1      WoxApi.installPlugin (package:wox/api/wox_api.dart:45)
<asynchronous suspension>
#2      WoxSettingController.installPlugin (package:wox/modules/setting/wox_setting_controller.dart:105)
<asynchronous suspension>

2024-12-26 15:20:50.651 G0000476 81262150-f68f-4cd4-8ab6-41f717866f87 [INF] [ UI] installing plugin: Emoji
2024-12-26 15:20:50.652 G0000477 7e1832fb-7f32-4f0c-817c-886964acc3ff [INF] [ UI] Posting data to http://localhost:53982/plugin/install
2024-12-26 15:20:50.654 G0000478 4cad15d9-a846-4034-861b-f87679280ca3 [INF] [Wox] start to get plugin manifest from Wox Official Plugin Store(https://raw.githubusercontent.com/Wox-launcher/Wox/v2/store-plugin.json)
2024-12-26 15:20:50.674 G0000478 4cad15d9-a846-4034-861b-f87679280ca3 [INF] [Wox] found 9 plugins from stores
2024-12-26 15:20:50.674 G0000478 4cad15d9-a846-4034-861b-f87679280ca3 [INF] [Wox] start to install plugin Emoji(0.0.2)
2024-12-26 15:20:50.674 G0000478 4cad15d9-a846-4034-861b-f87679280ca3 [ERR] [Wox] NODEJS runtime is not started, please start first
2024-12-26 15:20:50.675 G0000037 fadaf677-bb69-4f91-9d93-85366613824a [INF] [Wox] [SYS LOG] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: can't install plugin: NODEJS runtime is not started, please start first
#0      WoxHttpUtil.postData (package:wox/utils/wox_http_util.dart:36)
<asynchronous suspension>
#1      WoxApi.installPlugin (package:wox/api/wox_api.dart:45)
<asynchronous suspension>
#2      WoxSettingController.installPlugin (package:wox/modules/setting/wox_setting_controller.dart:105)
<asynchronous suspension>

2024-12-26 15:20:50.676 G0000458 7e1832fb-7f32-4f0c-817c-886964acc3ff [ERR] [ UI] Failed to post data, url=http://localhost:53982/plugin/install, data={id: 72a6fc3b-2915-4d50-b4ee-54968c174aba}, err=Exception: can't install plugin: NODEJS runtime is not started, please start first, stacktrace=#0      WoxHttpUtil.postData (package:wox/utils/wox_http_util.dart:36)
<asynchronous suspension>
#1      WoxApi.installPlugin (package:wox/api/wox_api.dart:45)
<asynchronous suspension>
#2      WoxSettingController.installPlugin (package:wox/modules/setting/wox_setting_controller.dart:105)
<asynchronous suspension>

2024-12-26 15:20:54.728 G0000484 b511a5fe-d58c-4170-a7c0-5ffac7e715fc [INF] [ UI] installing plugin: Sum Selection Numbers
2024-12-26 15:20:54.729 G0000485 9f0bc6f0-ecb3-410e-96e5-3d19623c60b1 [INF] [ UI] Posting data to http://localhost:53982/plugin/install
2024-12-26 15:20:54.730 G0000500 498276a6-a297-4e2b-9e18-83e71cb6279c [INF] [Wox] start to get plugin manifest from Wox Official Plugin Store(https://raw.githubusercontent.com/Wox-launcher/Wox/v2/store-plugin.json)
2024-12-26 15:20:54.750 G0000500 498276a6-a297-4e2b-9e18-83e71cb6279c [INF] [Wox] found 9 plugins from stores
2024-12-26 15:20:54.750 G0000500 498276a6-a297-4e2b-9e18-83e71cb6279c [INF] [Wox] start to install plugin Sum Selection Numbers(0.0.2)
2024-12-26 15:20:54.750 G0000500 498276a6-a297-4e2b-9e18-83e71cb6279c [ERR] [Wox] NODEJS runtime is not started, please start first
2024-12-26 15:20:54.751 G0000037 2a40bb89-1a5b-41c0-8a91-7ac6ee9327f8 [INF] [Wox] [SYS LOG] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: can't install plugin: NODEJS runtime is not started, please start first
#0      WoxHttpUtil.postData (package:wox/utils/wox_http_util.dart:36)
<asynchronous suspension>
#1      WoxApi.installPlugin (package:wox/api/wox_api.dart:45)
<asynchronous suspension>
#2      WoxSettingController.installPlugin (package:wox/modules/setting/wox_setting_controller.dart:105)
<asynchronous suspension>

2024-12-26 15:20:54.751 G0000486 9f0bc6f0-ecb3-410e-96e5-3d19623c60b1 [ERR] [ UI] Failed to post data, url=http://localhost:53982/plugin/install, data={id: bf145a9f-4976-4486-a671-d44eb64c7cd0}, err=Exception: can't install plugin: NODEJS runtime is not started, please start first, stacktrace=#0      WoxHttpUtil.postData (package:wox/utils/wox_http_util.dart:36)
<asynchronous suspension>
#1      WoxApi.installPlugin (package:wox/api/wox_api.dart:45)
<asynchronous suspension>
#2      WoxSettingController.installPlugin (package:wox/modules/setting/wox_setting_controller.dart:105)
<asynchronous suspension>

**Comment by qianlifeng** [comment]
please try the latest v2.beta.2

**Comment by salmanuc** [comment]
Same issue, using v2.beta.2

**Comment by qianlifeng** [comment]
Should be resolved in v2.beta.4. Will reopen if still exists.
