### ISSUE TITLE
Wox slow

### ISSUE THREAD

**Issue by rickmed** [Wox-launcher/Wox#412]
Version 1.1 is snappy. On this version, Wox freezes for a few ms on each typed character.

Build 1.2.603, Windows 10x64.
Please advice if is not the correct feedback format/channel.

**Comment by bao-qian** [comment]
1.1 or 1.2.603?

**Comment by rickmed** [comment]
I tested currently Build 1.2.603. Just saying that it feels slow compared to the much snappier version 1.1 of Wox.

**Comment by bao-qian** [comment]
Ok. What do you mean by "freezes for a few ms"?
Could you record a video? I recommend use ShareX to do this.

**Comment by rickmed** [comment]
Ended up restarting the machine and it fixed it. Will report back in case it is a wox issue and not a windows issue.

Congrats on the project.

**Comment by bao-qian** [comment]
Please star Wox if you like it.

**Comment by rickmed** [comment]
starred :)

**Comment by SMUsamaShah** [comment]
@happlebao 
It does become slow when launched after a while doing other tasks (VS, Eclipse etc). Using 1.2.613 (1.20 beta 2) on Windows 7 x64. 

It launched quickly and I typed `what` quickly and lifted my hand off the keyboard. First `w` appeared, than results of `w` appeared below, than remaining letters `h` `a` and `t`appeared one by one updating the drop down one by one respectively.

Next launch was instant, I could not _see_ the type and search process happening before my eyes.

**Comment by bao-qian** [comment]
@LifeH2O could you record a video ?

**Comment by SMUsamaShah** [comment]
@happlebao I wrote `poll` and then they appeared one by one. 
http://tinypic.com/player.php?v=2hpt9x1%3E&s=9
This was not as slow as I described earlier and I am unable to reproduce a video like that. But I can tell, it does become slow. 

I stopped using it and relied back on 'run' `win+R` as run was always faster than wox no matter how much load OS was bearing. Now started using it again. I already have everything installed and running in background as a service. May be we can use just that.

**Comment by happlebao** [comment]
thanks for video, I can confirm it.

of course <kbd>win</kbd>+<kbd>r</kbd> is faster than Wox, because there is no **searching**. And Wox support fuzzy match, e.g.vs15 for Visual Studio 2015.

for using running everything service, please open a separate issue.

**Comment by bao-qian** [comment]
- [x] use `Task` instead of `QueueUserWorkItem`
- [x] add `CancellationTokenSource` when updating result panel and executing query for all plugins
- [x] add async when updating result panel

**Comment by bao-qian** [comment]
@LifeH2O thanks for video, I can confirm it.

of course <kbd>win</kbd>+<kbd>r</kbd> is faster than Wox, because there is no **searching**. And Wox support fuzzy match, e.g. `vs15` for Visual Studio 2015.
<kbd>win</kbd>+<kbd>r</kbd> is usually used for executing cmd, you can type `>` to do that. That plugin also has a option to replace win+r in setting.

for using running everything service, please open a separate issue.

**Comment by eugenesvk** [comment]
I'm using **1.2.745** on Windows 10 x64 and would also like to confirm that it's a bit stuttering. Would be nice if delays in results display wouldn't affect the rate at which you type.
Here is my video as well (you can notice delay best when I hold backspace to remove search word around letters **se** in **se**ttings (since it's not influenced by my typing speed, I just hold backspace down)
https://github.com/eugenesvk/temp/commit/023102278f111639c56c602e8996ab82548d2a6f

**Comment by bao-qian** [comment]
@eugenesvk working on it, you will get some good news before next Monday.

**Comment by bao-qian** [comment]
Hi @rickmed @SMUsamaShah @eugenesvk 
please try again
https://ci.appveyor.com/project/happlebao/wox/build/1.2.866/artifacts

**Comment by eugenesvk** [comment]
Thanks, that's indeed snappier. There is still a slight dealy at the beginning (I guess when the number of matches is rather large), see e.g. this [video](https://github.com/eugenesvk/temp/blob/master/WoxSlowUpdate.mp4) — note when I start typing `sleep`, that's where the delay is most noticeable.
But still it's faster than it was before.

**Comment by bao-qian** [comment]
@eugenesvk yeah, there is still room for optimization when startup. but as you said, it's **slight** slow now, so I will optimize it in the next version.

**Comment by bao-qian** [comment]
@pohy I forgot to AT you for the new release.

**Comment by bao-qian** [comment]
- [x] use parallel linq + task to parse plugin config
- [x] use parallel foreach + task to init plugin
- [x] rewrite `getfileicon`, since it is pretty slow (http://stackoverflow.com/questions/2565885/net-read-binary-contents-of-lnk-file/2566008#2566008)
- [x] why `Preload 0 programs from cache` in the below logs? how about imagecache?

**Comment by SMUsamaShah** [comment]
@eugenesvk is right. It is faster but still sometimes typing lags behind the key presses.

**Comment by bao-qian** [comment]
@SMUsamaShah 
is it slow all the time or just initially?

**Comment by eugenesvk** [comment]
> is it slow all the time or just initially?

All the time. My video, for example, is a few hours past last restart.

**Comment by bao-qian** [comment]
What's your system setup? cpu model? ssd?

**Comment by eugenesvk** [comment]
Intel SSD 520 series, Intel Core i7-3770K, DDR3 SDRAM 16Gb
I don't have paths outside of SSD drive set in Wox catalog (system-wide everything service does have a fast HDD in its index, but when I search directly in everything it's ultra-fast search as well)

**Comment by bao-qian** [comment]
@eugenesvk did you feel it is faster when you type same query string (sleep) again?

**Comment by SMUsamaShah** [comment]
Got an exception when testing it. Sent the report

> Index was out of range. Must be non-negative and less than the size of the collection.
> Parameter name: index

I typed 'sleepe', noticed some lag so removed it than typed 'somethineasdfasdf ' quickly. Then selected this text and started typing 'asdfasdf' quickly. But instead of showing asdfasdf it suddenly showed crash message with 'somethineasdfasdf ' still written in wox bar.

**Comment by eugenesvk** [comment]
> did you feel it is faster when you type same query string (sleep) again?

Sorry, that's a tough one as it's hard to assess the level of delay. I am only certain that the delete test I mentioned above (when holding delete button there was a slowdown when only first couple of letters were left) is a bit faster now. I'm not certain whether the switch to sleep became faster or not.

**Comment by bao-qian** [comment]
@SMUsamaShah I think the report button will send it to previous maintainer instead of me.
Could you past your log to here? `Wox/Log`
It's it sth like this?

```
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Wox.ViewModel.ResultsViewModel.SelectNextResult() 
```

Did you pressed any of the following keys for that crash?
<kbd>ctrl</kbd><kbd>shift</kbd><kbd>up</kbd><kbd>down</kbd>

**Comment by SMUsamaShah** [comment]
```
2016-04-27 12:41:01.4532|INFO|Wox.Infrastructure.Logger.Log|Preload 0 programs from cache
2016-04-27 12:41:27.2459|FATAL|Wox.Infrastructure.Logger.Log|

```

```
## Exception
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   Source: mscorlib
   TargetAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
   TargetModule: CommonLanguageRuntimeLibrary
   TargetSite: Void ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Wox.ViewModel.ResultsViewModel.SelectPrevPage() in C:\projects\wox\Wox\ViewModel\ResultsViewModel.cs:line 172
   at Wox.MainWindow.OnPreviewKeyDown(Object sender, KeyEventArgs e) in C:\projects\wox\Wox\MainWindow.xaml.cs:line 268
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

```
## Environment

* Command Line: "D:\InstalledApps\wox\Wox.exe" 
* Timestamp: 2016-04-27T12:41:27.2064844+05:00
* IntPtr Length: 8
* System Version: Microsoft Windows NT 6.1.7601 Service Pack 1
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.5420 SP2
   * v3.0 3.0.30729.5420 SP2
   * v3.5 3.5.30729.5420 SP1
   * v4 Client 4.6.01055
   * v4 Full 4.6.01055
   * v4.0 Client 4.0.0.0

## Assemblies - Wox.exe

* Wox, Version=1.2.866.0, Culture=neutral, PublicKeyToken=null (D:\InstalledApps\wox\Wox.exe)
* Exceptionless, Version=1.5.2121.0, Culture=neutral, PublicKeyToken=fc181f0a46f65747 (D:\InstalledApps\wox\Exceptionless.dll)
* Wox.Infrastructure, Version=1.2.866.0, Culture=neutral, PublicKeyToken=null (D:\InstalledApps\wox\Wox.Infrastructure.dll)
* Wox.Core, Version=1.2.866.0, Culture=neutral, PublicKeyToken=null (D:\InstalledApps\wox\Wox.Core.dll)
* Wox.Plugin, Version=1.2.866.0, Culture=neutral, PublicKeyToken=null (D:\InstalledApps\wox\Wox.Plugin.dll)
* NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (D:\InstalledApps\wox\NLog.dll)
* Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (D:\InstalledApps\wox\Newtonsoft.Json.dll)
* Wox.Plugin.Caculator, Version=1.2.866.0, Culture=neutral, PublicKeyToken=null (D:\InstalledApps\wox\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
* YAMP, Version=1.4.0.22422, Culture=neutral, PublicKeyToken=null (D:\InstalledApps\wox\Plugins\Wox.Plugin.Caculator\YAMP.dll)
* Wox.Plugin.CMD, Version=1.2.866.0, Culture=neutral, PublicKeyToken=null (D:\InstalledApps\wox\Plugins\Wox.Plugin.CMD\Wox.Plugin.CMD.dll)
* WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (D:\InstalledApps\wox\WindowsInput.dll)
* Wox.Plugin.Color, Version=1.2.866.0, Culture=neutral, PublicKeyToken=null (D:\InstalledApps\wox\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
* Wox.Plugin.ControlPanel, Version=1.2.866.0, Culture=neutral, PublicKeyToken=null (D:\InstalledApps\wox\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
* Wox.Plugin.Everything, Version=1.2.866.0, Culture=neutral, PublicKeyToken=null (D:\InstalledApps\wox\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
* Wox.Plugin.Folder, Version=1.2.866.0, Culture=neutral, PublicKeyToken=null (D:\InstalledApps\wox\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
* Wox.Plugin.PluginIndicator, Version=1.2.866.0, Culture=neutral, PublicKeyToken=null (D:\InstalledApps\wox\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
* Wox.Plugin.PluginManagement, Version=1.2.866.0, Culture=neutral, PublicKeyToken=null (D:\InstalledApps\wox\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
* Wox.Plugin.Program, Version=1.2.866.0, Culture=neutral, PublicKeyToken=null (D:\InstalledApps\wox\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
* Wox.Plugin.Sys, Version=1.2.866.0, Culture=neutral, PublicKeyToken=null (D:\InstalledApps\wox\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
* Wox.Plugin.Url, Version=1.2.866.0, Culture=neutral, PublicKeyToken=null (D:\InstalledApps\wox\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
* Wox.Plugin.WebSearch, Version=1.2.866.0, Culture=neutral, PublicKeyToken=null (D:\InstalledApps\wox\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
* NAppUpdate.Framework, Version=0.3.2.0, Culture=neutral, PublicKeyToken=d1f1d1f19f9e5a56 (D:\InstalledApps\wox\NAppUpdate.Framework.dll)
* NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (D:\InstalledApps\wox\NHotkey.dll)
* NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (D:\InstalledApps\wox\NHotkey.Wpf.dll)
* Pinyin4Net, Version=2016.4.24.0, Culture=neutral, PublicKeyToken=null (D:\InstalledApps\wox\Pinyin4Net.dll)
* Wox.CrashReporter, Version=1.2.866.0, Culture=neutral, PublicKeyToken=null (D:\InstalledApps\wox\Wox.CrashReporter.dll)
* mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
* PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
* System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
* PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
* System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
* System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
* System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
* System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
* System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
* System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
* System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
* System.ServiceProcess, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceProcess\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.ServiceProcess.dll)
* PresentationFramework.Aero, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero.dll)
* System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
* PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll)
* PresentationFramework-SystemXmlLinq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXmlLinq\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXmlLinq.dll)
* PresentationFramework-SystemXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll)
* UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll)
```

---

I think I pressed <kbd>ctrl</kbd><kbd>shift</kbd><kbd>left arrow</kbd> to select 'somethineasdfasdf ' and started typing over it.

**Comment by bao-qian** [comment]
@SMUsamaShah @rickmed @eugenesvk @pohy
Hi, please try again.
there should be no more blocking.
I'd appreciate if you copy your logs (`%APPDATA%`\Wox\Logs`) to here after test
https://ci.appveyor.com/project/happlebao/wox/build/1.2.911/artifacts

@SMUsamaShah 
the bugs you mentioned also fixed in this version.

**Comment by eugenesvk** [comment]
Thanks for the fix! I can't notice any delays anymore. Hope they won't come back!
I'm not sure what those blocking issues are, so just attaching the logs FYI

Here are the logs (I see it references nonexisting folder `C:\projects\wox`)

```
2016-05-06 04:20:22.4484|INFO|Wox.App+<>c__DisplayClass11_0.<OnStartup>b__0|Preload 0 images from cache
2016-05-06 04:20:23.0679|INFO|Wox.Plugin.Program.Programs.Init|Preload 0 programs from cache
2016-05-06 04:26:35.7053|INFO|Wox.App+<>c__DisplayClass11_0.<OnStartup>b__0|Preload 200 images from cache
2016-05-06 04:26:36.1377|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|Program : Can't create instance
2016-05-06 04:26:36.1377|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|
2016-05-06 04:26:36.1377|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|Exception has been thrown by the target of an invocation.
2016-05-06 04:26:36.1433|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Wox.Core.Plugin.PluginsLoader.CSharpPlugins(List`1 source) in C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:line 49
2016-05-06 04:36:23.9938|INFO|Wox.App+<>c__DisplayClass11_0.<OnStartup>b__0|Preload 200 images from cache
2016-05-06 04:36:24.4254|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|Program : Can't create instance
2016-05-06 04:36:24.4254|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|
2016-05-06 04:36:24.4254|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|Exception has been thrown by the target of an invocation.
2016-05-06 04:36:24.4254|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Wox.Core.Plugin.PluginsLoader.CSharpPlugins(List`1 source) in C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:line 49
```

**Comment by bao-qian** [comment]
what do you mean by 

> I see it references nonexisting folder C:\projects\wox
> ??

**Comment by eugenesvk** [comment]
I mean e.g. this line in the log I quoted above
`at Wox.Core.Plugin.PluginsLoader.CSharpPlugins(List`1 source) in C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:line 49`

**Comment by bao-qian** [comment]
@eugenesvk  that's probably just a old log. could you delete that file, and re-launch wox?

**Comment by eugenesvk** [comment]
I don't have that file :) I don't even have that folder. That's why I was surprised to see it.
I thought this was some path hard-coded in your code.

**Comment by bao-qian** [comment]
sorry, what I mean is delete the old log and 

then re launch wox  

then upload new log

**Comment by eugenesvk** [comment]
Ah, ok. So far a fresh log has none of these errors, will post here if they appear again.

**Comment by bao-qian** [comment]
seems this problem is resolved now, reopen it if you still have this issue.

**Comment by SMUsamaShah** [comment]
It is now fast and typing is not blocked. There are icon drawing issues. e.g. On typing something, first we get a text list of results and then one by one their respective icons are drawn one by one from top to bottom. This does not look good. Even when it is now faster, the late drawing of icons make it appear slow. Like everything, you can probably place default icons for folders and files instantly and update them later.

**Comment by happlebao** [comment]
Idea is good! Could you open a new issue?
