### ISSUE TITLE
Instant crash whenever I open it

### ISSUE THREAD

**Issue by tritonality** [Wox-launcher/Wox#416]
Happens on 1.2.0 beta and 1.1.1

Tried moving the folder to different locations.  Instantly crashes on startup

Sometimes (can't really understand why) it will open and function normally.  Seems to be based on system restarts.
## Exception

```
System.NullReferenceException: Object reference not set to an instance of an object.
   Source: Wox
   TargetAssembly: Wox, Version=1.1.1.295, Culture=neutral, PublicKeyToken=null
   TargetModule: Wox.exe
   TargetSite: Void Execute(System.Collections.Generic.IList`1[System.String])
   at Wox.CommandArgs.CommandArgsFactory.Execute(IList`1 args) in c:\projects\wox\Wox\CommandArgs\CommandArgsFactory.cs:line 32
   at Wox.App.OnActivate(IList`1 args) in c:\projects\wox\Wox\App.xaml.cs:line 45
   at Wox.Helper.SingleInstance`1.ActivateFirstInstance(IList`1 args) in c:\projects\wox\Wox\Helper\SingleInstance.cs:line 447
   at Wox.Helper.SingleInstance`1.ActivateFirstInstanceCallback(Object arg) in c:\projects\wox\Wox\Helper\SingleInstance.cs:line 430
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)

```
## Environment

```
* Command Line: "C:\Program Files\Wox-1.1.1\Wox.exe" 
* Exception Handle: System.Windows.Application.DispatcherUnhandledException
* Timestamp: 2015-12-04T22:17:24.2057735-08:00
* IntPtr Length: 8
* System Version: Microsoft Windows NT 6.1.7601 Service Pack 1
* CLR Version: 2.0.50727.5485
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.5420 SP2
   * v3.0 3.0.30729.5420 SP2
   * v3.5 3.5.30729.5420 SP1
   * v4 Client 4.5.51209
   * v4 Full 4.5.51209
   * v4.0 Client 4.0.0.0
```
## Assemblies - Wox.exe

```
* Wox, Version=1.1.1.295, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.1.1\Wox.exe)
* Wox.Plugin, Version=1.1.1.295, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.1.1\Wox.Plugin.dll)
* Wox.Infrastructure, Version=1.1.1.295, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.1.1\Wox.Infrastructure.dll)
* WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Program Files\Wox-1.1.1\WindowsInput.dll)
* NHotkey, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.1.1\NHotkey.dll)
* Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Program Files\Wox-1.1.1\Newtonsoft.Json.dll)
* log4net, Version=1.2.13.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a (C:\Program Files\Wox-1.1.1\log4net.dll)
* mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorlib.dll)
* PresentationFramework, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\assembly\GAC_MSIL\PresentationFramework\3.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* WindowsBase, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\assembly\GAC_MSIL\WindowsBase\3.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System\2.0.0.0__b77a5c561934e089\System.dll)
* PresentationCore, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\assembly\GAC_64\PresentationCore\3.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.Core\3.5.0.0__b77a5c561934e089\System.Core.dll)
* System.Runtime.Remoting, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.Runtime.Remoting\2.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.Windows.Forms\2.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
* System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\assembly\GAC_MSIL\System.Drawing\2.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
* System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\assembly\GAC_MSIL\System.Configuration\2.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.Xml\2.0.0.0__b77a5c561934e089\System.Xml.dll)
* PresentationFramework.Classic, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\assembly\GAC_MSIL\PresentationFramework.Classic\3.0.0.0__31bf3856ad364e35\PresentationFramework.Classic.dll)
* System.ComponentModel.DataAnnotations, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\assembly\GAC_MSIL\System.ComponentModel.DataAnnotations\3.5.0.0__31bf3856ad364e35\System.ComponentModel.DataAnnotations.dll)
* System.Runtime.Serialization, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.Runtime.Serialization\3.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
* System.Xml.Linq, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.Xml.Linq\3.5.0.0__b77a5c561934e089\System.Xml.Linq.dll)
* System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_64\System.Data\2.0.0.0__b77a5c561934e089\System.Data.dll)
* System.Web, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\assembly\GAC_64\System.Web\2.0.0.0__b03f5f7f11d50a3a\System.Web.dll)
```
## Modules - Wox

```
* C:\Program Files\Wox-1.1.1\Wox.exe (Wox, 1.1.1.295, Wox, 1.1.1.295, ), 0x0000000001340000
* C:\Windows\SYSTEM32\ntdll.dll (NT Layer DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x0000000076F90000
* C:\Windows\SYSTEM32\MSCOREE.DLL (Microsoft .NET Runtime Execution Engine, 4.0.40305.0 (Main.040305-0000), Microsoft® .NET Framework, 4.0.40305.0, Microsoft Corporation), 0x000007FEF8660000
* C:\Windows\system32\KERNEL32.dll (Windows NT BASE API Client DLL, 6.1.7601.18015 (win7sp1_gdr.121129-1432), Microsoft® Windows® Operating System, 6.1.7601.18015, Microsoft Corporation), 0x0000000076AF0000
* C:\Windows\system32\KERNELBASE.dll (Windows NT BASE API Client DLL, 6.1.7601.18015 (win7sp1_gdr.121129-1432), Microsoft® Windows® Operating System, 6.1.7601.18015, Microsoft Corporation), 0x000007FEFD4A0000
* C:\Windows\system32\ADVAPI32.dll (Advanced Windows 32 Base API, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFDC90000
* C:\Windows\system32\msvcrt.dll (Windows NT CRT DLL, 7.0.7601.17744 (win7sp1_gdr.111215-1535), Microsoft® Windows® Operating System, 7.0.7601.17744, Microsoft Corporation), 0x000007FEFD810000
* C:\Windows\SYSTEM32\sechost.dll (Host for SCM/SDDL/LSA Lookup APIs, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFE210000
* C:\Windows\system32\RPCRT4.dll (Remote Procedure Call Runtime, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFD950000
* C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll (Microsoft .NET Runtime Execution Engine, 4.0.30319.34209 built by: FX452RTMGDR, Microsoft® .NET Framework, 4.0.30319.34209, Microsoft Corporation), 0x000007FEF8380000
* C:\Windows\system32\SHLWAPI.dll (Shell Light-weight Utility Library, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFE3C0000
* C:\Windows\system32\GDI32.dll (GDI Client DLL, 6.1.7601.18577 (win7sp1_gdr.140822-1508), Microsoft® Windows® Operating System, 6.1.7601.18577, Microsoft Corporation), 0x000007FEFE060000
* C:\Windows\system32\USER32.dll (Multi-User Windows USER API Client DLL, 6.1.7601.17514 (win7sp1_rtm.101119-1850), Microsoft® Windows® Operating System, 6.1.7601.17514, Microsoft Corporation), 0x0000000076890000
* C:\Windows\system32\LPK.dll (Language Pack, 6.1.7601.18177 (win7sp1_gdr.130605-1534), Microsoft® Windows® Operating System, 6.1.7601.18177, Microsoft Corporation), 0x000007FEFE100000
* C:\Windows\system32\USP10.dll (Uniscribe Unicode script processor, 1.0626.7601.18454 (win7sp1_gdr.140424-1533), Microsoft(R) Uniscribe Unicode script processor, 1.0626.7601.18454, Microsoft Corporation), 0x000007FEFE440000
* C:\Windows\system32\IMM32.DLL (Multi-User Windows IMM32 API Client DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFE0D0000
* C:\Windows\system32\MSCTF.dll (MSCTF Server DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFE2B0000
* C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorwks.dll (Microsoft .NET Runtime Common Language Runtime - WorkStation, 2.0.50727.5485 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5485, Microsoft Corporation), 0x000007FEF7930000
* C:\Windows\WinSxS\amd64_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.6195_none_88e41e092fab0294\MSVCR80.dll (Microsoft® C Runtime Library, 8.00.50727.6195, Microsoft® Visual Studio® 2005, 8.00.50727.6195, Microsoft Corporation), 0x000000006E9F0000
* C:\Windows\system32\shell32.dll (Windows Shell Common Dll, 6.1.7601.17514 (win7sp1_rtm.101119-1850), Microsoft® Windows® Operating System, 6.1.7601.17514, Microsoft Corporation), 0x000007FEFE510000
* C:\Windows\system32\ole32.dll (Microsoft OLE for Windows, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFDA80000
* C:\Windows\system32\profapi.dll (User Profile Basic API, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFD3F0000
* C:\Windows\assembly\NativeImages_v2.0.50727_64\mscorlib\fe6ac93181b40a571892e14bfb9d65f2\mscorlib.ni.dll (Microsoft Common Language Runtime Class Library, 2.0.50727.5485 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5485, Microsoft Corporation), 0x000007FEF6A50000
* C:\Windows\system32\CRYPTBASE.dll (Base cryptographic API DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFD320000
* C:\Windows\system32\uxtheme.dll (Microsoft UxTheme Library, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFB9D0000
* C:\Program Files (x86)\Direct Folders\dfh64.dll (, , , , ), 0x0000000000440000
* C:\Windows\system32\OLEAUT32.dll (, 6.1.7601.18679, , 6.1.7601.18679, Microsoft Corporation), 0x000007FEFDDA0000
* C:\Windows\system32\OLEACC.dll (Active Accessibility Core Component, 7.0.0.0 (win7sp1_gdr.110826-1504), Microsoft® Windows® Operating System, 6.1.7601.17676, Microsoft Corporation), 0x000007FEF99A0000
* C:\Windows\assembly\NativeImages_v2.0.50727_64\System\c7fb84e825f6604d7f4684ab96cbd148\System.ni.dll (.NET Framework, 2.0.50727.5485 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5485, Microsoft Corporation), 0x000007FEF5E90000
* C:\Windows\assembly\NativeImages_v2.0.50727_64\WindowsBase\a112eb3399caef2b6a4c9b995fe1ea3d\WindowsBase.ni.dll (WindowsBase.dll, 3.0.6920.5453 built by: Win7SP1GDR, Microsoft® .NET Framework, 3.0.6920.5453, Microsoft Corporation), 0x000007FED6F60000
* C:\Windows\assembly\NativeImages_v2.0.50727_64\PresentationCore\85f72cca29c67444ed2716b0cbcb1eae\PresentationCore.ni.dll (PresentationCore.dll, 3.0.6920.5453 built by: Win7SP1GDR, Microsoft® .NET Framework, 3.0.6920.5453, Microsoft Corporation), 0x000007FED4B80000
* C:\Windows\assembly\NativeImages_v2.0.50727_64\PresentationFramewo#\fd2485b871dd53f0ee4ef54b7e602d92\PresentationFramework.ni.dll (PresentationFramework.dll, 3.0.6920.5453 built by: Win7SP1GDR, Microsoft® .NET Framework, 3.0.6920.5453, Microsoft Corporation), 0x000007FED3920000
* C:\Windows\Microsoft.NET\Framework64\v3.0\WPF\wpfgfx_v0300.dll (wpfgfx_v0300.dll, 3.0.6920.5453 built by: Win7SP1GDR, Microsoft® .NET Framework, 3.0.6920.5453, Microsoft Corporation), 0x00000000677B0000
* C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Core\e388e09d57ab6d56558f3b32543a34ba\System.Core.ni.dll (.NET Framework, 3.5.30729.5420 built by: Win7SP1, Microsoft® .NET Framework, 3.5.30729.5420, Microsoft Corporation), 0x000007FEF5B10000
* C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorjit.dll (Microsoft .NET Runtime Just-In-Time Compiler, 2.0.50727.5467 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5467, Microsoft Corporation), 0x000007FEF68C0000
* C:\Windows\system32\SspiCli.dll (Security Support Provider Interface, 6.1.7601.18719 (win7sp1_gdr.150114-2007), Microsoft® Windows® Operating System, 6.1.7601.18719, Microsoft Corporation), 0x000007FEFD290000
* C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Runtime.Remo#\013d86a99e2d1f9a082431d654905ca7\System.Runtime.Remoting.ni.dll (Microsoft .NET Runtime Object Remoting, 2.0.50727.5488 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5488, Microsoft Corporation), 0x000007FED8050000
* C:\Windows\system32\CRYPTSP.dll (Cryptographic Service Provider API, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFCCC0000
* C:\Windows\system32\rsaenh.dll (Microsoft Enhanced Cryptographic Provider, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFC9C0000
* C:\Windows\system32\RpcRtRemote.dll (Remote RPC Extension, 6.1.7601.17514 (win7sp1_rtm.101119-1850), Microsoft® Windows® Operating System, 6.1.7601.17514, Microsoft Corporation), 0x000007FEFD3D0000
* C:\Windows\system32\dwmapi.dll (Microsoft Desktop Window Manager API, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFBCD0000
* C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Drawing\20dbd669c42888d4bf4949279ecaec94\System.Drawing.ni.dll (.NET Framework, 2.0.50727.5483 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5483, Microsoft Corporation), 0x000007FEE6A70000
* C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Windows.Forms\19bfbbbe2ebf4db54647f4aed0f3c443\System.Windows.Forms.ni.dll (.NET Framework, 2.0.50727.5483 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5483, Microsoft Corporation), 0x000007FEE59D0000
* C:\Program Files\Wox-1.1.1\Wox.Plugin.dll (Wox.Plugin, 1.1.1.295, Wox.Plugin, 1.1.1.295, ), 0x0000000068E20000
* C:\Program Files\Wox-1.1.1\Wox.Infrastructure.dll (Wox.Infrastructure, 1.1.1.295, Wox.Infrastructure, 1.1.1.295, ), 0x00000000676F0000
* C:\Program Files\Wox-1.1.1\WindowsInput.dll (WindowsInput, 1.0.4.0, WindowsInput, 1.0.4.0, michaelnoonan), 0x0000000068E10000
* C:\Program Files\Wox-1.1.1\NHotkey.dll (NHotkey, 1.1.0.0, NHotkey, 1.1.0.0, ), 0x0000000069940000
* C:\Windows\system32\psapi.dll (Process Status Helper, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x0000000077160000
* C:\Windows\system32\urlmon.dll (OLE32 Extensions for Win32, 9.00.8112.16421 (WIN7_IE9_RTM.110308-0330), Windows® Internet Explorer, 9.00.8112.16421, Microsoft Corporation), 0x0000000076C10000
* C:\Windows\system32\iertutil.dll (Run time utility for Internet Explorer, 9.00.8112.16609 (WIN7_IE9_GDR.150113-1802), Windows® Internet Explorer, 9.00.8112.16609, Microsoft Corporation), 0x0000000076D70000
* C:\Windows\system32\WININET.dll (Internet Extensions for Win32, 9.00.8112.16421 (WIN7_IE9_RTM.110308-0330), Windows® Internet Explorer, 9.00.8112.16421, Microsoft Corporation), 0x0000000076990000
* C:\Windows\system32\Normaliz.dll (Unicode Normalization DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x0000000077150000
* C:\Windows\system32\WindowsCodecs.dll (Microsoft Windows Codecs Library, 6.2.9200.17226 (win8_gdr.150108-1509), Microsoft® Windows® Operating System, 6.2.9200.17226, Microsoft Corporation), 0x000007FEFB440000
* C:\Windows\system32\mscms.dll (Microsoft Color Matching System DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEF9F00000
* C:\Windows\system32\USERENV.dll (Userenv, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFC730000
* C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Configuration\8b936558407ab33fd18006f6774034a8\System.Configuration.ni.dll (System.Configuration.dll, 2.0.50727.5483 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5483, Microsoft Corporation), 0x000007FED67F0000
* C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Xml\d09a5530f1283b469957bf146e2f4d65\System.Xml.ni.dll (.NET Framework, 2.0.50727.5485 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5485, Microsoft Corporation), 0x000007FED2BC0000
* C:\Windows\system32\WindowsCodecsExt.dll (Microsoft Windows Codecs Extended Library, 6.2.9200.16492 (win8_gdr_oobssr.130113-0015), Microsoft® Windows® Operating System, 6.2.9200.16492, Microsoft Corporation), 0x000007FEE0B60000
* C:\Windows\system32\icm32.dll (Microsoft Color Management Module (CMM), 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFA4C0000
* C:\Windows\assembly\NativeImages_v2.0.50727_64\PresentationFramewo#\98a441d50ecd23c14c25f64e8aaf98cc\PresentationFramework.Classic.ni.dll (PresentationFramework.Classic.dll, 3.0.6920.4902 built by: NetFXw7, Microsoft® .NET Framework, 3.0.6920.4902, Microsoft Corporation), 0x000007FEE1770000
* C:\Windows\system32\d3d9.dll (Direct3D 9 Runtime, 6.1.7601.17514 (win7sp1_rtm.101119-1850), Microsoft® Windows® Operating System, 6.1.7601.17514, Microsoft Corporation), 0x000007FEEAC70000
* C:\Windows\system32\VERSION.dll (Version Checking and File Installation Libraries, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFC6D0000
* C:\Windows\system32\d3d8thk.dll (Microsoft Direct3D OS Thunk Layer, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEEAC60000
* C:\Windows\system32\nvd3dumx.dll (NVIDIA WDDM D3D Driver, Version 355.98 , 10.18.13.5598, NVIDIA Windows WDDM D3D driver, 10.18.13.5598, NVIDIA Corporation), 0x000007FED1CF0000
* C:\Program Files\Wox-1.1.1\Newtonsoft.Json.dll (Json.NET .NET 3.5, 6.0.5.17707, Json.NET, 6.0.5.17707, Newtonsoft), 0x0000000068CE0000
* C:\Windows\assembly\NativeImages_v2.0.50727_64\System.ComponentMod#\421b85a4480fd929d60471489b6bc7ef\System.ComponentModel.DataAnnotations.ni.dll (System.ComponentModel.DataAnnotations.dll, 3.5.30729.5420, Microsoft® .NET Framework, 3.5.30729.5420, Microsoft Corporation), 0x000007FEE1ED0000
* C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Runtime.Seri#\5015b90fbd31c9ba4fff989b2c79711b\System.Runtime.Serialization.ni.dll (System.Runtime.Serialization.dll, 3.0.4506.5463 (Win7SP1GDR.030729-5400), Microsoft® .NET Framework, 3.0.4506.5463, Microsoft Corporation), 0x000007FED3620000
* C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Xml.Linq\afac5f7989224ed00526a8ec76defb11\System.Xml.Linq.ni.dll (.NET Framework, 3.5.30729.5420 built by: Win7SP1, Microsoft® .NET Framework, 3.5.30729.5420, Microsoft Corporation), 0x000007FED81C0000
* C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Data\326df77841f23d0e0039374a7d233416\System.Data.ni.dll (.NET Framework, 2.0.50727.5483 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5483, Microsoft Corporation), 0x000007FED0C10000
* C:\Windows\assembly\GAC_64\System.Data\2.0.0.0__b77a5c561934e089\System.Data.dll (.NET Framework, 2.0.50727.5483 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5483, Microsoft Corporation), 0x0000000055390000
* C:\Windows\system32\WS2_32.dll (Windows Socket 2.0 32-Bit DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFD7C0000
* C:\Windows\system32\NSI.dll (NSI User-mode interface DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFDD90000
* C:\Windows\system32\CRYPT32.dll (Crypto API32, 6.1.7601.18526 (win7sp1_gdr.140706-1506), Microsoft® Windows® Operating System, 6.1.7601.18526, Microsoft Corporation), 0x000007FEFD510000
* C:\Windows\system32\MSASN1.dll (ASN.1 Runtime APIs, 6.1.7601.17514 (win7sp1_rtm.101119-1850), Microsoft® Windows® Operating System, 6.1.7601.17514, Microsoft Corporation), 0x000007FEFD490000
* C:\Windows\Microsoft.NET\Framework64\v2.0.50727\diasymreader.dll (Dia based SymReader, 8.0.50727.5483 (Win7SP1GDR.050727-5400), Microsoft® Visual Studio® 2005, 8.0.50727.5483, Microsoft Corporation), 0x000007FEE44E0000
* C:\Program Files\Wox-1.1.1\log4net.dll (Apache log4net for .NET Framework 2.0, 1.2.13.0, log4net, 1.2, The Apache Software Foundation), 0x0000000068DC0000
* C:\Windows\system32\PresentationNative_v0300.dll (PresentationNative_v0300.dll, 3.0.6920.4902 built by: NetFXw7, Microsoft® .NET Framework, 3.0.6920.4902, Microsoft Corporation), 0x000000005B540000
* C:\Windows\system32\msctfui.dll (MSCTFUI Server DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEE1010000
* C:\Windows\system32\WINMM.dll (MCI API DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEF9EC0000
* C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Web\ddc3c337f9c115b46984748c7f8467b1\System.Web.ni.dll (System.Web.dll, 2.0.50727.5483 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5483, Microsoft Corporation), 0x000007FECBB60000
* C:\Windows\system32\powrprof.dll (Power Profile Helper DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFBD60000
* C:\Windows\system32\SETUPAPI.dll (Windows Setup API, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFDE80000
* C:\Windows\system32\CFGMGR32.dll (Configuration Manager DLL, 6.1.7601.17514 (win7sp1_rtm.101119-1850), Microsoft® Windows® Operating System, 6.1.7601.17514, Microsoft Corporation), 0x000007FEFD740000
* C:\Windows\system32\DEVOBJ.dll (Device Information Set DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFD720000
```
## Threads - 11

```
* 13140, Running Normal, Started: 12/4/2015 22:12:48, StartAddress: 0x0000000076FBC520
* 12792, Wait Normal, Started: 12/4/2015 22:12:48, StartAddress: 0x0000000076FBC520
* 12048, Wait Highest, Started: 12/4/2015 22:12:48, StartAddress: 0x0000000076FBC520
* 8340, Wait Normal, Started: 12/4/2015 22:12:48, StartAddress: 0x0000000076FBC520
* 11124, Wait Normal, Started: 12/4/2015 22:12:48, StartAddress: 0x0000000076FBC520
* 13220, Wait Normal, Started: 12/4/2015 22:12:48, StartAddress: 0x0000000076FBC520
* 8696, Wait Normal, Started: 12/4/2015 22:12:48, StartAddress: 0x0000000076FBC520
* 13044, Wait Normal, Started: 12/4/2015 22:12:48, StartAddress: 0x0000000076FBC520
* 11224, Wait Normal, Started: 12/4/2015 22:12:48, StartAddress: 0x0000000076FBC520
* 12212, Wait Normal, Started: 12/4/2015 22:12:48, StartAddress: 0x0000000076FBC520
* 13700, Wait Normal, Started: 12/4/2015 22:17:24, StartAddress: 0x0000000076FBC520
```

**Comment by bao-qian** [comment]
Hi, Thanks for your support and feedback.
1. As specific in [installation](https://github.com/Wox-launcher/Wox#installation), you should put wox under **user** folder. (this limit will be removed by the end of this month)
2. The error report is for 1.1 not 1.2
