### ISSUE TITLE
Wox crashes when Program plugin is selected

### ISSUE THREAD

**Issue by eugenesvk** [Wox-launcher/Wox#559]
1. Wox version 1.2.805
2. Please describe the steps to **reproduce** the bug
- Open Wox
- Go to `Plugin`
- Select `Program`
- Enjoy an empty window `Wox got an error`

The thing is, I've opened this plugin once before to try to add a custom location, but now it crashes all the time. Also, I've tried the same thing when all the addons are disabled (except for the **program** one, which I can't disable because I can't select it)
1. Please provide Windows version **10.0.10586**
2. Please provide Exception info if you have.
   Don't know where to get them, but see logs below
3. Please provide logs from `Wox\Logs` if you have.
   https://gist.github.com/eugenesvk/2c8545bf6cbdb45f7b600ea0473cb576
4. Please provide screenshot if you have. See before and after crash
   ![wox 1 pre-crash](https://cloud.githubusercontent.com/assets/12956286/14584272/a542ee6a-0446-11e6-87c0-3430a4fcc1af.PNG)
   ![wox 2 crash](https://cloud.githubusercontent.com/assets/12956286/14584273/a543da64-0446-11e6-8a50-d741ac8ec19e.PNG)

**Comment by eugenesvk** [comment]
This happens after I try to add one simple folder to index, here is my `settings_plugin_program.json` from `Wox\Config\` folder (the error goes away as soon as I delete this file, but then I can't use Wox for its primary purpose - to launch apps wherever they are :(

```
{
  "ProgramSources": [
    {
      "Location": "C:\\ProgramData\\Microsoft\\Windows\\Start Menu",
      "Type": "FileSystemProgramSource",
      "BonusPoints": 0,
      "Enabled": true,
      "Suffixes": [
        "lnk"
      ],
      "MaxDepth": 1,
      "Meta": null
    }
  ],
  "ProgramSuffixes": [
    "bat",
    "appref-ms",
    "exe",
    "lnk"
  ],
  "EnableStartMenuSource": true,
  "EnableRegistrySource": true
}
```

**Comment by eugenesvk** [comment]
By the way, this doesn't seem to happen in the latest release `v1.2.0-beta.2`, so I'll switch back to it meanwhile.
The latest release where I had it working was `Wox-1.2.745`, after this the app would either crash on launch or crashed when I went to view the plugin (I copy&pasted the settings folder, which had already some paths preset for this addon)

**Comment by lances101** [comment]
@eugenesvk, from your last message I did not understand if you have tried launching `1.2.805` with an empty settings folder. It could be possible that there is some incompatibility in the config after the upgrade. I've tried reproducing your error, but apparently I cannot recreate the same situation since I don't get the error message... 

Please try backuping your `Wox/Config` folder, clearing it and try to reproduce the error with `1.2.805`.

**Comment by eugenesvk** [comment]
Yes, I have tried to set it up fresh — same thing, the newest version can't have any paths in there. Will try again just to make sure.

**Comment by bao-qian** [comment]
I'm sorry, try use 1.2.802. The top version is not the stable build, it's a pr. It's confuse, because we don't have a server to put only stable build.

**Comment by eugenesvk** [comment]
Yes, I can reproduce it with the latest green build Wox-1.2.805

**Comment by eugenesvk** [comment]
1.2.802 has the same issue — a fresh version crashes whenever I add a path to that plugin.
Here is the log
https://gist.github.com/eugenesvk/7ad047a6300b977fce30aee3d2982b55

**Comment by lances101** [comment]
Sorry, @eugenesvk. I was not trying to actually add anything to the config before, my bad.

Converter for UI is trying to parse an array to a string. @happlebao, the way I see it being fixed is adding an extra converter for string arrays that outputs a single string (since that is what is intended from what I can understand) 

#553 is related to this.

**Comment by bao-qian** [comment]
hi @eugenesvk 
thanks for feedback.
new build is out, take a look: https://github.com/Wox-launcher/Wox/releases/tag/v1.2.857
please star this project if you like it.

**Comment by eugenesvk** [comment]
Stared it a while ago already.
It's much better now that it doesn't crash, but it's still buggy

1)  It doesn't allow editing of paths, once I click **Edit**, I get the following exception (also sent it via internal bug report)
`Object reference not set to an instance of an object.`
Exception Type: `System.NullReferenceException`
Source: `Wox.Plugin.Program`
Stack Trace

```
   at Wox.Plugin.Program.AddProgramSource..ctor(ProgramSource edit, Settings settings) in C:\projects\wox\Plugins\Wox.Plugin.Program\AddProgramSource.xaml.cs:line 25
   at Wox.Plugin.Program.ProgramSetting.btnEditProgramSource_OnClick(Object sender, RoutedEventArgs e) in C:\projects\wox\Plugins\Wox.Plugin.Program\ProgramSetting.xaml.cs:line 76
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

2) Suffixes aren't editable, they're are always shown as default `batappref-msexelnk` (in the interface without any separators, in json settings separated properly)

**Comment by bao-qian** [comment]
Thanks for report. will be fixed within 30 minutes :)

**Comment by eugenesvk** [comment]
That's too fast :)

**Comment by bao-qian** [comment]
@eugenesvk as I said :)
https://ci.appveyor.com/project/happlebao/wox/build/1.2.864/artifacts
