### ISSUE TITLE
最新的1.2.857添加Program目录不闪退了，但编辑报错

### ISSUE THREAD

**Issue by mokeyjay** [Wox-launcher/Wox#569]
版本：1.2.857
重现：点击程序（Program）插件，随意添加一个目录，添加成功后选中该目录点击编辑按钮，报错
系统：Win7 x64旗舰版

System.NullReferenceException
Wox.Plugin.Program
   at Wox.Plugin.Program.AddProgramSource..ctor(ProgramSource edit, Settings settings) in C:\projects\wox\Plugins\Wox.Plugin.Program\AddProgramSource.xaml.cs:line 25
   at Wox.Plugin.Program.ProgramSetting.btnEditProgramSource_OnClick(Object sender, RoutedEventArgs e) in C:\projects\wox\Plugins\Wox.Plugin.Program\ProgramSetting.xaml.cs:line 76
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
试一下 https://ci.appveyor.com/project/happlebao/wox/build/artifacts

> 缝缝补补又三年

**Comment by bao-qian** [comment]
没问题说一声，我放 release
有问题更要说一声。。。

**Comment by mokeyjay** [comment]
喵喵喵

用Wox启动phpStudy会报错说数据不完整，不过这个提示框应该是phpstudy弹的。直接双击启动或用Listary启动正常……不知你们是如何启动exe的呢？

**Comment by mokeyjay** [comment]
phpStudy http://www.phpstudy.net/

可以在虚拟机里装一个调试一下看为什么启动它会报错……
这是绿色的卸载起来也很方便

**Comment by bao-qian** [comment]
@mokeyjay 你传一个上来，我这下太慢。。。

**Comment by bao-qian** [comment]
#327 possible related

**Comment by bao-qian** [comment]
这程序对当前工作目录做了假设，这就是它【绿色】的来源。。。
你开个终端，然后在不是它解压目录的目录下运行，一样报错。。。

不要用这种玩意了，在 win 下搭这种服务器准没好事，我推荐你个东西
用 vagrant 一键安装 ubuntu，
然后用 phpstorm 远程调试部署

ref： 
https://confluence.jetbrains.com/display/PhpStorm/Configuring+PhpStorm+to+work+with+a+VM
https://confluence.jetbrains.com/display/PhpStorm/Configuring+a+Vagrant+VM+for+Debugging

**Comment by mokeyjay** [comment]
刚才练车去了不好意思

QAQ感谢大佬耐心测试&回复

实际上phpStudy这种玩意儿搭服务器肯定是不可能的，主要是为了本地测试而已
虽然我的公司的服务器是PHP 5.5，但偶尔接些外包，对方的PHP版本不固定，我甚至见过5.1的。为了开发方便，才选择了phpStudy这种可以灵活切换版本的环境

至于其他情况下是有用Vmware内的Ubuntu的ww

你这么一说我想起来用Wox打开cmd时工作目录也在Wox目录下了。感觉这样不太好，可能还会影响到除phpStudy外的不少软件
建议启动程序前修改一下当前目录？例如Listary就能够正常启动phpStudy

**Comment by bao-qian** [comment]
完工
https://ci.appveyor.com/project/happlebao/wox/build/1.2.859
