### ISSUE TITLE
Existing installed python questions

### ISSUE THREAD

**Issue by roose** [Wox-launcher/Wox#587]
1. What about people who don't have installed python?
2. On my system Python installed in path C:\Python27, in Python Directory dialog I don't have the possibility to choose it, only in Program Files
3. If I add python path to settings.json, python plugins still not working

**Comment by iEverX** [comment]
+1
I can't select my python installed in programe files (x86) too

**Comment by bao-qian** [comment]
1 installer will include Python and everything

**Comment by bao-qian** [comment]
my fault, I forgot to delete test code.

**Comment by bao-qian** [comment]
try this one:
https://github.com/Wox-launcher/Wox/releases/tag/v1.2.900

**Comment by bao-qian** [comment]
Thanks for report.
reopen it if you can't solve the problem

**Comment by bao-qian** [comment]
> By the way, for python dependency could you please allow a custom folder outside of the Program Files folder? I know I can just copy&paste my Conda install folder, but then I don't get the positive feedback that's it's set and I should restart my Wox and also it seems to just reset itself on restart.
> Everything seems to be working fine without any additional config
> Thank you!
> @eugenesvk

**Comment by bao-qian** [comment]
@eugenesvk
it should be possible, let me test it again

**Comment by bao-qian** [comment]
use %PATH% for temp fix

**Comment by bao-qian** [comment]
@eugenesvk
try this one: https://ci.appveyor.com/project/happlebao/wox/build/1.2.916/artifacts

**Comment by eugenesvk** [comment]
Hm, I see that the setting is saved in the `Settings.json` file
in `"PythonDirectory": "C:\\Dev\\Python\\Miniconda3",`
However, it's not showing up in the `Python Directory` settings of the app.

When I try the embedded HelloWorld plugin I get some errors, but maybe I'm just not doing the test properly — what would be the proper way to test that Wox reads my python properly?

![wox python](https://cloud.githubusercontent.com/assets/12956286/15063998/06d45626-1358-11e6-9ee5-6b39fb228f2e.png)
![wox python2](https://cloud.githubusercontent.com/assets/12956286/15064011/2a4acd1a-1358-11e6-8117-0e40af1c8d39.png)

**Comment by bao-qian** [comment]
correct:
![image](https://cloud.githubusercontent.com/assets/1169912/15064042/c6e5f1e2-1347-11e6-8389-adaec4eb662d.png)

**Comment by bao-qian** [comment]
yeah the python directory setting is still problematic...
try add python directory to %PATH%

**Comment by eugenesvk** [comment]
It's already in my path.
I get the following exception when I hit enter with your string (without Chinese characters). However, the output is the same (I get `Query: from hello world python`) before I hit enter
(and note that `C:\projects\wox\Wox` path again, which I don't have on my system)

```
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__24_8(Object o) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 177
   at Wox.MainWindow.OnPreviewKeyDown(Object sender, KeyEventArgs e) in C:\projects\wox\Wox\MainWindow.xaml.cs:line 220
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by bao-qian** [comment]
it should be fixed now.
try this build:
https://ci.appveyor.com/project/happlebao/wox/build/1.2.921/artifacts

**Comment by eugenesvk** [comment]
Can confirm that now my conda path is also visible in the Wox settings window. Enter doesn't raise any exceptions. Thank you
