### ISSUE TITLE
First line highlighting issue

### ISSUE THREAD

**Issue by eugenesvk** [Wox-launcher/Wox#593]
1. Please specify Wox version
   1.2.9.11
2. Please describe the steps to **reproduce** the bug
   Empty search bar and start typing anything
3. Please provide Windows version
   Windows 10 x64
4. Please provide Exception info if you have.
   None
5. Please provide **logs** from `%APPDATA%\Wox\Logs` if you have.

```
2016-05-06 04:20:22.4484|INFO|Wox.App+<>c__DisplayClass11_0.<OnStartup>b__0|Preload 0 images from cache
2016-05-06 04:20:23.0679|INFO|Wox.Plugin.Program.Programs.Init|Preload 0 programs from cache
2016-05-06 04:26:35.7053|INFO|Wox.App+<>c__DisplayClass11_0.<OnStartup>b__0|Preload 200 images from cache
2016-05-06 04:26:36.1377|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|Program : Can't create instance
2016-05-06 04:26:36.1377|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|
2016-05-06 04:26:36.1377|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|Exception has been thrown by the target of an invocation.
2016-05-06 04:26:36.1433|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Wox.Core.Plugin.PluginsLoader.CSharpPlugins(List`1 source) in C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:line 49
2016-05-06 04:36:23.9938|INFO|Wox.App+<>c__DisplayClass11_0.<OnStartup>b__0|Preload 200 images from cache
2016-05-06 04:36:24.4254|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|Program : Can't create instance
2016-05-06 04:36:24.4254|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|
2016-05-06 04:36:24.4254|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|Exception has been thrown by the target of an invocation.
2016-05-06 04:36:24.4254|ERROR|Wox.Core.Plugin.PluginsLoader.CSharpPlugins|   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Wox.Core.Plugin.PluginsLoader.CSharpPlugins(List`1 source) in C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:line 49
```
1. Please provide screenshot if you have
   ![wox highlight](https://cloud.githubusercontent.com/assets/12956286/15062550/90cda4a4-1349-11e6-8715-a263760f76ae.png)
   First line is not colored properly (this is automatic highlighting of the first line, if I use cursor keys, then it works fine and is highlighted properly with blueish background)

**Comment by bao-qian** [comment]
try this one
https://ci.appveyor.com/project/happlebao/wox/build/1.2.915/artifacts

**Comment by bao-qian** [comment]
it seems like you have problems with program plugin
please upload your logs **again** after you tried the new version

**Comment by eugenesvk** [comment]
Thank you, this works now!
I still get a bunch of mistakes silently in the log (see below), but I don't know whether they affect search in any way

```
2016-05-06 06:31:01.0868|INFO|Wox.App+<>c__DisplayClass11_0.<OnStartup>b__0|Preload 200 images from cache
2016-05-06 06:31:01.6301|INFO|Wox.Plugin.Program.Programs.Init|Preload 6625 programs from cache
2016-05-06 06:31:01.7368|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: c:\Users\Evgeny\AppData\Local\ElevatedDiagnostics
2016-05-06 06:31:01.7368|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:01.7368|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\appcompat\Programs
2016-05-06 06:31:01.7368|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:01.7724|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\AUInstallAgent
2016-05-06 06:31:01.7724|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:01.7724|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\CSC
2016-05-06 06:31:01.7724|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:01.8165|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\InfusedApps
2016-05-06 06:31:01.8165|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:01.9027|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\LiveKernelReports
2016-05-06 06:31:01.9027|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:01.9027|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\Logs\HomeGroup
2016-05-06 06:31:01.9027|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:01.9157|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\Logs\SystemRestore
2016-05-06 06:31:01.9157|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:01.9157|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\Logs\Telephony
2016-05-06 06:31:01.9157|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:01.9157|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\Logs\WindowsBackup
2016-05-06 06:31:01.9157|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:01.9157|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\Minidump
2016-05-06 06:31:01.9157|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:01.9253|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\ModemLogs
2016-05-06 06:31:01.9253|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:01.9253|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\Prefetch
2016-05-06 06:31:01.9253|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:01.9433|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\security\audit
2016-05-06 06:31:01.9433|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:01.9433|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\security\cap
2016-05-06 06:31:01.9433|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:01.9433|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\ServiceProfiles\NetworkService
2016-05-06 06:31:01.9433|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:02.2455|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\System32\config
2016-05-06 06:31:02.2455|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:02.2455|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\System32\Configuration
2016-05-06 06:31:02.2455|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:02.2635|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\System32\ias
2016-05-06 06:31:02.2635|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:02.2681|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\System32\MsDtc
2016-05-06 06:31:02.2681|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:02.2681|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\System32\networklist
2016-05-06 06:31:02.2681|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:02.2681|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\System32\sru
2016-05-06 06:31:02.2681|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:02.2861|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\System32\WDI
2016-05-06 06:31:02.2861|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:02.2861|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\System32\wfp
2016-05-06 06:31:02.2861|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:02.4304|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\SysWOW64\config
2016-05-06 06:31:02.4304|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:02.4304|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\SysWOW64\Configuration
2016-05-06 06:31:02.4304|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:02.4475|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\SysWOW64\MsDtc
2016-05-06 06:31:02.4475|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:02.4475|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\SysWOW64\networklist
2016-05-06 06:31:02.4475|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:02.4475|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\SysWOW64\sru
2016-05-06 06:31:02.4475|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:02.4475|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\SysWOW64\Tasks
2016-05-06 06:31:02.4475|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:02.4620|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Windows\Temp
2016-05-06 06:31:02.4620|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:03.2558|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Program Files (x86)\Dropbox\CrashReports
2016-05-06 06:31:03.2558|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
2016-05-06 06:31:03.2719|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|Program : GetAppFromDirectory failed: C:\Program Files (x86)\Google\CrashReports
2016-05-06 06:31:03.2719|ERROR|Wox.Plugin.Program.ProgramSources.FileSystemProgramSource.GetAppFromDirectory|
```

**Comment by bao-qian** [comment]
@eugenesvk it should affect the search result
open a separate issue and update a screenshot of program plugin settings

**Comment by eugenesvk** [comment]
Yep, though I don't even have `C:\Windows\System32` in my list. Anyway, will open a new ticket.
