### ISSUE TITLE
Add an silent exception to hitting Enter without selection

### ISSUE THREAD

**Issue by eugenesvk** [Wox-launcher/Wox#595]
1. Please specify Wox version
   1.2.916
2. Please describe the steps to **reproduce** the bug
   Try to kill a process
   a. type `kill`
   b. type process name (e.g. `vivaldi`)
   c. hit enter (noticing that auto-selection didn't select any process likely due to duplicates)
   ![wox kill](https://cloud.githubusercontent.com/assets/12956286/15065522/451457c2-1369-11e6-8cb4-c72cc7e5a270.png)
3. Please provide Windows version
   Windows 10 x64
4. Please provide Exception info if you have.
   Exception type: `System.ArgumentOutOfRangeException`
   Source `mscorlib`
   Stack trace

```
    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__24_8(Object o) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 177
   at Wox.MainWindow.OnPreviewKeyDown(Object sender, KeyEventArgs e) in C:\projects\wox\Wox\MainWindow.xaml.cs:line 220
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```
1. Please provide **logs** from `%APPDATA%\Wox\Logs` if you have.

```
2016-05-06 08:57:27.0225|FATAL|Wox.Helper.ErrorReporting.Report|
## Exception
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   Source: mscorlib
   TargetAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
   TargetModule: CommonLanguageRuntimeLibrary
   TargetSite: Void ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__24_8(Object o) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 177
   at Wox.MainWindow.OnPreviewKeyDown(Object sender, KeyEventArgs e) in C:\projects\wox\Wox\MainWindow.xaml.cs:line 220
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
## Environment

* Command Line: "C:\Apps\Utilities\Wox\Wox.exe" 
* Timestamp: 2016-05-06T08:57:27.0220442+03:00
* IntPtr Length: 8
* System Version: Microsoft Windows NT 6.2.9200.0
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.6.01038
   * v4 Full 4.6.01038
   * v4.0 Client 4.0.0.0

## Assemblies - Wox.exe

* Wox, Version=1.2.916.0, Culture=neutral, PublicKeyToken=null (C:\Apps\Utilities\Wox\Wox.exe)
* Exceptionless, Version=1.5.2121.0, Culture=neutral, PublicKeyToken=fc181f0a46f65747 (C:\Apps\Utilities\Wox\Exceptionless.dll)
* Wox.Infrastructure, Version=1.2.916.0, Culture=neutral, PublicKeyToken=null (C:\Apps\Utilities\Wox\Wox.Infrastructure.dll)
* Wox.Core, Version=1.2.916.0, Culture=neutral, PublicKeyToken=null (C:\Apps\Utilities\Wox\Wox.Core.dll)
* Wox.Plugin, Version=1.2.916.0, Culture=neutral, PublicKeyToken=null (C:\Apps\Utilities\Wox\Wox.Plugin.dll)
* NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Apps\Utilities\Wox\NLog.dll)
* Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Apps\Utilities\Wox\Newtonsoft.Json.dll)
* NAppUpdate.Framework, Version=0.3.2.0, Culture=neutral, PublicKeyToken=d1f1d1f19f9e5a56 (C:\Apps\Utilities\Wox\NAppUpdate.Framework.dll)
* Wox.Plugin.Caculator, Version=1.2.916.0, Culture=neutral, PublicKeyToken=null (C:\Apps\Utilities\Wox\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
* YAMP, Version=1.4.0.22422, Culture=neutral, PublicKeyToken=null (C:\Apps\Utilities\Wox\Plugins\Wox.Plugin.Caculator\YAMP.dll)
* Wox.Plugin.CMD, Version=1.2.916.0, Culture=neutral, PublicKeyToken=null (C:\Apps\Utilities\Wox\Plugins\Wox.Plugin.CMD\Wox.Plugin.CMD.dll)
* WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Apps\Utilities\Wox\WindowsInput.dll)
* Wox.Plugin.Color, Version=1.2.916.0, Culture=neutral, PublicKeyToken=null (C:\Apps\Utilities\Wox\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
* Wox.Plugin.ControlPanel, Version=1.2.916.0, Culture=neutral, PublicKeyToken=null (C:\Apps\Utilities\Wox\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
* Wox.Plugin.Everything, Version=1.2.916.0, Culture=neutral, PublicKeyToken=null (C:\Apps\Utilities\Wox\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
* Wox.Plugin.Folder, Version=1.2.916.0, Culture=neutral, PublicKeyToken=null (C:\Apps\Utilities\Wox\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
* Wox.Plugin.PluginIndicator, Version=1.2.916.0, Culture=neutral, PublicKeyToken=null (C:\Apps\Utilities\Wox\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
* Wox.Plugin.PluginManagement, Version=1.2.916.0, Culture=neutral, PublicKeyToken=null (C:\Apps\Utilities\Wox\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
* Wox.Plugin.Program, Version=1.2.916.0, Culture=neutral, PublicKeyToken=null (C:\Apps\Utilities\Wox\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
* Wox.Plugin.Sys, Version=1.2.916.0, Culture=neutral, PublicKeyToken=null (C:\Apps\Utilities\Wox\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
* Wox.Plugin.Url, Version=1.2.916.0, Culture=neutral, PublicKeyToken=null (C:\Apps\Utilities\Wox\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
* Wox.Plugin.WebSearch, Version=1.2.916.0, Culture=neutral, PublicKeyToken=null (C:\Apps\Utilities\Wox\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
* Wox.Plugin.ChangeCase, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Evgeny\AppData\Roaming\Wox\Plugins\Change Case-bc5279c0-e48a-465c-ba8f-76486f2857e7\Wox.Plugin.ChangeCase.dll)
* Wox.Plugin.CityWeather, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Evgeny\AppData\Roaming\Wox\Plugins\City Weather-4ee12d32-ee70-4fa0-820b-90140afa2232\Wox.Plugin.CityWeather.dll)
* Wox.Plugin.Clipboard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Evgeny\AppData\Roaming\Wox\Plugins\Clipboard History-7d435270-845c-49e3-a5a0-b8b5daa9139b\Wox.Plugin.Clipboard.dll)
* WindowsInput, Version=0.2.0.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\Evgeny\AppData\Roaming\Wox\Plugins\Clipboard History-7d435270-845c-49e3-a5a0-b8b5daa9139b\WindowsInput.dll)
* Wox.Plugin.Doc, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Evgeny\AppData\Roaming\Wox\Plugins\Dash.Doc-aeeb3a69-7acb-4a69-ac8a-9723682e469d\Wox.Plugin.Doc.dll)
* Wox.Plugin.IPAddress, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Evgeny\AppData\Roaming\Wox\Plugins\IP Address-4570e9e6-e7d3-4784-902e-b4ea49c2f717\Wox.Plugin.IPAddress.dll)
* ClassLibrary3, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Evgeny\AppData\Roaming\Wox\Plugins\Roman Numerals-cacbec47-85c6-4e45-afc3-5d7474116c9e\ClassLibrary3.dll)
* Wox.Plugin.Switcheroo, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\Evgeny\AppData\Roaming\Wox\Plugins\Switcheroo for Wox-2f032893-e4ab-4aff-ba6a-abe726ae95a0\Wox.Plugin.Switcheroo.dll)
* Switcheroo.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Evgeny\AppData\Roaming\Wox\Plugins\Switcheroo for Wox-2f032893-e4ab-4aff-ba6a-abe726ae95a0\Switcheroo.Core.dll)
* Wox.Plugin.Currency, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Evgeny\AppData\Roaming\Wox\Plugins\Wox.Plugin.Currency-5374adef-7475-4d77-97c6-aa1b0123fce0\Wox.Plugin.Currency.dll)
* Wox.Plugin.OpenCMD, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Evgeny\AppData\Roaming\Wox\Plugins\Wox.Plugin.OpenCMD-f859f5ab-5b78-48e8-ad73-d2cc2659bee7\Wox.Plugin.OpenCMD.dll)
* Wox.Plugin.ProcessKiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Evgeny\AppData\Roaming\Wox\Plugins\Wox.Plugin.ProcessKiller-e4fa955c-942a-4451-880a-1ed7ac1e661a\Wox.Plugin.ProcessKiller.dll)
* Wox.Plugin.Runner, Version=1.0.5.0, Culture=neutral, PublicKeyToken=null (C:\Users\Evgeny\AppData\Roaming\Wox\Plugins\Wox.Plugin.Runner-116f042b-0b2b-40bd-8023-1070fa88cff3\Wox.Plugin.Runner.dll)
* GalaSoft.MvvmLight, Version=5.1.1.35050, Culture=neutral, PublicKeyToken=bb738e8c4ab8c76c (C:\Users\Evgeny\AppData\Roaming\Wox\Plugins\Wox.Plugin.Runner-116f042b-0b2b-40bd-8023-1070fa88cff3\GalaSoft.MvvmLight.dll)
* Wox.Plugin.Timezone, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Evgeny\AppData\Roaming\Wox\Plugins\Wox.Plugin.Timezone-ccd9377d-52c7-4361-8e23-a235d08fc2ef\Wox.Plugin.Timezone.dll)
* Wox.Plugin.Volume, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Evgeny\AppData\Roaming\Wox\Plugins\Wox.Plugin.Volume-4e2723b0-dde5-4bb0-8d8e-9446b9abfe3d\Wox.Plugin.Volume.dll)
* NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Apps\Utilities\Wox\NHotkey.dll)
* NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Apps\Utilities\Wox\NHotkey.Wpf.dll)
* GalaSoft.MvvmLight.Extras, Version=5.1.1.35050, Culture=neutral, PublicKeyToken=04d01823daf1dbaa (C:\Users\Evgeny\AppData\Roaming\Wox\Plugins\Wox.Plugin.Runner-116f042b-0b2b-40bd-8023-1070fa88cff3\GalaSoft.MvvmLight.Extras.dll)
* Microsoft.Practices.ServiceLocation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Users\Evgeny\AppData\Roaming\Wox\Plugins\Wox.Plugin.Runner-116f042b-0b2b-40bd-8023-1070fa88cff3\Microsoft.Practices.ServiceLocation.dll)
* CoreAudio, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Evgeny\AppData\Roaming\Wox\Plugins\Wox.Plugin.Volume-4e2723b0-dde5-4bb0-8d8e-9446b9abfe3d\CoreAudio.dll)
* Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\Evgeny\AppData\Roaming\Wox\Plugins\Wox.Plugin.Runner-116f042b-0b2b-40bd-8023-1070fa88cff3\Newtonsoft.Json.dll)
* RestSharp, Version=104.4.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Evgeny\AppData\Roaming\Wox\Plugins\Wox.Plugin.Timezone-ccd9377d-52c7-4361-8e23-a235d08fc2ef\RestSharp.dll)
* Pinyin4Net, Version=2016.4.24.0, Culture=neutral, PublicKeyToken=null (C:\Apps\Utilities\Wox\Pinyin4Net.dll)
* Wox.CrashReporter, Version=1.2.916.0, Culture=neutral, PublicKeyToken=null (C:\Apps\Utilities\Wox\Wox.CrashReporter.dll)
* mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
* PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
* System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
* PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
* System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
* System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
* System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
* System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
* System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
* System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
* System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
* System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
* System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Web.Extensions\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.Extensions.dll)
* System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll)
* PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)
* UIAutomationProvider, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll)
* PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll)
* PresentationFramework-SystemXmlLinq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXmlLinq\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXmlLinq.dll)
* PresentationFramework-SystemXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll)
* UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll)
* Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll)
* PresentationFramework-SystemCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemCore\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemCore.dll)
* System.Deployment, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Deployment\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Deployment.dll)
* PresentationFramework-SystemDrawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemDrawing\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemDrawing.dll)
* QTTabBar, Version=1.0.0.0, Culture=neutral, PublicKeyToken=78a0cde69b47ca25 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\QTTabBar\v4.0_1.0.0.0__78a0cde69b47ca25\QTTabBar.dll)
```

I'd prefer for this error to be just silently ignored and if nothing is selected then hitting Enter should have simply no effect.
Thank you

**Comment by bao-qian** [comment]
the selection should be fixed in this build: 
the index exception should also be fixed in this build.
https://ci.appveyor.com/project/happlebao/wox/build/1.2.921/artifacts

But the file location specified in exception is extremely strange.

<del>my current guess is it loaded old version of .pdb files</del>
1. are you sure there is no directory called `C:\projects\wox` and you are running from `C:\Apps\Utilities\Wox\Wox.exe` ?
2. could you delete the whole directory of `C:\Apps\Utilities\Wox` completely and then unzip the new build ? (instead of overwrite old directory)

**Comment by eugenesvk** [comment]
> the selection should be fixed in this build: 

Confirm that, so far can't reproduce any errors, thank you

> the index exception should also be fixed

Can't test it now since something is always selected :)

> 1. are you sure there is no directory called C:\projects\wox and you are running from C:\Apps\Utilities\Wox\Wox.exe ?

Absolutely.

> 1. could you delete the whole directory of C:\Apps\Utilities\Wox completely and then unzip the new build ? (instead of overwrite old directory)

That's what I do every time with only one minor change — I move my custom theme from the old to the new folder.
Can it be a case of some addon misbehaving?

**Comment by bao-qian** [comment]
the exception is come from the main UI, so it can't be a plugin issue.
keep the theme won't affect anything at all.
i will keep an eye out for it
