### ISSUE TITLE
Python plugin crash

### ISSUE THREAD

**Issue by kosz78** [Wox-launcher/Wox#64]
Wox crashed with the following exception on Python plugins

```
Date:2014-03-26 19:14:38,654 Level:FATAL Msg:Wox has an error that can't be handled. System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Python.Runtime.GenericUtil.Register(Type t) in c:\Projects\Wox\Pythonnet.Runtime\genericutil.cs:line 42
   at Python.Runtime.AssemblyManager.ScanAssembly(Assembly assembly) in c:\Projects\Wox\Pythonnet.Runtime\assemblymanager.cs:line 270
   at Python.Runtime.AssemblyManager.Initialize() in c:\Projects\Wox\Pythonnet.Runtime\assemblymanager.cs:line 60
   at Python.Runtime.Runtime.Initialize() in c:\Projects\Wox\Pythonnet.Runtime\runtime.cs:line 166
   at Python.Runtime.PythonEngine.Initialize() in c:\Projects\Wox\Pythonnet.Runtime\pythonengine.cs:line 118
   at Wox.Commands.PluginCommand.SwitchPythonEnv(PluginPair thirdPlugin) in c:\Projects\Wox\Wox\Commands\PluginCommand.cs:line 64
   at Wox.Commands.PluginCommand.Dispatch(Query q) in c:\Projects\Wox\Wox\Commands\PluginCommand.cs:line 26
   at Wox.MainWindow.<TextBoxBase_OnTextChanged>b__7(String o) in c:\Projects\Wox\Wox\MainWindow.xaml.cs:line 215
   at Wox.DispatcherExtensions.<>c__DisplayClass2.<DelayInvoke>b__0(Object s, EventArgs e) in c:\Projects\Wox\Wox\DispatcherExtensions.cs:line 39
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Boolean isSingleParameter)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunInternal(Window window)
   at Wox.SingleInstanceManager.OnStartup(StartupEventArgs e) in c:\Projects\Wox\Wox\App.xaml.cs:line 43
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   at Wox.EntryPoint.Main(String[] args) in c:\Projects\Wox\Wox\App.xaml.cs:line 20
```

It seems probem in .net 4.5 that described here https://github.com/pythonnet/pythonnet/issues/3

**Comment by qianlifeng** [comment]
54417115f368d15144261f34c32cc81543168ad0
