### ISSUE TITLE
NullRef for wpm list output

### ISSUE THREAD

**Issue by Artoria2e5** [Wox-launcher/Wox#654]
WoX 1.3.46, Windows 10b14342
1. `alt`-`space`
2. `wpm list`
3. `return`
4. crash

```
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__24_8(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 185
   at Wox.MainWindow.OnPreviewKeyDown(Object sender, KeyEventArgs e) in C:\projects\wox\Wox\MainWindow.xaml.cs:line 321
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

听起来少了啥判断啊……

**Comment by bao-qian** [comment]
感谢纠错，我看看，其实代码一团糟（

**Comment by Artoria2e5** [comment]
Everything 没安装那个提示点了也会 NullRef，大概是没有指定操作的情况没处理？

**Comment by jhdxr** [comment]
everyting 没安装的情况能不能让插件把自己禁用掉，或者不要给任何结果了。这样子给一个everything 没有安装的提示其实并没有什么意义啊- -b

**Comment by bao-qian** [comment]
你可以点 disable 啊

**Comment by jhdxr** [comment]
@happlebao 是可以禁用（并且我也已经禁用了），我只是觉得从一般用户的角度来说感觉有点奇怪，我随便搜个东西，你最后都给我来一个everything没有安装。。。所以不返回结果从体验上来说会更好？

**Comment by bao-qian** [comment]
搜文件算一个主要功能啊…… 但很多人不知道这东西…

**Comment by bao-qian** [comment]
已修复
https://ci.appveyor.com/project/happlebao/wox/build/1.3.57
