### ISSUE TITLE
mscorlib System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by bithack3r** [Wox-launcher/Wox#676]
Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.10240.0
Date: 05/23/2016 11:04:27
Exception:
mscorlib
System.IO.DirectoryNotFoundException
Could not find a part of the path 'C:\Users\Osman\AppData\Roaming\Wox\Plugins\Everything-6a7624e7-39e7-43d4-a046-4978de8a06a3\EverythingSDK\x64'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at Wox.Infrastructure.Helper.ValidateDataDirectory(String bundledDataDirectory, String dataDirectory) in C:\projects\wox\Wox.Infrastructure\Helper.cs:line 39
   at Wox.Plugin.Everyth

ing.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Everything\Main.cs:line 137
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 28
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__18_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 90
   at System.Threading.Tasks.Parallel.<>c__DisplayClass9`1.<ForWorker>b__11()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass0.<ExecuteSelfReplicating>b__1(Object )

**Comment by bithack3r** [comment]
[log.pdf](https://github.com/Wox-launcher/Wox/files/276883/log.pdf)

**Comment by bao-qian** [comment]
Delete this directory

**Comment by bao-qian** [comment]
C:\Users\Osman\AppData\Roaming\Wox\Plugins\Everything-6a7624e7-39e7-43d4-a046-4978de8a06a3
