### ISSUE TITLE
clock plugin breaks wox

### ISSUE THREAD

**Issue by rickmed** [Wox-launcher/Wox#688]
Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.10240.0
Date: 05/24/2016 22:53:32
Exception:
Wox.Plugin.SimpleClock
System.TypeLoadException
Could not load type 'Wox.Infrastructure.Storage.BaseStorage`1' from assembly 'Wox.Infrastructure, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null'.
   at Wox.Plugin.SimpleClock.Commands.AlarmCommand.InitializeStorage(PluginInitContext context)
   at Wox.Plugin.SimpleClock.Commands.AlarmCommand..ctor(PluginInitContext context, CommandHandlerBase parent)
   at Wox.Plugin.SimpleClock.ClockPlugin.Init(PluginInitContext context)
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 28
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__18_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 90
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by bao-qian** [comment]
because @lances101 use undocument API (storate)...
ask him to update
https://github.com/lances101/Wox.Plugin.SimpleClock

**Comment by bao-qian** [comment]
@rickmed SimpleClock has been updated
