### ISSUE TITLE
Wox.Plugin.BrowserBookmark Exception after install

### ISSUE THREAD

**Issue by totpero** [Wox-launcher/Wox#709]
## English

Before you report any bugs try search existing issues
1. Please specify Wox version
   Wox version: 1.3.67
2. Please provide Windows version
   OS Version: Microsoft Windows NT 10.0.10586.0
3. Please provide Exception info if you have.

```
Exception:
Wox.Plugin.BrowserBookmark
System.TypeLoadException
Could not load type 'Wox.Infrastructure.Unidecoder' from assembly 'Wox.Infrastructure, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null'.
   at Wox.Plugin.BrowserBookmark.Bookmark.set_Name(String value)
   at Wox.Plugin.BrowserBookmark.ChromeBookmarks.ParseChromeBookmarks(String path, String source) in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\ChromeBookmarks.cs:line 51
   at Wox.Plugin.BrowserBookmark.ChromeBookmarks.LoadChromeBookmarks(String path, String name) in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\ChromeBookmarks.cs:line 69
   at Wox.Plugin.BrowserBookmark.ChromeBookmarks.LoadChromeBookmarks() in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\ChromeBookmarks.cs:line 76
   at Wox.Plugin.BrowserBookmark.ChromeBookmarks.GetBookmarks() in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\ChromeBookmarks.cs:line 16
   at Wox.Plugin.BrowserBookmark.Main.Init(PluginInitContext context) in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\Main.cs:line 26
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 28
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__18_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 90
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )


```

**Comment by bao-qian** [comment]
this plugin is broken
#590
