### ISSUE TITLE
[NullReferenceException] Wox wont start

### ISSUE THREAD

**Issue by Jainish** [Wox-launcher/Wox#728]
Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 06/01/2016 21:24:59
Exception:
Wox
System.NullReferenceException
Object reference not set to an instance of an object.
   at Wox.App.<OnStartup>b__8_0() in C:\projects\wox\Wox\App.xaml.cs:line 48
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2016-06-01.txt](https://github.com/Wox-launcher/Wox/files/294720/2016-06-01.txt)

**Comment by bao-qian** [comment]
try delete %APPDATA%\Wox

**Comment by bao-qian** [comment]
hi, please try new build:
https://ci.appveyor.com/project/happlebao/wox/build/1.3.156/artifacts

**Comment by Jainish** [comment]
Hi, that has solved the issue.
