### ISSUE TITLE
[WebSearch] Cannot add web searchs action

### ISSUE THREAD

**Issue by dlaflamme** [Wox-launcher/Wox#742]
Wox version: 1.3.67
Windows: 7
Error: I try to add a web search URL with action keyword "jira". I get a pop-up message "New ActionKeywords has been assigned to other plugin, please assign another new action keyword"

What I input to the new Web Searchers plugin:
Title: Jira
URL: https://jira.mydomain.com/jira/browse/{q}
Action Keyword: jira
Enable: checked

Logs:

```
2016-06-07 17:47:49.3135|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-06-07 17:47:49.3135|ERROR|Wox.Plugin.Everything.Everything.EverythingAPI+<Search>d__43.MoveNext|Error in the application.
2016-06-07 17:47:49.3195|ERROR|Wox.Plugin.Everything.Everything.EverythingAPI+<Search>d__43.MoveNext|
   at Wox.Plugin.Everything.Everything.EverythingAPI.<Search>d__43.MoveNext() in C:\projects\wox\Plugins\Wox.Plugin.Everything\Everything\EverythingAPI.cs:line 222
2016-06-07 17:47:49.9050|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-06-07 17:47:49.9050|ERROR|Wox.Plugin.Everything.Everything.EverythingAPI+<Search>d__43.MoveNext|Error in the application.
2016-06-07 17:47:49.9110|ERROR|Wox.Plugin.Everything.Everything.EverythingAPI+<Search>d__43.MoveNext|
   at Wox.Plugin.Everything.Everything.EverythingAPI.<Search>d__43.MoveNext() in C:\projects\wox\Plugins\Wox.Plugin.Everything\Everything\EverythingAPI.cs:line 222
2016-06-07 17:47:50.0701|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-06-07 17:47:50.0701|ERROR|Wox.Plugin.Everything.Everything.EverythingAPI+<Search>d__43.MoveNext|Error in the application.
2016-06-07 17:47:50.0701|ERROR|Wox.Plugin.Everything.Everything.EverythingAPI+<Search>d__43.MoveNext|
   at Wox.Plugin.Everything.Everything.EverythingAPI.<Search>d__43.MoveNext() in C:\projects\wox\Plugins\Wox.Plugin.Everything\Everything\EverythingAPI.cs:line 222
2016-06-07 17:47:50.8568|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-06-07 17:47:50.8568|ERROR|Wox.Plugin.Everything.Everything.EverythingAPI+<Search>d__43.MoveNext|Error in the application.
2016-06-07 17:47:50.8659|ERROR|Wox.Plugin.Everything.Everything.EverythingAPI+<Search>d__43.MoveNext|
   at Wox.Plugin.Everything.Everything.EverythingAPI.<Search>d__43.MoveNext() in C:\projects\wox\Plugins\Wox.Plugin.Everything\Everything\EverythingAPI.cs:line 222
2016-06-07 17:47:51.0831|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-06-07 17:47:51.0831|ERROR|Wox.Plugin.Everything.Everything.EverythingAPI+<Search>d__43.MoveNext|Error in the application.
2016-06-07 17:47:51.0831|ERROR|Wox.Plugin.Everything.Everything.EverythingAPI+<Search>d__43.MoveNext|
   at Wox.Plugin.Everything.Everything.EverythingAPI.<Search>d__43.MoveNext() in C:\projects\wox\Plugins\Wox.Plugin.Everything\Everything\EverythingAPI.cs:line 222
2016-06-07 17:50:47.6558|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-06-07 17:50:47.6558|ERROR|Wox.Core.Plugin.PluginManager.UpdateActionKeywordForPlugin|New ActionKeywords has been assigned to other plugin, please assign another new action keyword
2016-06-07 17:50:47.6558|ERROR|Wox.Core.Plugin.PluginManager.UpdateActionKeywordForPlugin|
   at Wox.Core.Plugin.PluginManager.UpdateActionKeywordForPlugin(PluginPair plugin, String oldActionKeyword, String newActionKeyword) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 255
```

**Comment by Duke9700** [comment]
I'm having this same issue. Regardless of the url or action keyword I try and use I get the same error "New ActionKeywords has been assigned to other plugin, please assign another new action keyword".

I'm also using version 1.3.67 but I'm on Windows 10

**Comment by kotcrab** [comment]
I proposed fix in #760, after its gets merged you will probably have to modify `%APPDATA%\Wox\Settings.json` and remove `Web Searches` `ActionKeywords` that are listed there but you don't see them in web search plugin settings.

**Comment by bao-qian** [comment]
hi @kotcrab @dlaflamme @Duke9700 
try new build
https://ci.appveyor.com/project/happlebao/wox/build/1.3.174/artifacts

**Comment by dlaflamme** [comment]
Created new issue regarding the 1.3.170 build. https://github.com/Wox-launcher/Wox/issues/791

**Comment by dlaflamme** [comment]
I still get the same message when trying to add a web search with action keyword "jira". However, I can add an identical one called "jira2." Where can I see where "jira" is already registered (perhaps it is cached somewhere from earlier)?

**Comment by kotcrab** [comment]
@dlaflamme my previous comment:

> you will have to modify `%APPDATA%\Wox\Settings.json` and remove `Web Searches` `ActionKeywords` that are listed there but you don't see them in web search plugin settings.

**Comment by bao-qian** [comment]
Sorry about it, I know this is a bad design....

**Comment by dlaflamme** [comment]
Thank you. Missed that comment.

**Comment by calebmeyer** [comment]
Windows 10, Wox build 1.3.183, and I am seeing this issue. 

I checked %APPDATA%\Wox, but there's no settings.json in that folder. 
There is one in %APPDATA%\Wox\Settings\Settings.json, but it doesn't show any custom web searches because I've never been able to create one.
