### ISSUE TITLE
[WebSearch] Exception after typing the last character of custom WebSearch keyword

### ISSUE THREAD

**Issue by homoroselaps** [Wox-launcher/Wox#763]
Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 06/13/2016 11:09:47
Exception:
mscorlib
System.ArgumentOutOfRangeException
Insertion index was out of range. Must be non-negative and less than or equal to size.
Parameter name: index
   at System.Collections.ArrayList.Insert(Int32 index, Object value)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   at System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2016-06-13.txt](https://github.com/Wox-launcher/Wox/files/311525/2016-06-13.txt)

**Comment by bao-qian** [comment]
hi @homoroselaps  
try new build
https://ci.appveyor.com/project/happlebao/wox/build/1.3.174/artifacts
