### ISSUE TITLE
[NullReferenceException] Wox got an error

### ISSUE THREAD

**Issue by bkdev98** [Wox-launcher/Wox#767]
Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.14342.0
Date: 06/14/2016 23:39:56
Exception:
Wox
System.NullReferenceException
Object reference not set to an instance of an object.
   at Wox.App.<OnStartup>b__8_0() in C:\projects\wox\Wox\App.xaml.cs:line 48
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---

[2016-06-14.txt](https://github.com/Wox-launcher/Wox/files/314443/2016-06-14.txt)

**Comment by bao-qian** [comment]
1. try delete %APPDATA%\Wox
2. please try new build: https://ci.appveyor.com/project/happlebao/wox/build/1.3.156/artifacts

**Comment by bao-qian** [comment]
close due to no response
