### ISSUE TITLE
[NullReferenceException] wox

### ISSUE THREAD

**Issue by amrgobara** [Wox-launcher/Wox#772]
Wox version: 1.3.67
OS Version: Microsoft Windows NT 6.3.9600.0
Date: 06/15/2016 21:27:03
Exception:
Wox.Plugin.Program
System.NullReferenceException
Object reference not set to an instance of an object.
   at Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 136
   at Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 102
   at Wox.Infrastructure.Stopwatch.Debug(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 19
   at Wox.Plugin.Program.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 94
   at Wox.Core.Plugin.PluginManager.<>c__DisplayClass18_0.<InitializePlugins>b__1() in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 83
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 27
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__18_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 81
   at System.Threading.Tasks.Parallel.<>c__DisplayClass2d`2.<ForEachWorker>b__23(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass11.<ExecuteSelfReplicating>b__10(Object param0)

**Comment by bao-qian** [comment]
upload the latest log from `%APPDATA%\Wox\Logs` please

**Comment by bao-qian** [comment]
close due to no response
ps: you could try delete %APPDATA%\Wox if it is not working

**Comment by ghost** [comment]
This happend to me as well, and your solution in clearing the appdata is correct!
