### ISSUE TITLE
[NullReferenceException] System.NullReferenceException (BUG)

### ISSUE THREAD

**Issue by TarasKovalenko** [Wox-launcher/Wox#781]
After running OS (Windows 10 Enterprise Insider Preview) Wox not started.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   Source: Wox
   TargetAssembly: Wox, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Wox.exe
   TargetSite: Void <OnStartup>b__8_0()
   at Wox.App.<OnStartup>b__8_0() in C:\projects\wox\Wox\App.xaml.cs:line 48
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

![wox_error](https://cloud.githubusercontent.com/assets/2806803/16170563/90480f0a-355f-11e6-9d40-691fd68d8a51.png)

[Log file](https://github.com/Wox-launcher/Wox/files/321707/2016-06-18.zip)

**Comment by bao-qian** [comment]
https://ci.appveyor.com/project/happlebao/wox/build/1.3.161/artifacts

**Comment by bao-qian** [comment]
close due to no response
ps: you could try delete %APPDATA%\Wox if above build is not working

**Comment by TarasKovalenko** [comment]
@happlebao after remove %APPDATA%\Wox all worked is good. but it is not very well

**Comment by bao-qian** [comment]
> but it is not very well 

what do you mean by this?
