### ISSUE TITLE
[WebSearch] Exception when deleting web pre-configured web searches

### ISSUE THREAD

**Issue by dlaflamme** [Wox-launcher/Wox#791]
## English

I am trying the build (1.3.170) mentioned in this issue: https://github.com/Wox-launcher/Wox/issues/742

When I try to delete web searches for things I don't use, I get the following exception:

Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: \domain\dfs\home\user\Application Data\Wox\Logs\1.3.170\2016-06-22.txt
2. copy below exception message

Wox version: 1.3.170
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 06/22/2016 10:43:11
Exception:
Wox.Core
System.NullReferenceException
Object reference not set to an instance of an object.
   at Wox.Core.Plugin.PluginManager.RemoveActionKeyword(String id, String oldActionkeyword) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 279
   at Wox.Plugin.WebSearch.SettingsControl.OnDeleteSearchSearchClick(Object sender, RoutedEventArgs e) in C:\projects\wox\Plugins\Wox.Plugin.WebSearch\SettingsControl.xaml.cs:line 38
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
Thanks for report, I will check later today

**Comment by dlaflamme** [comment]
One other piece of information. I can delete one of the search actions successfully. I get error when I try to delete a second one, I get the exception.

**Comment by bao-qian** [comment]
should be fixed now
https://ci.appveyor.com/project/happlebao/wox/build/1.3.174/artifacts

**Comment by dlaflamme** [comment]
Confirmed fixed.

**Comment by bao-qian** [comment]
Great!
