### ISSUE TITLE
[WebSearch] ActionKeyword - various crashes or errors

### ISSUE THREAD

**Issue by nicknormal** [Wox-launcher/Wox#794]
Greetings.
Sent here from Wox auto-popup with an error message.
How do I upload the log?
All I'm trying to do is change the 'Action Keyword' for WebSearchSetting[s]. I'm inputting strings that definitely haven't been used elsewhere and I'm getting the notorious "New ActionKeywords has been assigned to other plugin..." error.

Incredibly useful software, wish I could assign ActionKeywords without fault.

Thanks for your time.

Wox version: 1.3.67
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 06/22/2016 15:53:16
Exception:
mscorlib
System.ArgumentOutOfRangeException
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.set_Item(Int32 index, T value)
   at Wox.Core.Plugin.PluginManager.UpdateActionKeywordForPlugin(PluginPair plugin, String oldActionKeyword, String newActionKeyword) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 275
   at Wox.SettingWindow.<>c__DisplayClass34_0.<lbPlugins_OnSelectionChanged>b__0(IMultipleActionKeywords o, ActionKeywordsChangedEventArgs e) in C:\projects\wox\Wox\SettingWindow.xaml.cs:line 646
   at Wox.Plugin.ActionKeywordsChangedEventHandler.Invoke(IMultipleActionKeywords sender, ActionKeywordsChangedEventArgs e)
   at Wox.Plugin.WebSearch.WebSearchSetting.ConfirmButtonOnClick(Object sender, RoutedEventArgs e) in C:\projects\wox\Plugins\Wox.Plugin.WebSearch\WebSearchSetting.xaml.cs:line 89
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by nicknormal** [comment]
And fwiw the customized Web Searches that I built are now missing entirely from Wox :(

**Comment by bao-qian** [comment]
I'm sorry about your lose of settings.
there should be a backup button in the future version. #259 

your current exception should be solved with new build:
https://ci.appveyor.com/project/happlebao/wox/build/1.3.174
