### ISSUE TITLE
[BrowserBookmark] issue

### ISSUE THREAD

**Issue by DemonDante** [Wox-launcher/Wox#796]
Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.10586.0 (Windows 10 pro x64)

Date: 06/22/2016 19:11:06
Reproduce: Just install bookmarks plugin
Exception:
Wox.Plugin.BrowserBookmark
System.TypeLoadException
Could not load type 'Wox.Infrastructure.Unidecoder' from assembly 'Wox.Infrastructure, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null'.
   at Wox.Plugin.BrowserBookmark.Bookmark.set_Name(String value)
   at Wox.Plugin.BrowserBookmark.FirefoxBookmarks.<GetBookmarks>b__1(SQLiteDataReader x) in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:line 39
   at Wox.Plugin.BrowserBookmark.Extensions.<Select>d__0`1.MoveNext() in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:line 85
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Wox.Plugin.BrowserBookmark.FirefoxBookmarks.GetBookmarks() in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:line 39
   at Wox.Plugin.BrowserBookmark.Main.Init(PluginInitContext context) in d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\Main.cs:line 24
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 28
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__18_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 90
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

For some reason GitHub is being gay and not letting me attach log file, even if it is in a zip file, which is supposedly supported, so here is just a link to the file instead.
[http://iqu.ca/1/?92626F359783](url)

**Comment by lances101** [comment]
https://github.com/Wox-launcher/Wox.Plugin.BrowserBookmark/pull/4

@happlebao Updated bookmarks plugin to work with 1.3.0.

**Comment by happlebao** [comment]
@lances101 great work! I need wait for @qianlifeng to takedown the plugin, so I can update it ...

**Comment by happlebao** [comment]
Hi @DemonDante 
the plugin has been updated,
try again by
`wpm install Browser Bookmarks`
