### ISSUE TITLE
log "CheckInvalidPathChars" exception

### ISSUE THREAD

**Issue by dlaflamme** [Wox-launcher/Wox#826]
1. Wox version 1.3.86
2. When I start Wox, I see a message in the logs referring to invalid characters in a path. See below.
3. Windows 10

The exception below doesn't prevent Wox from starting. it may be nice to catch the exception and log it so it can be corrected.

Exception in logs:

2016-07-05 10:23:06.0229|INFO|Wox.Plugin.Program.Main.Init|Preload 1604 programs from cache
2016-07-05 10:23:06.1329|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-07-05 10:23:06.1530|ERROR|System.IO.Path.CheckInvalidPathChars|Illegal characters in path.
2016-07-05 10:23:06.1530|ERROR|System.IO.Path.CheckInvalidPathChars|
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
2016-07-05 10:23:06.1850|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-07-05 10:23:06.1850|ERROR|System.IO.Path.CheckInvalidPathChars|Illegal characters in path.
2016-07-05 10:23:06.1850|ERROR|System.IO.Path.CheckInvalidPathChars|
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)

**Comment by dlaflamme** [comment]
[2016-07-05-issue_826.txt](https://github.com/Wox-launcher/Wox/files/348108/2016-07-05-issue_826.txt)
