### ISSUE TITLE
System.IO.IOException The directory is not empty.

### ISSUE THREAD

**Issue by garodriguezlp** [Wox-launcher/Wox#837]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 07/06/2016 21:17:27
Exception:
mscorlib
System.IO.IOException
The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Wox.Core.Plugin.PluginInstaller.Install(String path) in C:\projects\wox\Wox.Core\Plugin\PluginInstaller.cs:line 75
   at Wox.PublicAPIInstance.<>c__DisplayClass13_0.<InstallPlugin>b__0() in C:\projects\wox\Wox\PublicAPIInstance.cs:line 105
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Wox.Plugin.PluginManagement.Main.<>c__DisplayClass12_1.<ResultForInstallPlugin>b__0(ActionContext c) in C:\projects\wox\Plugins\Wox.Plugin.PluginManagement\Main.cs:line 171
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 146
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2016-07-06.txt](https://github.com/Wox-launcher/Wox/files/351258/2016-07-06.txt)

**Comment by bao-qian** [comment]
the plugin Currency Converter seems broken.
could you try to delete that plugin?
C:\Users\gusta\AppData\Roaming\Wox\Plugins\Currency Converter

**Comment by garodriguezlp** [comment]
sure!

Thanks for the reply.

​

Atentamente,
​​

Gustavo Adolfo Rodríguez Libreros 
Email: Gustavo.Adolfo.Rodriguez.L@gmail.com [mailto:Gustavo.Adolfo.Rodriguez.L@gmail.com] 
Ingeniero de Sistemas - Universidad del Valle 
Cali - Colombia

[https://co.linkedin.com/in/gustavoarod]  [https://www.facebook.com/Gustavo.Adolfo.Rodriguez.L]  [https://twitter.com/GustavoARod]  [https://plus.google.com/+GustavoAdolfoRodr%C3%ADguezLibreros/]
On 7/19/2016 6:55:38 PM, happlebao notifications@github.com wrote:
the plugin Currency Converter seems broken.
could you try to delete that plugin?
C:\Users\gusta\AppData\Roaming\Wox\Plugins\Currency Converter

**Comment by bao-qian** [comment]
did you resolved this issue now ?

**Comment by garodriguezlp** [comment]
yes! Thanks!

​

Atentamente,
​​

Gustavo Adolfo Rodríguez Libreros 
Email: Gustavo.Adolfo.Rodriguez.L@gmail.com [mailto:Gustavo.Adolfo.Rodriguez.L@gmail.com] 
Ingeniero de Sistemas - Universidad del Valle 
Cali - Colombia

[https://co.linkedin.com/in/gustavoarod]  [https://www.facebook.com/Gustavo.Adolfo.Rodriguez.L]  [https://twitter.com/GustavoARod]  [https://plus.google.com/+GustavoAdolfoRodr%C3%ADguezLibreros/]
On 7/20/2016 5:02:44 AM, happlebao notifications@github.com wrote:
did you resolved this issue now ?
