### ISSUE TITLE
Object reference not set to an instance of an object. at Wox.Plugin.Program.Main.DefaultProgramSources() 

### ISSUE THREAD

**Issue by MakeshVineeth** [Wox-launcher/Wox#849]
Attached Log files:
[2016-07-15.txt](https://github.com/Wox-launcher/Wox/files/365408/2016-07-15.txt)

I would get the below exception message:

Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14388.0
Date: 07/15/2016 13:02:36
Exception:
Wox.Plugin.Program
System.NullReferenceException
Object reference not set to an instance of an object.
   at Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 136
   at Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 102
   at Wox.Plugin.Program.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 94
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 27
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by bao-qian** [comment]
try delete `%APPDATA%\Wox\Cache`

**Comment by MakeshVineeth** [comment]
It happened only after upgrading my PC to windows 10 new build. Re-installing the Wox fixed this problem.

**Comment by bao-qian** [comment]
thanks for feedback
