### ISSUE TITLE
Wox.Core System.MissingMethodException 错误

### ISSUE THREAD

**Issue by bqx619** [Wox-launcher/Wox#860]
## 中文 / Chinese
1. Wox 版本：1.3.67+1.3.138均出现
2. 如何**重现** bug：右击托盘图标选项,进行一些设置操作,例如:修改主题\查看插件等设置时
3. Windows 版本：Microsoft Windows NT 6.1.7601 Service Pack 1(windows7 sp1)
4. Exception：

```
Wox.Core
System.MissingMethodException
Method not found: 'Int32 System.Runtime.InteropServices.Marshal.SizeOf(!!0)'.
   at Wox.Core.Resource.Theme.SetWindowAccent(Window wind, AccentState themeAccentMode)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.ListBox.OnSelectionChanged(SelectionChangedEventArgs e)
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector.SetSelectedHelper(Object item, FrameworkElement UI, Boolean selected)
   at System.Windows.Controls.Primitives.Selector.NotifyIsSelectedChanged(FrameworkElement container, Boolean selected, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.ListBoxItem.OnSelected(RoutedEventArgs e)
   at System.Windows.Controls.ListBoxItem.OnIsSelectedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetCurrentValueInternal(DependencyProperty dp, Object value)
   at System.Windows.Controls.ListBox.NotifyListItemClicked(ListBoxItem item, MouseButton mouseButton)
   at System.Windows.Controls.ListBoxItem.OnMouseLeftButtonDown(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```
1. **logs** （`%APPDATA%\Wox\Logs\version\date.txt`)：部分

```
2016-07-22 21:53:27.3707|ERROR|Wox.Infrastructure.Image.ImageLoader.GetFileIcon|First Chance Exception:
2016-07-22 21:53:27.3717|ERROR|Wox.Infrastructure.Image.ImageLoader.GetFileIcon|Method not found: 'Int32 System.Runtime.InteropServices.Marshal.SizeOf(!!0)'.
2016-07-22 21:53:27.3717|ERROR|Wox.Infrastructure.Image.ImageLoader.GetFileIcon|
   at Wox.Infrastructure.Image.ImageLoader.GetFileIcon(String name)
   at Wox.Infrastructure.Image.ImageLoader.ShellIcon(String fileName) in C:\projects\wox\Wox.Infrastructure\Image\ImageLoader.cs:line 53
2016-07-22 21:53:27.3717|ERROR|Wox.Infrastructure.Image.ImageLoader.ShellIcon|Method not found: 'Int32 System.Runtime.InteropServices.Marshal.SizeOf(!!0)'.
2016-07-22 21:53:27.3717|ERROR|Wox.Infrastructure.Image.ImageLoader.ShellIcon|
   at Wox.Infrastructure.Image.ImageLoader.GetFileIcon(String name)
   at Wox.Infrastructure.Image.ImageLoader.ShellIcon(String fileName) in C:\projects\wox\Wox.Infrastructure\Image\ImageLoader.cs:line 53
```

**Comment by bao-qian** [comment]
Blur is not supported in win7.
the latest build will auto ignore it.
https://ci.appveyor.com/project/happlebao/wox/build/1.3.207/artifacts

**Comment by happlebao** [comment]
Blur is not supported in win7.
the latest build will auto ignore it.
https://ci.appveyor.com/project/happlebao/wox/build/1.3.207/artifacts

**Comment by bqx619** [comment]
ok,thank you
