### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by aaronortiz** [Wox-launcher/Wox#861]
## English

I think my workplace's policies are making my installation fail, although i was able to use Wox for a few days before this happened. I tried to reinstall.

I hope you can find the problem and help!

Aaron
[2016-07-22.txt](https://github.com/Wox-launcher/Wox/files/378553/2016-07-22.txt)

Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 07/22/2016 10:36:51
Exception:
Wox

System.NullReferenceException
Object reference not set to an instance of an object.
   at Wox.ViewModel.SettingWindowViewModel..ctor() in C:\projects\wox\Wox\ViewModel\SettingWindowViewModel.cs:line 28
   at Wox.App.<OnStartup>b__8_0() in C:\projects\wox\Wox\App.xaml.cs:line 44
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 27
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
it seems like settings are broken. try delete `%APPDATA%\Wox\Settings`. (back up before you do that)

**Comment by aaronortiz** [comment]
Thanks! Deleting the settings worked.
