### ISSUE TITLE
System.UriFormatException

### ISSUE THREAD

**Issue by clayzx** [Wox-launcher/Wox#883]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 07/29/2016 15:52:14
Exception:
System
System.UriFormatException
Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Wox.Core.Resource.Theme.GetResourceDictionary() in C:\projects\wox\Wox.Core\Resource\Theme.cs:line 70
   at Wox.Core.Resource.ResourceMerger.UpdateResource[T](T t) in C:\projects\wox\Wox.Core\Resource\ResourceMerger.cs:line 31
   at Wox.Core.Resource.Theme.ChangeTheme(String themeName) in C:\projects\wox\Wox.Core\Resource\Theme.cs:line 58
   at Wox.MainWindow.OnLoaded(Object sender, RoutedEventArgs _) in C:\projects\wox\Wox\MainWindow.xaml.cs:line 53
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2016-07-29.txt](https://github.com/Wox-launcher/Wox/files/390090/2016-07-29.txt)

**Comment by bao-qian** [comment]
你的 theme file 有问题。删了。

**Comment by bao-qian** [comment]
有问题再开
