### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by Redauser** [Wox-launcher/Wox#888]
Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 08/01/2016 09:30:17
Exception:
Wox
System.NullReferenceException
Object reference not set to an instance of an object.
   at Wox.App.<OnStartup>b__8_0() in C:\projects\wox\Wox\App.xaml.cs:line 48
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate  @catchHandler)

[2016-08-01.zip](https://github.com/Wox-launcher/Wox/files/393146/2016-08-01.zip)

**Comment by bao-qian** [comment]
delete `%APPDATA%\Wox\Settings` 
backup before delete

**Comment by bao-qian** [comment]
close due to no response
