### ISSUE TITLE
Wox.Plugin.Program.Main.DefaultProgramSources|Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ztmdsbt** [Wox-launcher/Wox#894]
1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：widnows 10 10.0.14939
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
   2016-08-02 23:50:42.5583|INFO|Wox.Plugin.Program.Main.Init|Preload 0 programs from cache
   2016-08-02 23:50:42.5793|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
   2016-08-02 23:50:42.5793|ERROR|Wox.Plugin.Program.Main.DefaultProgramSources|Object reference not set to an instance of an object.
   2016-08-02 23:50:42.5793|ERROR|Wox.Plugin.Program.Main.DefaultProgramSources|
   at Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 136
   2016-08-02 23:50:42.5793|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
   2016-08-02 23:50:42.5793|ERROR|System.Threading.Tasks.Parallel+<>c__DisplayClass17_0`1.<ForWorker>b__1|Object reference not set to an instance of an object.
   2016-08-02 23:50:42.5863|ERROR|System.Threading.Tasks.Parallel+<>c__DisplayClass17_0`1.<ForWorker>b__1|
   at Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 136
   at Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 102
   at Wox.Plugin.Program.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 94
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 27
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   2016-08-02 23:50:42.5863|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
   2016-08-02 23:50:42.5863|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|One or more errors occurred.
   2016-08-02 23:50:42.5863|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   2016-08-02 23:50:42.5863|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|Object reference not set to an instance of an object.
   2016-08-02 23:50:42.5863|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|
   at Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 136
   at Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 102
   at Wox.Plugin.Program.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 94
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 27
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   2016-08-02 23:50:42.5863|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
   2016-08-02 23:50:42.5863|ERROR|System.Threading.Tasks.Parallel.ForWorker|One or more errors occurred.
   2016-08-02 23:50:42.5863|ERROR|System.Threading.Tasks.Parallel.ForWorker|
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   2016-08-02 23:50:42.5863|ERROR|System.Threading.Tasks.Parallel.ForWorker|Object reference not set to an instance of an object.
   2016-08-02 23:50:42.5863|ERROR|System.Threading.Tasks.Parallel.ForWorker|
   at Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 136
   at Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 102
   at Wox.Plugin.Program.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 94
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 27
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   2016-08-02 23:50:42.6043|FATAL|Wox.Helper.ErrorReporting.Report|
   ## Exception

```
System.NullReferenceException: Object reference not set to an instance of an object.
   Source: Wox.Plugin.Program
   TargetAssembly: Wox.Plugin.Program, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Wox.Plugin.Program.dll
   TargetSite: System.Collections.Generic.List`1[Wox.Plugin.Program.ProgramSource] DefaultProgramSources()
   at Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 136
   at Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 102
   at Wox.Plugin.Program.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 94
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 27
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

System.AggregateException: One or more errors occurred.
   Source: mscorlib
   TargetAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
   TargetModule: CommonLanguageRuntimeLibrary
   TargetSite: Void ThrowIfExceptional(Boolean)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 94
   at Wox.App.<OnStartup>b__8_0() in C:\projects\wox\Wox\App.xaml.cs:line 53
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 28
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```
## Environment
- Command Line: "C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Wox.exe" 
- Timestamp: 08/02/2016 23:50:42
- IntPtr Length: 8
- System Version: Microsoft Windows NT 10.0.14393.0
- CLR Version: 4.0.30319.42000
- Installed .NET Framework: 
  - v2.0.50727 2.0.50727.4927 SP2
  - v3.0 3.0.30729.4926 SP2
  - v3.5 3.5.30729.4926 SP1
  - v4 Client 4.6.01586
  - v4 Full 4.6.01586
  - v4.0 Client 4.0.0.0
## Assemblies - Wox.exe
- Wox, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Wox.exe)
- Wox.Infrastructure, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Wox.Infrastructure.dll)
- Wox.Plugin, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Wox.Plugin.dll)
- Wox.Core, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Wox.Core.dll)
- Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Newtonsoft.Json.dll)
- HelloWorldCSharp, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\HelloWorldCSharp\HelloWorldCSharp.dll)
- Wox.Plugin.Caculator, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
- YAMP, Version=1.4.0.22422, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Caculator\YAMP.dll)
- Wox.Plugin.Color, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
- Wox.Plugin.ControlPanel, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
- Wox.Plugin.Everything, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
- Wox.Plugin.Folder, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
- Wox.Plugin.PluginIndicator, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
- Wox.Plugin.PluginManagement, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
- Wox.Plugin.Program, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
- Wox.Plugin.Shell, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
- WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\WindowsInput.dll)
- Wox.Plugin.Sys, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
- Wox.Plugin.Url, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
- Wox.Plugin.WebSearch, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
- NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\NHotkey.dll)
- NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\NHotkey.Wpf.dll)
- NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\NLog.dll)
- mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
- PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
- PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
- System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
- WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
- System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
- System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
- System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
- System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
- System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
- System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
- System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
- System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
- System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
- System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
- PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)
- System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)

2016-08-02 23:50:53.5324|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-08-02 23:50:53.5324|ERROR|Wox.Plugin.Shell.Main.API_GlobalKeyboardEvent|Object reference not set to an instance of an object.
2016-08-02 23:50:53.5324|ERROR|Wox.Plugin.Shell.Main.API_GlobalKeyboardEvent|
   at Wox.Plugin.Shell.Main.API_GlobalKeyboardEvent(Int32 keyevent, Int32 vkcode, SpecialKeyState state) in C:\projects\wox\Plugins\Wox.Plugin.Shell\Main.cs:line 278
2016-08-02 23:50:54.5463|FATAL|Wox.Helper.ErrorReporting.Report|
## Exception

```
System.NullReferenceException: Object reference not set to an instance of an object.
   Source: Wox.Plugin.Shell
   TargetAssembly: Wox.Plugin.Shell, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Wox.Plugin.Shell.dll
   TargetSite: Boolean API_GlobalKeyboardEvent(Int32, Int32, Wox.Plugin.SpecialKeyState)
   at Wox.Plugin.Shell.Main.API_GlobalKeyboardEvent(Int32 keyevent, Int32 vkcode, SpecialKeyState state) in C:\projects\wox\Plugins\Wox.Plugin.Shell\Main.cs:line 278
   at Wox.Infrastructure.Hotkey.GlobalHotkey.LowLevelKeyboardProc(Int32 nCode, UIntPtr wParam, IntPtr lParam) in C:\projects\wox\Wox.Infrastructure\Hotkey\GlobalHotkey.cs:line 86

```
## Environment
- Command Line: "C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Wox.exe" 
- Timestamp: 08/02/2016 23:50:54
- IntPtr Length: 8
- System Version: Microsoft Windows NT 10.0.14393.0
- CLR Version: 4.0.30319.42000
- Installed .NET Framework: 
  - v2.0.50727 2.0.50727.4927 SP2
  - v3.0 3.0.30729.4926 SP2
  - v3.5 3.5.30729.4926 SP1
  - v4 Client 4.6.01586
  - v4 Full 4.6.01586
  - v4.0 Client 4.0.0.0
## Assemblies - Wox.exe
- Wox, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Wox.exe)
- Wox.Infrastructure, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Wox.Infrastructure.dll)
- Wox.Plugin, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Wox.Plugin.dll)
- Wox.Core, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Wox.Core.dll)
- Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Newtonsoft.Json.dll)
- HelloWorldCSharp, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\HelloWorldCSharp\HelloWorldCSharp.dll)
- Wox.Plugin.Caculator, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
- YAMP, Version=1.4.0.22422, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Caculator\YAMP.dll)
- Wox.Plugin.Color, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
- Wox.Plugin.ControlPanel, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
- Wox.Plugin.Everything, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
- Wox.Plugin.Folder, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
- Wox.Plugin.PluginIndicator, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
- Wox.Plugin.PluginManagement, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
- Wox.Plugin.Program, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
- Wox.Plugin.Shell, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
- WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\WindowsInput.dll)
- Wox.Plugin.Sys, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
- Wox.Plugin.Url, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
- Wox.Plugin.WebSearch, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
- NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\NHotkey.dll)
- NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\NHotkey.Wpf.dll)
- NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\Kaihang An\AppData\Local\Wox\app-1.3.183\NLog.dll)
- mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
- PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
- PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
- System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
- WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
- System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
- System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
- System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
- System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
- System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
- System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
- System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
- System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
- System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
- System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
- PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)
- System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
- PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll)
- UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll)
- System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)

**Comment by bao-qian** [comment]
1. 试一下删缓存：`%APPDATA%\Wox\Cache`
2. 不行的话试一下删设置，删前记得备份： `%APPDATA%\Wox\Settings`

**Comment by ztmdsbt** [comment]
删缓存解决了. 
Thank you!
