### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by Neetordy** [Wox-launcher/Wox#906]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 08/06/2016 06:42:23
Exception:
Wox.Plugin.Program

System.NullReferenceException
Object reference not set to an instance of an object.
   at Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 136
   at Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 102
   at Wox.Plugin.Program.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 94
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 27
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

[2016-08-06.txt](https://github.com/Wox-launcher/Wox/files/404730/2016-08-06.txt)

**Comment by bao-qian** [comment]
1. 试一下删缓存：`%APPDATA%\Wox\Cache`
2. 不行的话试一下删设置，删前记得备份： `%APPDATA%\Wox\Settings`

**Comment by bao-qian** [comment]
有问题再开
