### ISSUE TITLE
Wox.Infrastructure.Exception.WoxJsonRPCException

### ISSUE THREAD

**Issue by shuson** [Wox-launcher/Wox#910]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 08/07/2016 13:24:43
Exception:
Wox.Core
Wox.Infrastructure.Exception.WoxJsonRPCException
[0807/132443:ERROR:crash_report_database_win.cc(412)] unexpected header

   at Wox.Core.Plugin.JsonRPCPlugin.Execute(ProcessStartInfo startInfo) in C:\projects\wox\Wox.Core\Plugin\JsonRPCPlugin.cs:line 156
   at Wox.Core.Plugin.PythonPlugin.ExecuteCallback(JsonRPCRequestModel rpcRequest) in C:\projects\wox\Wox.Core\Plugin\PythonPlugin.cs:line 50
   at Wox.Core.Plugin.JsonRPCPlugin.<>c__DisplayClass7_0.<Query>b__0(ActionContext c) in C:\projects\wox\Wox.Core\Plugin\JsonRPCPlugin.cs:line 60
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 146
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
在用哪个插件的时候出现这个问题？

**Comment by shuson** [comment]
我自己的插件， 这部分用到了JsonRPCAction
`'JsonRPCAction': {
                    'method': 'open_url',
                    'parameters': [ptitle['href']]
                }`
也许是因为格式问题？

**Comment by bao-qian** [comment]
不好意思我忘了
`:crash_report_database_win.cc`
这你插件写的有问题啊。。。
你给个地址和说明  我可以帮忙看一看

**Comment by shuson** [comment]
麻烦你了，是这个文件
https://github.com/shuson/wox-plugin-sgcn/blob/master/sgcn.py

**Comment by bao-qian** [comment]
好像不是你的问题
是我的问题。。
我下班开电脑调一调

**Comment by dahendel** [comment]
[2017-01-19.txt](https://github.com/Wox-launcher/Wox/files/717726/2017-01-19.txt)

Steps to **reproduce** the bug: fz *site to connect to*

Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 01/19/2017 14:37:20
Exception:
Wox.Core
Wox.Infrastructure.Exception.WoxJsonRPCException
Traceback (most recent call last):
  File "C:\Users\nwo8002\AppData\Roaming\Wox\Plugins\Open in Filezilla-0e8b8d42-b79e-4e74-8dbf-520622e75db8\main.py", line 130, in <module>
    OpenInFz()
  File "C:\Users\nwo8002\AppData\Roaming\Wox\Plugins\Open in Filezilla-0e8b8d42-b79e-4e74-8dbf-520622e75db8\main.py", line 45, in __init__
    super(OpenInFz, self).__init__()
  File "C:\Users\nwo8002\AppData\Local\Wox\app-1.3.183\JsonRPC\wox.py", line 21, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\nwo8002\AppData\Roaming\Wox\Plugins\Open in Filezilla-0e8b8d42-b79e-4e74-8dbf-520622e75db8\main.py", line 121, in open_in_fz
    Popen([self.config['exe'], "-c", "0"+server])
  File "C:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

   at Wox.Core.Plugin.JsonRPCPlugin.Execute(ProcessStartInfo startInfo) in C:\projects\wox\Wox.Core\Plugin\JsonRPCPlugin.cs:line 156
   at Wox.Core.Plugin.PythonPlugin.ExecuteCallback(JsonRPCRequestModel rpcRequest) in C:\projects\wox\Wox.Core\Plugin\PythonPlugin.cs:line 50
   at Wox.Core.Plugin.JsonRPCPlugin.<>c__DisplayClass7_0.<Query>b__0(ActionContext c) in C:\projects\wox\Wox.Core\Plugin\JsonRPCPlugin.cs:line 60
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 146
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
