### ISSUE TITLE
System.Threading.Tasks.TaskCanceledException

### ISSUE THREAD

**Issue by andrey-str** [Wox-launcher/Wox#912]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 08/07/2016 20:04:24
Exception:
mscorlib
System.Threading.Tasks.TaskCanceledException
A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<GitHubUpdateManager>d__2b.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.Factory.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Wox.Core.Updater.<UpdateApp>d__0.MoveNext() in C:\projects\wox\Wox.Core\Updater.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by andrey-str** [comment]
[2016-08-07.txt](https://github.com/Wox-launcher/Wox/files/405617/2016-08-07.txt)

**Comment by bao-qian** [comment]
thanks, this exception is ignorable.

**Comment by andrey-str** [comment]
It is, Wox just asks me to post it here each time :-)

**Comment by bao-qian** [comment]
sorry for the inconvenience, it will be auto ignored next time :)

**Comment by bao-qian** [comment]
are you behind a proxy / firewall?

**Comment by andrey-str** [comment]
Kind of, I'm on OpenVPN connection.
