### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by niv-d** [Wox-launcher/Wox#914]
## English

Try search existing issues before you open new one
1. Wox version / commit number: 1.3.183
2. Steps to **reproduce** the bug: Start wox
3. Windows version: Microsoft Windows NT 10.0.10586.0
4. Exception:
   Wox version: 1.3.183
   OS Version: Microsoft Windows NT 10.0.10586.0
   Date: 08/08/2016 13:02:19
   Exception:
   Wox.Plugin.Program
   System.NullReferenceException
   Object reference not set to an instance of an object.
   at Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 136
   at Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 102
   at Wox.Plugin.Program.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 94
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 27
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
   [2016-08-07.txt](https://github.com/Wox-launcher/Wox/files/407397/2016-08-07.txt)

**Comment by bao-qian** [comment]
delete `%APPDATA%\Wox`
back up `%APPDATA\Wox\Settings` before you do that

**Comment by bao-qian** [comment]
close due to no response.
