### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by pantox** [Wox-launcher/Wox#926]
## English

Try search existing issues before you open new one
1. Wox version / commit number: 1.3.183
2. Steps to **reproduce** the bug: deleted chars with back key
3. Windows version: 10 Pro German
4. Exception:
   [2016-08-17.txt](https://github.com/Wox-launcher/Wox/files/422251/2016-08-17.txt)

Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 08/17/2016 11:44:38
Exception:
mscorlib
System.ArgumentOutOfRangeException
Der Einfügeindex liegt außerhalb des gültigen Bereichs. Der Index darf keine negative Zahl sein und muss kleiner oder gleich der Größe sein.
Parametername: index
   bei System.Collections.ArrayList.Insert(Int32 index, Object value)
   bei System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   bei System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   bei System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   bei MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
something wrong with a file icon, 
to identify which file
upload a screenshot of wox when you get this exception.

**Comment by pantox** [comment]
can't remember the search phrase, so I can't reproduce the error.

**Comment by nakulbende** [comment]
Do the icon files have to be a certain resolution? Perhaps I had high resolution files?

**Comment by bao-qian** [comment]
@nakulbende no, high resolution is fine

**Comment by bao-qian** [comment]
known info so far:
possible related to web search plugin or `ImageLoader`

**Comment by nakulbende** [comment]
I cant reproduce the crash - I just tried to set an icon, which works until I restart wox, which erases any settings done to the plugin icons.

**Comment by happlebao** [comment]
@nakulbende upload 
1. the icon
2. `%APPDATA%\Wox\Settings\Settings.json`
3. `%APPDATA%\Wox\Settings\Plugins\Wox.Plugin.WebSearchWox\Settings\Settings.json`

**Comment by bao-qian** [comment]
I'd appreciate if sb can **reproduce** the crash

**Comment by nakulbende** [comment]
Here you go!

Nakul Prabhakar Bende
Graduate Student,
Hayward Research group, PSE, UMass Amherst
http://nakulbende.com

- Ever tried. Ever failed. Try Again. Fail again. Fail better.
 --Samuel Beckett

**Comment by nakulbende** [comment]
Actually, I updated the settings.json for plugint o include the icon paths,
and restarted the wox. TO my surprise - the file was re-written! and all
the icon paths were deleted.



Nakul Prabhakar Bende
Graduate Student,
Hayward Research group, PSE, UMass Amherst
http://nakulbende.com

- Ever tried. Ever failed. Try Again. Fail again. Fail better.
 --Samuel Beckett

**Comment by nakulbende** [comment]
Hello @happlebao, I was able to reproduce the crash. Here is what I know by now. 

- This seems to be an issue with websearch plugin, as the crash mostly happens when i am searching a keyword or editing the search queries. 

- This crash happened while I was trying to add a new query.

- No matter how many times I set the icon files, either by GUI or by editing settiongs.json, the icon settings get reset after a re-start. In fact, the settings.json file gets overewritten. Surprisingly, only the icon paths are lost, and the query details and keywords are fine.

and the screenshot: 

![image](https://cloud.githubusercontent.com/assets/8712050/23331541/edb7bb1c-fb35-11e6-9fac-8bb191c5549a.png)

Here is the log: 

Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 02/25/2017 08:34:02
Exception:
Wox.Plugin.WebSearch
System.NullReferenceException
Object reference not set to an instance of an object.
   at Wox.Plugin.WebSearch.SearchSourceSettingWindow..ctor(IList`1 sources, PluginInitContext context, SearchSource old) in C:\projects\wox\Plugins\Wox.Plugin.WebSearch\SearchSourceSetting.xaml.cs:line 23
   at Wox.Plugin.WebSearch.SettingsControl.OnEditSearchSourceClick(Object sender, RoutedEventArgs e) in C:\projects\wox\Plugins\Wox.Plugin.WebSearch\SettingsControl.xaml.cs:line 47
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by nakulbende** [comment]
Maybe a little more details, and I hope this helps

- If I make a new entry, and put a png in plugin/image folder, selecting icon file generates this error even if the file is in the appropriate folder.

![image](https://cloud.githubusercontent.com/assets/8712050/23331585/0e61958a-fb37-11e6-9c41-c4a33cc73666.png)

- If I restart wox, the error goes away, I can set the icon, and it actually shows up in search queries!

![image](https://cloud.githubusercontent.com/assets/8712050/23331595/3b5cc528-fb37-11e6-9c31-667088e31e2e.png)
![image](https://cloud.githubusercontent.com/assets/8712050/23331597/459eaf10-fb37-11e6-9410-de066eb611a9.png)

- But again, if I restart, this just goes away. 
![image](https://cloud.githubusercontent.com/assets/8712050/23331602/5d2d2e90-fb37-11e6-8905-294aa7a32e8d.png)

**Comment by bao-qian** [comment]
@nakulbende 
hi thank for you update, but this is a seperate issue, and has already been solved by 
https://github.com/Wox-launcher/Wox/releases/tag/v1.3.357

**Comment by nakulbende** [comment]
Hey @happlebao 

Thanks so much! I look forward to get this on a stable channel - I am not sure how unstable are the pre-release channel. 

Again, thanks for Wox!

**Comment by archon810** [comment]
Just happened to me in version 1.3.578.

### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Started typing wpm.
2. Crash.

### Wox Error Window text

Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\Artem Russakovskii\AppData\Roaming\Wox\Logs\1.3.578\2019-01-06.txt
2. copy below exception message

```
Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.17763.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\Artem Russakovskii\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 01/06/2019 11:53:49
Exception:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.set_Item(Int32 index, Object value)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   at System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```


### Detailed logs
https://gist.github.com/4d35e422a657c42daa8a36b9f6f95d01

Hope this helps. The issue was not reproducible upon typing wpm after a restart.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
