### ISSUE TITLE
ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by joooohnli** [Wox-launcher/Wox#928]
1. Wox version / commit number: v1.3.183
2. Steps to **reproduce** the bug: alt + space => crash
3. Windows version:win 7
4. Exception:
   Wox version: 1.3.183
   OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
   Date: 08/18/2016 12:46:38
   Exception:
   mscorlib
   System.ArgumentOutOfRangeException
   Insertion index was out of range. Must be non-negative and less than or equal to size.
   Parameter name: index
   at System.Collections.ArrayList.Insert(Int32 index, Object value)
   at System.Windows.Data.ListCollectionView.AdjustShadowCopy(NotifyCollectionChangedEventArgs e)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   at System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
   [2016-08-18.txt](https://github.com/Wox-launcher/Wox/files/424157/2016-08-18.txt)
6. Screenshot (optional):

**Comment by bao-qian** [comment]
try to make a clean log
1. delete `%APPDATA%\Wox\Logs\version\same_date.txt`
2. start wox, and reproduce errors
3. upload new log (``%APPDATA%\Wox\Logs\version\same_date.txt`)

**Comment by bao-qian** [comment]
close due to no response
