### ISSUE TITLE
[Wox.Plugin.Doc] System.Data.SQLite.SQLiteException

### ISSUE THREAD

**Issue by rodshtein** [Wox-launcher/Wox#929]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 08/18/2016 18:44:50
Exception:
System.Data.SQLite
System.Data.SQLite.SQLiteException
unable to open database file
   at System.Data.SQLite.SQLite3.Open(String strFilename, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   at System.Data.SQLite.SQLiteConnection.Open()
   at Wox.Plugin.Doc.DocSet.CheckTableExists(String table, String path) in e:\github\Wox.Plugin.Doc\DocSet.cs:line 50
   at Wox.Plugin.Doc.DocSet.Load(String pluginDirectory) in e:\github\Wox.Plugin.Doc\DocSet.cs:line 36
   at Wox.Plugin.Doc.Main.Init(PluginInitContext context) in e:\github\Wox.Plugin.Doc\Main.cs:line 31
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 28
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

2016-08-18 12:04:31.9982|INFO|Wox.Plugin.Program.Main.Init|Preload 228 programs from cache
2016-08-18 12:04:37.3437|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-08-18 12:04:37.3437|ERROR|System.Windows.Forms.DataFormats.GetFormat|Clipboard format registration did not succeed.
2016-08-18 12:04:39.9639|ERROR|System.Windows.Forms.DataFormats.GetFormat|
   at System.Windows.Forms.DataFormats.GetFormat(String format)
2016-08-18 12:05:37.0569|INFO|Wox.App.<OnStartup>b__8_0|Preload 200 images from cache
2016-08-18 12:05:48.9089|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-08-18 12:05:48.9089|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-08-18 12:05:49.0081|ERROR|System.Windows.Interop.InteropBitmap..ctor|Invalid cursor handle. (Exception from HRESULT: 0x8007057A)
2016-08-18 12:05:49.0101|ERROR|System.Windows.Interop.InteropBitmap..ctor|Invalid cursor handle. (Exception from HRESULT: 0x8007057A)
2016-08-18 12:05:49.4415|ERROR|System.Windows.Interop.InteropBitmap..ctor|
   at System.Windows.Interop.InteropBitmap..ctor(IntPtr hicon, Int32Rect sourceRect, BitmapSizeOptions sizeOptions)
2016-08-18 12:05:49.4415|ERROR|System.Windows.Interop.InteropBitmap..ctor|
   at System.Windows.Interop.InteropBitmap..ctor(IntPtr hicon, Int32Rect sourceRect, BitmapSizeOptions sizeOptions)
2016-08-18 12:05:49.4946|ERROR|Wox.Infrastructure.Image.ImageLoader.AssociatedIcon|Invalid cursor handle. (Exception from HRESULT: 0x8007057A)
2016-08-18 12:05:49.4946|ERROR|Wox.Infrastructure.Image.ImageLoader.AssociatedIcon|Invalid cursor handle. (Exception from HRESULT: 0x8007057A)
2016-08-18 12:05:50.1458|ERROR|Wox.Infrastructure.Image.ImageLoader.AssociatedIcon|
   at System.Windows.Interop.InteropBitmap..ctor(IntPtr hicon, Int32Rect sourceRect, BitmapSizeOptions sizeOptions)
   at System.Windows.Interop.Imaging.CreateBitmapSourceFromHIcon(IntPtr icon, Int32Rect sourceRect, BitmapSizeOptions sizeOptions)
   at Wox.Infrastructure.Image.ImageLoader.ImageFromIcon(Icon icon) in C:\projects\wox\Wox.Infrastructure\Image\ImageLoader.cs:line 74
   at Wox.Infrastructure.Image.ImageLoader.AssociatedIcon(String path) in C:\projects\wox\Wox.Infrastructure\Image\ImageLoader.cs:line 86
2016-08-18 12:05:50.1458|ERROR|Wox.Infrastructure.Image.ImageLoader.AssociatedIcon|
   at System.Windows.Interop.InteropBitmap..ctor(IntPtr hicon, Int32Rect sourceRect, BitmapSizeOptions sizeOptions)
   at System.Windows.Interop.Imaging.CreateBitmapSourceFromHIcon(IntPtr icon, Int32Rect sourceRect, BitmapSizeOptions sizeOptions)
   at Wox.Infrastructure.Image.ImageLoader.ImageFromIcon(Icon icon) in C:\projects\wox\Wox.Infrastructure\Image\ImageLoader.cs:line 74
   at Wox.Infrastructure.Image.ImageLoader.AssociatedIcon(String path) in C:\projects\wox\Wox.Infrastructure\Image\ImageLoader.cs:line 86
2016-08-18 15:10:42.8138|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-08-18 15:10:42.8548|ERROR|System.Windows.Forms.DataFormats.GetFormat|Clipboard format registration did not succeed.
2016-08-18 15:10:42.8548|ERROR|System.Windows.Forms.DataFormats.GetFormat|
   at System.Windows.Forms.DataFormats.GetFormat(String format)
2016-08-18 17:59:20.1619|INFO|Wox.Plugin.Program.Main.Init|Preload 228 programs from cache
2016-08-18 17:59:25.2681|INFO|Wox.App.<OnStartup>b__8_0|Preload 200 images from cache
2016-08-18 18:18:41.5361|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-08-18 18:18:41.5451|ERROR|System.Runtime.InteropServices.ComTypes.IDataObject.GetData|CloseClipboard Failed (Exception from HRESULT: 0x800401D4 (CLIPBRD_E_CANT_CLOSE))
2016-08-18 18:18:41.8991|ERROR|System.Runtime.InteropServices.ComTypes.IDataObject.GetData|
   at System.Runtime.InteropServices.ComTypes.IDataObject.GetData(FORMATETC& format, STGMEDIUM& medium)
   at System.Windows.Forms.DataObject.OleConverter.GetDataFromOleOther(String format)
2016-08-18 18:18:41.9061|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-08-18 18:18:41.9061|ERROR|System.Runtime.InteropServices.ComTypes.IDataObject.GetData|Invalid tymed (Exception from HRESULT: 0x80040069 (DV_E_TYMED))
2016-08-18 18:18:41.9176|ERROR|System.Runtime.InteropServices.ComTypes.IDataObject.GetData|
   at System.Runtime.InteropServices.ComTypes.IDataObject.GetData(FORMATETC& format, STGMEDIUM& medium)
   at System.Windows.Forms.DataObject.OleConverter.GetDataFromOleHGLOBAL(String format)
2016-08-18 18:18:41.9176|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-08-18 18:18:41.9342|ERROR|System.Runtime.InteropServices.ComTypes.IDataObject.GetData|Invalid tymed (Exception from HRESULT: 0x80040069 (DV_E_TYMED))
2016-08-18 18:18:41.9532|ERROR|System.Runtime.InteropServices.ComTypes.IDataObject.GetData|
   at System.Runtime.InteropServices.ComTypes.IDataObject.GetData(FORMATETC& format, STGMEDIUM& medium)
   at System.Windows.Forms.DataObject.OleConverter.GetDataFromOleIStream(String format)
2016-08-18 18:44:44.0174|INFO|Wox.Plugin.Program.Main.Init|Preload 229 programs from cache
2016-08-18 18:44:45.5024|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-08-18 18:44:45.5115|ERROR|System.Data.SQLite.SQLite3.Open|unable to open database file
2016-08-18 18:44:45.5399|ERROR|System.Data.SQLite.SQLite3.Open|
   at System.Data.SQLite.SQLite3.Open(String strFilename, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
2016-08-18 18:44:45.5459|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-08-18 18:44:45.5459|ERROR|System.Data.SQLite.SQLiteConnection.Open|unable to open database file
2016-08-18 18:44:45.5579|ERROR|System.Data.SQLite.SQLiteConnection.Open|
   at System.Data.SQLite.SQLite3.Open(String strFilename, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   at System.Data.SQLite.SQLiteConnection.Open()
2016-08-18 18:44:45.6539|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-08-18 18:44:45.6539|ERROR|System.Threading.Tasks.Parallel+<>c__DisplayClass17_0`1.<ForWorker>b__1|unable to open database file
2016-08-18 18:44:46.3849|ERROR|System.Threading.Tasks.Parallel+<>c__DisplayClass17_0`1.<ForWorker>b__1|
   at System.Data.SQLite.SQLite3.Open(String strFilename, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   at System.Data.SQLite.SQLiteConnection.Open()
   at Wox.Plugin.Doc.DocSet.CheckTableExists(String table, String path) in e:\github\Wox.Plugin.Doc\DocSet.cs:line 50
   at Wox.Plugin.Doc.DocSet.Load(String pluginDirectory) in e:\github\Wox.Plugin.Doc\DocSet.cs:line 36
   at Wox.Plugin.Doc.Main.Init(PluginInitContext context) in e:\github\Wox.Plugin.Doc\Main.cs:line 31
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 28
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
2016-08-18 18:44:49.8340|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-08-18 18:44:49.8400|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|One or more errors occurred.
2016-08-18 18:44:49.8400|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2016-08-18 18:44:49.8400|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|unable to open database file
2016-08-18 18:44:49.8680|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|
   at System.Data.SQLite.SQLite3.Open(String strFilename, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   at System.Data.SQLite.SQLiteConnection.Open()
   at Wox.Plugin.Doc.DocSet.CheckTableExists(String table, String path) in e:\github\Wox.Plugin.Doc\DocSet.cs:line 50
   at Wox.Plugin.Doc.DocSet.Load(String pluginDirectory) in e:\github\Wox.Plugin.Doc\DocSet.cs:line 36
   at Wox.Plugin.Doc.Main.Init(PluginInitContext context) in e:\github\Wox.Plugin.Doc\Main.cs:line 31
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 28
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
2016-08-18 18:44:49.8735|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-08-18 18:44:49.8735|ERROR|System.Threading.Tasks.Parallel.ForWorker|One or more errors occurred.
2016-08-18 18:44:49.8875|ERROR|System.Threading.Tasks.Parallel.ForWorker|
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
2016-08-18 18:44:49.8875|ERROR|System.Threading.Tasks.Parallel.ForWorker|unable to open database file
2016-08-18 18:44:49.9015|ERROR|System.Threading.Tasks.Parallel.ForWorker|
   at System.Data.SQLite.SQLite3.Open(String strFilename, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   at System.Data.SQLite.SQLiteConnection.Open()
   at Wox.Plugin.Doc.DocSet.CheckTableExists(String table, String path) in e:\github\Wox.Plugin.Doc\DocSet.cs:line 50
   at Wox.Plugin.Doc.DocSet.Load(String pluginDirectory) in e:\github\Wox.Plugin.Doc\DocSet.cs:line 36
   at Wox.Plugin.Doc.Main.Init(PluginInitContext context) in e:\github\Wox.Plugin.Doc\Main.cs:line 31
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 28
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
2016-08-18 18:44:50.1348|FATAL|Wox.Helper.ErrorReporting.Report|
## Exception

```
System.Data.SQLite.SQLiteException: unable to open database file
   Source: System.Data.SQLite
   TargetAssembly: System.Data.SQLite, Version=1.0.93.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139
   TargetModule: System.Data.SQLite.dll
   TargetSite: Void Open(System.String, System.Data.SQLite.SQLiteConnectionFlags, System.Data.SQLite.SQLiteOpenFlagsEnum, Int32, Boolean)
   at System.Data.SQLite.SQLite3.Open(String strFilename, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   at System.Data.SQLite.SQLiteConnection.Open()
   at Wox.Plugin.Doc.DocSet.CheckTableExists(String table, String path) in e:\github\Wox.Plugin.Doc\DocSet.cs:line 50
   at Wox.Plugin.Doc.DocSet.Load(String pluginDirectory) in e:\github\Wox.Plugin.Doc\DocSet.cs:line 36
   at Wox.Plugin.Doc.Main.Init(PluginInitContext context) in e:\github\Wox.Plugin.Doc\Main.cs:line 31
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 28
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

System.AggregateException: One or more errors occurred.
   Source: mscorlib
   TargetAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
   TargetModule: CommonLanguageRuntimeLibrary
   TargetSite: Void ThrowIfExceptional(Boolean)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 94
   at Wox.App.<OnStartup>b__8_0() in C:\projects\wox\Wox\App.xaml.cs:line 53
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 28
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```
## Environment
- Command Line: "C:\Users\Kot\AppData\Local\Wox\app-1.3.183\Wox.exe" 
- Timestamp: 08/18/2016 18:44:50
- IntPtr Length: 8
- System Version: Microsoft Windows NT 10.0.10586.0
- CLR Version: 4.0.30319.42000
- Installed .NET Framework: 
  - v2.0.50727 2.0.50727.4927 SP2
  - v3.0 3.0.30729.4926 SP2
  - v3.5 3.5.30729.4926 SP1
  - v4 Client 4.6.01038
  - v4 Full 4.6.01038
  - v4.0 Client 4.0.0.0
## Assemblies - Wox.exe
- Wox, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\Wox.exe)
- Wox.Infrastructure, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\Wox.Infrastructure.dll)
- Wox.Plugin, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\Wox.Plugin.dll)
- Wox.Core, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\Wox.Core.dll)
- Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\Newtonsoft.Json.dll)
- HelloWorldCSharp, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\Plugins\HelloWorldCSharp\HelloWorldCSharp.dll)
- Wox.Plugin.Caculator, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
- YAMP, Version=1.4.0.22422, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Caculator\YAMP.dll)
- Wox.Plugin.Color, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
- Wox.Plugin.ControlPanel, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
- Wox.Plugin.Everything, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
- Wox.Plugin.Folder, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
- Wox.Plugin.PluginIndicator, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
- Wox.Plugin.PluginManagement, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
- Wox.Plugin.Program, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
- Wox.Plugin.Shell, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
- WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\WindowsInput.dll)
- Wox.Plugin.Sys, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
- Wox.Plugin.Url, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
- Wox.Plugin.WebSearch, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
- Wox.Plugin.Clipboard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Roaming\Wox\Plugins\Clipboard History-203876f1-5efc-4901-a123-9abbb1a68ea4\Wox.Plugin.Clipboard.dll)
- WindowsInput, Version=0.2.0.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\Kot\AppData\Roaming\Wox\Plugins\Clipboard History-203876f1-5efc-4901-a123-9abbb1a68ea4\WindowsInput.dll)
- Wox.Plugin.Doc, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Roaming\Wox\Plugins\Dash.Doc-bd070549-a068-41f0-92b1-7ac4d8fd046c\Wox.Plugin.Doc.dll)
- Wox.Plugin.Giphy, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Roaming\Wox\Plugins\Giphy-ac67b300-f3ba-450a-8827-733c482d6931\Wox.Plugin.Giphy.dll)
- Wox.Plugin.KickassTorrents, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Roaming\Wox\Plugins\KickassTorrents-755669cb-c27b-4071-b4ba-22ff58001dce\Wox.Plugin.KickassTorrents.dll)
- Wox.Plugin.PirateBay, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Roaming\Wox\Plugins\PirateBay-4f2a43b4-139a-4425-969e-0e8b3df14158\Wox.Plugin.PirateBay.dll)
- NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\NHotkey.dll)
- NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\NHotkey.Wpf.dll)
- NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\Kot\AppData\Local\Wox\app-1.3.183\NLog.dll)
- System.Data.SQLite, Version=1.0.93.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139 (C:\Users\Kot\AppData\Roaming\Wox\Plugins\Dash.Doc-bd070549-a068-41f0-92b1-7ac4d8fd046c\System.Data.SQLite.dll)
- mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
- PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
- WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
- System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
- System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
- PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
- System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
- System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
- System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
- System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
- System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
- System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
- System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
- System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
- System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
- System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
- PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)
- System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
- System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll)

2016-08-18 18:45:08.6994|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-08-18 18:45:08.6994|ERROR|System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment|Application identity is not set.
2016-08-18 18:45:08.7269|ERROR|System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment|
   at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()

**Comment by lances101** [comment]
@zamkevich What docsets do you have installed? How did you install them? You should end up with a  path similar to the following 
`Wox\Plugins\Dash.Doc-4a4e8058-f8f6-4f23-aee4-4804a0ceea72\Docset\CSS.docset\`

**Comment by rodshtein** [comment]
The error was in the plugin settings.

**Comment by lances101** [comment]
@zamkevich @happlebao resolved?

**Comment by rodshtein** [comment]
yep!
