### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by mzaur** [Wox-launcher/Wox#935]
## English

Try search existing issues before you open new one
1. Wox version / commit number: 
   [2016-08-20.txt](https://github.com/Wox-launcher/Wox/files/428494/2016-08-20.txt)
2. Steps to **reproduce** the bug: Open Wox. 
   This started when I installed a new graphics card AMD RX 480 and installed the new 16.8.2 AMD drivers. Did not have issue previously.
3. Windows version: Windows 10 latest
4. Exception:
   Wox version: 1.3.183
   OS Version: Microsoft Windows NT 10.0.14393.0
   Date: 08/20/2016 14:52:25
   Exception:
   Wox.Plugin.Program
   System.NullReferenceException
   Object reference not set to an instance of an object.
   at Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 136
   at Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 102
   at Wox.Plugin.Program.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 94
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 27
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 
## 中文 / Chinese

提问之前搜索一下已经有的 issue
1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by bao-qian** [comment]
cache broken
you could either delete `%APPDATA%\Wox\Cache` or download new build https://ci.appveyor.com/project/happlebao/wox/build/1.3.272

**Comment by mzaur** [comment]
Thanks. Deleting cache did not fix. 

Github still has .138 build. Not sure how to download from the link you sent?

**Comment by mzaur** [comment]
Nevermind got it. 272 still doesn't fix though :/ It closes before I can copy exception

[2016-08-20.txt](https://github.com/Wox-launcher/Wox/files/428552/2016-08-20.txt)

```
System.NullReferenceException: Object reference not set to an instance of an object.
   Source: Wox.Plugin.Shell
   TargetAssembly: Wox.Plugin.Shell, Version=1.3.272.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Wox.Plugin.Shell.dll
   TargetSite: Boolean API_GlobalKeyboardEvent(Int32, Int32, Wox.Plugin.SpecialKeyState)
   at Wox.Plugin.Shell.Main.API_GlobalKeyboardEvent(Int32 keyevent, Int32 vkcode, SpecialKeyState state) in C:\projects\wox\Plugins\Wox.Plugin.Shell\Main.cs:line 278
   at Wox.Infrastructure.Hotkey.GlobalHotkey.LowLevelKeyboardProc(Int32 nCode, UIntPtr wParam, IntPtr lParam) in C:\projects\wox\Wox.Infrastructure\Hotkey\GlobalHotkey.cs:line 86

```

**Comment by bao-qian** [comment]
try delete `%APPDATA%\Wox\Settings\Plugins\Wox.Plugin.Shell`

**Comment by mzaur** [comment]
OK I did. Now it doesn't crash. Stays open. But if I type something in the search box, I get no results. Reinstalling Wox did not fix.
[2016-08-20.txt](https://github.com/Wox-launcher/Wox/files/428594/2016-08-20.txt)

**Comment by mzaur** [comment]
I go to settings -> plugin -> everything and it crashes

Wox version: 1.3.272
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True
Python Path: 
Everything SDK Path: C:\Users\Michael\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 08/20/2016 18:51:07
Exception:
Wox.Plugin.Everything
System.NullReferenceException
Object reference not set to an instance of an object.
   at Wox.Plugin.Everything.EverythingSettings.View_Loaded(Object sender, RoutedEventArgs re) in C:\projects\wox\Plugins\Wox.Plugin.Everything\EverythingSettings.xaml.cs:line 18
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2016-08-20.txt](https://github.com/Wox-launcher/Wox/files/428597/2016-08-20.txt)

**Comment by bao-qian** [comment]
It seems like all setting files are broken..
just delete whole directory:
`%APPDATA%\Wox\`
remember backup the directory before you do that.

**Comment by mzaur** [comment]
That fixed it thanks!
