### ISSUE TITLE
System.NullReferenceException - ImageCache is used by another program

### ISSUE THREAD

**Issue by jupitia** [Wox-launcher/Wox#946]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 08/25/2016 11:13:48
Exception:
Wox
System.NullReferenceException
Object reference not set to an instance of an object.
   at Wox.ViewModel.SettingWindowViewModel..ctor() in C:\projects\wox\Wox\ViewModel\SettingWindowViewModel.cs:line 28
   at Wox.App.<OnStartup>b__8_0() in C:\projects\wox\Wox\App.xaml.cs:line 44
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 27
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jupitia** [comment]
[2016-08-25.txt](https://github.com/Wox-launcher/Wox/files/437377/2016-08-25.txt)

**Comment by bao-qian** [comment]
delete `%APPDATA%\Wox`, backup before you do that

**Comment by jupitia** [comment]
I figured it out by trying to install v1.3.0, which generated a more reader friendly error report addressing that a file in %APPDATA%/%/Wox relates to image cache was using by another program. It simply led me to delete that folder, and install v1.3.183 successfully.

**Comment by bao-qian** [comment]
Thanks for your info
