### ISSUE TITLE
Wox.Plugin.ImgurScreenshot

### ISSUE THREAD

**Issue by djedlajn** [Wox-launcher/Wox#957]
[2016-09-01.txt](https://github.com/Wox-launcher/Wox/files/449403/2016-09-01.txt)
## Known problems for 1.3.813:
1. `System.NullReferenceException`: try reset wox by delete %APPDATA%\Wox, backup before you do that
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: 设置 http 代理
## English

Try search existing issues before you open new one
1. Wox version: 1.3.183
2. Steps to **reproduce** the bug: Just try using Snap Plugin
3. OS Version: Microsoft Windows NT 10.0.14393.0
4. Exception: 

```
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 09/01/2016 12:36:43
Exception:
Wox.Plugin.ImgurScreenshot
System.MissingMethodException
Method not found: 'Void Wox.Plugin.Query..ctor(System.String)'.
   at Main.<>c__DisplayClass4_0.<Query>b__0(ActionContext e)
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 146
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```
1. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
2. Screenshot (optional): 
## 中文 / Chinese

提问之前搜索一下已经有的 issue
1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by bao-qian** [comment]
just delete this plugin from `%APPDATA%\Wox\Plugins\Wox.Plugin.ImgurScreenshot`

**Comment by djedlajn** [comment]
The wox works really well, i have deleted the plugin with uninstall command the error occurs only when i try to use plugin, i was hoping to submit more data so that plugin gets fixed because it is really awesome idea.

**Comment by lances101** [comment]
@kadza93 the plugin was compiled for an older version of Wox and has not been updated since. I don't know if you will be able to contact the developer, but [here's the link to the wpm page](http://www.getwox.com/plugin/51). The problem is that the dev did not provide a github link to his repo or any other contact information. 

Last time a similar thing happened with the `Translate` plugin, I decompiled, fixed and reuploaded it with a different name. But right now I don't have enough time to maintain another plugin. If somebody volunteers that would be great. 

@happlebao, this is not a Wox issue. We don't really have a procedure of what to do with out of date plugins, but I guess this issue can be closed unresolved.

**Comment by djedlajn** [comment]
@lances101 Thanks for heads up i suppose that fix for future problems of this kind would be solved if github repos wore made to be mandatory for plugin to get approval.
