### ISSUE TITLE
Exception during startup

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#964]
```
2016-09-05 19:42:13.7510|ERROR|Wox.Plugin.Program.Programs.Win32.LnkProgram|Error when parsing shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Desktop.lnk
2016-09-05 19:42:14.1676|ERROR|Wox.Plugin.Program.Programs.UWP.<InitializeAppDisplayInfo>b__34_0|Can't get logo for windows.immersivecontrolpanel
2016-09-05 19:42:14.1676|ERROR|Wox.Plugin.Program.Programs.UWP.<InitializeAppDisplayInfo>b__34_0|Can't get logo for Microsoft.BioEnrollment
2016-09-05 19:42:14.1766|ERROR|Wox.Plugin.Program.Programs.UWP.<InitializeAppDisplayInfo>b__34_0|The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
2016-09-05 19:42:14.1766|ERROR|Wox.Plugin.Program.Programs.UWP.<InitializeAppDisplayInfo>b__34_0|The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
2016-09-05 19:42:14.1896|ERROR|Wox.Plugin.Program.Programs.UWP.<InitializeAppDisplayInfo>b__34_0|
   at Windows.ApplicationModel.AppDisplayInfo.GetLogo(Size size)
   at Wox.Plugin.Program.Programs.UWP.<InitializeAppDisplayInfo>b__34_0(AppListEntry a) in C:\Users\Ricky\Documents\GitHub\Wox\Plugins\Wox.Plugin.Program\Programs\UWP.cs:line 113
2016-09-05 19:42:14.1896|ERROR|Wox.Plugin.Program.Programs.UWP.<InitializeAppDisplayInfo>b__34_0|
   at Windows.ApplicationModel.AppDisplayInfo.GetLogo(Size size)
   at Wox.Plugin.Program.Programs.UWP.<InitializeAppDisplayInfo>b__34_0(AppListEntry a) in C:\Users\Ricky\Documents\GitHub\Wox\Plugins\Wox.Plugin.Program\Programs\UWP.cs:line 113
2016-09-05 19:42:14.2637|ERROR|Wox.Plugin.Program.Programs.UWP.<InitializeAppDisplayInfo>b__34_0|Can't get logo for Microsoft.Windows.SecondaryTileExperience
2016-09-05 19:42:14.2637|ERROR|Wox.Plugin.Program.Programs.UWP.<InitializeAppDisplayInfo>b__34_0|The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
2016-09-05 19:42:14.2637|ERROR|Wox.Plugin.Program.Programs.UWP.<InitializeAppDisplayInfo>b__34_0|
   at Windows.ApplicationModel.AppDisplayInfo.GetLogo(Size size)
   at Wox.Plugin.Program.Programs.UWP.<InitializeAppDisplayInfo>b__34_0(AppListEntry a) in C:\Users\Ricky\Documents\GitHub\Wox\Plugins\Wox.Plugin.Program\Programs\UWP.cs:line 113
2016-09-05 19:42:14.4720|ERROR|Wox.Plugin.Program.Programs.UWP.<InitializeAppDisplayInfo>b__34_0|Can't get logo for Windows.MiracastView
2016-09-05 19:42:14.4720|ERROR|Wox.Plugin.Program.Programs.UWP.<InitializeAppDisplayInfo>b__34_0|The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
2016-09-05 19:42:14.4865|ERROR|Wox.Plugin.Program.Programs.UWP.<InitializeAppDisplayInfo>b__34_0|
   at Windows.ApplicationModel.AppDisplayInfo.GetLogo(Size size)
   at Wox.Plugin.Program.Programs.UWP.<InitializeAppDisplayInfo>b__34_0(AppListEntry a) in C:\Users\Ricky\Documents\GitHub\Wox\Plugins\Wox.Plugin.Program\Programs\UWP.cs:line 113
2016-09-05 19:42:14.4720|ERROR|Wox.Plugin.Program.Programs.UWP.<InitializeAppDisplayInfo>b__34_0|Can't get logo for Windows.PrintDialog
2016-09-05 19:42:14.5040|ERROR|Wox.Plugin.Program.Programs.UWP.<InitializeAppDisplayInfo>b__34_0|The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
2016-09-05 19:42:14.5040|ERROR|Wox.Plugin.Program.Programs.UWP.<InitializeAppDisplayInfo>b__34_0|
   at Windows.ApplicationModel.AppDisplayInfo.GetLogo(Size size)
   at Wox.Plugin.Program.Programs.UWP.<InitializeAppDisplayInfo>b__34_0(AppListEntry a) in C:\Users\Ricky\Documents\GitHub\Wox\Plugins\Wox.Plugin.Program\Programs\UWP.cs:line 113
```
- [ ] desktop.lnk
- [x] logo for uwp system apps

**Comment by bao-qian** [comment]
```
2017-01-30 00:23:49.5788|ERROR|UWP.LogoPathFromUri| <Windows.MiracastView_cw5n1h2txyewy!Microsoft.Windows.MiracastView> can't find logo uri for <SmallLogo.png>, Package location <C:\Windows\MiracastView>.
2017-01-30 00:23:49.6583|ERROR|UWP.ResourceFromPri|-------------------------- Begin exception --------------------------
2017-01-30 00:23:49.6648|ERROR|UWP.ResourceFromPri|Load pri failed <@{Microsoft.BingFoodAndDrink_3.0.4.336_x64__8wekyb3d8bbwe? ms-resource:///resources/AppDescription}> with HResult <2147942522> and location <C:\Program Files\WindowsApps\Microsoft.BingFoodAndDrink_3.0.4.336_x64__8wekyb3d8bbwe>.
2017-01-30 00:23:49.6648|ERROR|UWP.ResourceFromPri|Exception message:
 <Unspecified error

'Microsoft Corporation' violates pattern constraint of '\bms-resource:.{1,256}'.
>
2017-01-30 00:23:49.6783|ERROR|UWP.ResourceFromPri|Exception stack trace:
 <>
2017-01-30 00:23:49.6783|ERROR|UWP.ResourceFromPri|-------------------------- End exception --------------------------
2017-01-30 00:23:49.7018|ERROR|UWP.ResourceFromPri|-------------------------- Begin exception --------------------------
2017-01-30 00:23:49.7148|ERROR|UWP.ResourceFromPri|Load pri failed <@{Microsoft.MicrosoftOfficeHub_17.7608.23501.0_x64__8wekyb3d8bbwe? ms-resource://Microsoft.MicrosoftOfficeHub/officehubintl/AppManifest_GetOffice_Description}> with HResult <2147942522> and location <C:\Program Files\WindowsApps\Microsoft.MicrosoftOfficeHub_17.7608.23501.0_x64__8wekyb3d8bbwe>.
2017-01-30 00:23:49.7148|ERROR|UWP.ResourceFromPri|Exception message:
 <Unspecified error

'Microsoft Corporation' violates pattern constraint of '\bms-resource:.{1,256}'.
>
2017-01-30 00:23:49.7258|ERROR|UWP.ResourceFromPri|Exception stack trace:
 <>
2017-01-30 00:23:49.7258|ERROR|UWP.ResourceFromPri|-------------------------- End exception --------------------------
```

<del> for the last two,
we can test `SHLoadIndirectString` with 1 full origin pri path, 2 temp path in user directory, so check whether it is a permission issue. and test `ms-resource://Microsoft.BingFoodAndDrink/resources/AppDescription` and `ms-resource://resources/AppDescription` for format issue. </del>

since bing/msn food & drink is discontinued and getoffice is useless, just uninstall it.
