### ISSUE TITLE
System.Net.WebException

### ISSUE THREAD

**Issue by ghost** [Wox-launcher/Wox#970]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 09/09/2016 11:41:57
Exception:
System
System.Net.WebException
The operation has timed out
   at System.Net.FileWebRequest.GetResponse()
   at MS.Internal.WpfWebRequestHelper.GetResponseStream(WebRequest request, ContentType& contentType)
   at System.Windows.ResourceDictionary.set_Source(Uri value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
[2016-09-09.txt](https://github.com/Wox-launcher/Wox/files/463682/2016-09-09.txt)

**Comment by bao-qian** [comment]
> the remote name could not be resolved: 'api.github.com'

check your network settings...
