### ISSUE TITLE
spotify plugin error

### ISSUE THREAD

**Issue by arlyon** [Wox-launcher/Wox#979]
Could be due to a plugin. Was searching with the spotify plugin at time of crash.

[2016-09-13.txt](https://github.com/Wox-launcher/Wox/files/470375/2016-09-13.txt)

Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 09/13/2016 19:04:18
Exception:
mscorlib
System.ArgumentOutOfRangeException
Insertion index was out of range. Must be non-negative and less than or equal to size.
Parameter name: index
   at System.Collections.ArrayList.Insert(Int32 index, Object value)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   at System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
due to the plugin, uninstall it (delete it from %APPDATA%\Plugins)
