### ISSUE TITLE
Error:http代理？

### ISSUE THREAD

**Issue by TheNetAdmin** [Wox-launcher/Wox#998]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 09/29/2016 09:51:44
Exception:
mscorlib
System.Threading.Tasks.TaskCanceledException
A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<GitHubUpdateManager>d__2b.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.Factory.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

在`known problems`里面说要用`http代理`，设置成什么代理才行？

**Comment by bao-qian** [comment]
被墙了 
翻墙代理啊。。。
wox 中设置 http 代理
